CREATE TABLE cold_spring_glen_encounters (
    `list_encounter` VARCHAR(435) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(12) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO cold_spring_glen_encounters VALUES ('A bunch of kids are down here playing some game you''ve never seen before and repeating a little musical phrase that you suspect has a deeper meaning. Make a Lore (-2) check. If you pass, you recognize what the children''s rhyme really means. Gain 1 Spell.','Lore -2','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('A man is being thrown violently by an unseen force. If you help, lose 3 Stamina as you suffer the same fate. Even if you are knocked unconscious, the man, David Packard, remembers your bravery. Take his Ally card or, if it is not available, he offers you something to finish that thing off once and for all." You may search the Common Item deck for Dynamite and take it.',NULL,'Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('A man wearing exotic robes and a strange hat tells you that he can see your fate. If you are Cursed or have any Exhibit Items, he tells you that he is called The Messenger. Take his Ally card or, if it is not available, gain 2 Clue tokens. If you are not Cursed  and do not have any Exhibit Items, nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('A police car is abandoned here. Make a Fight (-1) check to pry open the trunk. If you pass, search the Common Item deck and take the first Weapon you find. If you fail, lose 1 Stamina.','Fight -1','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('After a brisk swim in the murky river, you emerge to find yourself covered in brown, bloated leeches. Shuddering in the cold morning air, you begin the laborious task of pulling the squirming, glistening parasites loose one at a time. Lose 3 points, divided between Sanity and Stamina however you like.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('As the sun sets beneath the horizon, hundreds of whippoorwills begin to sing in a wild, frenzied chorus that tears at your mind. Lose 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('As you push through some hanging moss, dozens of black and red spiders fall on your head and neck. Make a Will (-2) check. If you fail, you are bitten several times, reducing you to 0 Stamina. If you pass, you remain perfectly still until they crawl off, then you find an odd item beneath the moss. Draw 1 Unique Item.','Will -2','Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('In the middle of the night, you are suddenly confronted by the spectre of someone wrongly killed, whose body was buried in a shallow grave near here. If you recover his remains and give him a proper burial you are delayed and Blessed.',NULL,'Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('In the night, you can hear something enormous high above you breaking through the branches of trees. Make a Will (-1) check. If you fail, you make a mad dash for safety. Lose 1 Sanity and move to the streets.','Will -1','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Make a Luck (-2) check. If you pass, you discover a strange stone statue deep within the glen. Its hands are outstretched, waiting for you to place something in them. If you discard a Unique Item worth at least $5, then skip the Mythos Phase this turn. If you fail the check, then nothing happens.','Luck -2','Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Make a Luck (-2) check. If you pass, you discover a strange stone statue deep within the glen. Its hands are outstretched, waiting for you to place something in them. If you discard a Unique Item worth at least $5, then skip the Mythos Phase this turn. If you fail the Luck check, then nothing happens.','Luck -2','Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Make a Luck (-2) check. If you pass, you discover a strange stone statue deep within the glen. Its hands are outstretched, waiting for you to place something in them. If you discard a Unique Item worth at least $5, then skip the Mythos Phase this turn. If you fail the check, then nothing happens.','Luck -2','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Make a Luck (-2) check. If you pass, you discover a strange stone statue deep within the glen. Its hands are outstretched, waiting for you to place something in them. If you discard a Unique Item worth at least $5, then skip the Mythos Phase this turn. If you fail the check, then nothing happens.','Luck -2','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Make a Luck (-2) check. If you pass, you discover a strange stone statue deep within the glen. Its hands are outstretched, waiting for you to place something in them. If you discard a Unique Item worth at least $5, then skip the Mythos Phase this turn. If you fail the check, then nothing happens.','Luck -2','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Moving quietly through the underbrush, you overhear a young woman talking to herself. She is fretting about some money her uncle owes to a rather unsavory character. If you wish, you may give her $5 to pay the debt. If you do, she introduces herself as Corinna Jones and asks if she can help you in any way. Take her Ally card if it''s available. If it is not, gain 1 Skill as she teaches you something useful in exchange for your help.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Moving quietly through the underbrush, you overhear a young woman talking to herself. She is fretting about some money her uncle owes to a rather unsavory character. If you wish, you may give her $5 to pay the debt. If you do, she introduces herself as Corinna Jones and asks if she can help you in any way. Take her Ally card if it''s available. If it is not, gain 1 Skill as she teaches you something useful in exchange for your help.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Moving quietly through the underbrush, you overhear a young woman talking to herself. She is fretting about some money her uncle owes to a rather unsavory character. If you wish, you may give her $5 to pay the debt. If you do, she introduces herself as Corinna Jones and asks if she can help you in any way. Take her Ally card if it''s available. If it is not, gain 1 Skill as she teaches you something useful in exchange for your help.',NULL,'Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Moving quietly through the underbrush, you overhear a young woman talking to herself. She is fretting about some money her uncle owes to a rather unsavory character. If you wish, you may give her $5 to pay the debt. If you do, she introduces herself as Corinna Jones and asks if she can help you in any way. Take her Ally card if it''s available. If it is not, gain 1 Skill as she teaches you something useful in exchange for your help.',NULL,'Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Painted faintly upon a stone, you see an image of a primitive figure invoking otherworldly forces. Suddenly, an ominous shadow moves across the stone. Gain 1 Spell and then a monster appears.',NULL,'Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Several dead fish are floating in the river. Investigating, you find that it is sea water rather than fresh water. Make a Lore (-2) check to try to find answers. Gain 1 Clue token for each success.','Lore -2','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('The night sky is clear when you get away from the city. As you watch, a shooting star crosses the sky and you make a wish. Make a Luck (-2) check. If you pass, you are Blessed.','Luck -2','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('The pool is extremely cold, but clean and pure, allowing you to scrub away some of the grime from your adventures. Gain 1 Sanity and 1 Stamina.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('The Sheldon Gang is looking for new recruits. If you want to prove how tough you are, spend either at least 5 toughness  worth of monster trophies or 1 gate trophy. If you spend the trophies, take a Sheldon Gang Membership card. If not, they rough you up and tell you to hit the road. Move to the street and lose 1 Stamina.',NULL,'Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('The terrible words of The King in Yellow have been echoing in your ears ever since you left Arkham. But here, the gentle sound of the river helps soothe your mind. Make a Will (-1) [2] check. If you pass, you are Blessed','Will -1 [2]','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('The water splashes upwards as a monster appears.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Tripping as you climb down a steep incline, you roll a bit and smack up against an ancient stone statue. Gain 1 Spell, but lose 2 Stamina.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Walking along a narrow path through the woods, you duck to avoid some low-hanging foliage. The leaves brush the back of your neck. Pass a Luck (-1) check or something warm and moist slides down the back of your shirt. Lose 2 Sanity.','Luck -1','Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('You come across a human skull with a star-shaped hole in it. Oddly, it seems to have been ruptured from the inside. Shivering, you replace the skull where you found it. Lose 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('You notice that a piece of driftwood looks to have letters of some kind carved into it. Make a Lore (-2) check to decipher the coded message. If you pass, gain 1 Spell.','Lore -2','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('You slide down a muddy hill and strike your head against a rock. Half-conscious, your mind fills with images of horrific gods. When you awake, a bizarre chant still echoes in your thoughts. Gain 1 Spell and lose 1 Stamina.',NULL,'Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('You stumble across an ancient stone table. It has several deep groves carved into its surface and stained dark brown. If you spend 1 monster trophy with a moon dimensional symbol, the ancient beings here are pleased. Any one investigator you choose (even yourself) is Blessed.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('You wander for several hours, then emerge in a clearing some time after dark. Looking up at the vast, starry sky, you are struck by just how insignificant mankind is within this cold, uncaring universe. Lose 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Your feet sink into the soft mud. To your horror, you realize you are continuing to sink. Make a Fight (-1) [2] check to free yourself. If you pass, you are Blessed and feel as if you have a new love of life. If you fail, lose 1 Stamina and you are delayed waiting to be rescued.','Fight -1 [2]','Miskatonic Horror');
INSERT INTO cold_spring_glen_encounters VALUES ('Your leg is suddenly caught in a bear trap. Lose 1 Stamina. If you are still conscious, make a Fight (-1) check to free yourself. If you fail, you are delayed, waiting for someone to help you.','Fight -1','Miskatonic Horror');
