CREATE TABLE devils_hopyard_encounters (
    `list_encounter` VARCHAR(354) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(9) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO devils_hopyard_encounters VALUES ('A scientist from Miskatonic University is here to examine the dead plant life. He''s happy to explain some of the area''s stranger aspects, but he uses highly technical language. Make a Lore (-2) check to decipher what''s he''s saying. Gain 1 Clue token for each success.','Lore -2','Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('A sickly monster appears.  You receive an extra +1 bonus on any Combat check against it.',NULL,'Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('A small black plant grows here, where no other vegetation survives.  Something about its smell compels you to eat one of its small red berries.  Gain 1 Clue token and lose 1 Stamina.',NULL,'Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('After stumbling over yet another piece of debris in this dry, barren expanse, you begin to notice a pattern in the way that a certain type of jagged black rock is strewn across the field.  Pass a Lore (-2) check to gain 2 Clue tokens.','Lore -2','Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('As you walk in the moonlight, you are struck by a curious sight. You are casting two shadows. Looking up, you are stunned to see two moons. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Gibberish and obscenities are carved into the bark of some of the dead trees ringing the hopyard. You recognize occult symbols on the most twisted and deformed specimens.  Pass a Luck (-1) check to draw 1 Spell.','Luck -1','Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('In the moonlight, you hear a local farmer muttering to himself and gathering the dirt from this area into a small pouch. Make a Luck (-2) check to hear what he''s saying. If you pass, you realize he''s reciting an ancient ritual and you draw 1 Spell.','Luck -2','Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Make a Luck (-1) check. If you fail, your health has been adversely affected by your time here. Draw 1 Injury card.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Make a Luck (-1) check.  If you pass, you discover an underground chamber containing some alien techonology.  Draw 1 Unique Item.','Luck -1','Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Make a Luck (-2) check.  If you pass, you stumble across a pile of unusual debris. Picking through it, you find an unusual item. Draw 2 Unique Items and keep one.','Luck -2','Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('No wildlife of any kind will approach this barren field and the silence is unnerving. Make a Will (+1) check and lose 3 Sanity, reducing the amount of Sanity lost by 1 for each success rolled (to a minimum of 0).','Will +1','Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Pass a Luck (-1) check or you have been here too long, and strange hungers have been awakened in you. Draw 1 Madness card.','Luck -1','Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Picking your way between the dead plants, you come across an old man gathering some strange fungus.  He introduces himself as Zebulon Whateley and ask if you know the Art.  If you discard 1 Spell, take his Ally card.  If it''s isn''t available, gain 4 Clue tokens instead.',NULL,'Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Picking your way between the dead plants, you come across an old man gathering some strange fungus.  He introduces himself as Zebulon Whateley and ask if you know the Art.  If you discard 1 Spell, take his Ally card.  If it''s isn''t available, gain 4 Clue tokens instead.',NULL,'Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Picking your way between the dead plants, you come across an old man gathering some strange fungus. He introduces himself as Zebulon Whateley and asks if you know the Art. If you discard 1 Spell, take his Ally card. If it isn''t available, gain 4 Clue tokens instead.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Picking your way between the dead plants, you come across an old man gathering some strange fungus. He introduces himself as Zebulon Whateley and asks if you know the Art. If you discard 1 Spell, take his Ally card. If it isn''t available, gain 4 Clue tokens instead.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Sickly-colored steam begins to rise from invisible fissures in the earth. Make a Speed (-1) check to cover your mouth before breathing it in. If you fail, lose 2 Stamina.','Speed -1','Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Standing next to one of the dead trees, near the hopyard, you look up and see a decayed noose hanging from one of the branches. You take it as a bad sign. Make a Luck (+0) check. If you fail, you are Cursed.','Luck +0','Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('The atmosphere here is stifling. Make a Fight (-1) check or lose 1 Stamina and 1 Sanity. If you are reduce to 0 Sanity or Stamina, you are devoured.','Fight -1','Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('The fumes in the air here make you feel woozy and you have to sit down.  Stay here next turn.',NULL,'Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('The ground beneath your feet gives way suddenly and you drop down for what seems forever. Move to the first area of the Underworld, have an encounter there, and then immediately return here.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('The ground has been dug up in several places, and you think you may be able to find tracks of the creature that was digging. Make a Luck (-1) check and gain 1 Clue token if you pass.','Luck -1','Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('The smoke here burns your eyes and you begin to see things that couldn''t possibly be real. Make a Luck (+0) check. If you pass, it was nothing more han a terrifying mirage. Lose 1 Sanity. If you fail, it''s no hallucination. A monster appears. Treat this monster as if it has the Nightmarish 1 ability if it doesn not already have the Nightmarish ability.','Luck +0','Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('Through one of the fissures in the stony ground, you see something shining. Make a Fight (-2) check. If you pass, you manage to free the object. Gain 1 Unique Item.','Fight -2','Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You feel as if this desolate area is draining you of your life. Lose 1 Stamina. Then, if either the Act I or Act II card is in play, you must additionally discard 1 Skill if you are able.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You find the carcass of a deer laying in the clearing. While it doesn''t appear to have any injuries, blood has erupted from its nose and eyes. Deciding that discretion is the better part of valor, you move to the street.',NULL,'Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You hear a panicked cry from inside a nearby cloud of brownish smoke.  If you rush to help, you pull someone inside the cloud to safety, but hurt yourself badly doing so.  Draw 1 Ally and 1 Injury card.',NULL,'Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You hear a panicked cry from inside a nearby cloud of brownish smoke.  If you rush to help, you pull someone inside the cloud to safety, but hurt yourself badly doing so.  Draw 1 Ally and 1 Injury card.',NULL,'Dunwich Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You hear a panicked cry from inside a nearby cloud of brownish smoke. if you rush to help, you pull someone inside the cloud to safety, but hurt yourself badly doing so. Draw 1 Ally and 1 Injury card.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You hear a panicked cry from inside a nearby cloud of brownish smoke. if you rush to help, you pull someone inside the cloud to safety, but hurt yourself badly doing so. Draw 1 Ally and 1 Injury card.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You hear a panicked cry from inside a nearby cloud of brownish smoke. if you rush to help, you pull someone inside the cloud to safety, but hurt yourself badly doing so. Draw 1 Ally and 1 Injury card.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You hear a panicked cry from inside a nearby cloud of brownish smoke. if you rush to help, you pull someone inside the cloud to safety, but hurt yourself badly doing so. Draw 1 Ally and 1 Injury card.',NULL,'Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You see what looks like a deer walking toward you, seemingly unafraid. You then see that eating the grass near this place has mutated it. Make a Fight (-1) check to defend yourself. Lose 1 Stamina if you fail.','Fight -`1','Miskatonic Horror');
INSERT INTO devils_hopyard_encounters VALUES ('You''ve heard that strange creatures appear at night in the hopyard. If you wish, you may spend the night here and observe. If you do so, you are delayed and gain 3 Clue tokens observing the creatures that dwell here in the night.',NULL,'Miskatonic Horror');
