CREATE TABLE gardners_place_encounters (
    `list_encounter` VARCHAR(421) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(16) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO gardners_place_encounters VALUES ('A bit of dirt has been disturbed here, revealing an oddly shaped skull. Something warns you that touching it could be a bad idea, but it seems to glow with power at the same time. If you decide to touch it, draw 1 Skill and 1 Madness card.',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('A bit of dirt has been disturbed here, revealing an oddly shaped skull. Something warns you that touching it could be a bad idea, but it seems to glow with power at the same time. If you decide to touch it, draw 1 Skill and 1 Madness card.',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('A bit of dirt has been disturbed here, revealing an oddly shaped skull. Something warns you that touching it could be a bad idea, but it seems to glow with power at the same time. If you decide to touch it, draw 1 Skill and 1 Madness card.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('A bit of dirt has been disturbed here, revealing an oddly shaped skull. Something warns you that touching it could be a bad idea, but it seems to glow with power at the same time. If you decide to touch it, draw 1 Skill and 1 Madness card.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('A bit of dirt has been disturbed here, revealing an oddly shaped skull. Something warns you that touching it could be a bad idea, but it seems to glow with power at the same time. If you decide to touch it, draw 1 Skill and 1 Madness card.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('A bit of dirt has been disturbed here, revealing an oddly shaped skull. Something warns you that touching it could be a bad idea, but it seems to glow with power at the same time. If you decide to touch it, draw 1 Skill and 1 Madness card.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('A famed escape artist is investigating the area''s legends of an unearthly glow which permeates the area at night. If you give him 2 of your Spells (discarding them), he introduces himself as Erich Weiss; take his Ally card if it''s available. If it''s not available, he shows you a trick instead, and you gain 2 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('A gate and a monster appear!',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('A gate and a monster appear!',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('A horrifying monster appears!',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('A mutated monster appears! You suffer an extra -1 penalty on any Combat checks against it.',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('A weathered man comes up to you as you approach the Gardners'' house. Introducing himself as Ammi Pierce, he tells you that it might be wise to steer clear of the house right now, and asks if you might have anything that might help the family''s strange affliction. If you discard 1 Unique Item, Ammi joins you in gratitude. Take his Ally card if it''s available. If it is not, remove 1 Dunwich Horror token from the board.',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('A weathered man comes up to you as you approach the Gardners'' house. Introducing himself as Ammi Pierce, he tells you that it might be wise to steer clear of the house right now, and asks if you might have anything that might help the family''s strange affliction. If you discard 1 Unique Item, Ammi joins you in gratitude. Take his Ally card if it''s available. If it is not, remove 1 Dunwich Horror token from the board.',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('A weathered man comes up to you as you approach the Gardners'' house. Introducing himself as Ammi Pierce, he tells you that it might be wiser to steer clear of the house right now, and asks if you might have anything that might help the family''s strange affliction. If you discard 1 Unique Item, Ammi joins you in gratitude. Take his Ally card if it''s available. If it is not, remove 1 Dunwich Horror token from the board.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('A weathered man comes up to you as you approach the Gardners'' house. Introducing himself as Ammi Pierce, he tells you that it might be wiser to steer clear of the house right now, and asks if you might have anything that might help the family''s strange affliction. If you discard 1 Unique Item, Ammi joins you in gratitude. Take his Ally card if it''s available. If it is not, remove 1 Dunwich Horror token from the board.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('After walking around the house, you become aware of fine bits of a stange metal stuck to your clothes. You can feel the metallic dust emanating a strange energy. Gain 1 Clue token and then make a Luck (-1) check. If you fail, a monster appears.','Luck -1','Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('Approaching the house, you notice three youngs boys crouching in the bushes by the side of the drive. Questioning them, you get nothing but variations on the rumors you''ve heard in town: One boy insists the place is haunted, while the other two maintain that Mrs. Gardner is a witch. However, just as you''re about to give up in despair, one of them lets slip a detail of great importance to you. Gain 2 Clue tokens.',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('Emaciated cattle wander through the area, their hide turned grey by some unknown force. Make a Lore (-1) check. If you pass, gain 1 Clue token as you gain useful knowledge by studying these strangely afflicted creatures.','Lore -1','Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('Erica Carlyle is investigating the stories of the mysterious stone that fell from the heavens, and her interest is piqued by your tales of the bizarre. If you have $3 or less, she agrees to help you and help pay your way. Take her Ally card or, if it is not available, gain a Retainer card.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('Inside the Gardners'' house you find strange, erratic writings covering some of the walls. Most of it seems to be nonsense but hidden within the ramblings are some startling revelations. If you choose to investigate thoroughly, gain 3 Clue tokens, and you are delayed.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('Make a Luck (-1) check. If you fail, something deep within the well seems to call to you. Pass a Will (-1) check or you leap into the well to be devoured. If you pass either check, nothing happens.','Luck -1
Will -1
','Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('Night falls, and you witness the vegetation of the area glowing and squirming of its own accord. Lose 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('Strange currents of mystical energy flow through this area. If 2 or more rifts are open, add 1 Dunwich Horror token to the board.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('The more corrupt Dunwich becomes, the more this area rots the minds of those who encounter it. Make a Will (+2) check. If the number of successes is less than the total number of monster tokens in Dunwich locations and Dunwich street areas, draw a [[Madness] card.','Will +2','Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('Wandering through the house, you peer into the attic. Inside, a filthy woman squats on the floor like an animal and growls viciously at you before leaping to attack. Pass a Speed (-1) check to escape or lose 1 Stamina. In either event, lose 1 Sanity.','Speed -1','Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('You are attacked by a hideous bald creature that leaps out of the bushes at you. Make a Luck (-1) check. If you pass, the creature is weak and easily slain. If you fail, its sharp teeth tear into your neck. Lose 2 Stamina. In either event, you lose 1 Sanity as you realize that thise abomination was once an ordinary rabbit.','Luck -1','Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('You are filled with an unnatural vigor. Your Stamina is restored to its maximum. In addition, you gain 3 extra Stamina above your maximum that cannot be restored once lost.',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('You are filled with an unnatural vigor. Your Stamina is restored to its maximum. In addition, you gain 3 extra Stamina above your maximum that cannot be restored once lost.',NULL,'Dunwich Horror');
INSERT INTO gardners_place_encounters VALUES ('You are filled with an unnatural vigor. Your Stamina is restored to its maximum. In addition, you gain 3 extra Stamina above your maximum that cannot be restored once lost.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('You are filled with an unnatural vigor. Your Stamina is restored to its maximum. In addition, you gain 3 extra Stamina above your maximum that cannot be restored once lost.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('You are filled with an unnatural vigor. Your Stamina is restored to its maximum. In addition, you gain 3 extra Stamina above your maximum that cannot be restored once lost.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('You are filled with an unnatural vigor. Your Stamina is restored to its maximum. In addition, you gain 3 extra Stamina above your maximum that cannot be restored once lost.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('You have definitely been affected by the unearthly energies of this place. Draw 1 Corruption card.',NULL,'Miskatonic Horror');
INSERT INTO gardners_place_encounters VALUES ('You notice an odd piece of metallic ore on the ground. If you touch it, make a Luck (-1) check. If you pass, it smoothly transforms into an odd item. Take the first Unique Item from the deck that isn''t a Tome. If you fail, it is absorbed into your skin and assaults your mind. Draw 1 Madness card.','Luck -1','Dunwich Horror');
