CREATE TABLE whateley_farm_encounters (
    `list_encounter` VARCHAR(412) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(11) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO whateley_farm_encounters VALUES ('A folded note addressed to "Wilbur" pokes out from under the door. Having a look at it, you discover it is written in some sort of code. Make a Lore (-2) check to decipher it. If you pass, gain 2 Clue tokens.','Lore -2','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('A foreign gentleman is examining the farm. If you have any Exhibit Items or your will is 2 or lower, he shows interest in your presence and introduces himself as Dr. Ali Kafour. Take his Ally card or, if it is not available, listen to him share his theories on ancient beliefs and gain 2 Clue tokens.If you do not have and Exhibit Items or you Wll is more than 2, nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('A gate and a monster appear!',NULL,'Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('A hot, sickly wind is blowing across the farmyard. You feel something seeping into your pores. Make a Will (+0) check. If you fail, gain 1 Corruption card.','Will +0','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('A priest stands at the front door, hoping to offer spiritual help to those within. If you are Cursed or either your Stamina or Sanity is 2 or lower, he introduces himself as Father Iwanicki. Take his Ally card or, if it is not available, you may search the Unique Item deck for the Holy Water card and take it.',NULL,'Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('An oozing monster appears!',NULL,'Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('As you approach the house, you hear something large and almost serpentine thrashing about inside. Pass a Lore (-1) check to realize your danger and escape without rousing its ire. If you fail, lose 1 Stamina as something huge and unseen bats you away from the Whateley farm.','Lore -1','Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('As you approach the old Whateley farm, a man runs up to you. "For God''s sake, don''t go in there!" He introduces himself as Earl Sawyer, the Whateleys'' nearest neighbor. You talk, and he reveals a dangerous plan for dealing with the strange goings-on. If you add 1 Dunwich Horror token to the board, he joins you. Take his Ally card if it''s available. If it is not, draw 1 Spell, 1 Unique Item, and 1 Common Item.',NULL,'Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('As you approach the old Whateley farm, a man runs up to you. "For God''s sake, don''t go in there!" He introduces himself as Earl Sawyer, the Whateleys'' nearest neighbor. You talk, and he reveals a dangerous plan for dealing with the strange goings-on. If you add 1 Dunwich Horror token to the board, he joins you. Take his Ally card if it''s available. If it is not, draw 1 Spell, 1 Unique Item, and 1 Common Item.',NULL,'Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('As you approach the old Whateley farm, a man runs up to you. "For God''s sake, don''t go in there!" He introduces himself as Earl Sawyer, the Whateleys'' nearest neighbor. You talk, and he reveals a dangerous plan for dealing with the strange goings-on. If you add 1 Dunwich Horror token to the board, he joins you. Take his Ally card if it''s available. If it is not, draw 1 Spell, 1 unique Item, and 1 Common Item.',NULL,'Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('As you approach the old Whateley farm, a man runs up to you. "For God''s sake, don''t go in there!" He introduces himself as Earl Sawyer, the Whateleys'' nearest neighbor. You talk, and he reveals a dangerous plan for dealing with the strange goings-on. If you add 1 Dunwich Horror token to the board, he joins you. Take his Ally card if it''s available. If it is not, draw 1 Spell, 1 unique Item, and 1 Common Item.',NULL,'Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('Examining one of the haggard cows that shamble around the farm, you realize that something has been draining the creature''s blood on a regular basis. Lose 1 Sanity and move to the street.',NULL,'Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('Examining the remnants of a recent magic ritual, you learn something important about the inner workings of magic. Draw 1 Spell and gain 1 Clue token.',NULL,'Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('Feeling thirsty, you lower a bucket into the old well to draw up a drink. Make a Luck (-1) check. If you pass, the bucket contains several gold coins. Gain $3. If you fail, the bucket is filled with blood and entrails. Lose 1 Sanity and move to the street.','Luck -1','Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('If you pass a Luck (-1) check, you discover some of Wizard Whateley''s notes and find a way to interfere with his plans. You may remove 1 Dunwich Horror token from the board.','Luck -1','Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('If you pass a Luck (-1) check, you discover some of Wizard Whateley''s notes and find a way to interfere with his plans. You may remove 1 Dunwich Horror token from the board.','Luck -1','Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('If you pass a Luck (-1) check, you discover some of Wizard Whateley''s notes and find a way to interfere with his plans. You may remove 1 Dunwich Horror token from the board.','Luck -1','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('If you pass a Luck (-1) check, you discover some of Wizard Whateley''s notes and find a way to interfere with his plans. You may remove 1 Dunwich Horror token from the board.','Luck -1','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('If you pass a Luck (-1) check, you discover some of Wizard Whateley''s notes and find a way to interfere with his plans. You may remove 1 Dunwich Horror token from the board.','Luck -1','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('If you pass a Luck (-1) check, you discover some of Wizard Whateley''s notes and find a way to interfere with his plans. You may remove 1 Dunwich Horror token from the board.',NULL,'Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('It looks like the barn has recently been repaired. Putting your ear to the door, you can hear something moving in there. Gain 1 Clue token. Then pass a Luck (-2) check or lose 2 Sanity as you come to understand what those awful noises are.','Luck -2','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('Leaning against a wooden fence near the Whateley farm, you get some tarry black substance on your hand. Examining it gives you some insight into the nature of the Dunwich Horror. Gain 1 Clue token.',NULL,'Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('Next to a weathered chair in front of the Whateleys'' home is a torn up scholastic journal about ancient books. the language is a bit dense but you struggle through. Make a Lore (-2) check. If you pass, gain 1 Clue token.','Lore -2','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('Snooping around you''ve set off a shotgun trap! Pass a Speed (-2) check or lose 1 Stamina.','Speed -2','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('The barrel of a gun pokes out of a window aimed at you. "You got muh book?" You may discard a Tome. If you do, the unseen figure strikes up a conversation with you. Gain 3 Clue tokens. If you do not, you are ordered off the land. Move to the streets.',NULL,'Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('Through the shutters you see a book lying open on a table inside. You may make a Sneak (-2) check to enter undetected and examine it. If you pass, draw 2 Spells, keep 1 and discard the other. If you fail, lose 1 Stamina and move to the street as you are evicted from the building.','Sneak -2','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('Walking up the path towards the Whateley farm, you come across the carcass of a dog that someone has shot. Rethinking your visit, you turn right back around and leave. Move to the street.',NULL,'Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('You are looking around behind the Whateley farm when you discover the foundation of an old building. Carved into the foundation is a list of names that you recognize from your occult researches and several you''ve never heard before. Gain 2 Clue tokens.',NULL,'Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('You can''t see it, but you know something exists on this farm that is horrible. You can feel this malevolent force watching your every move. Lose 1 Sanity. You may add 1 Dunwich Horror token to the board. If you do so, gain 3 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('You discover a local man unconscious by a broken fence. Make a Lore (-1) check to administer first aid. If you pass, gain a Clue token as he tells you what happened. If you fail, you are delayed waiting for a doctor.','Lore -1','Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('You find a wrinkled scroll laying on the woodpile. If you pass a Luck (-1) check, it turns out to be mystical in nature: Draw 1 Spell. If you fail, the scroll contains the rantings of a madman: Lose 1 Sanity.','Luck -1','Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('You notice that the back door of the Whateley home is open. If you go inside, make a Luck (-1) [2] check. If you pass, you learn the secret of the Whateley gold, and you may search the Spell deck for an Alchemical Process card and take it. If you fail, Lavinia Whateley catches you and Curses you.','Luck -1 [2]','Dunwich Horror');
INSERT INTO whateley_farm_encounters VALUES ('You see a dog sniffing and digging at the ground beneath a particular tree. After a few minutes of excavation, you unearth the remains of some victim of a brutal attack. Lose 1 Stamina. But the contents of his wallet remain intact, providing his name and some cash. Gain 1 Clue token and $1.',NULL,'Miskatonic Horror');
INSERT INTO whateley_farm_encounters VALUES ('You see a light on in the house! Make a Sneak (-1) check to eavesdrop on what''s going on inside. If you pass, gain 1 Spell. If you fail, you race away before you are caught. Move to the streets.','Sneak -1','Miskatonic Horror');
