CREATE TABLE ancient_ones (
    `list_name` VARCHAR(14) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8,
    `list_doom` INT,
    `list_image` VARCHAR(24) CHARACTER SET utf8,
    `list_combat_rating` VARCHAR(2) CHARACTER SET utf8,
    `list_defenses` VARCHAR(42) CHARACTER SET utf8,
    `list_abilities_combat_rating` INT,
    `list_abilities_defenses` VARCHAR(18) CHARACTER SET utf8,
    `list_abilities_worshippers` VARCHAR(243) CHARACTER SET utf8,
    `list_abilities_power` VARCHAR(473) CHARACTER SET utf8,
    `list_abilities_attack` VARCHAR(435) CHARACTER SET utf8,
    `list_abilities_start_of_battle` VARCHAR(89) CHARACTER SET utf8,
    `list_abilities_eihort_s_brood` VARCHAR(160) CHARACTER SET utf8,
    `list_abilities_doom_track` INT,
    `list_abilities_start_of_battle` VARCHAR(102) CHARACTER SET utf8
);
INSERT INTO ancient_ones VALUES ('Abhoth','Dunwich Horror',11,'/File:Abhoth2.png','-4','Magical Resistance',-4,'Magical Resistance','Abhoth has no human worshippers.  Return all Cultists to the box at the start of the game.  Place the 3 Child of Abhoth monsters on this sheet.  Children of Abhoth that are defeated return to this sheet.  They can never be claimed as trophies.','Abominations - While Abhoth stirs in his slumber, each time a monster surge occurs, place a random Child of Abhoth on the surging gate.  If all 3 Children of Abhoth are already on the board, raise the terror level by 2 and add 1 doom token to the doom track.','Each investigator must discard a total of 3 Clue tokens, monster trophies, gate trophies, and/or Items or be devoured.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Atlach-Nacha','Kingsport Horror',13,'/File:Atlach-Nacha.png','-5','Magical Resistance, Physical Resistance',NULL,NULL,'Atlach-Nacha is worshipped by the terrible Leng Spiders.  Leng Spiders are fast, and their toughness is increased by 2.','Web Between Worlds - While Atlach-Nacha stirs in his slumber, all gate openings are gate bursts.  In addition, all Mystic cards are discarded without their special effects taking place.','The Investigators must, as a group, choose one Ally in play or one investigator.  If an Ally is chosen, it is returned to the box.  If an investigator is chosen, that investigator is devoured.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Azathoth',NULL,14,'/File:Azathoth.png','-∞','None',NULL,NULL,'Since Azathoth promises nothing except destruction, only the insane worship him.  However, their fanaticism gives them strength.  Maniacs have their toughness increased by 1.','Absolute Destruction - If Azathoth awakens, the game is over and the investigators lose.','The end is here!  Azathoth destroys the world.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Bokrug','Innsmouth Horror',12,'/File:Bokrug.jpg','-X','Magical Resistance, Physical Resistance',NULL,NULL,'Bokrug is worshipped by the ghosts of its followers, the Beings of Ib. At the start of the game, place the four Being of Ib monster tokens on this sheet.Investigators suffer the penalties listed on each Being of Ib on this sheet.','Vengeance for the Dead - While Bokrug stirs in his slumber, any investigator may spend 2 gate trophies, 10 toughness worth of monster trophies, or 1 gate trophy and 5 toughness worth of monster trophies during the Upkeep Phase while in any Other World to remove one Being of Ib of his choice from this sheet.','Add 1 clue token to this sheet. If this brings the total number of clues and Beings of Ib on this sheet to eight or more, the investigators are devoured and lose the game.','X is set to twice the number of Beings of Ib on this sheet.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Chaugnar Faugn','Innsmouth Horror',12,'/File:Chaugnar_Faugn.jpg','-4','Physical Immunity',NULL,NULL,'Chaugnar Faugn is worshipped by a fierce and fanatical jungle tribe. All Tcho-tchos and Tcho-tcho Priests gain +2 toughness.','Curse of the Jungle - While Chaugnar Faugn stirs in his slumber, any investigator carrying an Elder Sign or in the same neighborhood as an elder sign token suffers a -1 penalty to all skill checks.','Each investigator must discard three Clue tokens, one Ally, or be devoured. Chaugnar Faugn cannot have more than three doom tokens removed from his doom track during a single round of combat - he ignores all further successes.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Cthugha','Innsmouth Horror',13,'/File:Cthugha.jpg','-5','Physical Resistance',NULL,NULL,'Cthugha is worshipped by its smaller brethren. Fire Vampires gain +2 toughness and deal 1 extra Stamina as combat damage.','Sweltering Heat - While Cthugha stirs in its slumber, each investigator loses 1 Stamina for each movement point over 3 he spends each turn. Reading Tomes does not count towards this total. In addition, all Weather cards are ignored when drawn - a new card being drawn instead.','Roll a die. Each investigator must lose a total of that many Clue tokens, Stamina, and/or Sanity or be devoured. Any weapon used in an attack against Cthugha is discarded after the attack is made.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Cthulhu',NULL,13,'/File:Cthulhu.png','-6','Special (See Attack)',NULL,NULL,'Cthulhu''s worshippers often have the Innsmouth Look, a sign of monstrous ancestors.  Cultists have a horror rating of -2 and a horror damage of 2 Sanity.','Dreams of Madness - While Cthulhu stirs in his slumber, investigators have their maximum Sanity and maximum Stamina reduced by 1.','Each investigator lowers either his maximum Sanity or Maximum Stamina by 1 (his choice).  After Cthulhu attacks 1 doom token is placed back on Cthulhu''s doom track if it isn''t already full.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Daoloth','Promotional offer',12,'/File:Daoloth_AO.jpg','-4','Special (See Attack)',NULL,NULL,'The followers of Daoloth are astronomers that can see into both the past and the future.  When Cultists move, they do not follow normal movement rules.  Instead, they move to the nearest investigator in a street area or unstable location.','The Render of Veils - While Daoloth stirs in his slumber, immediately after each monster surge, replace all open gates, one at a time.  Do this by reshuffling the gate into the pile of gate markers and drawing a new one to take its place.  Then, discard all explored markers.  This is not treated as a new gate opening (no doom tokens are added to the doom track and no monsters are drawn).  Investigators are not drawn through these gates until the Arkham Encounter phase.','Draw a Mythos Card.  If the card instructs the players to place a gate in a location that does not have an elder sign on it, the first player is devoured. If the card instructs players to place a gate in a location that does have an elder sign on it, remove the elder sign from that location.  If the Mythos Card does not instruct players to place a gate in a location, 1 token is placed back on Daoloth''s doom track if it is not full.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Eihort','Kingsport Horror',12,'/File:Eihort.png','-4','Physical Immunity',NULL,NULL,'Eihort''s worshippers are infested with his blood.  Each time an investigator defeats a Cultist, that investigator gains a brood token.','Eihort''s Bargain - While Eihort stirs in his slumber, any investigator who seals a gate gains 1 brood token.  Any brood tokens on an investigator who is devoured are immediately added to Eihort''s doom track as doom tokens.  Eihort can exceed 12 doom tokens on his doom track.','The first player gains one brood token.','When Eihort awakens, each investigator gains one brood token.','Each time an investigator gains a brood token, roll a die.  If the roll is lower than the number of brood tokens possessed by that investigator, he is devoured.',NULL,NULL);
INSERT INTO ancient_ones VALUES ('Ghatanothoa','Innsmouth Horror',13,'/File:Ghatanothoa.jpg','-6','None',NULL,NULL,'Ghatanothoa is worshipped by certain ancient reptiles and fungi from Yuggoth. Lloigor and Mi-Go gain +2 toughness.','Annihilating Gaze - While Ghatanothoa stirs in his slumber, place the eight visage tokens facedown on this sheet. Each time an investigator gains 2 or more Clue tokens at once, he must turn a visage token faceup. If it has Ghatanothoa''s face on it, he is devoured. If not, leave the token faceup. Once four visage tokens are faceup, turn them facedown and shuffle the visage tokens.','Each investigator must spend 1 movement point or be devoured. This increases by 1 point in each successive round (e.g. 2 points in round 2, 3 in round three, etc.).Each investigator''s attack against Ghatanothoa deals one less success than normal.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Glaaki','Dunwich Horror',12,'/File:Glaaki2.png','-5','Physical Resistance',NULL,NULL,'Glaaki''s worshippers are relentless undead creatures.  Cultists are Undead and stalkers.  Place the 5 Servant of Glaaki monsters on this sheet.  Servants of Glaaki that are defeated return to this sheet.  They can never be claimed as trophies.','Undead Servants - While Glaaki stirs in his slumber, each time an Ally is discarded or removed from the game, draw a mythos card and place a random Servant of Glaaki on the gate location shown (even if it is sealed).  If all 5 Servants of Glaaki are already on the board, Glaaki immediately awakens.  If an investigator is devoured, raise the terror level by 2.','Raise the terror level by 1.  If it is 10 or higher, all investigators are devoured.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Hastur',NULL,13,'/File:Hastur.png','-X','Physical Resistance',NULL,NULL,'Hastur''s worshippers ride byakhee mounts that they call with enchanted whistles.  Cultists are flying monsters and their combat rating is -2.','The King in Yellow - While Hastur stirs in his slumber, the cost to seal a gate is 8 Clue tokens instead of 5.','Each investigator must pass a Luck (+1) check or lose 2 Sanity.  This check''s modifier decreases by 1 each turn (+0 the 2nd turn, -1 the 3rd turn, etc.)','X is set to the current terror level.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Ithaqua',NULL,11,'/File:Ithaqua.png','-3','None',NULL,NULL,'Ithaqua''s worshippers eat the flesh of their fellow men, gaining supernatural power through their dark practice.  Cultists have their toughness increased by 2.','Icy Winds - While Ithaqua stirs in his slumber, any investigator in a street area at the end of the Mythos phase loses 1 Stamina.  In addition, all Weather cards are discarded without their special effects taking place.','Each investigator must pass a Fight (+1) check or lose 2 Stamina.  This check''s modifier decreases by 1 each turn (+0 the 2nd turn, -1 the 3rd turn, etc.)','Investigators must roll a die for every item they have, discarding the item on a failure.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Nyarlathotep',NULL,11,'/File:Nyarlathotep.png','-4','Magical Resistance',NULL,NULL,'Nyarlathotep has innumerable cults all over the world.  Cultists have the Endless ability.','A Thousand Masks - At the start of the game add the 5 Mask monsters to the cup.  Multiple Mask monsters can be in play at once.','Each investigator must pass a Lore (+1) check or lose 1 Clue token.  Any investigator with no Clue tokens left is devoured.  This check''s modifier decreases by 1 each turn (+0 the 2nd turn, -1 the 3rd turn, etc.)','Any investigator with no Clue tokens is devoured.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Nyogtha','Innsmouth Horror',12,'/File:Nyogtha.jpg','-8','None',NULL,NULL,'Nyogtha is worshipped by a variety of beings in return for teaching them spells. Witches, Warlocks, and Ghouls gain +1 toughness and Physical Resistance.','Tendrils from Below - While Nyogtha stirs in its slumber, at the start of the game, place the Tendril of Nyogtha monster token on this sheet. Each time a monster (but not a gate) appears during an encounter, the Tendril of Nyogtha is encountered instead. If it is defeated, return the Tendril to this sheet. It cannot be claimed as a trophy.','The first player is pulled underground. Roll a die. On a success, that player escapes with their life; otherwise they are devoured.Nyogtha''s combat rating is -3 for the first player only.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Quachil Uttaus','Innsmouth Horror',12,'/File:QuachilUttaus.jpg','-3','Physical Immunity, Magical Immunity',NULL,NULL,'Quachil Uttaus is worshipped by wizards who call upon him for immortality. Warlocks gain +2 toughness and Endless. Investigators do not collect clue tokens from defeating a Warlock unless they can ignore the Endless ability.','Footprints in the Dust - While Quachil Uttaus stirs in his slumber, shuffle the three dust decks at the start of the game and place them facedown on this sheet.At the start of each turn, the first player must either spend 2 clue tokens or draw a card from the lowest-numbered dust deck that still has undrawn cards in it.','Quachil Uttaus touches the first player, who ages to dust and blows away in the wind. The first player is devoured.','All Allies are returned to the box.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Rhan-Tegoth','Innsmouth Horror',11,'/File:RhanTegoth.jpg','-4','Physical Immunity',NULL,NULL,'Rhan-Tegoth is worshipped by the twisted creatures of the tundra. Gnoph-Keh gain Nightmarish 1.','Insatiable HungerWhile Rhan-Tegoth stirs in his slumber, any Cultist that is drawn from the monster cup is placed on this sheet. The terror level then increases by 1, a doom token is added to the doom track, and a replacement monster is drawn.','Rhan-Tegoth drains the blood from a victim. The investigator with the highest current Stamina (first player breaks ties) rolls dice equal to his Stamina and loses 1 Stamina for each failed die. For each Stamina Rhan-Tegoth drains, the investigators must inflict one extra success on him in order to defeat him.','Rhan-Tegoth gains 2 extra doom tokens for each Cultist on this sheet.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Shub-Niggurath',NULL,12,'/File:Shub-Niggurath.png','-5','Physical Immunity',NULL,NULL,'Shub-Niggurath''s young are numberless.  Dark Young have the Endless ability.','Black Goat of the Woods - While Shub-Niggurath stirs in her slumber, all monsters have their toughness increased by 1.','Each investigator must pass a Sneak (+1) check or lose 1 monster trophy.  Any investigator with no monster trophies left is devoured.  The check''s modifier decreases by 1 each turn (+0 the 2nd turn, -1 the 3rd turn, etc.)','Any investigator with no monster trophies is devoured.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Shudde M''ell','Dunwich Horror',12,'/File:ShuddeMell2.png','-3','Magical Resistance and Physical Resistance',NULL,NULL,'Shudde M''ell is worshipped by his inhuman children.  Chthonians deal their damage when moving on a roll of 2-6 instead of a roll of 4-6.','World Cracking - While Shudde M''ell stirs in his slumber place the 7 rubble tokens face down near the board.  Each time a monster surge occurs, draw a rubble token.  The token is placed on the location it shows, closing that location for the rest of the game.  If there are no rubble tokens left when one should be drawn, the game is over and the investigators lose.','One undrawn rubble token is discarded.  If there are no rubble tokens left to discard when Shudde M''ell attacks, Arkham is destroyed by a massive earthquake and all investigators are devoured.',NULL,NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Tsathoggua','Dunwich Horror',13,'/File:Tsathoggua2.png','-6','None',NULL,NULL,'Tsathoggua is served by black, amorphous creatures.  Formless Spawn gain +1 toughness and become stalkers.','Malaise - While Tsathoggua stirs in his slumber, investigators cannot use the special ability of any locations other than the Arkham Asylum, Curiositie Shoppe, General Store, Ye Olde Magick Shoppe, and St. Mary''s Hospital.  This does not prevent investigators from having encounters or traveling between cities.  In addition, all Urban cards are discarded without their special effects taking place.','Each investigator must discard 2 monster trophies and 1 gate trophy or be devoured.','Investigators discard all Clue tokens.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Y''Golonac','Kingsport Horror',12,'/File:YGolonac.png','-4','Physical Resistance',NULL,NULL,'Y''Golonac''s worshippers are possessed by him and revert to their normal form upon death.  Each time an investigator defeats a Cultist, increase the terror level by 1.','Corrupting Text - While Y''Golonac stirs in his slumber, each time an investigator draws a Tome from any deck after dealing out starting equipment (whether he keeps the Tome or not) add one doom token to Y''Golonac''s doom track.','Wounds from Y''Golonac''s hands remain open and bleeding.  Each investigator loses 1 point of Sanity and/or Stamina, split between the two however he likes.  This increases by 1 point each successive round (e.g., 2 points in round two, 3 in round three, etc.).',NULL,NULL,12,NULL);
INSERT INTO ancient_ones VALUES ('Yibb-Tstll','Kingsport Horror',11,'/File:Yibb-Tstll.png','-X','Special',NULL,NULL,':Yibb-Tstll is served by the Nightgaunts.  All Nightgaunts have their horror damage increased to 3 Sanity.','All-Seeing - While Yibb-Tstll stirs in her slumber, the difficulty of all Evade checks is increased by 1.In addition, no investigator can have more than 5 Clue tokens at once.When Yibb-Tstll awakens, X is set to the number of Clue tokens left on the board.','The first player rolls dice equal to his focus.  If he does not roll at least one success, he is devoured.  If he rolls two or more successes he is Blessed.  It takes twice as many successes as usual to remove each doom token from Yibb-Tstll''s doom track.','When Yibb-Tstll awakens all investigators lose all Clue tokens.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Yig',NULL,10,'/File:Yig.png','-3','None',NULL,NULL,'Yig''s worshippers are actually disguised serpent people.  Their bite is highly poisonous.  Cultists have a combat rating of +0 and a combat damage of 4 Stamina.','Yig''s Anger - While Yig stirs in his slumber, he gains a doom token whenever a Cultist is defeated or an investigator is Lost in Time and Space.','Each investigator must pass a Speed (+1) check or lose 1 Sanity and 1 Stamina.  This check''s modifier decreases by 1 each turn (+0 the 2nd turn, -1 the 3rd turn, etc.)','Every investigator is Cursed. Any investigator that already has a Curse is devoured.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Yog-Sothoth',NULL,12,'/File:Yog-Sothoth.png','-5','Magical Immunity',NULL,NULL,'Yog-Sothoth''s worshippers have powerful magical abilities.  Cultists have Magical Immunity and a combat rating of -1.','The Key and the Gate - While Yog-Sothoth stirs in his slumber, the difficulty to close or seal a gate increases by 1.  In addition, any investigator Lost in Time and Space is devoured.','Each investigator must pass a Will (+1) check or lose 1 gate trophy.  Any investigator with no gate trophies left is devoured.  This check''s modifier decreases by 1 each turn (+0 the 2nd turn, -1 the 3rd turn, etc.)','Any investigator with no gate trophies is devoured.',NULL,NULL,NULL);
INSERT INTO ancient_ones VALUES ('Zhar','Innsmouth Horror',11,'/File:Zhar.jpg','-3','Special',NULL,NULL,'Zhar is worshipped by an evil tribe. Tcho-tchos and Tcho-tcho Priests gain Overwhelming 1','The Twin Horror - When a new gate opens, roll two dice. If doubles are rolled, immediately draw and resolve a mythos card.If Zhar awakens, it must be defeated twice. After removing its last doom token for the first time, any further successes from that attack are ignored and Zhar''s doom track is refilled.','Each investigator is in turn wrapped in a tentacle, then crushed. If no player has the Zhar token, give the Zhar token to the first player. That player then loses one hand for use in combat. If an investigator already has the Zhar token he is devoured. The first player marker does not get passed until its current holder is devoured.',NULL,NULL,NULL,'Zhar gains Magical Immunity. Once Zhar has been defeated once, this becomes Physical Immunity instead.');
