CREATE TABLE heralds (
    `list_title` VARCHAR(27) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8,
    `list_image` VARCHAR(78) CHARACTER SET utf8,
    `list_subtitle` VARCHAR(30) CHARACTER SET utf8,
    `list_effect` VARCHAR(222) CHARACTER SET utf8,
    `list_abilities_title` VARCHAR(30) CHARACTER SET utf8,
    `list_abilities_flavor` VARCHAR(330) CHARACTER SET utf8,
    `list_abilities_description` VARCHAR(975) CHARACTER SET utf8
);
INSERT INTO heralds VALUES ('Father Dagon','Innsmouth Horror','/File%3AFatherDagon.png','King of the Deep Ones','When Father Dagon is the Herald, place one uprising token on the Deep Ones Rising track at the start of the game and after each time the Feds raid Innsmouth. You must play with the Innsmouth board to use this Herald.','Plans Set in Motion','Vast, Polyphemous-like, and loathsome, it darted like a stupendous monster of nightmares to the monolith, about which it flung its gigantic scaly arms.','Draw and resolve one additional mythos card at the start of the game.Every time the terror level increases, each investigator must spend 1 Clue token. If one or more investigators are unable to do so, add one doom token to the doom track. Investigators who can spend a Clue token must still do so.');
INSERT INTO heralds VALUES ('Father Dagon','Innsmouth Horror','/File%3AFatherDagon.png','King of the Deep Ones','When Father Dagon is the Herald, place one uprising token on the Deep Ones Rising track at the start of the game and after each time the Feds raid Innsmouth. You must play with the Innsmouth board to use this Herald.','Teeming Masses',NULL,'If Cthulhu is the Ancient One, his combat rating is improved by -1 (to -7). When Cthulhu awakens, add up the total toughness of any monsters with the plus dimensional symbol in play. The investigators must inflict that many extra successes on Cthulhu in order to defeat him.');
INSERT INTO heralds VALUES ('Father Dagon','Innsmouth Horror','/File%3AFatherDagon.png','King of the Deep Ones','When Father Dagon is the Herald, place one uprising token on the Deep Ones Rising track at the start of the game and after each time the Feds raid Innsmouth. You must play with the Innsmouth board to use this Herald.','King and Queen',NULL,'Both Father Dagon and Mother Hydra may be used as Heralds during the same game. All of their effects are cumulative with each other. So, for instance, two uprising tokens are placed on the deep Ones rising track at the start of the game and after each time the Feds raid Innsmouth.');
INSERT INTO heralds VALUES ('Ghroth','Kingsport Horror','/File%3AGhroth.png','The Nemesis Moon','When Groth is the Herald, place two extra doom tokens on the Ancient One''s doom track at the start of the game.','The End is Near','The comet-god comes, singing to the stars and planets as it passes; waking the strange and terrible gods that lie slumbering beneath.','The Ancient One''s doom track begins the game with two extra doom tokens on it.');
INSERT INTO heralds VALUES ('Ghroth','Kingsport Horror','/File%3AGhroth.png','The Nemesis Moon','When Groth is the Herald, place two extra doom tokens on the Ancient One''s doom track at the start of the game.','Looming Omens',NULL,'Each time an Environment (Mystic) card is drawn from the mythos deck, every investigator must either spend a Clue token or else the first player rolls a die and consults the chart below:
1: Each investigator in Arkham loses 1 Sanity
2: Each investigator in Arkham loses 1 Stamina.
3-4: No effect.
5: Raise the terror level by 1.
6: Add a doom token to the Ancient One''s doom track.');
INSERT INTO heralds VALUES ('Lurker at the Threshold','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=AH_Lurker_Herald_sheet.png','The All-in-One and One-in-All','When the Lurker at the Threshold is the Herald, at the start of the game, shuffle the Reckoning deck and place it by the Herald sheet. Then place the Dark Pact cards near the Herald sheet and create a pool of Power tokens.','Rites of Magick',NULL,'Whenever an investigator casts a Spell, he may accept the Lurker at the Threshold''s aid. If he does so, he reduces the Sanity cost of the Spell to 0 and automatically passes the Spell check, but must immediately take a Blood Pact, Soul Pact, or Bound Ally card and follow its instructions. He must then draw and resolve a Reckoning card. (Note: an investigator may never have more than one of each kind of Dark Pact and may not accept the Lurker at the Threshold''s aid if he already has one of each kind of Dark Pact.)');
INSERT INTO heralds VALUES ('Lurker at the Threshold','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=AH_Lurker_Herald_sheet.png','The All-in-One and One-in-All','When the Lurker at the Threshold is the Herald, at the start of the game, shuffle the Reckoning deck and place it by the Herald sheet. Then place the Dark Pact cards near the Herald sheet and create a pool of Power tokens.','Ever-present Temptation',NULL,'At the start of any turn, an investigator may make a pact with the Lurker at the Threshold. If he does so, he takes a Blood Pact, Soul Pact, or Bound Ally card and follow its instructions. An investigator may take more than one type of Dark Pact card on his turn, but may never have more then one of each type of Dark Pact. (Note: do not draw and resolve a Reckoning card when you take a Dark Pact card at the start of a turn.)');
INSERT INTO heralds VALUES ('Lurker at the Threshold','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=AH_Lurker_Herald_sheet.png','The All-in-One and One-in-All','When the Lurker at the Threshold is the Herald, at the start of the game, shuffle the Reckoning deck and place it by the Herald sheet. Then place the Dark Pact cards near the Herald sheet and create a pool of Power tokens.','The One Beyond',NULL,'Each time a Gate opens, draw and resolve a Reckoning card. Do not draw and resolve a Reckoning card for the Gate that opens at the start of the game.');
INSERT INTO heralds VALUES ('Lurker at the Threshold','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=AH_Lurker_Herald_sheet.png','The All-in-One and One-in-All','When the Lurker at the Threshold is the Herald, at the start of the game, shuffle the Reckoning deck and place it by the Herald sheet. Then place the Dark Pact cards near the Herald sheet and create a pool of Power tokens.','They Shall Break Through Again',NULL,'Investigators receive –1 to all Fight and Lore checks to close or seal Gates.');
INSERT INTO heralds VALUES ('Mother Hydra','Innsmouth Horror','/File%3AMotherHydra.png','Queen of the Deep Ones','When Mother Hydra is the Herald, place one uprising token on the Deep Ones Rising track at the start of the game and after each time the Feds raid Innsmouth. You must play with the Innsmouth board to use this Herald.','The Lurking Horror','Swollen like some grotesque fertility idol worshipped by a forgotten tribe of men, the creature was nonetheless able to knife through the waves with terrifying grace and purpose. With a flash of shark teeth and a bloom of red, another sailor died screaming.','One extra monster appears each time a monster surge occurs.Each time an investigator is knocked unconscious, driven insane, lost in time and space, or devoured, draw one monster from the monster cup and place it in the outskirts.');
INSERT INTO heralds VALUES ('Mother Hydra','Innsmouth Horror','/File%3AMotherHydra.png','Queen of the Deep Ones','When Mother Hydra is the Herald, place one uprising token on the Deep Ones Rising track at the start of the game and after each time the Feds raid Innsmouth. You must play with the Innsmouth board to use this Herald.','Tekeli-li! Tekeli-li!',NULL,'If Cthulhu is the Ancient One, his combat rating is improved by -1 (to -7). When Cthulhu awakens, each investigator must lower either his maximum Sanity or maximum Stamina (his choice) by 1 for each Shoggoth or Proto-Shoggoth in play.');
INSERT INTO heralds VALUES ('Mother Hydra','Innsmouth Horror','/File%3AMotherHydra.png','Queen of the Deep Ones','When Mother Hydra is the Herald, place one uprising token on the Deep Ones Rising track at the start of the game and after each time the Feds raid Innsmouth. You must play with the Innsmouth board to use this Herald.','King and Queen',NULL,'Both Father Dagon and Mother Hydra may be used as Heralds during the same game. All of their effects are cumulative with each other. So, for instance, two uprising tokens are placed on the deep Ones rising track at the start of the game and after each time the Feds raid Innsmouth.');
INSERT INTO heralds VALUES ('The Black Goat of the Woods','The Black Goat of the Woods','/File%3AHeraldBlackGoatOfTheWoods.png','The Goat with a Thousand Young','When Black Goat of the Woods is the Herald, at the start of game, set aside all monster markers with the hexagon dimension symbol to form a hexagon monster cup.','Praises and Abundance','From the wells of night to the gulfs of space, from the gulfs of space to the wells of night, ever the praises of the Great Ones. Ever their praises and abundance to the Black Goat of the Woods! Iä! Iä! The Goat with a Thousand Young!','When a gate opens, draw a monster from the cup as normal, then draw a second monster from the hexagon cup and place both monsters on the gate''s location.
When a monster surge occurs, draw half the monsters (round down) from the hexagon cup.
Hexagon monsters are not removed from the game board when a hexagon gate is closed.
Each time an investigator defeats a hexagon monster, he or she draws a Corruption card.');
INSERT INTO heralds VALUES ('The Black Goat of the Woods','The Black Goat of the Woods','/File%3AHeraldBlackGoatOfTheWoods.png','The Goat with a Thousand Young','When Black Goat of the Woods is the Herald, at the start of game, set aside all monster markers with the hexagon dimension symbol to form a hexagon monster cup.','Lord of the Woods',NULL,'Dark Young move as normal monsters.');
INSERT INTO heralds VALUES ('The Black Goat of the Woods','The Black Goat of the Woods','/File%3AHeraldBlackGoatOfTheWoods.png','The Goat with a Thousand Young','When Black Goat of the Woods is the Herald, at the start of game, set aside all monster markers with the hexagon dimension symbol to form a hexagon monster cup.','Pagan Rites',NULL,'Each time a monster surge occurs, add one doom token to the doom track.');
INSERT INTO heralds VALUES ('The King in Yellow','The Tattered King','/wiki/index.php?title=Special%3AUpload&wpDestFile=HeraldTheKingInYellow2.png',NULL,'When the King in Yellow is the Herald, place the yellow sign tokens on this sheet, then shuffle the Blight deck and place it facedown near the board at the start of the game.','The Yellow Sign',NULL,'as if it were a doom token.');
INSERT INTO heralds VALUES ('The King in Yellow','The Tattered King','/wiki/index.php?title=Special%3AUpload&wpDestFile=HeraldTheKingInYellow2.png',NULL,'When the King in Yellow is the Herald, place the yellow sign tokens on this sheet, then shuffle the Blight deck and place it facedown near the board at the start of the game.','Yellow Sign Tokens',NULL,'The effects of yellow sign tokens vary based on where they are placed, and are described below:
Terror track: Each time the investigators place a yellow sign token on the terror track, the first player draws a random card from the Blight deck and places it into play.
Doom track: Yellow sign tokens placed on the doom track are treated exactly like doom tokens.');
INSERT INTO heralds VALUES ('Tulzscha','Kingsport Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=HeraldTulzscha.png','The Green Flame','When Tulzcha is the Herald, place one extra Cultist on the first open gate at the start of the game.','Preparing the Way','But what frightened me most was that flaming column, spouting volcanically from depths profound and inconceivable; casting no shadows as a healthy flame should, and coating the nitrous stone above with a nasty, venomous verdigris. For in all that seething combustion no warmth lay, but only the clamminess of death and corruption.','Place one Cultist on the first open gate at the start of the game in addition to the normal monsters that emerge from the gate.
Cultists are Elusive. When a Cultist adjacent to an elder sign token moves, it moves to that elder sign''s location. The Sky is considered to be adjacent to all locations for this purpose.
If a Cultist begins the Mythos Phase in the same location as an elder sign token, discard the elder sign token and return the Cultist to the cup.');
INSERT INTO heralds VALUES ('The Dark Pharaoh','Curse of the Dark Pharaoh (Revised Edition)','http://www.fantasyflightgames.com/ffg_content/Arkham_Horror/darkpharaohbig.jpg','Avatar of Nyarlathotep','When the Dark Pharoah is the Herald, place The Dark Pharoah monster token in the monster cup at the start of the game even if Nyarlathotep is not the Ancient One.','The Pharoah''s Curse','Know, O Thief, that these things are mine, For I am the Dark Pharoah, him of the Crawling Chaos. Take what is mine and your blood will boil in your skin, As I reveal to you my Other Faces and my True Glory.','The Pharoah''s curse has come to Arkham, following the Egyptian exhibit that is currently visiting Miskatonic University. The effects of the Pharoah''s curse are described below:
Know, O Thief: Each time an investigator gains a Unique Item (including starting equipment) that investigator loses 1 Sanity.
These Things are Mine: Each time an investigator gains an Exhibit item, roll a die. On a failure that investigator is Cursed.
Blood Will Boil: At the start of the Upkeep Phase, before rolling to get rid of Curses, each Cursed investigator loses 1 Stamina.
My Other Faces: All Mask monsters gain 1 toughness. In addition, each time a Mask monster is defeated, add one doom token to the Ancient One''s doom track.
My True Glory: If Nyarlathotep is the Ancient One and he awakens, his combat modifier increases by 1 (to -5, -6, etc.) and has one extra doom token placed on his doom track (for a total of 12, 13, etc.) for each Mask monster on the board.');
INSERT INTO heralds VALUES ('The Dunwich Horror','Miskatonic Horror','http://www.fantasyflightgames.com/ffg_content/Arkham_Horror/ahheraldbig.jpg','Son of Yog-Sothoth','When the Dunwich Horror is the Herald, place one Dunwich Horror token on the Dunwich Horror track at the start of the game. You must play with the Dunwich board to use this Herald.','The Whateley Prophecy','"Let me tell ye sumthin - some day yew folks''ll hear a child o'' Lavinny''s a-callin'' its father''s name on the top o'' Sentinel Hill!" - Wizard Whateley','The effects of the Whateley Prophecy are described below:
Unnatural Growth: The Dunwich Horror track starts out with one token on it at the start of the game and one additional token when the terror track reaches 3, 6, and 9. This is in addition to the normal conditions in which tokens are added to it.
Yog-Sothoth''s Child: The Dunwich Horror is considered to have a circle dimensional symbol as well as a moon dimensional symbol, but only for purposes of movement. It cannot be banished or pulled through a gate because of this symbol.
Father''s Name: When the Dunwich Horror moves, it adds a doom token to the Ancient One''s doom track on a 3-6 instead of a 4-6. (The version included in Miskatonic Horror activates on a roll of 2–6.)
Father and Son: If Yog-Sothoth is the Ancient One, and he awakens when the Dunwich Horror is on the board, Yog-Sothoth''s combat modifier increases by 3 (to -8) and he has five extra doom tokens placed on his doom track (for a total of 17).');
