CREATE TABLE arkham_asylum_encounters (
    `list_encounter` VARCHAR(444) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(11) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO arkham_asylum_encounters VALUES ('"Everything''s going to be fine," says a kindly patient in the lounge, seeming quite lucid.  He pats your hand, gets up, and walks off.  The strange thing is, you find yourself quite convinced.  Gain 3 Sanity.',NULL,'Kingsport Horror');
INSERT INTO arkham_asylum_encounters VALUES ('"It''s a new treatment," says the doctor, as orderlies you didn''t notice before grab your arms from behind.  "It''s very promising."  Roll a die.  On a success, restore both your Sanity and Stamina to their maximum values.  On a failure, reduce them to 1.',NULL,'Kingsport Horror');
INSERT INTO arkham_asylum_encounters VALUES ('"This one''s got some wisdom to him," one of the orderlies says as he shows you a withered old Egyptian scholar who was recently committed. "It''s like he seen somethin'', and if you look close in his eyes, you can see it too." If you look into the patient''s eyes, make a Will (-2) check. If you pass, you gain 4 Clue tokens. If you fail, you immediately go insane.','Will -2','Curse of the Dark Pharaoh');
INSERT INTO arkham_asylum_encounters VALUES ('A doctor working on dream therapy asks if you''d be willing to venture into a patient''s nightmares; he seems to be beset by dreams of animal-headed men, blinding sand, and strange pyramids. If you agree, you gain 3 Clue tokens but immediately move to the Dreamlands.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO arkham_asylum_encounters VALUES ('A patient becomes irrationally possessive over one of your belongings. Make a Fight (-3) check. If you fail choose 1 Common Item or Unique Item and discard it.','Fight -3','The Lurker at the Threshold');
INSERT INTO arkham_asylum_encounters VALUES ('A seemingly-sane inmate is willing to pay you to help him escape. If you agree to help, you may make a Sneak (-1) check. If you succeed, gain $3. If you fail, you are arrested.','Sneak -1','The Lurker at the Threshold');
INSERT INTO arkham_asylum_encounters VALUES ('A surprising number of society''s elite have checked in lately, and they need assistants to represent their interests during their "time abroad." Pass a Will (-2) check to gain a Retainer card.','Will -2','The King in Yellow');
INSERT INTO arkham_asylum_encounters VALUES ('A voice on the other side of a locked door sounds familiar. It seems like someone from your childhood, maybe a teacher or a friend of your parents. The voice calls out your name and promises you a slow, painful death. Lose 1 Sanity.',NULL,'The Black Goat of the Woods');
INSERT INTO arkham_asylum_encounters VALUES ('All of the Asylum''s patients begin speaking in the same strange tounge at once. Make a Lore (-1) check. If you pass, gain 1 Clue token as you realize that they''re all speaking ancient Sumerian, a language that only a few scholars in the world know!','Lore -1','Curse of the Dark Pharaoh');
INSERT INTO arkham_asylum_encounters VALUES ('An absentminded orderly hands you a clipboard containing the wrong form.  You''re about to point out his mistake when he snaps, "I haven''t got all day!  Are you the next of kin, or aren''t you?"  You sign the form to defuse his anger, and he hands you a bag containing some deceased soul''s personal effects.  Among them, you find $4.',NULL,'Kingsport Horror');
INSERT INTO arkham_asylum_encounters VALUES ('An inmate confides in you that he is actually a reporter, investigating the conditions at the asylum. He fears he will not keep his sanity much longer and begs you to smuggle his notes to Editor Doyle Jeffries. Pass a Sneak (-1) check to receive $3 for your troubles. If not, the nursing staff confiscates the notes and burns them. You must move to the street.','Sneak -1','The Black Goat of the Woods');
INSERT INTO arkham_asylum_encounters VALUES ('An irate orderly shoves a babbling madman at you, shouting "You deal with him!" before storming off. Pass a Will (-2) check to calm him down enough to decipher his ravings and gain 2 Clue tokens.','Will -2','Innsmouth Horror');
INSERT INTO arkham_asylum_encounters VALUES ('Doctor Mintz has a maniacal gleam in his eye as he approaches. Pass a Fight (-2) check to escape. If you fail, lose 1 Stamina and gain 1 Sanity under his new treatment.','Fight -2','Innsmouth Horror');
INSERT INTO arkham_asylum_encounters VALUES ('Doctor Mintz says that one of the patients has been specifically asking for you. The lunatic calmly offers to put you in touch with unearthly power in exchange for information. For each Clue token you spend, you may draw 1 Spell. Choose 1 Spell to keep from among those you draw and discard the others.',NULL,'The Black Goat of the Woods');
INSERT INTO arkham_asylum_encounters VALUES ('Getting lost as you wander the halls, you wind up in the basement just in time to see two orderlies toss a bodybag into the furnace.  Make a Luck (-1) check.  If you pass, you manage to quietly flee the asylum.  Move to the street.  If you fail, you cry out, attracting their attention.  Fleeing through the halls, you eventually lose them, but not before hours have passed.  Stay here next turn.','Luck -1','Dunwich Horror');
INSERT INTO arkham_asylum_encounters VALUES ('In the Doctor''s study, you find a book of helpful notes gathered from inmate interviews.  Make a Lore (+0) check and consult the following chart:Successes:0) Their stories fill you with horror even as you learn a few bits of knowledge.  Lose 1 Sanity and gain 1 Clue token.1-2) You find several pieces of useful information.  Gain 2 Clue tokens.3+) One of the interviews contains vital information.  Gain 3 Clue tokens.','Lore +0',NULL);
INSERT INTO arkham_asylum_encounters VALUES ('Nurse Heather accidentally injects you with a sleeping draught. You may make a Fight (-2) check to resist.  If you fail or choose not to resist, lose your next turn and gain 2 Sanity from the prolonged rest.  If you pass, nothing happens.','Fight -2',NULL);
INSERT INTO arkham_asylum_encounters VALUES ('Nurse Heather is coming!  Make a Speed (-1) check to hide in time.  If you pass you see her drop something as she walks by.  Draw 1 Unique Item.  If you fail, she throws you out.  Move to the street.','Speed -1',NULL);
INSERT INTO arkham_asylum_encounters VALUES ('On the Healing of Mind and Spirit is the title of the book you find sitting, unattended, on one of the end tables in the lounge.  Intrigued, you flip through its pages.  Restore your Sanity to its maximum and gain a Clue token.',NULL,'Kingsport Horror');
INSERT INTO arkham_asylum_encounters VALUES ('One of the doctors seems especially interested in your dreams.  "Dreams are the key to the subconscious, and you clearly have some very deep-seated issues."  Amazingly, telling someone else about your nightmares seems to free you of them.  Stay here next turn and restore your Sanity to its maximum value.',NULL,'Dunwich Horror');
INSERT INTO arkham_asylum_encounters VALUES ('One of the doctors tells you about an experimental treatment that might help you.  It''s expensive, however.  You may pay $5 to roll a die.  On a success, discard one of your Madness cards.  On a failure, gain 2 Sanity.',NULL,'Dunwich Horror');
INSERT INTO arkham_asylum_encounters VALUES ('One of the doctors tells you about an experimental treatment that might help you.  It''s expensive, however.  You may pay $5 to roll a die.  On a success, discard one of your Madness cards.  On a failure, gain 2 Sanity.',NULL,'Dunwich Horror');
INSERT INTO arkham_asylum_encounters VALUES ('One of the doctors tries hypnotic therapy to allow you to tap into your subconscious.  You have strange visions of faraway places and times that allow you to reach a greater understanding of yourself.  Gain 1 Sanity and 2 Clue tokens.',NULL,'Dunwich Horror');
INSERT INTO arkham_asylum_encounters VALUES ('Sneaking into the file room, you begin looking through the patient interviews for information that could be of use to you.  If you pass a Lore (-1) [2] check, then roll a die and gain that many Clue tokens.  If you fail, nothing happens.','Lore -1 [2]','Dunwich Horror');
INSERT INTO arkham_asylum_encounters VALUES ('The doctors allow you to observe the therapy session of one of the asylum''s most disturbed patients. Make a Will (-1) check to maintain your wits enough to garner useful information from his story. If you pass, gain 2 Clue tokens. Then, whether you pass or not, lose 1 Sanity after learning of his bone-chilling experiences.','Will -1','The Lurker at the Threshold');
INSERT INTO arkham_asylum_encounters VALUES ('The guards of the sanitarium are aware that there is an intruder.  Make a Sneak (-1) check to escape.  If you pass, move to the street.  If you fail, you are arrested and taken to the Police Station.','Sneak -1',NULL);
INSERT INTO arkham_asylum_encounters VALUES ('The inmates begin to chant in unison, screaming about the "black Kem of Re and Amen, Isis, and Osiris!" It nearly drives you mad - but that which doesn''t kill you only makes you stronger. If your Will is 1 or lower, you may search the Skill deck and take the Will card.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO arkham_asylum_encounters VALUES ('The more time you spend with them, the more their ramblings make sense. Gain up to 3 Clue tokens, but for every Clue token you take, you lose 2 Sanity.',NULL,'The King in Yellow');
INSERT INTO arkham_asylum_encounters VALUES ('The screams of the insane drive you out of the Asylum... but then you realize that you can still hear them in your mind, praising the coming of the Dark Pharaoh! Take the Psychic card, but you cannot stand to be near the Asylum: You are Barred from Downtown.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO arkham_asylum_encounters VALUES ('The screams of the insane seem to permeate the Asylum... and you realize that you are hearing the voices in your mind! You cry out to silence voices only you can hear. Passers-by stare at you suspiciously. Place a Patrol marker on the street area of Downtown Then take the Psychic card, if it is available.',NULL,'Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO arkham_asylum_encounters VALUES ('Volunteers for art therapy are requested. The inmates'' paintings are a window into their madness. Pass a Will (-1) check to gain 2 Clue tokens. If you fail, lose 1 Sanity.','Will -1','The King in Yellow');
INSERT INTO arkham_asylum_encounters VALUES ('You are mistaken for an inmate.  Doctor Mintz has the guards subdue you and conducts an experiment.  Make a Will (-1) [2] check to discover the results.  If you pass, the injections seem to increase your capacity for learning.  Draw 1 Skill.  If you fail, his memory drug fails miserably, resulting in lost knowledge.  You must discard one of the following (your choice), if able: 4 Clue tokens, or 2 Spells, or 1 Skill.','Will -1 [2]',NULL);
INSERT INTO arkham_asylum_encounters VALUES ('You discover that the patient you''ve been looking for has been lobotomized. He can''t answer your questions now. Draw one Ally card from the Ally deck and return it to the box.',NULL,'The Lurker at the Threshold');
INSERT INTO arkham_asylum_encounters VALUES ('You discover two men struggling, each claiming that he is a doctor and that the other is an inmate. Make a Luck (-2) check. If you succeed, you assist the real doctor in subduing the patient and regain 2 Sanity as you reaffirm your ability to discern between the rational and the mad. If you do not succeed, lose 2 Stamina as the real maniac stabs you in the back.','Luck -2','The Black Goat of the Woods');
INSERT INTO arkham_asylum_encounters VALUES ('You feel a moment''s guilt at wandering into a restricted area, but something''s just not right in this place.  Unfortunately, before you can get far, Nurse Heather steps up behind you and injects something into your arm.  "Come with me. You shouldn''t be back here."  Your head swimming, you easily agree with her.  The next thing you know, you''re standing outside the gates with no memory of what happened.  Move to the street and gain 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO arkham_asylum_encounters VALUES ('You find some strange medicine labeled "Dream Enhancers" in a dusty cabinet.  If you choose to take it, make a Lore (-1) check.  If you pass, your visions show you how to perform a ritual.  Draw 1 Spell.  Otherwise, nothing happens.','Lore -1',NULL);
INSERT INTO arkham_asylum_encounters VALUES ('You hear Nurse Heather use your name in a discussion with an orderly. They must know you''re here! Make a Sneak (-1) check to eavesdrop. If you pass, gain 1 Clue token. If you fail, you''re thrown out. Move to the street.','Sneak -1','Innsmouth Horror');
INSERT INTO arkham_asylum_encounters VALUES ('You hear a strange singsong voice that says, "The way of an eagle in the air; the way of a serpent upon the rock." Pass a Lore (-1) check to gain 1 Clue token','Lore -1','The King in Yellow');
INSERT INTO arkham_asylum_encounters VALUES ('You hear screaming.  When you open a heavy cell door to investigate, a dark shape leaps out at you!  It''s an insane man in a straightjacket babbling about invisible horrors.  Make a Lore (-2) check to glean some useful information from him.  If you pass, gain 2 Clue tokens.  If you fail, lose 1 Stamina as he attacks you.','Lore -2',NULL);
INSERT INTO arkham_asylum_encounters VALUES ('You sneak into a finger-painting session. Gain 1 Sanity.',NULL,'Innsmouth Horror');
