CREATE TABLE bank_of_arkham_encounters (
    `list_encounter` VARCHAR(439) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(20) CHARACTER SET utf8,
    `list_expansion` VARCHAR(27) CHARACTER SET utf8
);
INSERT INTO bank_of_arkham_encounters VALUES ('"Have you come to empty out your safety deposit box?" One of the tellers hands you a key. "This way, please." Confused, you follow her as she leads you down into the vault, where you retrieve a small box and open it up with the key. Make a Luck (-1) check. If you pass, you find an odd object inside. Gain 1 Unique Item. If you fail, the box contains only a stern warning for you to flee Arkham immediately, never to return. Lose 1 Sanity.','Luck -1','Dunwich Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('"Please," says the man outside the bank. "We lost everything. Please help." For every $1 you give him, gain 1 Sanity.',NULL,'Innsmouth Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('"This is a stick-up, see? Nobody move!" Three men armed with tommy guns rob the bank while you''re standing in line. Make a Combat (-1) check. If you pass, you drive them off. Nothing happens. If you fail, lose all of your money.','Combat -1',NULL);
INSERT INTO bank_of_arkham_encounters VALUES ('"You''ve miscounted," says the teller, recounting your deposit and demonstrating that-- sure enough-- you had two dollars more than you thought. Gain $2.',NULL,'Kingsport Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('A child is struggling to bring an enormous jar of pennies to the teller. You may make a Fight (-1) check to help him out. If you pass, gain 1 Sanity and $1 for your efforts. If you fail, lose 1 Stamina.','Fight -1','The Lurker at the Threshold');
INSERT INTO bank_of_arkham_encounters VALUES ('A dirty, bedraggled man in Egyptian robes stops you on your way into the bank, and intones, "It is easier for a camel to pass through the eye of a needle than it is for a rich man to enter heaven!" If you discard all of your money, you are Blessed.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO bank_of_arkham_encounters VALUES ('A group of women are collecting charitable donations on behalf of orphans and widows. If you contribute $3, regain 1 Sanity as they thank you profusely.',NULL,'The Black Goat of the Woods');
INSERT INTO bank_of_arkham_encounters VALUES ('A large painting of historic Arkham hangs in the bank lobby. Examining it, you notice an unnerving circle of stones barely visible on the edge of the city. Lose 1 Sanity.',NULL,'The Lurker at the Threshold');
INSERT INTO bank_of_arkham_encounters VALUES ('A little old lady stands in front of you in line counting out a bag of pennies to deposit. Lose 1 Sanity.',NULL,NULL);
INSERT INTO bank_of_arkham_encounters VALUES ('A man approaches you with a business proposition. "The Bank won''t give me any money, but I know I can make us a fortune!" If you''re interested in investing, give him $5 and take a Retainer card.',NULL,'The Black Goat of the Woods');
INSERT INTO bank_of_arkham_encounters VALUES ('A man wearing dirty and tattered clothing is loitering outside the bank. He offers to sell you his last possession to get some food money for him and his family. If you accept, pay $2 and make a Luck (-1) check. If you pass, draw 1 Unique Item. If you fail, draw 1 Common Item.','Luck -1',NULL);
INSERT INTO bank_of_arkham_encounters VALUES ('A teller you''ve never seen before insists she just saw you come in and make a deposit the day before. She proves it by showing you your signature. Gain $5, but lose 1 Sanity.',NULL,NULL);
INSERT INTO bank_of_arkham_encounters VALUES ('A young woman is examining the contents of a safe deposit box bequethed to her by her late mother. It is an ancient book written in a language she doesn''t understand, and she asks you if you recognize the language. Make a Lore (-1) [2] check. If you pass, gain 2 Clue tokens as you decipher the text.','Lore -1 [2]','The Lurker at the Threshold');
INSERT INTO bank_of_arkham_encounters VALUES ('An old woman has just absentmindedly left the envelope the teller gave her behind. Will you return it to her? You may either gain $5 or become Blessed.',NULL,'Innsmouth Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('As you stand in line for the teller, the bank Vice President motions you over to his office. "We''re aware of the good you''ve done. The Bank of Arkham thanks you." You may spend  10 toughness worth of monster trophies, 1 gate trophy and 5 toughness worth of monster trophies, or 2 gate trophies to either gain $10 or to discard any investigator''s Bank Loan.',NULL,'Kingsport Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('As you step in front of the teller line, you see that there are two windows open. "Next!" both call out at the same time. Make a Luck (-1) check. If you succeed, your are Blessed. If you fail, you are Cursed.','Luck -1','Kingsport Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('Father Michael is hesitant to walk back to South Church alone, saying that the "Legacy of the Pharaohs" exhibit has cast a pall upon Arkham. If you escort him, move immediately to South Church. Do not have an encounter there, but you may trade in monster and gate trophies to be Blessed as described at that location. If you escort him and have the Motorcycle or Map item or the Mists of Releh spell, you are Blessed for free.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO bank_of_arkham_encounters VALUES ('It seems that bank interest rates are especially favorable today. You may take out a Bank Loan if you don''t already have one. If you do so, Gain $15 instead of the normal $10. However, you still only need to pay back the normal $10.',NULL,'Dunwich Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('Looking down at your bank statement, it appears that the bank has made an error in your favor. When you try to bring it to the teller''s attention, she primly tells you, "We don''t make mistakes here at the First Bank of Arkham." Shrugging, you keep the money. Gain $3.',NULL,'Dunwich Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('One of the other customers in the bank recognizes you and offers you a lift. Move to any location or street area in Arkham. If you move to a location, immediately have an encounter there.',NULL,NULL);
INSERT INTO bank_of_arkham_encounters VALUES ('The bank guard starts making friendly conversation with you about the people he sees every day. Make a Luck (+0) check. If you pass, gain 1 Clue token. If you fail, his manager interrupts him before he can share anything useful.','Luck +0','The Black Goat of the Woods');
INSERT INTO bank_of_arkham_encounters VALUES ('The bank hosts a fund drive for the arts. If you spend $1 to make a donation, you are entered in a lottery. Pass a Luck (-2) check to draw 1 Unique Item.','Luck -2','The King in Yellow');
INSERT INTO bank_of_arkham_encounters VALUES ('The bank offers a special incentive to anyone who opens an account: Take out a loan and get free tickets to the next performance of "The King in Yellow." You may take out a Bank Loan if you don''t already have one, gaining $12 from the loan instead of $10. However, if you do so, you also lose 1 Sanity.',NULL,'The King in Yellow');
INSERT INTO bank_of_arkham_encounters VALUES ('The bank Vice President tucks something into your pocket as he passes by. "A bit of help for you and your friends," he whispers in your ear. All investigators gain $1.',NULL,'Kingsport Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('The line stretches on forever. However, you hear two people in front of you whispering something important. Gain 1 Clue token, but stay here next turn.',NULL,'Dunwich Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('The lines of businessmen. The tellers at their alters. The communion of the safety deposit room. In a flash of insight, or perhaps madness, you realize that a bank is simply another form of church and that whatever god it is consecrated to is watching you. You may spend any or all of your Sanity. After spending the Sanity, roll 1 die for each point you spent. If you rolled any successes, you are Blessed.',NULL,'The King in Yellow');
INSERT INTO bank_of_arkham_encounters VALUES ('The money you''ve just withdrawn is not from any country you know. Gain $3, but pass a Will (-1) check or lose 1 Sanity.','Will -1','Innsmouth Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('The old man behind you in line hands you a folded paper oracle. "Lucky five. Trust me." Folding it back and forth five times, you lift the paper flap to see what it says. Make a Luck (-1) check. If you pass, it says, "Fortune favors you." You are Blessed. If you fail, it says, "Too bad." You are Cursed.','Luck -1','Dunwich Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('The old man standing outside the bank looks into you face hopefully. "Spare some change?" If you give him $2 or discard a Whiskey card, he whispers a few words of power in your ears. Draw 1 Spell. If you do not give him $2, nothing happens.',NULL,'Dunwich Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('The strange events have prompted a mob of people to empty their accounts and leave town. Pass a Will (-2) check to change their minds or the bank closes for the rest of the game. Move to the street.','Will -2','The Black Goat of the Woods');
INSERT INTO bank_of_arkham_encounters VALUES ('The teller hands you a safety deposit box key. "This is for you." If you choose  to open the box, make a Luck (-2) check. If you pass, draw 1 Unique item. If you fail, lose 2 Sanity and move to the street as you flee the bank in terror.','Luck -2','Innsmouth Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('You are retrieving some papers from the safety deposit vault when a portal to another place and time suddenly opens, nearly sucking the guard in! If you push him out of the way, you are Blessed, but must immediately move to the Plateau of Leng.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO bank_of_arkham_encounters VALUES ('You find a penny with a strange sigil carved into it. Amused, you flip it in the air, but then gasp as you feel the sudden gathering of magical forces around you. Make a Luck (-2) check. If you pass, the penny comes up heads. You are Blessed. If you fail, it comes up tails. you are Cursed.','Luck -2','The Lurker at the Threshold');
INSERT INTO bank_of_arkham_encounters VALUES ('You find a penny with a strange sigil carved into it. Amused, you flip it in the air, then gasp as you feel the sudden gathering of magical forces around you. Make a Luck (-2) check. If you pass, the penny comes up heads. You are Blessed. If you fail, it comes up tails. You are Cursed.','Luck -2',NULL);
INSERT INTO bank_of_arkham_encounters VALUES ('You head up the steps as a bank robber in a mask dashes out, running into you and dropping a sack full of money. If you would like to return the money, gain 1 Sanity. If you want to keep it and run away, gain $10 but lose 1 Sanity and take the Wanted card.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO bank_of_arkham_encounters VALUES ('You recognize several members of the Sheldon Gang in line. If you have a Sheldon Gang Membership, you keep silent as they run a classic con on the bank teller, and they slip you $4 on the way out of the bank. If you do not have a membership, knowing that they''ve got to be up to no good, you warn the bank guard and directs them to leave. However, you get punched in the stomach by one of the Sheldon boys on their way out. Lose 1 Stamina.',NULL,'Dunwich Horror');
INSERT INTO bank_of_arkham_encounters VALUES ('You see a customer going into seizures. If you want to try to help, make a Fight (-2) check to restrain him and keep him from hurting himself or a Lore (-2) check to correctly sedate him. If you fail, lose 2 Stamina as he lashes out. If you pass, the convulsions subside and a nun rushes to you side, saying, "Bless you, good sir, for helping." You are Blessed.','Fight -2
OR
Lore -2
','Curse of the Dark Pharaoh');
INSERT INTO bank_of_arkham_encounters VALUES ('You see a richly dressed man making a large withdrawal. On the way out, he lights his cigar with a piece of green paper which he then drops on the ground. Pass a Speed (-1) check to stub it out with your toe before it burns up. You discover it to be a slightly singed two dollar bill. Gain $2.','Speed -1',NULL);
INSERT INTO bank_of_arkham_encounters VALUES ('You wander past the bank after hours, and see the night watchman convulsing on the floor! Make a Fight (-2) check to restrain him. If you fail, you lose 1 Stamina. If you pass, he begins speaking in tongues, and some unknown power Blesses you.','Fight -2','The King in Yellow');
