CREATE TABLE curiositie_shoppe_encounters (
    `list_encounter` VARCHAR(471) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(11) CHARACTER SET utf8,
    `list_expansion` VARCHAR(27) CHARACTER SET utf8
);
INSERT INTO curiositie_shoppe_encounters VALUES ('"According to legend, this mirror was once used to travel from our world into the lands beyond. Does this interest you?" If you wish, you may discard any Common Item, Unique Item, or Spell to move to the first area of any Other World.',NULL,'The Lurker at the Threshold');
INSERT INTO curiositie_shoppe_encounters VALUES ('"Durn roof keeps leakin''... ruinin'' my wares!" If you offer to fix the roof for the shopkeeper, make a Speed (-1) check. If you fail, you fall and lose 2 Stamina. If you pass, he is grateful, and offers to give you any Common Item in the deck with a value equal to or lower than your number of successes.','Speed -1','Curse of the Dark Pharaoh');
INSERT INTO curiositie_shoppe_encounters VALUES ('"Free. Help yourself." Make a Lore (-1) check to repair the item you find beneath the sign. If you pass, draw 1 Common Item. If you fail, lose 1 Stamina as you injure yourself.','Lore -1','The King in Yellow');
INSERT INTO curiositie_shoppe_encounters VALUES ('"Perhaps we can help each other." Oliver Thomas, the shopkeep, searches you face with a speculative look. "If you have some information for me, I could teach you something extremely useful." You may pay 2 Clue tokens to draw 1 Spell.',NULL,'Dunwich Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('A man with a crate checks his watch outside the locked shop as you walk up. Seeing you, he turns. "Do you know anyone who might be interested in these? I just want to be rid of them." Turn over the top three Unique Item cards. Any players may buy them for their list prices. If players disagree about who may buy what, you decide.',NULL,'Kingsport Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('A portrait half obscured behind a bookshelf catches your eye. There''s something strange about it, but you''re in no mood to move the shelf. On the other hand, you''d be a fool to ignore the gnawing feeling that the pattern-- which you can just barely make out-- might be important. Make a Lore (-2) [2] check. If you succeed, search the Unique Items deck for an Elder Sign.','Lore -2 [2]','Kingsport Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('A pulsing void gapes behind a bookshelf, sending out waves of heat. Pass a Fight (-1) check or it sucks you in, hurling you into the Abyss. Have one encounter there, then immediately return.','Fight -1',NULL);
INSERT INTO curiositie_shoppe_encounters VALUES ('A sale takes place. All players may participate. Turn over the top 3 Common Item cards and the top Unique Item card. Any player may buy one or more of these cards for their list price. If there is a disagreement over who gets to buy a certain card, you decide. Any items not sold are discarded.',NULL,NULL);
INSERT INTO curiositie_shoppe_encounters VALUES ('A sale takes place. All players may participate. Turn over the top 2 Common Item cards and the top 2 Unique Item cards. Any player may buy one or more of these cards for their list price. If there is a disagreement over who gets to buy a certain card, you decide. Any items not sold are discarded.',NULL,'Dunwich Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('A sale takes place. All players may participate. Turn over the top 2 Common Item cards and the top 2 Unique Item cards. Any player may buy one or more of these cards for their list price. If there is a disagreement over who gets to buy a certain card, you decide. Any items not sold are discarded.',NULL,'The Black Goat of the Woods');
INSERT INTO curiositie_shoppe_encounters VALUES ('An elderly blind man is running his hand along shelves, searching for a mysterious object. If you help him, he will gratefully offer to purchase something else in the store for you. Search the Common Item deck for one free item of your choice and be Blessed. Or instead, you can take the mysterious object for yourself. Search the Unique Item deck for one item of your choice to purchase for list price.',NULL,'Innsmouth Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('As you wander into the back of the shop, you hear a noise. Pass a Speed (-1) check or you look up just in time to see a descending club. Everything goes black. When you awaken, you are somewhere else. Draw a mythos card and move to the gate location shown on it, then immediately have an encounter there.','Speed -1',NULL);
INSERT INTO curiositie_shoppe_encounters VALUES ('Examining a fragile vase, it slips out of your hands. Pass a Speed (-1) check to catch it or Oliver Thomas makes you buy it for $3. If you fail to catch it and don''t have $3, move to the street.','Speed -1','The Black Goat of the Woods');
INSERT INTO curiositie_shoppe_encounters VALUES ('If you look hard, you can find some real bargains here! Draw a number of cards from the Common Item deck equal to your focus (maximum 3). You may purchase any of the drawn items for $1 less than the list price, and must discard the rest.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO curiositie_shoppe_encounters VALUES ('Jackpot! You find just what you''ve been looking for. Search either the Common or Unique Item deck and purchase any one item of your choice at list price.',NULL,NULL);
INSERT INTO curiositie_shoppe_encounters VALUES ('Oliver Thomas has an extremely rare book on display, but it is not for sale. He''s willing to let you have a look at it. Make a Will (-1) check to quickly memorize as much as you can of this informative text. Gain 1 Clue token for each success you roll.','Will -1','The Lurker at the Threshold');
INSERT INTO curiositie_shoppe_encounters VALUES ('Oliver Thomas, the shopkeeper, greets you enthusiastically. "There was an item here earlier that I just knew was meant for you. I''m not sure where it went, but I imagine if it was meant to be, you''ll be able to find it." Make a Will (-2) check. If you pass, gain 1 Unique Item. If you fail, gain 1 Common Item.','Will -2','The Lurker at the Threshold');
INSERT INTO curiositie_shoppe_encounters VALUES ('Oliver Thomas, the wizened old owner of the Curiositie Shoppe, offers you a fortune cookie. Thanking him, you open it, only to be overcome by a wave of dizziness as a hazy vision of the future rushes past your eyes. You may search the mythos deck for any one card and return it to the box.',NULL,'Dunwich Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('On a high shelf is a puzzle box. You may spend $1 to purchase it and then pass a Lore (-1) check and consult the following chart to determine what''s inside:Successes:0) Nothing1) Gain $3 and a Clue token2+) Draw a Spell and gain $5','Lore -1','Innsmouth Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('Other customers are intrigued by your knowledge of the items in the shop. The more you describe the histories of these objects, the more people purchase. Make a Lore (+0) check. If you pass, Oliver Thomas is so grateful for your help with sales that he offers you $3 for your efforts.','Lore +0','The Lurker at the Threshold');
INSERT INTO curiositie_shoppe_encounters VALUES ('Pass a Luck (-1) check or you accidentally drop an item. Discard 1 item of your choice. If you have no items to drop, then draw again for a different encounter.','Luck -1',NULL);
INSERT INTO curiositie_shoppe_encounters VALUES ('The shop seems to be closed early. You peer through the windows and see... something your mind cannot comprehend! Lose 1 Sanity.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO curiositie_shoppe_encounters VALUES ('The shopkeeper eyes one of your possessions. "I have need of that object. Will you sell it to me?" You may sell any one of your Unique Items for twice its listed price.',NULL,'Dunwich Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('The shopkeeper eyes one of your possessions. "I have need of that object. Will you sell it to me?" You may sell any one of your Unique Items for twice its listed price.',NULL,'Dunwich Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('The shopkeeper eyes one of your possessions. "I have need of that object. Will you sell it to me?" You may sell any one of your Unique Items for twice its listed price.',NULL,'Innsmouth Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('The shopkeeper has purchased a display of kitschy Egyptian items to drum up business. Make a Lore (+0) check. If you fail, it looks realistic to you. If you pass, you point out a few items that are set up improperly, and help him rearrange the display. In return, he offers you any one non-Weapon Common Item at half price.','Lore +0','Curse of the Dark Pharaoh');
INSERT INTO curiositie_shoppe_encounters VALUES ('There are some amusing games at the Shoppe to celebrate the opening night of "The King in Yellow." Correctly guess the cost of the next Common Item in the deck, and you get to keep that item! Otherwise, discard it.',NULL,'The King in Yellow');
INSERT INTO curiositie_shoppe_encounters VALUES ('There''s an inscription on the back of this mirror! If you spend $3 to purchase it, you can attempt to translate it. Pass a Lore (-1) check and draw 1 Spell if you pass.','Lore -1','The Black Goat of the Woods');
INSERT INTO curiositie_shoppe_encounters VALUES ('You are looking over an unusual item when Oliver Thomas, the shopkeep walks up behind you. "Oh, you don''t want that," he says. "Of course, if you''ll take it off my hands, you can have it for free." You may search the Unique Item deck for any one card and take it. If you do so, you are Cursed.',NULL,'Dunwich Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('You come across a blasphemous idol sitting innocently on a shelf. Lose 1 Sanity.',NULL,'Innsmouth Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('You disturb one of the antiques in the shop and a large cloud of dust rises from it. Coughing, you go outside for some fresh air. Move to the street.',NULL,'Dunwich Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('You don''t see anyone in the shop, and yet a small army of wind-up toys wheel their way across the floor towards you. Lose 1 Sanity.',NULL,'The Black Goat of the Woods');
INSERT INTO curiositie_shoppe_encounters VALUES ('You examine an obscene statue. Pass a Luck (-2) check or else you feel a cold dread spread through your body as you hold it. You are Cursed.','Luck -2',NULL);
INSERT INTO curiositie_shoppe_encounters VALUES ('You find a dead cat on the front stoop of the shop. Pass a Luck (-1) check to find the weapon that killed it in the grass nearby. Search the Common Item deck and take the first Weapon you find.','Luck -1','The King in Yellow');
INSERT INTO curiositie_shoppe_encounters VALUES ('You get into a debate with the shopkeeper regarding the value of material wealth vs. knowledge, and he challenges you to prove your point. If you pass a Will (-1) check, you may discard a Common Item or any number of Clue tokens. If you discard a Common Item, draw a number of Clue tokens equal to its value. If you discard Clue tokens, search the Common Item deck and take any number of items with a total value equal to or less than the number of Clue tokens discarded.','Will -1','Curse of the Dark Pharaoh');
INSERT INTO curiositie_shoppe_encounters VALUES ('You hear a clatter and a curse. Rushing to the sound, you find Oliver Thomas rubbing a bruised elbow among spilled curios. "Damned rubbish!" he seethes. "Take it away and any that''s not broken is yours!" Make a Luck (-2) check. If you succeed, draw 3 Unique Item cards and keep any that cost $4 or less. Discard the rest.','Luck -2','Kingsport Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('You never know what you''ll find in the lost and found box. Spend up to $5. For each $1 you pay, draw one card from the Common Item deck. You may keep one card, but you must discard the rest.',NULL,'The King in Yellow');
INSERT INTO curiositie_shoppe_encounters VALUES ('You trip over a stack of books obviously undisturbed for years, if not decades. Make a Lore (-1) check. If you succeed, search the Unique Item deck and take the first Tome you find.','Lore -1','Kingsport Horror');
INSERT INTO curiositie_shoppe_encounters VALUES ('You weed through piles of junk looking for something useful. Make a Luck (-1) check to see what you find. If you pass, your search has resulted in success. You may look at the top cards of both the Common and Unique Item decks. You may purchase one, both, or neither at list price.  If you fail, there is little of interest here, but you may look at the top card of the Common Item deck and purchase it for its list price.','Luck -1',NULL);
