CREATE TABLE hibbs_roadhouse_encounters (
    `list_encounter` VARCHAR(376) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(9) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO hibbs_roadhouse_encounters VALUES ('"Care to make a couple extra bucks?" The proprietor needs some help moving in the new pool table. Make a Fight (-1) check and gain $2 if you pass.','Fight -1','The Lurker at the Threshold');
INSERT INTO hibbs_roadhouse_encounters VALUES ('"Friendly game of pool?" Make a Speed (+0) check and consult the chart below.Successes:0) You lose $3.1-2) You notice that your opponent is cheating! If you confront him, he shoves $3 at you but scowls, telling you you''d better not come back here. You are Barred from Easttown.3) You gain $3.','Speed +0','Curse of the Dark Pharaoh');
INSERT INTO hibbs_roadhouse_encounters VALUES ('"Friendly game of pool?" Make a Speed (+0) check and consult the chart below.Successes:0) You lose $3.1-2) You notice that your opponent is cheating! If you confront him, place a Patrol marker on the street area of Easttown and gain $3. As he shoves the money at you, he scowls, telling you you''d better not come back here.3) You gain $3.','Speed +0','Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO hibbs_roadhouse_encounters VALUES ('"Hey, psst. You look like someone who could use a little information." Looking over at the bartender, you see him holding out his hand. You may pay him up to $6, gaining 1 Clue Token for every $2 you pay him.',NULL,'Dunwich Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('"Hey, psst. You look like someone who could use a little information." Looking over at the bartender, you see him holding out his hand. You may pay him up to $6, gaining 1 Clue Token for every $2 you pay him.',NULL,'Innsmouth Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('"Nothing interesting''s happened here in a week," sighs a bored barfly as you step up to the bar. Taking stock of the mostly empty place, you believe it. As you think better and turn to go, the man takes a cue from the owner''s dirty look and stands to go with you, asking "Where are you headed?" Take Ryan Dean''s Ally card. If it''s not available, draw two Common Items instead.',NULL,'Kingsport Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('"So, what''s your story, friend?" A smiling man inquires about your adventures over a glass of gin. You tell him your story. If you spend 3 Clue Tokens, he introduces himself as Ryan Dean and asks to join you. Take his Ally card. If it''s not available, he gives you some useful items instead. Draw 2 Common Items.',NULL,NULL);
INSERT INTO hibbs_roadhouse_encounters VALUES ('"So, what''s your story, friend?" A smiling man inquires about your adventures over a glass of gin. You tell him your story. If you spend 3 Clue Tokens, he introduces himself as Ryan Dean and asks to join you. Take his Ally card. If it''s not available, he gives you some useful items instead. Gain 2 Common Items.',NULL,'Dunwich Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('"So, what''s your story, friend?" A smiling man inquires about your adventures over a glass of gin. You tell him your story. If you spend 3 Clue Tokens, he introduces himself as Ryan Dean and asks to join you. Take his Ally card. If it''s not available, he gives you some useful items instead. Gain 2 Common Items.',NULL,'The Black Goat of the Woods');
INSERT INTO hibbs_roadhouse_encounters VALUES ('"You''re in my seat, friend," says someone behind you. If you succeed in a Will (-1) check, you stare him down and keep you chair. If you fail, his meaty associates toss you in their trunk and dump you somewhere. Draw a Mythos card and move to the Gate location shown on it, then have an encounter in your new location.','Will -1','Kingsport Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A barfly sits down next to you and shares boring and incoherent stories. Make a Will (-1) check to endure these dull tales until he''s finished talking. If you pass, he tells you, "You''re a good sort," and offers you a gift. Draw 1 Common Item.','Will -1','The Lurker at the Threshold');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A horrible monster appears!',NULL,NULL);
INSERT INTO hibbs_roadhouse_encounters VALUES ('A horrible Monster appears!',NULL,'The Black Goat of the Woods');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A horrible monster appears!',NULL,'Innsmouth Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A man sets down a briefcase, muttering furtively. "Have you seen the yellow sign?" Pass a Lore (-3) check to draw the yellow sign in a pool of beer on the counter, at which he nods and leaves the briefcase. Search the Common Item deck and take the first Weapon you find, and gain $10!','Lore -3','Curse of the Dark Pharaoh');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A man with an accordian is playing tunes and everybody is singing along. If you choose to stay late into the evening, gain 2 Sanity, but lose 1 Stamina.',NULL,'The Lurker at the Threshold');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A regular needs funds to get out of town, fast. He offers to sell you whatever is in his trunk. Make a Will (+0) check to convince him to show you his best goods. If you pass, draw a number of Common Items equal to the number of successes you rolled, and purchase any that you wish for their list price. Discard the rest.','Will +0','The King in Yellow');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A sly, smiling man challenges you to a game of billiards. Incensed by his insulting manner, you accept. You bet either $2 or an item of your choice. Unfortunately, he turns out to be a pool shark and cleans you out. You lose your bet',NULL,'Dunwich Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A stranger buys you a drink. You may search the Common Item deck for a Whiskey card and take it.',NULL,NULL);
INSERT INTO hibbs_roadhouse_encounters VALUES ('A stranger buys you a drink. You may search the Common Item deck for a Whiskey card and take it.',NULL,'Innsmouth Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A stranger buys you a drink. You may search the Common Item deck for a Whiskey card and take it.',NULL,'Dunwich Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('A truck driver at the bar has a flat tire and needs help changing it. If you pass a Fight (-1) check, you help him out and he offers you some of his cargo for free. Search the Common Item deck for your choice of a Lantern, Map of Arkham, or Dark Cloak, and take that card.','Fight -1','Curse of the Dark Pharaoh');
INSERT INTO hibbs_roadhouse_encounters VALUES ('An old-timer sits down next to you and offers to teach you a trick in exchange for a drink. If you agree, gain 1 Spell for the price of $3.',NULL,'The Black Goat of the Woods');
INSERT INTO hibbs_roadhouse_encounters VALUES ('As you sip your drink, suddenly a fight breaks out in the bar! Pass a Luck (-1) check to make it to the door before the cops show up. If you fail, you''re arrested unless you''re the Deputy.','Luck -1','Dunwich Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('As you sip your drink, suddenly a fight breaks out in the bar! Pass a Luck (-1) check to make it to the door before the cops show up. If you fail, you''re arrested unless you''re the Deputy.','Luck -1','Dunwich Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('Erica Carlyle is slumming it, and seems intrigued by your tales of mystery. If you have $3 or less, she agrees to join you and help pay your way. Take her Ally card or, if it is not available, gain a Retainer card.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO hibbs_roadhouse_encounters VALUES ('Joey "The Rat" Vigil slips into an empty chair at your table and whispers, "Pssst! Wanna buy something?" Look at the top 3 cards of the Common Item deck. You may purchase any or all of them for $1 above the list price. "Hey, I''ve got overhead!" the Rat explains',NULL,NULL);
INSERT INTO hibbs_roadhouse_encounters VALUES ('Make a Speed (-1) check to complete a transaction. If you pass, you make $2 out of the deal. If you fail, someone catches you doing something you shouldn''t, and blackmails you. You either lose $5 or, if you either cannot or will not pay, you are reduced to 1 Stamina.','Speed -1','The King in Yellow');
INSERT INTO hibbs_roadhouse_encounters VALUES ('One of the bigger men in the bar challenges you to a game of darts. You must pay $1 to play, since bets are placed up front. Then, make a Luck (-2) check. If you pass, you win with a big bullseye. Gain $3. If you fail, the big guy claps you on the shoulder and says, "No hard feelings, eh? I''ll buy you a drink." Gain 1 Sanity. If you cannot pay, nothing happens.','Luck -2','Dunwich Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('Pass a Luck (-1) check or a pickpocket cleans you out! Lose all your money.','Luck -1',NULL);
INSERT INTO hibbs_roadhouse_encounters VALUES ('Pass a Speed (-2) check to avoid being bumped into and knocked over. If you pass, nothing happens. If you do not, the proprietor tells you that you''ve had enough for one night and you are moved to the street.','Speed -2','Innsmouth Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('Prohibition failed to influence the proprietor of Hibb''s. You drink heavily while quizzing the locals about the strange goings-on in Arkham. Make a Will (-1) check. If you pass, you hold your liquor and learn something. Gain 2 Clue tokens. If you fail, you pass out. Move to the street and either have 1 item (your choice) or all of your money stolen.','Will (-1)',NULL);
INSERT INTO hibbs_roadhouse_encounters VALUES ('The man at the bar next to you is deep in his cups. Pass a Luck (+0) check to realize that he''s a loan officer from the Bank. He is so drunk that he barely remembers his name. You may gain a Bank Loan from him, or if you have a Bank Loan already, may convince him that you have paid it off, and may discard the Bank Loan card.','Luck +0','Curse of the Dark Pharaoh');
INSERT INTO hibbs_roadhouse_encounters VALUES ('The only empty seat is next to a strange, diminutive man. He has no ears, and is missing all of the fingers on his left hand. If you pass a Luck (+0) check, he cackles, says "You did well, though you knew it not," and hands you $2.','Luck +0','The King in Yellow');
INSERT INTO hibbs_roadhouse_encounters VALUES ('The proprietor asks you to clean out the old shed and offers you your choice of money or whatever you find inside. You may either gain $1 or draw 2 Common Items, keeping one and discarding the other.',NULL,'The King in Yellow');
INSERT INTO hibbs_roadhouse_encounters VALUES ('Whoever was sitting here before you used a knife to carve a horribe symbol into the surface of the table. Make a Will (-1) check and lose 1 Sanity if you fail. Then, whether you passed or not, search the Common Item deck for the Knife and take it.','Will -1','The Lurker at the Threshold');
INSERT INTO hibbs_roadhouse_encounters VALUES ('You enter a "friendly" card game. Make a Luck (-1) check. If you pass, you win $5. If you fail, you lose $3. If you lose and can''t pay, the boys rough you up and throw you outside. Lose 1 Stamina and move to the street.','Luck -1',NULL);
INSERT INTO hibbs_roadhouse_encounters VALUES ('You find that tipping well gets the proprietor talking. For every $1 you spend, gain 1 Clue Token, to a maximum of $3.',NULL,'The Black Goat of the Woods');
INSERT INTO hibbs_roadhouse_encounters VALUES ('You look up and everyone''s gone - you must have fallen asleep at the bar. Unnerved by the eerie silence of the previously hopping establishment, you grab the bottle in front of you and skedaddle. Search the Common Items deck for a Whiskey card.',NULL,'Kingsport Horror');
INSERT INTO hibbs_roadhouse_encounters VALUES ('You stand inside the door, surveying the crooks, drunks, and miscreants. Would anyone even be able to notice if a greater evil arose among this scum? The only way to ensure Arkham''s safety is to act now. If you have an Elder Sign, you may discard it to seal this location.',NULL,'Kingsport Horror');
