CREATE TABLE historical_society_encounters (
    `list_encounter` VARCHAR(377) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(25) CHARACTER SET utf8,
    `list_expansion` VARCHAR(27) CHARACTER SET utf8
);
INSERT INTO historical_society_encounters VALUES ('"After my husband passed away, I thought the Society would be interested in his documents. He was very influential in Arkham." Make a Luck (-2) check to see if the curator recognizes their arcane significance. If you pass, gain 1 Spell as the Society passes these papers off to you.','Luck -2','The Lurker at the Threshold');
INSERT INTO historical_society_encounters VALUES ('A guest lecturer provides a lengthy but informative presentation about his explorations of ancient sites. You may make a Lore (-1) [2] check and stay here next turn. If you pass, gain 1 Skill.','Lore -1 [2]','The Lurker at the Threshold');
INSERT INTO historical_society_encounters VALUES ('A monster appears and attacks you as you approach the front door!',NULL,'Dunwich Horror');
INSERT INTO historical_society_encounters VALUES ('A monster appears and attacks you as you approach the front door!',NULL,'The Black Goat of the Woods');
INSERT INTO historical_society_encounters VALUES ('A monster appears and attacks you as you approach the front door!',NULL,'Innsmouth Horror');
INSERT INTO historical_society_encounters VALUES ('A golden tiara on display is covered in bizarre and unnatural engravings. Make a Lore (-1) check and gain 1 Clue token for each success.','Lore -1','Innsmouth Horror');
INSERT INTO historical_society_encounters VALUES ('A large stone disc is on display which bears ancient pictograms. As you examine it, the room seems to fill with whispering voices. Pass a Will (-1) check to resist being overcome by its power or you are lost in time and space.','Will -1','The Black Goat of the Woods');
INSERT INTO historical_society_encounters VALUES ('A past-life believer offers to channel the spirits of the ancients. You may join in and make a Will (+0) check to draw Spells until you draw one with a Sanity cost of 0; keep that Spell and discard the rest. Alternatively, you may watch her technique, and make a  Luck (-1) check. If you pass, you may take the Psychic card.','Will +0
-OR-

Luck -1
','Curse of the Dark Pharaoh');
INSERT INTO historical_society_encounters VALUES ('A representative of the society is visiting a historic Arkham home to pick up old photos of the neighborhoods and invites you to tag along. If you accept, move to the Unnamable and draw 2 cards, encountering one card of your choice and discarding the other.',NULL,'The Black Goat of the Woods');
INSERT INTO historical_society_encounters VALUES ('A retired actor, once the favorite of European theater, gestures to you. "Take this, my young friend," he says. "You''ll need it against what''s coming." He hands  you a collection of news articles regarding the run of "The King in Yellow" in Paris. Pass a Lore (-1) check to sense an arcane pattern to them and draw a Spell. If you fail, you must discard 2 Clue tokens, if able.','Lore -1','The King in Yellow');
INSERT INTO historical_society_encounters VALUES ('A weary old man holds out a stack of paper and says "It''s a memoir of my travels along the Nile, but I doubt the world will last long enough for it to be published." If you wish to read it, remain here next turn and make a Will (+0) check. You may draw cards from the Skill deck equal to your number of successes, and may keep one of them.','Will +0','Curse of the Dark Pharaoh');
INSERT INTO historical_society_encounters VALUES ('A white-haired professor offers to help you if you can prove the legitimacy of your mission. You may spend a gate trophy to take Professor Armitage''s Ally card, or, if it''s not available, draw 1 Unique Item.',NULL,'Kingsport Horror');
INSERT INTO historical_society_encounters VALUES ('An actor from "The King in Yellow" leads a theater course. It''s amazing what skills an actor needs to master in order to look like the real thing. Pass a Will (-2) check to draw Skill cards equal to the number of successes rolled. Keep one, and discard the rest. If you fail, you learn something you wish you hadn''t in the theater exercises, and are Cursed.','Will -2','The King in Yellow');
INSERT INTO historical_society_encounters VALUES ('Finding an unusual book, you read a spell from it. You may move any elder sign token on the board to any unsealed, unstable location. If there is a gate there, it is immediately sealed, and any monsters there are returned to the monster cup. If there are no elder sign tokens on he board, take a Clue token.',NULL,'Kingsport Horror');
INSERT INTO historical_society_encounters VALUES ('Make a Lore (-1) check to dig up inspirational travel journals penned by residents of Arkham who traveled to the mysterious and dangerous Nile. If you pass, you may search the Skill deck and take the Bravery card.','Lore -1','Curse of the Dark Pharaoh');
INSERT INTO historical_society_encounters VALUES ('Make a Luck (-2) check. If you pass, then while paging through the historical records, you come across a piece of information that makes everything come together for you. If you have fewer than 5 Clue tokens, gain enough Clue tokens to bring your total up to 5. If you fail, nothing happens.','Luck -2','Dunwich Horror');
INSERT INTO historical_society_encounters VALUES ('One of the Society members is heading over to the library to do some research and offers you a ride. If you accept, move to the Library and draw 2 cards, encountering one card of your choice and discarding the other.',NULL,'Dunwich Horror');
INSERT INTO historical_society_encounters VALUES ('Pass a Luck (-1) [2] check to gain insight into a skill while studying the old volumes of books. Draw 1 Skill, but stay here next turn.','Luck -1 [2]',NULL);
INSERT INTO historical_society_encounters VALUES ('Pay  $3 fee to gain access to the private library. If you refuse, move to the street. If you pay, make a Luck (-1) check. If you pass, you learn an ancient spell from a dusty ledger. Draw 1 Spell. If you fail, you doze off and enter The Dreamlands. Have an encounter there, then immediately return here.','Luck -1',NULL);
INSERT INTO historical_society_encounters VALUES ('Perusing the county records, you discover something horrifying about your family tree. Lose 1 Sanity.',NULL,NULL);
INSERT INTO historical_society_encounters VALUES ('The diary of an early immigrant settler in Arkham mentions a band of pagans that resided in the Woods, worshipping a vile Black Goat. If you currently possess a "One of the Thousand" Cult Membership, gain 3 Clue tokens and lose 1 Sanity. If not, simply gain 1 Clue token.',NULL,'The Black Goat of the Woods');
INSERT INTO historical_society_encounters VALUES ('The Historical Society is holding more educational discussion groups than normal, thanks to the buzz of the "King in Yellow" performances. Make a (+0) check in your lowest current skill. If you pass, draw 1 Skill.','(lowest current skill) +0','The King in Yellow');
INSERT INTO historical_society_encounters VALUES ('The society is discarding what it calls a "taxidermist''s trick." Draw a monster from the cup and claim it as a monster trophy, even if it has the Endless ability.',NULL,'Innsmouth Horror');
INSERT INTO historical_society_encounters VALUES ('The Society members are bird watching in the woods. The janitor offers you a ride there. If you accept, move to the Woods and draw 2 cards, encountering one card of your choice and discarding the other.',NULL,NULL);
INSERT INTO historical_society_encounters VALUES ('The society''s latest treasure, an ancient cask from Europe, is not altogether harmless. A monster appears when it is opened, attacking you. If you pass a Combat check against the monster, you find it was entombed with an ancient scroll. Draw 1 Spell.','Combat check','The King in Yellow');
INSERT INTO historical_society_encounters VALUES ('Weary of your travels, you lean back in one of the comfortable chairs for a while and rest. Gain 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO historical_society_encounters VALUES ('When you arrive, you discover that the members of the Society are on their monthly outing to Independence Square. The janitor, who''s heading there shortly, offers to give you a lift. You may move to Independence Square and draw two cards, encountering one of your choice, and discarding the other.',NULL,'Kingsport Horror');
INSERT INTO historical_society_encounters VALUES ('While researching, you find a story about a series of disappearances that occurred in the earliest days of Arkham. Coincidentally, you notice a newspaper reporting a similar disappearance just last week. Return 1 Ally at random from the Ally deck to the box. Then gain 3 Clue tokens.',NULL,'The Lurker at the Threshold');
INSERT INTO historical_society_encounters VALUES ('You admire the artifacts donated to the Society over the years. One in particular catches your attention, and as you examine it, your hairs prickle. If there are three or fewer elder sign tokens on the board, draw a Skill. If there are four or more, you are Cursed.',NULL,'Kingsport Horror');
INSERT INTO historical_society_encounters VALUES ('You attempt to get some first-hand accounts of Arkham history from some of the older members of the society. Make a Luck (-1) check. If you pass, you''re able to glean several vital facts from their stories. Gain 1 Clue token. Whether you fail or not, stay here next turn.','Luck -1','Dunwich Horror');
INSERT INTO historical_society_encounters VALUES ('You encounter a friendly old professor from Miskatonic University. If you spend 1 gate trophy, he introduces himself as Professor Armitage and offers to join forces with you. Take his Ally card if it is available, otherwise draw 1 Unique Item.',NULL,NULL);
INSERT INTO historical_society_encounters VALUES ('You encounter a friendly old professor from Miskatonic University. If you spend 1 gate trophy, he introduces himself as Professor Armitage and offers to join forces with you. Take his Ally card if it is available, otherwise draw 1 Unique Item.',NULL,'Dunwich Horror');
INSERT INTO historical_society_encounters VALUES ('You encounter a friendly old professor from Miskatonic University. If you spend 1 gate trophy, he introduces himself as Professor Armitage and offers to join forces with you. Take his Ally card if it is available, otherwise draw 1 Unique Item.',NULL,'Innsmouth Horror');
INSERT INTO historical_society_encounters VALUES ('You encounter a friendly old professor from Miskatonic University. If you spend 1 Gate trophy, he introduces himself as Professor Armitage and offers to join forces with you. Take his Ally card if it is available; otherwise, draw 1 Unique Item.',NULL,'The Lurker at the Threshold');
INSERT INTO historical_society_encounters VALUES ('You find a book with two of its pages stuck together. Pass a Luck (-1) check to pull them apart without damaging them. Between the two pages is a magical incantation. Draw 1 Spell. If you fail the check, you tear the pages and ruin the incantation.','Luck -1','Dunwich Horror');
INSERT INTO historical_society_encounters VALUES ('You find a cipher for interpreting old texts and hieroglyphics! You may immediately use any Tome or other item that requires an expenditure of movement points to use.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO historical_society_encounters VALUES ('You find a painting of your grandparents wearing strange occult pendants. You may search the Skill deck for the Expert Occultist or Lore card and take it, but if you do so you must also take the Tainted card.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO historical_society_encounters VALUES ('You meet Cindy Fleming, a young geology professor at the University. She offers to show you some interesting formations at the Black Cave. If you accept, move to the Black Cave and draw 2 cards, encountering one card of your choice and discarding the other.',NULL,NULL);
INSERT INTO historical_society_encounters VALUES ('You notice a creepy man watching you as you peruse the books. With a feeling of dread you try to slip out without being followed. Make a Sneak (-1) check. If you pass, you lose the man. If you fail, you are accosted in the street. He is a wizard and he casts a dark spell on you as you flee. Lose 2 Stamina, move to the street, and you are Cursed.','Sneak -1',NULL);
