CREATE TABLE independence_square_encounters (
    `list_encounter` VARCHAR(434) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO independence_square_encounters VALUES ('A brass band plays some soft music from the veranda. Tapping your feet along with the catchy tunes, you feel better than you have in a while. Gain 2 Sanity.',NULL,'Dunwich Horror');
INSERT INTO independence_square_encounters VALUES ('A bronze plate near Founder''s Rock commemorates the establishing of the city. You notice that a line of odd symbols runs along the border of the marker. Make a Lore (-1) check to interpret their meaning. If you pass, gain 1 Spell.','Lore -1','The Lurker at the Threshold');
INSERT INTO independence_square_encounters VALUES ('A dark shadow fall across Founder''s Rock, and then dissolves as the sun passes behind a bank of clouds. A monster appears!',NULL,'Kingsport Horror');
INSERT INTO independence_square_encounters VALUES ('A fluttering yellow leaf falls from the old oak in the center of the square, and you glimpse a design on its surface. Make a Speed (-1) check to catch it before it falls among the other leaves. If you pass, you see that the leaf''s veins form the shape of the Yellow Sign: Gain 1 Clue token.','Speed -1','The King in Yellow');
INSERT INTO independence_square_encounters VALUES ('A gate and a monster appear!',NULL,'Dunwich Horror');
INSERT INTO independence_square_encounters VALUES ('A gate and a monster appear!',NULL,'Dunwich Horror');
INSERT INTO independence_square_encounters VALUES ('A gate and a monster appear!',NULL,'The Black Goat of the Woods');
INSERT INTO independence_square_encounters VALUES ('A gate and a monster appear!',NULL,'Innsmouth Horror');
INSERT INTO independence_square_encounters VALUES ('A group of boys play baseball on the public diamond, shouting and laughing. You stop to watch for a while, and find yourself both refreshed and heartened. Gain 1 Stamina and 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO independence_square_encounters VALUES ('A pair of friendly picnickers share their lunch with you. Gain 1 Stamina.',NULL,NULL);
INSERT INTO independence_square_encounters VALUES ('A shadow falls across you from no apparent source and you shiver with more than just cold. Pass a Will (-1) check or lose 1 Stamina and 1 Sanity.','Will -1',NULL);
INSERT INTO independence_square_encounters VALUES ('A sheaf of papers with hieroglyphics translations blows past you on the wind. Make a Speed (-1) check. If you fail, a young lady runs past you after them. If you pass, you catch them and are thanked profusely by Sarah Danforth, an archaeology student from Miskatonic. Take her Ally card. If it is not available, gain 1 Clue token instead as she chats with you about the visiting museum exhibit.','Speed -1','Curse of the Dark Pharaoh');
INSERT INTO independence_square_encounters VALUES ('A storm strikes in the midst of rehearsals, and the actors flee for cover, leaving some of their props behind. Pass a Lore (-2) check to realize that one of the props is real, and draw a Unique Item.','Lore -2','The King in Yellow');
INSERT INTO independence_square_encounters VALUES ('A well-dressed gentleman approaches a group of children and begins to lead one away... and something tells you that he''s up to no good. If you confront him, he transforms. A monster appears! Treat this monster as if it had the Ambush special ability. If you defeat it, draw 1 Exhibit Item, but place a Patrol marker on the street area of Downtown after being seen assaulting a respected citizen.',NULL,'Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO independence_square_encounters VALUES ('A well-dressed gentleman approaches a group of children and begins to lead one away... and something tells you that he''s up to no good. If you confront him, he transforms, and you are surprised by a monster. If you defeat it, draw 1 Exhibit Item, but you are Barred from Downtown for assaulting a respected citizen. If you mind your own business, the child is later found dead.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO independence_square_encounters VALUES ('An old gypsy man is being attacked by a mysterious robed figure. Make a Fight (-2) check to help fend off the assailant. If you pass, the gypsy insists you accept a token of his gratitude. Gain 1 Unique Item.','Fight -2','The Lurker at the Threshold');
INSERT INTO independence_square_encounters VALUES ('Anna Kaslow gives you a tarot reading. Look at the top card of the mythos deck. If it isn''t "The Story Continues," then you may choose to discard it to the bottom of the deck. If it is "The Story Continues," return it to the top of the deck.',NULL,'Dunwich Horror');
INSERT INTO independence_square_encounters VALUES ('As you brush up against Founder''s Rock, a strange lethargy seizes your limbs. Lose 1 Stamina.',NULL,'Dunwich Horror');
INSERT INTO independence_square_encounters VALUES ('As you pass by a game of horseshoes, a bad throw sends one straight at you. Pass a Speed (+0) check or lose 1 Stamina.','Speed +0','The Black Goat of the Woods');
INSERT INTO independence_square_encounters VALUES ('As you pass through the entry arch on Peabody Avenue, all sound dissolves into a cosmic silence. Make a Luck (-1) check. If you succeed, the mundane noises of Arkham return. If you fail, you are drawn through the gate nearest this location, and you are Cursed.','Luck -1','Kingsport Horror');
INSERT INTO independence_square_encounters VALUES ('From a bench in Independence Square you can watch the comings and goings of the town''s major figures. Gain 1 Clue token.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO independence_square_encounters VALUES ('Luckily, it''s just another quiet day in the Square. No encounter.',NULL,'Dunwich Horror');
INSERT INTO independence_square_encounters VALUES ('Make a Will (-1) check. If you pass it, Anna Kaslow the fortune teller offers her help in your investigation. Take her Ally card if it is still available. Otherwise, gain 2 Clue tokens. If you fail, nothing happens.','Will -1',NULL);
INSERT INTO independence_square_encounters VALUES ('Make a Will (-1) check. If you pass it, Anna Kaslow the fortune teller, offers her help in your investigation. Take her Ally card if it is still available. If it is not, gain 2 Clue tokens. If you fail, nothing happens.','Will -1','Dunwich Horror');
INSERT INTO independence_square_encounters VALUES ('Make a Will (-1) check. If you succeed, you may take Anna Kaslow''s Ally card, or, if it''s not available, 2 Clue tokens.','Will -1','Kingsport Horror');
INSERT INTO independence_square_encounters VALUES ('Make a Will (-1) check. If you pass it, Anna Kaslow the fortune teller, offers her help in your investigation. Take her Ally card if it is still available. Otherwise, gain 2 Clue tokens. If you fail, nothing happens.','Will -1','Innsmouth Horror');
INSERT INTO independence_square_encounters VALUES ('Pass a Fight (-1) check to intimidate a policeman or he rousts you from the park. Move to the street.','Fight -1',NULL);
INSERT INTO independence_square_encounters VALUES ('Pass a Sneak (-2) check to catch a glimpse of the actors rehearsing for the play, gaining 2 Clue tokens. If you fail, no sooner do they notice you than a monster appears!','Sneak -2','The King in Yellow');
INSERT INTO independence_square_encounters VALUES ('The gazebo seems to swell with menace and you dare not approach. Pass a Will (-2) check or move to the street.','Will -2','Innsmouth Horror');
INSERT INTO independence_square_encounters VALUES ('The gypsies are singing and dancing. You may join them. Make a Luck (-1) check. If you pass, gain 2 Clue tokens as you realize what they''re singing about. If you fail, the gypsy spell is completed and a gate appears!','Luck -1','Innsmouth Horror');
INSERT INTO independence_square_encounters VALUES ('The staff of the visiting museum exhibit puts on an educational show in the park, but it is rather confusing. Make a Lore (-1) check. If you pass, you gain Clue tokens equal to your focus (maximum 3). If you fail, you lose Clue tokens equal to your focus (maximum 3).','Lore -1','Curse of the Dark Pharaoh');
INSERT INTO independence_square_encounters VALUES ('There are gypsies camped in the park. Make a Luck (-1) check if you wish to interact with them. If you pass, an old man has spread several items on a blanket for sale. Draw 1 Unique Item and you may buy it for $1 less than the list price. If you fail, a hag comes up to you and tells you that death shadows you. You scoff at her and she cuts the side of your face with her fingernail, drawing blood. Lose 1 Stamina and you are Cursed.','Luck -1',NULL);
INSERT INTO independence_square_encounters VALUES ('There are gypsies camped out in the park. They are master thieves and you are their target. Pass a Luck (-2) check or lose 1 item of your choice.','Luck -2',NULL);
INSERT INTO independence_square_encounters VALUES ('You find the remains of a small fire. Among the ashes you find a few scraps of paper that didn''t completely burn. Make a Luck (+0) check and consult the chart below.Successes:0) You are Cursed.1) Gain 1 Clue token.2+) Gain 1 Spell.','Luck +0','The Black Goat of the Woods');
INSERT INTO independence_square_encounters VALUES ('You hoped to get near enough to the gypsy camp to eavesdrop, but a dog bark has alerted them that there is an intruder. Make a Sneak (-1) check to escape! If you fail, you are Cursed.','Sneak -1','The Lurker at the Threshold');
INSERT INTO independence_square_encounters VALUES ('You learn that cultists are bribing the mayor with stolen items from the "Legacy of the Pharaohs" exhibit, and often drop them off on his doorstep. If you would like to reappropriate them, make a Sneak (-1) check. If you fail, you are arrested. If you roll 1 success, you get away, but empty-handed. If you roll 2 successes, you get away with the packages: Draw 1 Unique Item or Exhibit Item.','Sneak -1','Curse of the Dark Pharaoh');
INSERT INTO independence_square_encounters VALUES ('You meet Anna Kaslow, a fortune teller who may have some insight into your investigation. Make a Will (-1) check. If you pass, you persuade her to help you. Take her Ally card if it is available. Otherwise, gain 2 Clue tokens. If you fail, nothing happens.','Will -1','The Black Goat of the Woods');
INSERT INTO independence_square_encounters VALUES ('You see someone battling a monster and rush to help. A monster appears! If you fight and defeat it, you may roll a number of dice equal to its toughness. If you roll a success, you may draw a random Ally. If you do not roll any successes, you may draw a Unique Item.',NULL,'The King in Yellow');
INSERT INTO independence_square_encounters VALUES ('You start digging in a patch of grond where, as long as you can recall, no grass has ever grown. Make a Luck (-2) check. If you pass, gain 2 Clue tokens as you unearth a pocket watch inscribed with the name of a man who went missing decades ago. If you fail, lose 1 Stamina for exhausting yourself fruitlessly.','Luck -2','The Lurker at the Threshold');
INSERT INTO independence_square_encounters VALUES ('You touch Founder''s Rock. Make a Luck (-1) check. If you pass, there is an electrifying shock that opens your mind to the elder things of eons past. Lose 1 Stamina, but gain 2 Clue tokens and draw 1 Spell. If you fail, you find a strange carving. As you finger the grooves, a gate opens here and you are drawn through it.','Luck -1',NULL);
