CREATE TABLE inner_sanctum_encounters (
    `list_encounter` VARCHAR(415) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO inner_sanctum_encounters VALUES ('"Admiring our library?" Carl Sanford asks you. "Membership has privileges. Borrow one of our texts if you wish." Search Unique Item deck and take the first Tome you find.',NULL,'The Lurker at the Threshold');
INSERT INTO inner_sanctum_encounters VALUES ('"In a hurry?" Carl Sanford asks. He offers to guide you through the old tunnels that connect the Lodge to the rest of the city. Move to any location or  street area in Arkham. If you move to a location, immediately have an encounter there, drawing 2 cards and encountering either of them.',NULL,'Innsmouth Horror');
INSERT INTO inner_sanctum_encounters VALUES ('"Time to pay your dues, brother. We need a champion, and you''ve been chosen." You are handed a weapon and thrown through a doorway into oblivion. You may search the Unique Item deck and take the first magical weapon you find, but you are transported to R''lyeh.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO inner_sanctum_encounters VALUES ('"You must always be studying," Carl Sanford tells you. Make a Lore (-1) check. If you pass, draw 1 Spell. If you fail, you are delayed, and then draw 1 Spell.','Lore -1','Innsmouth Horror');
INSERT INTO inner_sanctum_encounters VALUES ('A fellow Lodge member helps you perform a ritual designed to protect you and your friends. Make a Lore (+0) check to see the deeper meanings. Gain 1 Clue token for each success.',NULL,'The Black Goat of the Woods');
INSERT INTO inner_sanctum_encounters VALUES ('A glass orb in this chamber contains a swirling fog. As you handle the sphere, the misty shroud parts to divulge what seems to be the future. Draw the top five cards from the Mythos deck and put them back on top of the deck in any order you desire.','Lore +0','Kingsport Horror');
INSERT INTO inner_sanctum_encounters VALUES ('A gorgeous youth invites you into a meditation chamber. If you go in, you must lose a total of 4 Spells or Stamina, divided up as you choose, but you may search the Exhibit Item deck for the Mask of the Three Fates card and take it. If it is not there, gain 4 Clue tokens instead. If you do not go in, the young witch casts a hex to make others mistrust you. Place a Patrol marker on the street area of French Hill.',NULL,'Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO inner_sanctum_encounters VALUES ('A gorgeous youth invites you into a meditation chamber. If you go in, you must lose a total of 4 Spells or Stamina, divided up as you choose, but you may search the Exhibit Item deck for the Triune Mask (errata: should be Mask of the Three Fates) card and take it. If you do not go in, the young witch casts a hex upon you, and you are Barred from French Hill.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO inner_sanctum_encounters VALUES ('A member of the inner circle explains that the Lodge sometimes supports the studies and explorations of the like-minded. Give any other investigator all of your Clue tokens. You are Blessed.',NULL,'Kingsport Horror');
INSERT INTO inner_sanctum_encounters VALUES ('A member of the Lodge leads you into the Inner Sanctum and shows you a ring that can be used to fight against evil. As you slip it on, he directs you to concentrate on a target and try to overpower it with your mind. You may spend 1 Stamina to make a Will (-1) check. If you succeed, claim any non-spawn monster on the board as a trophy.','Will -1','Kingsport Horror');
INSERT INTO inner_sanctum_encounters VALUES ('A newly ordained member of the Lodge should be seen but not heard. Pass a Sneak (-1) check to gain 2 Clue tokens. If you fail, the stern glares of the higher-ranking members at least give you motivation: You may search the Spell deck for the Stealth card and take it.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO inner_sanctum_encounters VALUES ('A strange maze-like symbol has been carved in the wall. Do you dare to follow it with your eyes? If so, pass a Will (+0) check to gain a Clue token. If you fail, you lose 1 Sanity.',NULL,'The King in Yellow');
INSERT INTO inner_sanctum_encounters VALUES ('An executive at the Bank of Arkham is also a member and offers to pull a few strings. You may choose any one player who currently has a Bank Loan and discard it without paying.',NULL,'The Black Goat of the Woods');
INSERT INTO inner_sanctum_encounters VALUES ('Carl Sanford accuses you of stealing from the Lodge. Make a Will (-1) check to prove that you''ve been framed. If you fail, lose 1 Stamina and your Silver Twilight Membership, and then move to the streets. If you pass, there is no effect.','Will -1','The Lurker at the Threshold');
INSERT INTO inner_sanctum_encounters VALUES ('Carl Sanford does not trust you and at the climax of the monthly ceremony spits a spell at you. Pass a Luck (-2) check or you are Cursed.','Luck -2',NULL);
INSERT INTO inner_sanctum_encounters VALUES ('Carl Sanford has an important task for you. Take the first Mission card from the Unique Item deck. However, you''ll have the Lodge''s help completing it, so place 1 Clue token on it to begin (you may skip the first location on the card).',NULL,'Dunwich Horror');
INSERT INTO inner_sanctum_encounters VALUES ('Carl Sanford places a powerful spell of protection on you. If you are Cursed, discard the Curse card. If you are not Cursed, you may search the Mythos deck for any two cards of your choice and return them to the box.',NULL,'Dunwich Horror');
INSERT INTO inner_sanctum_encounters VALUES ('Entering the workroom, you see a smith working on an ancient heirloom. He says "Your piece is finished, you vulture," and throws it at you in disgust. Make a Speed (-2) check. If you pass, you may search the Unique Item deck and take the first Weapon you find. If you fail, you lose 2 Stamina.','Speed -2','The King in Yellow');
INSERT INTO inner_sanctum_encounters VALUES ('If you currently posses a "One of the Thousand" Cult Membership, the Inner Sanctum has found out about your double life! You must immediately lose either your Inner Sanctum* of "One of the Thousand" card. Either way, you lose 2 Stamina. If you are not One of the Thousand, you have no encounter.',NULL,'The Black Goat of the Woods');
INSERT INTO inner_sanctum_encounters VALUES ('Membership has it privileges. Pass a Will (-1) check to draw Unique Items equal to the number of successes. You may purchase any of the items drawn, using any combination of money, Clue tokens (1 Clue token = $2), or Spells (1 Spell = $3).','Will -1','The King in Yellow');
INSERT INTO inner_sanctum_encounters VALUES ('One of the Lodge brothers has a valuable opportunity for you. Take the first Task card from the Common Item deck. However, thanks to your connections in the Lodge, place 1 Clue token on it to begin (you may skip the first location on the card).',NULL,'Dunwich Horror');
INSERT INTO inner_sanctum_encounters VALUES ('One of the Lodge brothers notices your distress and casts a spell to help you. Restore either your Stamina or Sanity to its maximum.  If both are already at  your maximum, then you are Blessed instead.',NULL,'Dunwich Horror');
INSERT INTO inner_sanctum_encounters VALUES ('One of the Lodge brothers pulls you aside after a meeting. "I had a very disturbing dream last night. It told me that something terrible would happen unless I gave you this." So saying, he presses $5 into your hands. Gain $5.',NULL,'Dunwich Horror');
INSERT INTO inner_sanctum_encounters VALUES ('Only the strongest of will may enter the Lodge''s prized library. Make a Will (-1) check. If you pass, you gain 3 Clue tokens and may search the Spell deck for any one Spell and take it. If you fail, you lose your Silver Twilight Lodge Membership.','Will -1','Curse of the Dark Pharaoh');
INSERT INTO inner_sanctum_encounters VALUES ('Participating in the monthly ceremony, you witness great power and great evil. Lose up to 3 Sanity and gain that many Clue tokens.',NULL,NULL);
INSERT INTO inner_sanctum_encounters VALUES ('Pay your monthly dues of $3 or lose 2 Sanity from strange dreams sent to you by Carl Sanford when he kicks you out of the Order. If you are kicked out, lose your Silver Twilight Lodge Membership.',NULL,NULL);
INSERT INTO inner_sanctum_encounters VALUES ('Researching the dimensional gates that have been opening up in town, you find an arcane ritual for redirecting them. You may move any one open gate from its current location to any other unstable location without an elder sign token. Any monsters at the gate''s new location are returned to the cup, and any investigators there are drawn through the gate.',NULL,'Dunwich Horror');
INSERT INTO inner_sanctum_encounters VALUES ('The Inner Sanctum asks for your help in a banishing ritual. Discard one monster trophy with a dimensional symbol other than moon to return all monsters in Arkham with the same dimensional symbol to the cup.',NULL,'Innsmouth Horror');
INSERT INTO inner_sanctum_encounters VALUES ('The Lodge has decided to clean up the town. Choose one dimension symbol other than the moon and return all non-Spawn monsters in Arkham with that symbol to the cup.',NULL,'The Black Goat of the Woods');
INSERT INTO inner_sanctum_encounters VALUES ('The Lodge Members have gathered to perform a powerful banishment ritual. Make a Lore (-2) check. If you pass, you may either gain 2 Clue tokens or choose one monster in the same location as an open Gate and return that monster to the monster cup.','Lore -2','The Lurker at the Threshold');
INSERT INTO inner_sanctum_encounters VALUES ('The members are extremely concerned about the celestial bodies being "changed" by some outside force, ask you to investigate. Make a Lore (-1) check. If you pass, you gain 2 Clue tokens and draw a Spell to aid you on your mission.','Lore -1','The King in Yellow');
INSERT INTO inner_sanctum_encounters VALUES ('The Order of the Silver Twilight casts a banishment spell in their monthly ceremony. Spend 1 Sanity to make a Luck (-1) check. If you pass, claim any one monster on the board as a trophy. If you fail, nothing happens.','Luck -1',NULL);
INSERT INTO inner_sanctum_encounters VALUES ('There is an inscription above an alcove. Pass a Lore (-2) check to understand it. If you do, it reads "Place herein a thing mundane, it will become a thing of fame." You gain 1 Clue token and may draw 1 Unique Item or Exhibit Item. If you discard a Common Item of your choice, you may keep the item drawn; otherwise, discard it.','Lore -2','Curse of the Dark Pharaoh');
INSERT INTO inner_sanctum_encounters VALUES ('While in the Inner Sanctum, you examine a scroll concerning the aspects of gates. Make a Lore (+0) check, rolling one extra die for each open gate. Take a Clue token for each success you roll.','Lore +0','Kingsport Horror');
INSERT INTO inner_sanctum_encounters VALUES ('Within this spiritually attuned chamber, you find that if you open your mind to the spirit world, the spirits will bestow eldritch knowledge upon you. Gain up to 3 Spells and then lose 1 Sanity for each spell chosen.',NULL,'The Lurker at the Threshold');
INSERT INTO inner_sanctum_encounters VALUES ('You are allowed into the vault of Silver Secrets. Pass a Luck (-2) check to steal a very unusual item. Search the Unique Item deck and take any one Unique Item you want.','Luck -2',NULL);
INSERT INTO inner_sanctum_encounters VALUES ('You attend a ceremony in which the order opens a gate and a monster bursts out of it before the gate closes once more. A monster appears!',NULL,NULL);
INSERT INTO inner_sanctum_encounters VALUES ('You may make a Lore (-1) check to assist in a ritual. If you pass, heal every investigator, including yourself, to full Sanity and Stamina. If you attempt to assist and fail, the ritual goes terribly awry, sending nightmares throughout the city. Raise the terror level by 1.','Lore -1','Innsmouth Horror');
INSERT INTO inner_sanctum_encounters VALUES ('You participate in a warding ritual led by Carl Sanford. You may spend 2 more Clue tokens than it would normally cost you to seal a gate in order to place an elder sign token on any unstable location without an open gate. If you do not spend the Clue tokens or cannot currently seal gates, then nothing happens.',NULL,'Dunwich Horror');
INSERT INTO inner_sanctum_encounters VALUES ('You''re invited to take part in a Gating ceremony. If you agree, spend 2 Clue tokens and 1 Sanity to make a Lore (-2) check. If you pass, close one gate of your choice. If you fail, nothing happens.','Lore -2',NULL);
