CREATE TABLE mas_boarding_house_encounters (
    `list_encounter` VARCHAR(417) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO mas_boarding_house_encounters VALUES ('"Jazz" Mulligan, the head janitor from the college comes for some of Ma''s famous apple pie. While he''s visiting, he demonstrates how he got his nickname by playing some soulful blues on his harmonica. Gain 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('A portrait of one of Arkham''s founding fathers hangs in Ma''s sitting room. On the back of the painting is a series of symbols and numbers. Pass a Lore (-1) check to interpret their meaning and gain a Clue token for each success.','Lore -1','The Lurker at the Threshold');
INSERT INTO mas_boarding_house_encounters VALUES ('A reporter staying at Ma''s announces that he will pay handsomely for tales of the macabre. Take $1 for every elder sign token on the board as you relate your exploits.',NULL,'Kingsport Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('Abigail Foreman drops in for tea with Ma. You are invited to sit in as well. If you accept, gain 1 Stamina and 1 Clue token, and stay here next turn as you attend the tea party.',NULL,'Dunwich Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('After supper while sitting on the porch you strike up a conversation with another guest: Ryan Dean, a traveling salesman. You may make a Will (+0) check. If you pass, Ryan has a deal for you. You may draw either 1 Common Item or 1 Unique Item and purchase it at list price. If you fail, stay here next turn listening to bawdy stories and tall tales.','Will +0',NULL);
INSERT INTO mas_boarding_house_encounters VALUES ('An elderly woman walks up to the porch and strikes up a conversation with you. She tells you that this had been her home during a very difficult time in her life. You spend the afternoon in nostalgic conversation about Arkham history. Gain 1 Clue token.',NULL,'The Black Goat of the Woods');
INSERT INTO mas_boarding_house_encounters VALUES ('As a favor, you volunteer to head to the basement to have a look at the pipes. The steps are mostly rotten and are starting to fall apart under your weight. Make a Speed (+0) check to avoid injury. If you fail, lose 1 Stamina.','Speed +0','The Lurker at the Threshold');
INSERT INTO mas_boarding_house_encounters VALUES ('Chanting neighbors keep you up all night. Pass a Luck (-1) check or lose your choice of 1 Stamina or 1 Sanity','Luck -1',NULL);
INSERT INTO mas_boarding_house_encounters VALUES ('Deputy Dingby stops by Ma''s for breakfast. This is, as you might guess, an unmitigated disaster. After Ma shoos him out of her kitchen, everyone pitches in to help her clean up the mess. Stay here next turn.',NULL,'Dunwich Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('If you''re healthy enough, Ma could sure use some help rebuilding the porch. If you have 3 or more Stamina, take a Retainer card.',NULL,'The Lurker at the Threshold');
INSERT INTO mas_boarding_house_encounters VALUES ('It''s dinner time, and Ma has spread all the fixings. You resist the urge to sit down and have a meal, but the same can''t be said of the rest of your party. If you have an Ally, discard it. Fortunately, another willing soul finds the prospect of helping you out exciting. Draw a random Ally. If the Ally deck is empty, nothing happens.',NULL,'Kingsport Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('It''s mystery meat Monday at Ma''s. As you walk into the kitchen, she shoves a spoonful of the unknown chow into your mouth and directs you to swallow. Make a Luck (-1) check. If you succeed, restore your Stamina to its maximum. If you fail, lose 1 Sanity, and your lunch.','Luck -1','Kingsport Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('Joey "the Rat" waves to you from the side of the house. "I''ve got some information you might be interested in. Only $4." You may pay $4 to gain 2 Clue tokens "Hey, info like this don''t come cheap, ya know!"',NULL,'Dunwich Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('Ma apologizes, but her kitchen is being redone. If you want, she''ll give you a ride to Velma''s Diner. If you go there, immediately have an encounter.',NULL,'Innsmouth Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('Ma asks you to give her a hand moving a piano into the house. If you agree to help, make a Fight (-1) check. If you pass, Ma gratefully tucks $3 into your pocket. If you pass (errata: should say "fail"), you lose 1 Stamina and are delayed by the frustrating struggle.','Fight -1','The Black Goat of the Woods');
INSERT INTO mas_boarding_house_encounters VALUES ('Ma doesn''t like the look of you and your "gang". Pay $1, plus $1 for each Ally you have, or move to the street.',NULL,'Innsmouth Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('Ma Mathison comments that you look pallid, and suggests some yard work to get you feeling fit. Pass a Sneak (-1) check to sneak a nap in the shed instead and gain 2 Stamina. If you fail, lose 1 Stamina from Ma''s "tough love" prescription.','Sneak -1','The King in Yellow');
INSERT INTO mas_boarding_house_encounters VALUES ('Ma Mathison offers board as well as room; the bigger the boarder, the bigger the lunch. Search the Common Item deck and take the Food card. Then make a Fight (-1) check. For each success, you may place a token on the Food card; when you use the Food, you may discard the token instead of discarding the card.','Fight -1','Curse of the Dark Pharaoh');
INSERT INTO mas_boarding_house_encounters VALUES ('Ma Mathison offers you a free night''s stay so that she doesn''t have open rooms in case "one o'' them actor types looks to board here." You regain 1 Stamina, but pass a Luck (-1) check or you lose 1 Sanity due to bad dreams.','Luck -1','The King in Yellow');
INSERT INTO mas_boarding_house_encounters VALUES ('Ma Mathison serves her special soup at supper. Roll a die and gain that much Stamina',NULL,NULL);
INSERT INTO mas_boarding_house_encounters VALUES ('Ma Mathison tells you that the best room on the house is available for the night. If you want, pay $3 to spend the night there. Gain 4 points split between Sanity and Stamina however you choose.',NULL,NULL);
INSERT INTO mas_boarding_house_encounters VALUES ('Ma runs a tight ship! You awake refreshed. Gain 2 points split between Stamina and Sanity however you choose.',NULL,'Innsmouth Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('Ma sends you up to tell Mr. Ahrens that supper is ready. His door is ajar and as you push it open, you find that he has tied a noose to the rafters and taken his own life. Lose 1 Sanity.',NULL,'The Black Goat of the Woods');
INSERT INTO mas_boarding_house_encounters VALUES ('Ma''s is full to capacity this time of year. Although Ma is known to become cranky with those who steal away her business, you spend some time getting to know the guests, looking especially for those who might be of use in your investigation. You may become Cursed to draw a random Ally.',NULL,'Kingsport Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('Oliver Thomas, the owner of the Curiositie Shoppe, stops by with a gift for Ma. "Landsakes, what do I need with more knickknacks? Here, you give it someone who can actually use it!" Draw 1 Unique Item.',NULL,'Dunwich Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('Sheriff Engle comes by to see his dear old mother and Ma cooks up a huge mess of grub for everybody. Gain 1 Sanity and 1 Stamina.',NULL,'Dunwich Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('Staring at a painting in one of the rooms, you find yourself drawn into it. Make a Luck (+0) check. If you pass, move to The Dreamlands. Have one encounter there and immediately return here. If you fail, move to the Abyss. Have one encounter there and immediately return here.','Luck +0',NULL);
INSERT INTO mas_boarding_house_encounters VALUES ('The gable room faces east and brings in clean air from the sea. You gain 1 Stamina immediately, and may stay here next turn in order to gain an additional 2 Stamina.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO mas_boarding_house_encounters VALUES ('The last guest to stay in your room had to leave in a hurry and left something behind. Draw 1 Common Item.',NULL,NULL);
INSERT INTO mas_boarding_house_encounters VALUES ('You ambush several monsters emerging from a secret tunnel! Make a Sneak (-2) check and consult the table below.Successes:0) Three monsters appear!1) Draw 1 monster trophy from the cup, but 2 monsters appear!2) Draw 2 monster trophies from the cup, but 1 monster appears!3+) You tear aside the sub-window''s curtain, revealing the dawn''s light and all of the monsters disintegrate! Draw 3 monster trophies from the cup.','Sneak -2','Curse of the Dark Pharaoh');
INSERT INTO mas_boarding_house_encounters VALUES ('You black out somewhere in Southside and wake up to find yourself in the Boarding House. Regain 1 Stamina, then make a Fight (+1) check. If you fail, you regain another Stamina, but you fall back asleep and are delayed.','Fight +1','The King in Yellow');
INSERT INTO mas_boarding_house_encounters VALUES ('You find a poorly boarded-up passage in the basement that opens into a winding tunnel. If you venture into it, you exit in the Silver Twilight Lodge. Draw 2 cards and encounter one card of your choice, discarding the other.',NULL,NULL);
INSERT INTO mas_boarding_house_encounters VALUES ('You recognize the man asking after a room as a wanted murderer. Pass a Speed (-2) check to stop him from getting away and to collect a $5 reward from the police. If you fail, he fights his way free and you lose 1 Stamina.','Speed -2','The Black Goat of the Woods');
INSERT INTO mas_boarding_house_encounters VALUES ('You sneak down to Ma''s kitchen for a midnight snack. Make a Luck (+0) check to see if there''s any leftovers waiting for you. Gain 1 Stamina per success.','Luck +0','The Lurker at the Threshold');
INSERT INTO mas_boarding_house_encounters VALUES ('You wake up to find your bed burning! Pass a Speed (+0) check to escape. If you fail, you are lost in time and space. In any event, there is no sign of the fire afterwards.','Speed +0','The King in Yellow');
INSERT INTO mas_boarding_house_encounters VALUES ('You''re getting ready to turn in for the night when you discover a corpse lying in your bed. Pass a Will (-1) check to keep your cool. If you fail, the terror level increases by 1. In any case, examining the body yields 1 Clue token.','Will -1','Innsmouth Horror');
INSERT INTO mas_boarding_house_encounters VALUES ('You''re invited to a midnight séance. If you attend, you may commune with the spirit realm: look at the top 2 cards of the Mythos deck and replace them, facedown, in any order you like. However, Ma Mathison breaks up the séance and says, "Yew devil worshippers better not come round no more!" Place a Patrol marker on the street area of Southside.',NULL,'Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO mas_boarding_house_encounters VALUES ('You''re invited to a midnight séance. If you attend, you may commune with the spirit realm: Look at the top two cards of the Mythos deck and replace them, facedown, in any order you like. However Ma Mathison breaks up the séance and says that "yew devil worshippers better not come round no more!" You are Barred from Southside.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO mas_boarding_house_encounters VALUES ('Your room''s last occupant left a small shrine to Osiris. Make a Luck (+0) check. If you pass, a monster appears. If you fail, a monster appears and you must take the Harried card.','Luck +0','Curse of the Dark Pharaoh');
INSERT INTO mas_boarding_house_encounters VALUES ('Zebulon Whateley visits from Dunwich to bring Ma a tonic for her cough. In addition, if your Lore is currently 4 or more, he takes you aside and teaches you a spell. Draw 1 Spell.',NULL,'Dunwich Horror');
