CREATE TABLE newspaper_encounters (
    `list_encounter` VARCHAR(433) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(25) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO newspaper_encounters VALUES ('"Get out!" snarls the surly janitor, shaking a fist at you as he pokes his head into the archive room. "We''re closed!" As he moves off down the hallway, he shouts back over his shoulder, "If I come back and you''re still here..." Make a Will (-1) check. If you succeed, gain 2 Clue tokens. If you fail, move to the street.','Will -1','Kingsport Horror');
INSERT INTO newspaper_encounters VALUES ('"Get out!" snarls the surly janitor, shaking a fist at you as he pokes his head into the archive room. "We''re closed!" As he moves off down the hallway, he shouts back over his shoulder, "If I come back and you''re still here..." Make a Will (-1) check. If you succeed, gain 2 Clue tokens. If you fail, move to the street.','Will -1','Kingsport Horror');
INSERT INTO newspaper_encounters VALUES ('"Make yourself useful or get out of here!" You may choose to help load papers onto trucks. If you do, make a Fight (-1) check. If you pass, gain $2. If you fail, lose 1 Stamina. If you choose not to help load the trucks.move to the streets.','Fight -1','The Lurker at the Threshold');
INSERT INTO newspaper_encounters VALUES ('"You may be on to something about that new play. See what you can find out." If you do not already have a Retainer card, you may spend a Clue token to gain one.',NULL,'The King in Yellow');
INSERT INTO newspaper_encounters VALUES ('A competitor to the Arkham Advertiser offers you money to sabotage the presses. If you accept, gain $5 and make a Sneak (-2) check. If you fail, you are arrested as well as Barred from Northside.','Sneak -2','Curse of the Dark Pharaoh');
INSERT INTO newspaper_encounters VALUES ('A competitor to the Arkham Advertiser offers you money to sabotage the presses. If you accept, gain $5 and make a Sneak (-2) check. If you fail, you are arrested. Regardless of the result, place a Patrol marker on the street area of Northside.','Sneak -2','Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO newspaper_encounters VALUES ('A reporter has disappeared, leaving only cryptic and ominous notes about the story she was investigating. If you can make any sense of them, the editor would gladly pay you.Make a Lore (-3) check. If you pass, gain $2 and 1 Clue token.','Lore -3','The Lurker at the Threshold');
INSERT INTO newspaper_encounters VALUES ('A reporter will pay you handsomely, whether in money or information, for an exposé on the life of a monster hunter. Discard any number of monster trophies to gain $1 or 2 Clue tokens (in any combination) (errata: should be $2 or 1 Clue token) for each point of toughness worth of monsters discarded.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO newspaper_encounters VALUES ('A staff photographer pulls you aside and offers to sell you some pictures he took that the paper won''t publish. Spend $3 to gain 2 Clue tokens.',NULL,'The Black Goat of the Woods');
INSERT INTO newspaper_encounters VALUES ('Earn $5 for a story.',NULL,NULL);
INSERT INTO newspaper_encounters VALUES ('Earn $5 for a story.',NULL,'Dunwich Horror');
INSERT INTO newspaper_encounters VALUES ('Earn $5 for a story.',NULL,'Innsmouth Horror');
INSERT INTO newspaper_encounters VALUES ('Editor Doyle Jefferies is offering top dollar for anyone who can provide a first-hand account of the strange events plaguing Arkham. You may move to the nearest Gate. If you do, take a Retainer card and you are drawn through the Gate. If no Gates are open, nothing happens.',NULL,'The Lurker at the Threshold');
INSERT INTO newspaper_encounters VALUES ('Editor Doyle Jefferies is ready to publish what he knows about what''s really going on in Arkham. Pass a Will (-2) check to talk him out of it. If you are unsuccessful, raise the Terror level by 1.','Will -2','The Black Goat of the Woods');
INSERT INTO newspaper_encounters VALUES ('Editor Doyle Jefferies offers you a Retainer in return for your fascinating stories. Take a Retainer card.',NULL,NULL);
INSERT INTO newspaper_encounters VALUES ('Editor Doyle Jefferies offers you a Retainer in return for your fascinating stories. Take a Retainer card.',NULL,NULL);
INSERT INTO newspaper_encounters VALUES ('Editor Doyle Jefferies offers you a Retainer in return for your fascinating stories. Take a Retainer card.',NULL,'Dunwich Horror');
INSERT INTO newspaper_encounters VALUES ('Editor Doyle Jefferies offers you a Retainer in return for your fascinating stories. Take a Retainer card.',NULL,'The Black Goat of the Woods');
INSERT INTO newspaper_encounters VALUES ('Flipping through the early edition, you are surprised to see that one of the classified ads begins with your name. Reading it, you realize that it contains several coded clues to the nature of the threat that faces Arkham. Pass a Lore (-1) check to gain 3 Clue tokens.','Lore -1',NULL);
INSERT INTO newspaper_encounters VALUES ('Good thing you had that camera with you earlier. You may spend 3 toughness worth of monster trophies to gain 2 Clue tokens.',NULL,'The King in Yellow');
INSERT INTO newspaper_encounters VALUES ('If Coded Messages is facedown, you come across the editor, Doyle Jefferies, in the hall and begin to tell hiim about the Mythos. "Hang on now. Do you have any proof?" You may spend 1 gate trophy, 1 monster trophy, and 1 Clue token to give him enough proof. If you do, turn Coded Messages faceup. "Okay, I''m convinced. If you need to get a message to your friends, just let me know." If you do not spend the trophies, nothing happens.',NULL,'Dunwich Horror');
INSERT INTO newspaper_encounters VALUES ('If you pass a Luck (-1) check, then one of the newspaper delivery men offers you a ride in his truck while he makes his rounds. If you accept, move to any street area or location in Arkham. If you move to a location, immediately have an encounter there. If you fail the check, nothing happens.','Luck -1','Dunwich Horror');
INSERT INTO newspaper_encounters VALUES ('Pass a Luck (-1) check to find an article that a local citizen told you would shed light on the recent strange activities. Gain 1 Clue token.',NULL,NULL);
INSERT INTO newspaper_encounters VALUES ('Someone has sent an anonymous package to the paper. Whatever is inside is leaking a dark, sticky fluid. Upon seeing what''s inside, lose 1 Sanity.',NULL,'The Lurker at the Threshold');
INSERT INTO newspaper_encounters VALUES ('Staring into the presses is like watching the flow of history passing by you. You begin to see a strange pattern to it all. Take the Visions card.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO newspaper_encounters VALUES ('Talking to the editor, Doyle Jefferies, you realize that he could be a good source of information. You may either buy up to 3 Clue tokens for $2 each, or sell up to 3 Clue tokens for $2 each.',NULL,'Dunwich Horror');
INSERT INTO newspaper_encounters VALUES ('The editor asks you to answer phones on a busy night. You pick up one call and hear nothing at first. Then you hear your name being whispered by something that can''t possibly be human. Make a Will (-1) check or lose 1 Sanity. Then make a Speed (-2) check to activate a call trace in time. If you pass, you learn that it came from the museum exhibit. Gain 2 Clue tokens','Will -1
-THEN-

Speed -2
','Curse of the Dark Pharaoh');
INSERT INTO newspaper_encounters VALUES ('The staff of the Advertiser are uncharacteristically closemouthed. As you leave, you find yourself surrounded by sallow-skinned ruffians. Make a Fight (-1) check and lose 3 Stamina. This loss is reduced by 1 for every success (minimum 0).','Fight -1','Innsmouth Horror');
INSERT INTO newspaper_encounters VALUES ('There are some real bargains in the classified ads. You may draw a Common Item and purchase it at half price, rounding up.',NULL,'The Black Goat of the Woods');
INSERT INTO newspaper_encounters VALUES ('They say there are hidden messages in the newsprint that can only be seen halfway through the printing process. Pass a Sneak (-3) check to catch a glimpse and gain 2 Clue tokens. If you fail, you are arrested.','Sneak -3','The King in Yellow');
INSERT INTO newspaper_encounters VALUES ('Walking down a narrow hallway, you bump into a young man carrying various chemicals used for the printing presses. He drops one of the jars he''s carrying and it breaks, sending burning fumes up into your face. Lose 1 Stamina.',NULL,'Dunwich Horror');
INSERT INTO newspaper_encounters VALUES ('While going through the archives, you find a yellowed collection of Innsmouth Courier newspapers. Gain 1 Clue token.',NULL,'Innsmouth Horror');
INSERT INTO newspaper_encounters VALUES ('You accidentally tip over a bottle of ink and are aghast at the pattern the ink forms on the newsroom floor. Lose 1 Sanity.',NULL,NULL);
INSERT INTO newspaper_encounters VALUES ('You call around for a story, asking about mysterious occurrences related to the visiting museum exhibit. Make a Luck (+0) check. For each success, you may take 1 Clue token from any locations in Arkham and add it to your pool. If there are not Clue tokens in Arkham, you may not gain any.','Luck +0','Curse of the Dark Pharaoh');
INSERT INTO newspaper_encounters VALUES ('You earn a hefty fee for a story and get a ride with Doyle Jefferies, the editior. Gain $2 and move to any location or street area in Arkham. If you move to a location, immediately have an encounter there.',NULL,NULL);
INSERT INTO newspaper_encounters VALUES ('You open what seems like the hundredth file whose contents bear no relation either to each other or the drawer where you found them. You are delayed.',NULL,'Kingsport Horror');
INSERT INTO newspaper_encounters VALUES ('You sigh loudly, folding an archive copy of the Advertiser shut, no wiser than when you opened it. The reporter on the other side of the room looks up. "Help you find something?" he asks. "I''ve got nothing but time...for a price." Buy as many Clues as you like for $3 each.',NULL,'Kingsport Horror');
INSERT INTO newspaper_encounters VALUES ('You spin a yarn to a group of assembled reporters. Make a Will (-1) check to see how many of them believe you. Gain $1 per success.','Will -1','Innsmouth Horror');
INSERT INTO newspaper_encounters VALUES ('You watch some workers cleaning the presses with rages while the machines are still running, and you wonder if that''s safe. A moment later, your thought proves prophetic as one of them screams, his arm caught in the press. Several workers rush to his aid, while others clear the room. You are moved to the street.',NULL,'Dunwich Horror');
INSERT INTO newspaper_encounters VALUES ('You''ve experienced some strange things. Doyle Jeffries, the editor, will pay you $5 for an interview. If you accept, you are delayed.',NULL,'The King in Yellow');
