CREATE TABLE police_station_encounters (
    `list_encounter` VARCHAR(365) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(27) CHARACTER SET utf8
);
INSERT INTO police_station_encounters VALUES ('"Haven''t had time to bring him out to the asylum," Sheriff Engle explains when he notices you eyeing a straitjacketed lunatic ranting in one of the cells. That''s when you realize what the madman''s saying. You are delayed as you jot notes about his ravings, but gain 2 Clue Tokens.',NULL,'Kingsport Horror');
INSERT INTO police_station_encounters VALUES ('"Please! My husband is innocent! He could never commit those atrocities!" Deputy Dingby refuses to listen to the woman, but her story explains much of what has been going on. Gain 1 Clue token.',NULL,'The Lurker at the Threshold');
INSERT INTO police_station_encounters VALUES ('"Sure, Deputy, I''ve got a permit for that. Yeah, that too." You''re lying through your teeth, but if you can sell it, he''ll drop the issue. Make a Will (-1) check. If you fail, you must discard all of your Weapon cards, and are arrested.','Will -1','Kingsport Horror');
INSERT INTO police_station_encounters VALUES ('"You okay, fella? You''re not making sense." Sheriff Engle wants to keep you out of trouble. If you currently have 2 or less Sanity, make a Fight (+0) check. If you fail, lose all your Weapons and lose 1 Stamina.','Fight +0','The Lurker at the Threshold');
INSERT INTO police_station_encounters VALUES ('A brawl breaks out at the front desk and you get swept up into the fray. Make a Fight (+0) check or lose 1 Stamina.','Fight +0','The Black Goat of the Woods');
INSERT INTO police_station_encounters VALUES ('A protestor was arrested outside a performance of "The King in Yellow," and his ranting can be heard from the cells. Pass a Lore (-1) check to gain a Clue Token.','Lore -1','The King in Yellow');
INSERT INTO police_station_encounters VALUES ('Deputy Dingby accidently drops a case file as he makes his way past you. Pass a Sneak (+0) check to search the Common Item deck for a Research Materials card and take it.','Sneak +0',NULL);
INSERT INTO police_station_encounters VALUES ('Deputy Dingby, excitedly cleaning his gun, fires a bullet from the chamber in your direction. Pass a  Luck (-1) check to avoid getting shot. If you fail, lose 2 Stamina.','Luck -1',NULL);
INSERT INTO police_station_encounters VALUES ('Deputy Dingby forgot to bring his lunch today, and if you help him out, he''ll become very friendly and chatty. You may give the Deputy either the Food Common Item card or $1 to gain 1 Clue token in return.',NULL,'The Lurker at the Threshold');
INSERT INTO police_station_encounters VALUES ('Deputy Dingby has left the keys to the evidence locker sitting on his desk. Make a Sneak (-2) check and, if you succeed, search the Common Item deck for an item of your choice.','Sneak -2','Innsmouth Horror');
INSERT INTO police_station_encounters VALUES ('Deputy Dingby somehow manages to handcuff the two of you together. Stay here next turn, but you actually gain some valuable information listening to Dingby prattle on until Sheriff Engle returns. Gain 1 Clue Token.',NULL,'Dunwich Horror');
INSERT INTO police_station_encounters VALUES ('If you succeed at a Luck (-1) check, then Deputy Dingby absentmindedly leaves you holding his gun. You may search the Common Item deck for a .45 Revolver (errata: should read .38 Revolver) card and take it.','Luck -1',NULL);
INSERT INTO police_station_encounters VALUES ('Looking at one of the wanted posters, you realize that you''ve already taken care of that particular threat. You may spend 1 monster trophy with a moon dimensional symbol to gain $5.',NULL,'Dunwich Horror');
INSERT INTO police_station_encounters VALUES ('Looking at one of the wanted posters, you realize that you''ve already taken care of that particular threat. You may spend 1 monster trophy with a moon dimensional symbol to gain $5.',NULL,'Dunwich Horror');
INSERT INTO police_station_encounters VALUES ('Looking at one of the wanted posters, you realize that you''ve already taken care of that particular threat. You may spend 1 monster trophy with a moon dimensional symbol to gain $5.',NULL,'Innsmouth Horror');
INSERT INTO police_station_encounters VALUES ('Make a Sneak (-1) check to listen in on an interrogation, and consult the following chart.Successes:0) You misunderstand what is discussed. Lose 1 Clue Token. 1-2) Deputy Dingby sees you standing by the door. Pay $2 to gain 1 Clue Token. 3+) What you overhear helps you put the pieces together. Gain 2 Clue Tokens.','Sneak -1','Curse of the Dark Pharaoh');
INSERT INTO police_station_encounters VALUES ('On the wall is a map of the city with pins marking the places where incidents have occured. Imagining lines between these points, an unnerving symbol is revealed to you. Pass a Will (-1) check or lose 2 Sanity.','Will -1','The Black Goat of the Woods');
INSERT INTO police_station_encounters VALUES ('One of the jail''s "guests" decides to end it all rather than face justice, and Deputy Dingby offers you a pick of his belongings. Pass a Luck (+0) check to draw a number of cards from the Common Item deck equal to the number of successes rolled. Keep 1 card and discard the rest.','Luck +0','Curse of the Dark Pharaoh');
INSERT INTO police_station_encounters VALUES ('One of the men in the holding cells tries to intimidate you with stories about the things he''s seen. Make a Will (-1) check. If you pass, gain 1 Clue Token. If you fail, move to the street and lose 1 Sanity as the man laughs at your retreating back.','Will -1',NULL);
INSERT INTO police_station_encounters VALUES ('One of the prisoners carefully searches your face for any sign of pity, "Please, you gotta get me outta here! Something''s coming to Arkham! Something horrible!" You try to laugh away his concerns, but the abject terror in his voice sends a chill down your spine. Lose 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO police_station_encounters VALUES ('Pass a Will (-1) check to convince Deputy Dingby to share some files with you that are very interesting. Gain 2 Clue Tokens.','Will -1',NULL);
INSERT INTO police_station_encounters VALUES ('Sheriff Engle blocks the door into the Police Station. "Sorry, I''ve got to lock up for a bit. I''ll be back later". Everyone in the Police Station (but not the Jail Cell) is moved to the street.',NULL,'Dunwich Horror');
INSERT INTO police_station_encounters VALUES ('Sheriff Engle blocks the door into the Police Station. "Sorry, I''ve got to lock up for a bit. I''ll be back later". Everyone in the Police Station (but not the Jail Cell) is moved to the street.',NULL,'Dunwich Horror');
INSERT INTO police_station_encounters VALUES ('Sheriff Engle eyes you suspiciously. "Hey, you were part of that trouble earlier." Pay him $3 or spend the next turn delayed answering his questions.',NULL,'Innsmouth Horror');
INSERT INTO police_station_encounters VALUES ('Sheriff Engle is training security guards for performances of "The King in Yellow," but the training is rigorous. Make a Fight (-1) check to qualify. If you pass, you may search the Common Item deck and take the first Weapon you find. If you fail, you lose 1 Stamina.','Fight -1','The King in Yellow');
INSERT INTO police_station_encounters VALUES ('Sheriff Engle listens to your tale. He''s ready to take action, assuming that he believes you. Pass a Will (-3) check to convince him. If you do, choose one location or street area and return all monsters in it to the cup as armed law enforcement officers storm in.','Will -3','The Black Goat of the Woods');
INSERT INTO police_station_encounters VALUES ('Sheriff Engle nods to you as you enter the Police Station. "Something I can help you with?" If you spend 3 Clue tokens, you convince him that Arkham is in danger and he issues you a weapon. Take the first Weapon from the Common Item deck.',NULL,'Dunwich Horror');
INSERT INTO police_station_encounters VALUES ('Sheriff Engle notes that you''re carrying an awful lot of weapons. Either pay him $5 or discard all of your Weapons.',NULL,NULL);
INSERT INTO police_station_encounters VALUES ('Sheriff Engle trusts you and asks you to step into his office to discuss the recent strange events. Pass a Luck (-2) check to convince him to take you into his confidence and give you something to help you out. Draw 1 Unique Item.','Luck -2',NULL);
INSERT INTO police_station_encounters VALUES ('Sheriff Engle wrestles a prisoner into the lobby of the Police Station. The handcuffed man bumps into you and whispers, "I can''t be found with this." Make a Sneak (-1) check. If you pass, draw 1 Common item.','Sneak -1','The Lurker at the Threshold');
INSERT INTO police_station_encounters VALUES ('The phone at the front desk is ringing, but no one seems to be answering it. If you pick up the receiver, an unearthly voice whispers awful secrets to you. Lose 1 Sanity, but make a Will (-1) check and gain 1 Clue Token for each success.','Will -1','Innsmouth Horror');
INSERT INTO police_station_encounters VALUES ('The police are desperate for leads and are offering a reward for information. Gain $1 for each Clue Token in your possession.',NULL,'The Black Goat of the Woods');
INSERT INTO police_station_encounters VALUES ('The police department is decommissioning one of its paddy wagons and empties its trunk into the garbage. Pass a Luck (+1) check to draw a number of Common Items equal to the successes rolled. Choose one Item and discard the rest.','Luck +1','The King in Yellow');
INSERT INTO police_station_encounters VALUES ('The word "Reward" on a leaflet gets your attention. You may spend one monster trophy with a moon dimensional symbol on it to gain $5.',NULL,'Kingsport Horror');
INSERT INTO police_station_encounters VALUES ('With all the strange outsiders coming to see the visiting museum exhibit, Sheriff Engle worries about Arkham''s safety. If you have a Physical weapon, he gives you some training, and you may search the Skill deck for the Marksman card and take it. If you do not have a Physical weapon, search the Common Item deck and take the first Weapon you find.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO police_station_encounters VALUES ('You are called in for questioning about missing artifacts from the "Legacy of the Pharaohs" exhibit. Make a Will (-1) check. If you pass, the Sheriff believes you are innocent, and his questions tip you off about a few things; Gain 1 Clue Token. If you fail, he doubts your word, and accuses you of a crime! Choose between being arrested and taking the Wanted card.','Will -1','Curse of the Dark Pharaoh');
INSERT INTO police_station_encounters VALUES ('You stop by to say hello when you hear an argument from Sheriff Engle''s office. "But why would a killer perfume the body with lavender and peppermint?" Make a Lore (-2) check. If you pass, you recognize those herbs as being used in an ancient Egyptian embalming practices. Gain 1 Clue Token and the Sheriff rewards you with the Private Investigator card.','Lore -2','Curse of the Dark Pharaoh');
INSERT INTO police_station_encounters VALUES ('You''re called in for your expertise in the unusual to help examine a violent man who attacked cast members of "The King in Yellow." Make a Lore (-1) check. If you pass, gain 2 Clue Tokens. If you fail, Sheriff Engle demands that you stay and sort out the case. Stay here next turn.','Lore -1','The King in Yellow');
INSERT INTO police_station_encounters VALUES ('You''re sitting in the reception area when Sheriff Engle steps out of the back. He looks at you intently. Make a Will (-1) check. If you succeed, he hands you a pair of handcuffs and says "You look like you could put these to good use." Search the Common Items deck for a Handcuffs card. If you fail, nothing happens.','Will -1','Kingsport Horror');
