CREATE TABLE river_docks_encounters (
    `list_encounter` VARCHAR(454) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO river_docks_encounters VALUES ('"Listen," says Joey "The Rat". "These just fell off the back of the boat, you get me?" Draw 2 Common Items. You may purchase one of them for $1 more than its list price.',NULL,'Innsmouth Horror');
INSERT INTO river_docks_encounters VALUES ('A crate bobs by the dock. Pass a Fight (-2) check to pull it from the river and draw 1 Common Item.','Fight -2','The King in Yellow');
INSERT INTO river_docks_encounters VALUES ('A horrific stench draws your attention to the body of some bizarre marine creature, rotting on the edge of the docks. As you move towards it, an uneasy feeling grows in the pit of your stomach, as though you are meddling with something best left alone. Make a Will (-1) check. If you pass, lose 1 Sanity. If you fail, lose 2 Sanity. In either event, if you are not reduced to 0 Sanity, you find something clutched in its webbed hands. Draw 1 Unique Item.','Will -1',NULL);
INSERT INTO river_docks_encounters VALUES ('A load of cargo, precariously balanced on the edge of the dock, goes into the river with a splash. If you dive in and try to retrieve it, a monster appears, and you suffer a -1 to your Combat checks. If you evade or defeat the monster, you may draw 2 Common Items.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO river_docks_encounters VALUES ('A rowdy dock hand doesn''t like the looks of you and challenges you to a fistfight. Make a Fight (+1) [2] check. If you pass, lose 1 Stamina, but you may search the Skill deck for the Fight card and take it. If you fail, the dock workers spit on you, and you run off. Lose 2 Stamina and place a Patrol marker on the street area of the Merchant District.','Fight +1','Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO river_docks_encounters VALUES ('A rowdy dock hand doesn''t like the looks of you, and challenges you to a fistfight. Make a Fight (+1) [2] check. If you pass, lose 1 Stamina, but you may search the Skill deck for the Fight card and take it. If you fail, the dock workers spit on you and you run off. Lose 2 Stamina and you are Barred from the Merchant District.','Fight +1','Curse of the Dark Pharaoh');
INSERT INTO river_docks_encounters VALUES ('A shambling heap clambers from the river and engulfs you. If you pass a Fight (-2) check, you find a Common Item in the aftermath. Otherwise, lose 1 Stamina.','Fight -2','The King in Yellow');
INSERT INTO river_docks_encounters VALUES ('A terrified young student from Miskatonic University seems to have wound up here by accident. Make a Will (+1) check to keep him calm enough to safely guide him back to more familiar streets. If you pass, he gratefully offers you $2 for your assistance.','Will +1','The Lurker at the Threshold');
INSERT INTO river_docks_encounters VALUES ('A woman stands on the docks waiting for her husband to return, six years after his boat sank. As she tells you her sad tale, she hears her name called out by a familiar voice. Her husband has survived and returned at last! She calls you her lucky charm and Blesses you from the bottom of her heart.',NULL,'The Black Goat of the Woods');
INSERT INTO river_docks_encounters VALUES ('A young man is anxiously trying to arrange passage out of the city. Upon questioning him, he admits to horrific and revealing dreams of an impending doom. Gain 1 Clue Token.',NULL,'The Black Goat of the Woods');
INSERT INTO river_docks_encounters VALUES ('An unruly gang has descended upon Abner Weems, the local drunk. Pass a Fight (-1) check to chase them off. If you succeed, Abner gives you the object he took which got him in trouble in the first place. Gain 1 Common Item. If you do not succeed, lose 1 Stamina.','Fight -1','The Black Goat of the Woods');
INSERT INTO river_docks_encounters VALUES ('As a truck is driving away from the warehouse, you see a crate fall off the back. Unfortuneately, Joey "the Rat" saw it too. Make a Speed (+1) check to beat him to the crate. If you pass, gain 1 Common Item.','Speed +1','The Lurker at the Threshold');
INSERT INTO river_docks_encounters VALUES ('As the dock workers switch shifts for the night, you notice an ornate money clip at your feet. You pick it up, telling yourself you will use the bills clasped within for the greater good. Take $2, but pass a Luck (-1) check or become Cursed.','Luck -1','Kingsport Horror');
INSERT INTO river_docks_encounters VALUES ('As the walking dead unload cargo from a ship with no name, you notice a box of booty forgotten under the gangplank. Make a Luck (-1) check. If you succeed, draw one Common Item. If its value is $2 or less, draw an additional Common Item.','Luck -1','Kingsport Horror');
INSERT INTO river_docks_encounters VALUES ('As you look out across the waves, you feel strangely compelled to throw yourself into the ocean''s watery embrace. Pass a Will (+1) check or you are Lost in time and space.','Will +1',NULL);
INSERT INTO river_docks_encounters VALUES ('At the end of the dock, an elderly gentleman graps a paper bag tightly, mumbling unintelligibly and pacing. He sees you and points, motioning for you to give him something. Not wanting to upset this strange hermit, you search for something to give him. You may discard 1 Common Item to draw 1 Unique Item.',NULL,'Kingsport Horror');
INSERT INTO river_docks_encounters VALUES ('If you have any Tomes but no Weapons, a crew of roustabouts mocks you for your "book learning" and begins to push you around. Lose 2 Stamina.',NULL,'The King in Yellow');
INSERT INTO river_docks_encounters VALUES ('Items in an abandoned warehouse are being auctioned off. The selection is quite good, but prices are running high. Draw the top three Common Items from their deck. You may purchase 1 of them for $1 more than the listed price. Discard any items that are not purchased.',NULL,'The Lurker at the Threshold');
INSERT INTO river_docks_encounters VALUES ('Joey "The Rat" is huddled under the roof of one of warehouses. Seeing you, he waves you over. "Look, I think I''ve gotten in over my head this time. Ever since I got this thing weird stuff''s been going on. I''ll give you $5 to take it off my hands! Please, think of my wife and kids!" If you accept, draw 1 Common Item, gain $5, and become Cursed.',NULL,'Dunwich Horror');
INSERT INTO river_docks_encounters VALUES ('One of the warehouse foremen could use someone who''s good with numbers. Make a Lore (+0) check. If you pass, gain $3 for every success you rolled. If you fail, he throws you out hard enough to make you bounce after checking your numbers. Lose 1 Stamina and move to the street.','Lore +0','Dunwich Horror');
INSERT INTO river_docks_encounters VALUES ('Rising from the watery depths, the corpse of a murder victim floats to the surface. Lose 1 Sanity, but gain $3 from the grateful police who are working on the case.',NULL,'The Black Goat of the Woods');
INSERT INTO river_docks_encounters VALUES ('Rotten food in a shipping crate has attracted a multitude of maggots. Under the repulsive feast, you see a wad of cash. Make a Will (-1) check to reach through the writhing mass and take $3 per success. If you fail, lose 1 Stamina and move to the street.','Will -1','Kingsport Horror');
INSERT INTO river_docks_encounters VALUES ('Sitting by the dock, you freeze in silent horror as something slowly rises from the water. You cannot make out what it is, but judging by the number of stars it blots out with its bulk, it is considerably bigger than a whale. After an eternity, it slowly sinks beneath the waves once more. Lose 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO river_docks_encounters VALUES ('Staring out across the placid waters, you look at the stars reflected in their depths and let the soft sound of the waves comfort you. Gain 1 Sanity',NULL,'Dunwich Horror');
INSERT INTO river_docks_encounters VALUES ('The dock workers are short-handed and offer you a job as a stevedore for the day. Make a Fight (+0) check. If you pass, gain $3 for every success you rolled. If you fail, the boss gets tired of your lollygagging and throws you out. Lose 1 Stamina and move to the street.','Fight +0',NULL);
INSERT INTO river_docks_encounters VALUES ('The docks are overloaded with shipments coming in to support the museum exhibit. No one will notice if something goes missing. Make a Sneak (-1) check. For each success, you may draw 1 Common Item. You may keep any non-Weapon cards, and must discard the rest.','Sneak -1','Curse of the Dark Pharaoh');
INSERT INTO river_docks_encounters VALUES ('The leading lady of "The King in Yellow" arrives via a steamer packet from the coast. She confuses you for a porter and hands you her bags to carry. Make a Luck (-1) check. If you pass, she leaves one of them with you as a souvenir. Draw 1 Common Item. If you fail, she accuses you of trying to steal it and you are arrested.','Luck -1','The King in Yellow');
INSERT INTO river_docks_encounters VALUES ('The men unloading those boxes have stooped postures and wide, staring eyes. If you try to investigate what they''re doing, make a Sneak (-2) check. If you pass, you find 1 Unique Item in a crate. If you fail, lose 2 Stamina and 1 Sanity.','Sneak -2','Innsmouth Horror');
INSERT INTO river_docks_encounters VALUES ('This area has always smelled foul, but today something in the river smells absolutely noxious. Make a Speed (-2) check to reach fresher air. If you fail, lose 1 Stamina. Whether you pass or not, move to the street.','Speed -2','The Lurker at the Threshold');
INSERT INTO river_docks_encounters VALUES ('Walking along the dock you see something floating in the water near the edge of the dock. You reach for it - make a Luck (-1) check. If you pass, you dredge up something useful. Draw 1 Common Item. If you fail, you pull to the surface the tentacle that immediately wraps around your neck and drags you under the water and out to sea. Lose 1 Sanity and 3 Stamina before you break free.','Luck -1',NULL);
INSERT INTO river_docks_encounters VALUES ('Walking along the river at night, you bump into a man smoking a stoagie and wearing a trenchcoat. "You look like a person with problems. It just so happens that my business is making problems go away." You may pay $6 to automatically defeat any 1 non-Spawn monster on the board.',NULL,'Dunwich Horror');
INSERT INTO river_docks_encounters VALUES ('Walking along the river at night, you bump into a man smoking a stoagie and wearing a trenchcoat. "You look like a person with problems. It just so happens that my business is making problems go away." You may pay $6 to automatically defeat any 1 non-Spawn monster on the board.',NULL,'Dunwich Horror');
INSERT INTO river_docks_encounters VALUES ('Walking along the river at night, you bump into a man smoking a stoagie and wearing a trenchcoat. "You look like a person with problems. It just so happens that my business is making problems go away." You may pay $6 to automatically defeat any 1 non-Spawn monster on the board.',NULL,'Innsmouth Horror');
INSERT INTO river_docks_encounters VALUES ('You bump into Abner Weems, the local drunk. Leaning on your shoulder, he cries as he tells you how his wife and daughter were taken away by a black, three-eyed creature one night. He then babbles for a while, talking about ways to fight such monsters. Make a Luck (-1) check. If you pass, his babbling is helpful. Gain 2 Clue Tokens.','Luck -1','Dunwich Horror');
INSERT INTO river_docks_encounters VALUES ('You bump into Abner Weems, the local drunk. You help him find a place to sleep for the night, and he mumbles something to you over and over. Make a Luck (-1) check. If you pass, his mumbling is a magical chant. Draw 1 Spell. If you fail, it''s gibberish. Nothing happens.','Luck -1',NULL);
INSERT INTO river_docks_encounters VALUES ('You notice a piece of wood floating in the water; carved into it is the name of a ship long since sunk. As you touch it, visions of the drowning passengers'' last moments of life flood through your mind. Pass a Speed (-1) check to hurl it away from you. If you fail, you fall to the ground with a cry. Lose 1 Sanity.','Speed -1',NULL);
INSERT INTO river_docks_encounters VALUES ('You open some crates on the dock. Inside you find some useful things. Draw 2 Common Items. Next, make a Luck (-1) check. If you pass, you get away without being seen. If you fail, you are arrested and taken to the Police Station.','Luck -1',NULL);
INSERT INTO river_docks_encounters VALUES ('You see men of questionable character guiding one of the visiting museum curators toward the edge of the dock...his hands are tied! He pleads to you for help with silent eyes. If you aid him, make a Fight (-2) check. If you pass, you wrest the weapon from one and chase them off; you may search the Common Item deck and take the Tommy Gun card. If you fail, lose 2 Stamina.','Fight -2','Curse of the Dark Pharaoh');
INSERT INTO river_docks_encounters VALUES ('You stare into the river, contemplating its currents and depths. Make a Luck (+0) check. If you pass, you realize that time, fate, all of reality, are like a river; take the Visions card. If you fail, a pair of dock workers knock you into the river as a lark, and you catch a cold. Lose 1 Stamina.','Luck +0','Curse of the Dark Pharaoh');
INSERT INTO river_docks_encounters VALUES ('Your footsteps on the wooden dock are echoed by splashing noises below that keep pace with you. Make a Will (+0) check. If you fail, lose 2 Sanity and move to the street. If you pass, lose 1 Sanity but stay where you are.','Will +0','Innsmouth Horror');
