CREATE TABLE south_church_encounters (
    `list_encounter` VARCHAR(427) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO south_church_encounters VALUES ('"A strong soul must be willing to make sacrifices," Father Michael says. You may discard a single beneficial Investigator card (a Spell, Item, Ally, etc.) to make a Luck (+1) check. If you pass, you are restored to full Sanity. If you fail, you gain only 1 Sanity.','Luck +1','The King in Yellow');
INSERT INTO south_church_encounters VALUES ('"Father Michael?" You look into the back office, and see the priest being assaulted by a demonic servitor of Horus! If you have a Cross, Holy Water, or Blessing card, you drive it off. Father Michael is shaken, and asks you to assist in running the church while he atones. If you drove off the being, you may take the Anointed card.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO south_church_encounters VALUES ('"Pray for Arkham, my son." Make a Will (-2) check and consult the chart below:Successes:0) The Dark Pharaoh hears your prayer. Each investigator must make a Will (-2) check or be Cursed.1-2) New and old gods alike hear you. Each investigator gains 1 Stamina and 1 Sanity, but add 1 doom counter to the doom track.3+) Hope is rekindled. You gain 2 Sanity, and each investigator may make a Will (-2) check in order to be Blessed.','Will -2','Curse of the Dark Pharaoh');
INSERT INTO south_church_encounters VALUES ('"You! You are the one who has stood against the evil that plagues this town. We are all so grateful!" A crowd surrounds you, expressing gratitude and adoration. Gain 2 Sanity.',NULL,'The Lurker at the Threshold');
INSERT INTO south_church_encounters VALUES ('A man attacks Father Michael as he tends to the grounds! Pass a Fight (-1) check to drive the man off. If you fail, you are Cursed.','Fight -1','The King in Yellow');
INSERT INTO south_church_encounters VALUES ('A terrified young man staggers into the church seeking sanctuary. He tries to explain what has traumatized him, but it is difficult to interpret his ravings. Pass a Lore (-1) check to gain 1 Clue token.','Lore -1','The Black Goat of the Woods');
INSERT INTO south_church_encounters VALUES ('An esteemed organist from the Church of St. Barnabe in France has been haunting South Church, disturbing the flock with his otherworldly playing. Father Michael asks you to convince him to leave. Pass a Fight (-2) check to intimidate him into leaving and gain 2 Sanity. If you fail, he troubles your dreams, and you are reduced to 1 Sanity.','Fight -2','The King in Yellow');
INSERT INTO south_church_encounters VALUES ('Exhausted and drained, you sit and listen to the choir for a while. Their beautiful singing helps get you back on your feet. Perhaps there''s no meaning to the universe, but then again, perhaps we give it our own meaning. Gain 2 Stamina and 2 Sanity.',NULL,'Dunwich Horror');
INSERT INTO south_church_encounters VALUES ('Father Michael convinces you that there are members of his congregation in greater need than you. Donate either half your money (rounded up) or half your items (your choice, rounded up) to the poor.',NULL,NULL);
INSERT INTO south_church_encounters VALUES ('Father Michael directs you to the box for donations and tells you to take what you need. Take $2 or draw a Common Item.',NULL,'Kingsport Horror');
INSERT INTO south_church_encounters VALUES ('Father Michael is impressed by your conviction in the fight against the rising evil. You are Blessed.',NULL,'Kingsport Horror');
INSERT INTO south_church_encounters VALUES ('Father Michael, sensing that some evil may be afflicting you without your knowledge, suddenly submerges your head in the font of holy water. Make a Luck (-1) check. If you succeed, restore your Sanity to its maximum. If you fail, lose 1 Stamina.','Luck -1','Kingsport Horror');
INSERT INTO south_church_encounters VALUES ('Father Michael talks with you for a little while about your doubts and fears. You come away from the talk feeling a lot better than you did before. Gain 2 Sanity.',NULL,'Dunwich Horror');
INSERT INTO south_church_encounters VALUES ('Father Michael''s sermon is comforting, but a little dull, and you''ve dozed off. Stay here next turn and restore your Sanity to its maximum.',NULL,'The Lurker at the Threshold');
INSERT INTO south_church_encounters VALUES ('If you can show Father Michael proof of the doom that threatens Arkham, he will agree to lead the congregation in a prayer to purge the streets of evil. If you spend 1 Gate trophy, you may remove all monsters from the Southside neighborhood.',NULL,'The Lurker at the Threshold');
INSERT INTO south_church_encounters VALUES ('If you have any Exhibit Items, Father Michael calls them profane works and demands that you destroy them. If you refuse, place a Patrol marker on the street area of Southside. If you agree, you gain 1 Sanity and 1 Clue token per item discarded.',NULL,'Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO south_church_encounters VALUES ('If you have any Exhibit Items, Father Michael calls them profane works and demands that you destroy them. If you refuse, you are Barred from Southside. If you agree, you gain 1 Sanity and 1 Clue token per item discarded.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO south_church_encounters VALUES ('Kneeling in one of the pews to pray, you come across an unusual book. Take the first Tome from the Unique Item deck.',NULL,'Dunwich Horror');
INSERT INTO south_church_encounters VALUES ('Knowing that you are engaged in God''s work, Father Michael Blesses you.',NULL,NULL);
INSERT INTO south_church_encounters VALUES ('Knowing that you are engaged in God''s work, Father Michael Blesses you.',NULL,'Dunwich Horror');
INSERT INTO south_church_encounters VALUES ('Knowing that you are engaged in God''s work, Father Michael Blesses you.',NULL,'Innsmouth Horror');
INSERT INTO south_church_encounters VALUES ('Make a Luck (-2) check. If you pass, then you stare up at the stained glass windows, see the light shining in through them, and realize that your troubles aren''t as bad as you thought they were. All investigators who are Cursed may discard their Curse cards.','Luck -2','Dunwich Horror');
INSERT INTO south_church_encounters VALUES ('Noticing you eying the holy water, Father Michael tells you, "Take what you need, my child." You may search the Unique Item deck for a Holy Water card and take it.',NULL,NULL);
INSERT INTO south_church_encounters VALUES ('Reading one of the bibles in the pews, you seek spiritual guidance. Letting it fall open to a page, you read, "The Lord helps those who help themselves." Oddly, it makes you feel better. You may spend 2 Clue tokens to discard the current Environment from play.',NULL,'Dunwich Horror');
INSERT INTO south_church_encounters VALUES ('Someone left a box of donation items at the Church''s doorstep. You notice an odd, grotesque idol. Make a Will (+0) check. If you fail, you are Cursed.','Will +0','The Lurker at the Threshold');
INSERT INTO south_church_encounters VALUES ('Stumbling into the church, you look up in horror to realize that you''ve just interrupted someone''s funeral. Stammering an apology, you move to the street.',NULL,'Dunwich Horror');
INSERT INTO south_church_encounters VALUES ('The church is having a bake sale! Everything smells delicious. Spend $1 on treats to regain 1 Stamina.',NULL,'The Black Goat of the Woods');
INSERT INTO south_church_encounters VALUES ('The Cult of the Black Goat has vandalized the church, and Father Michael asks for your help in painting over the blasphemous graffiti and cleaning up the damage. If you wish to help, you are delayed by the effort, but Father Michael Blesses you for your hard work.',NULL,'The Black Goat of the Woods');
INSERT INTO south_church_encounters VALUES ('The morning sun shines through the stained-glass windows, warming your spirit. Gain Sanity equal to the number of locations with sealed gates.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO south_church_encounters VALUES ('Upon entering the church, you are attacked by Father Michael with a giant cross, who for some reason believes you to be in league with the devil. Make a Speed (-1) check. If you pass, you escape. If you fail, lose 2 Stamina. In either case, move to the street.','Speed -1',NULL);
INSERT INTO south_church_encounters VALUES ('Whatever else might be wrong in Arkham, you feel safe here. Gain 1 Sanity.',NULL,'Innsmouth Horror');
INSERT INTO south_church_encounters VALUES ('When the donation tray comes around, you find yourself guiltily contributing. You lose $1.',NULL,'Innsmouth Horror');
INSERT INTO south_church_encounters VALUES ('You admire a new stained-glass window from the pews, but if you could peer directly through it, how illuminated life would seem! Make a Fight (-2) check to climb up to it safely. If you pass, gain 1 Sanity. If you fail. lose 2 Stamina.','Fight -2','The King in Yellow');
INSERT INTO south_church_encounters VALUES ('You could swear a drain pipe gargoyle moved. Lose 1 Sanity.',NULL,NULL);
INSERT INTO south_church_encounters VALUES ('You enter the confessional. "Bless me, Father, for I have sinned." Make a Luck (+0) check and consult the chart below:Successes:0) "Father? Are you there?" You hear a scream in the next compartment! Lose 3 Sanity and move to the street.1) "Father?" There is no answer. Sighing, you leave. Move to the street.2+) "I don''t remember my last confession." Raise your Sanity to its maximum value.','Luck +0',NULL);
INSERT INTO south_church_encounters VALUES ('You interrupt an arguement between Father Michael and a member of the Esoteric Order of Dagon. If you join in on the side of Dagon, gain 2 Clue tokens as you urge the man to talk. If you join in on the side of the Church, Father Michael''s grateful smile restores 2 Sanity.',NULL,'Innsmouth Horror');
INSERT INTO south_church_encounters VALUES ('You join in the morning mass. Spend 1 Clue token to ask for heavenly aid. If you do so, roll a die. On a success, your prayers are answered. Remove 1 doom token from the Ancient One''s doom track.',NULL,NULL);
INSERT INTO south_church_encounters VALUES ('You light a candle in prayers for those souls believed to be lost. You may choose one Ally card that has been returned to the box and reshuffle it back into the Ally deck. If no Ally cards have been returned to the box, gain 1 Sanity instead.',NULL,'The Black Goat of the Woods');
INSERT INTO south_church_encounters VALUES ('You stumble through the doors, desperately seeking peace. But then you realize that the powers you face care nothing for morals, or hope, or humanity. Lose an amount of Sanity equal to the number of gates currently open.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO south_church_encounters VALUES ('You touch the altar and a bright light flashes. Draw a mythos card and go to the gate location shown. Draw four location cards and choose one of them to encounter, discarding the others.',NULL,'Kingsport Horror');
