CREATE TABLE st_marys_hospital_encounters (
    `list_encounter` VARCHAR(350) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(16) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO st_marys_hospital_encounters VALUES ('A medium beckons you into a room full of the bereaved, grieving for the recently deceased. He confides that his power is insufficient to complete his ritual and contact the dead man''s spirit. If you will help him, he can tell you many secrets. You may discard a Spell to take 3 Clue tokens.',NULL,'Kingsport Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('A patient appears to be choking on something. But then, horribly, a swarm of locusts vomits forth from his mouth! If you flee, move to the street. If you stay to try to help him, the locusts burrow into your body. Lose 1 Stamina and 1 Sanity, but you may search the Spell deck for a Plague of Locusts spell and take it.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO st_marys_hospital_encounters VALUES ('A visiting scholar, Dr. Ali Kafour, gives a lecture on the preparatory procedures used to create mummies. If you watch the brain removal demonstration, make a Will (+0) check. For each success you roll, you may gain 1 Clue token; for every clue token you choose to gain, however, you must discard 1 Sanity.','Will +0','Curse of the Dark Pharaoh');
INSERT INTO st_marys_hospital_encounters VALUES ('Although you adhere to the belief that hospital food should be avoided, your body demands sustenance. Gain 1 Stamina and search the Common Item deck for a "Food" card.',NULL,'Kingsport Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('An old man who looks to be near death gestures you toward his bedside. If you approach, he tries to hand you something as his last breath gurgles out. Make a Speed (-1) check. If you pass, you catch the object; draw 1 Exhibit Item. If you fail, the ancient canopic jar shatters on the ground, and you are Cursed!','Speed -1','Curse of the Dark Pharaoh');
INSERT INTO st_marys_hospital_encounters VALUES ('An orderly quickly closes the door to the morgue, but not before you catch a glimpse of what''s inside. Make a Speed (-1) check and gain 1 Clue token per success.','Speed -1','Innsmouth Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('As you walk through the halls of St. Mary''s, a nurse shoves a wheelchair into your legs, forcing you to sit. She wheels you recklessly through the hospital, informing you frequently that you will be "good as new." Then, stopping abruptly, she tips you out of the chair and to the floor, and speeds off. Unbelievably, your Stamina is restored to full.',NULL,'Kingsport Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('By quietly listening to the nurses talk, you are able to learn some useful information. Gain 1 Clue token.',NULL,'Dunwich Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('Dr. Mortimore eyes you with suspicion. "Excuse me, but who are you here to see?" Pass a Will (-1) check to come up with a plausible excuse and remain here. If you fail, the Doctor has security escort you outside. Move to the street.','Will -1','Dunwich Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('Make a Luck (-1) check. If you pass, you realize that Dr. Mortimore is sneaking up behind you with a hypodermic needle filled with a phosphorescent gel. You avoid his experiment and subdue the mad doctor. The city awards you $3 and you gain 2 Sanity in the process. If you fail, lose 2 Sanity, then you are dumped in the street.','Luck -1',NULL);
INSERT INTO st_marys_hospital_encounters VALUES ('Nurse Sharon asks for your help in organizing some records that were accidentally dropped and scattered. Pass a Lore (+0) check to gain 1 Clue token.','Lore +0','The King in Yellow');
INSERT INTO st_marys_hospital_encounters VALUES ('Nurse Sharon offers to bandage up your wounds. Gain 2 Stamina.',NULL,'Dunwich Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('Nurse Sharon slips something into your hand when the doctor isn''t looking. Pass a Sneak (-1) check to keep anyone else from noticing. If you do, you later examine the object and find it to be an old parchment with a spell scratched on it. Draw 1 Spell. If you fail, an orderly takes it away from you and you gain nothing.','Sneak -1',NULL);
INSERT INTO st_marys_hospital_encounters VALUES ('One of the doctors tells you about an experimental treatment that might help you. It''s expensive, however. You may pay $5 to roll a die. On a success, discard one of your Injury cards. On a failure, gain 2 Stamina.',NULL,'Dunwich Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('One of the doctors tells you about an experimental treatment that might help you. It''s expensive, however. You may pay $5 to roll a die. On a success, discard one of your Injury cards. On a failure, gain 2 Stamina.',NULL,'Dunwich Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('One of the staff physicians talks some sense into you. You are disabused of certain crazy but accurate notions. Lose 1 Clue token.',NULL,NULL);
INSERT INTO st_marys_hospital_encounters VALUES ('Someone has left a package unattended in the waiting room. Pass a Luck (-2) check to draw 1 Unique Item before the hospital staff finds it.','Luck -2','The Black Goat of the Woods');
INSERT INTO st_marys_hospital_encounters VALUES ('The ambulance crew is heading home for the night and offers you a lift. Move to any street area or location in Arkham. If you choose to move to a location, immediately have an encounter there.',NULL,'Dunwich Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('The cafeteria food, while tasteless, is quite nutritious. Gain 1 Stamina.',NULL,'The Black Goat of the Woods');
INSERT INTO st_marys_hospital_encounters VALUES ('The corpse you are examining isn''t quite dead yet. It reaches out and grabs you by the throat. Lose 1 Sanity. Then, you must fight the corpse. If you pass a Combat (-1) check, you defeat it and gain 1 Clue token. Otherwise, move to the street.','Combat -1',NULL);
INSERT INTO st_marys_hospital_encounters VALUES ('The Doctor escorts you behind a curtain where the body of some other unfortunate investigator has been laid. The corpse has been torn to shreds. Pass a Will (-1) check or lose 1 Sanity. If you pass, you may also search the body and find a helpful item. Draw 1 Unique Item. If you fail, you run away screaming. Move to the street.','Will -1',NULL);
INSERT INTO st_marys_hospital_encounters VALUES ('The doctors insist on treating you! Ignoring any protests, they anesthetize you and start patching you up. When you come to, you''re physically fine but your thoughts are pretty foggy. Gain 2 Stamina but lose a Clue token if you have any.',NULL,'The Lurker at the Threshold');
INSERT INTO st_marys_hospital_encounters VALUES ('The doctors know that something strange is going on, but don''t have time to talk. If you want to question them, you''ll need to look like you need medical aid. For each point of Stamina you are below you maximum, you may roll 1 die. Gain 1 Clue token for each success.',NULL,'The King in Yellow');
INSERT INTO st_marys_hospital_encounters VALUES ('The hospital has a ward for special cases, but it is off-limits to the public. Make a Sneak (-3) check and gain 1 Clue token for each success you roll.','Sneak -3','The King in Yellow');
INSERT INTO st_marys_hospital_encounters VALUES ('The waiting room is filled with people complaining about a cough they''ve developed from a strange dust in the air. If you interview them, pass a Fight (-1) check to gain 2 Clue tokens. If you fail, you develop the cough yourself and can''t stay in the area without hacking and choking; you are Barred from Uptown.','Fight -1','Curse of the Dark Pharaoh');
INSERT INTO st_marys_hospital_encounters VALUES ('The waiting room is filled with people complaining about a cough they''ve developed from a strange dust in the air. If you interview them, pass a Fight (-1) check to gain 2 Clue tokens. If you fail, you develop the cough yourself. People begin to fear that you are the source of the ailment. Place a Patrol marker on the street area of Uptown.','Fight -1','Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO st_marys_hospital_encounters VALUES ('Tired, you sit down in a waiting room chair and accidentally doze off. When you awaken, you find out that several hours have passed. Stay here next turn.',NULL,'Dunwich Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('When the nurse returns your clothes after a routine exam, something''s not right. Make a Luck (-1) check. If you fail, one of your items has gone missing (your choice). If you pass, gain $2.','Luck -1','Innsmouth Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('You agree to undergo an experimental treatment. Roll a die. On a 1-3, gain that many Stamina. On a 4-6, nothing happens.',NULL,NULL);
INSERT INTO st_marys_hospital_encounters VALUES ('You enter the chapel, unnoticed by a stranger who prays aloud for the health of her husband. Some of her words contain shocking information. Pass a Sneak (-1) check to gain 1 Clue token for each success.','Sneak -1','The Black Goat of the Woods');
INSERT INTO st_marys_hospital_encounters VALUES ('You find a doctor''s bag sitting unattended. Inside, there''s bandages, rubbing alcohol, and medicines. Gain 2 Stamina.',NULL,'The Lurker at the Threshold');
INSERT INTO st_marys_hospital_encounters VALUES ('You find what appears to be the discarded skin of a human being. Lose 1 Sanity, then draw a monster at random from the cup and place it in the outskirts.',NULL,'Innsmouth Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('You notice that a collection of patients in for some sort of skin condition share a loathsome commonality of appearance. Lose 1 Sanity, but gain 1 Clue token.',NULL,'Innsmouth Horror');
INSERT INTO st_marys_hospital_encounters VALUES ('You scrounge up some painkillers. Regain 2 Stamina.',NULL,'The Black Goat of the Woods');
INSERT INTO st_marys_hospital_encounters VALUES ('You sit next to a small boy in the waiting room while his mother is in surgery. He tells you that his mommy protected him from a big monster with scary fangs. You tell him everything will be fine. Gain 1 Clue token and lose 1 Sanity.',NULL,'The Lurker at the Threshold');
INSERT INTO st_marys_hospital_encounters VALUES ('You sneak a peek at the medical records for a recent admission who was involved in a cult ritual. Pass a Lore (+0) check to learn something about the cult''s methods Gain 1 Clue token.','Lore +0',NULL);
INSERT INTO st_marys_hospital_encounters VALUES ('You stumble upon an autopsy room and see something on the table that looks like a man... but with the head of an alligator! Pass a Lore (+1) check to gain 1 Clue token, then pass a Will (-1) check or lose 1 Sanity.','Lore +1
Will -1
','Curse of the Dark Pharaoh');
INSERT INTO st_marys_hospital_encounters VALUES ('You stumble upon an autopsy room. Make a Will (-2) check to stay calm while you investigate. If you pass, gain 2 Clue tokens. If you fail, lose 1 Stamina as you cut yourself on one of the autopsy implements.','Will -2','The King in Yellow');
INSERT INTO st_marys_hospital_encounters VALUES ('You think a man in the waiting room is having a more serious emergency than he realizes. Make a Lore (-2) check to make a correct diagnosis. If you pass, gain 1 Sanity. If you fail, move to the streets as you are curtly asked to leave.','Lore -2','The Lurker at the Threshold');
INSERT INTO st_marys_hospital_encounters VALUES ('You try to rouse a man from a coma brought on by a visit to the Black Cave. Awakening, he begins to ramble. If you are lucky, you will be able to make out some of the words before the nurse comes. Gain a number of Clue tokens equal to your Luck.',NULL,'Kingsport Horror');
