CREATE TABLE the_unnamable_encounters (
    `list_encounter` VARCHAR(423) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(27) CHARACTER SET utf8
);
INSERT INTO the_unnamable_encounters VALUES ('A box full of documents in the closet has grown damp and moldy. Make a Luck (+1) check to see if anything of value has been spared. If you pass, gain 1 Clue token.','Luck +1','The Lurker at the Threshold');
INSERT INTO the_unnamable_encounters VALUES ('A gleam of metal draws your attention to the fireplace, which suddenly ignites! You may attempt a Speed (-3) check to pull an item from the fire before it is destroyed. If you pass, draw 1 Unique Item. If you attempt it and fail, lose 1 Stamina.','Speed -3','The King in Yellow');
INSERT INTO the_unnamable_encounters VALUES ('A group of cultists scampers through the night. If you follow them, make a Sneak (+0) check to watch where they bury their prize. If you pass, you may draw 1 Unique Item or Exhibit Item. If you fail, they turn and smile: a monster surprises you from behind!','Sneak +0','Curse of the Dark Pharaoh');
INSERT INTO the_unnamable_encounters VALUES ('A hideous monster appears!',NULL,'Dunwich Horror');
INSERT INTO the_unnamable_encounters VALUES ('A hideous monster appears!',NULL,'The Black Goat of the Woods');
INSERT INTO the_unnamable_encounters VALUES ('A hideous monster appears!',NULL,'Innsmouth Horror');
INSERT INTO the_unnamable_encounters VALUES ('A monster and a gate appear!',NULL,NULL);
INSERT INTO the_unnamable_encounters VALUES ('A monster and a gate appear!',NULL,'Kingsport Horror');
INSERT INTO the_unnamable_encounters VALUES ('A monster and a gate appear!',NULL,'Innsmouth Horror');
INSERT INTO the_unnamable_encounters VALUES ('A pen and paper rest on a table next to your chair. Picking up the pen, you black out for an uncertain amount of time. When you regain your senses, the paper is covered with strange messages, not written in your handwriting. Make a Lore (-1) check and gain 1 Clue token for each success. Then, whether you pass or not, lose 1 Sanity.','Lore -1','The Lurker at the Threshold');
INSERT INTO the_unnamable_encounters VALUES ('A repellent, tar-like appendage is dragging an item of interest quickly through the halls. Make a Speed (-2) check. If you pass, draw 2 Unique Items and keep 1. If you fail, lose 2 Stamina as you are dragged across the floor.','Speed -2','The Lurker at the Threshold');
INSERT INTO the_unnamable_encounters VALUES ('A stranger approaches and struggles to explain the nature of the creature inside the house. Pass a Lore (+0) check to understand his words and gain 1 Clue token.','Lore +0','The Black Goat of the Woods');
INSERT INTO the_unnamable_encounters VALUES ('A tapestry in the corridor catches your eye as the patterns in its weave appear to shift; you think it may be possible to reach into the hanging. If you choose to try, roll four dice. If you roll any failures, you are devoured as the patterns come alive. If you roll four successes, take a Doom token from the Doom track and place it on an unstable location of your choice as an Elder Sign token.',NULL,'Kingsport Horror');
INSERT INTO the_unnamable_encounters VALUES ('A useful weapon sits here in the center of a pentagram. Search the Unique Item deck and look at the first Weapon you find. You may either keep it and be Cursed or discard it and gain 1 Clue token.',NULL,'The King in Yellow');
INSERT INTO the_unnamable_encounters VALUES ('A voice - perhaps the house itself - begins whispering to you. Make a Will (-2) check. Gain 1 Clue token for each success, but lose either 1 Stamina or 1 Sanity if you fail.','Will -2','The King in Yellow');
INSERT INTO the_unnamable_encounters VALUES ('As you look out of an upstairs window, you see an unfamiliar cityscape with twin suns setting over strange towers. Gain 1 Clue token, but you must pass a Will (-2) check or lose 1 Sanity.','Will -2','The King in Yellow');
INSERT INTO the_unnamable_encounters VALUES ('Entering one of the rooms, you see a chess set on a table. In growing horror, you watch as the pieces begin moving by themselves and shattering into splinters as they are captured. Fleeing the house, you move to the street.',NULL,'Dunwich Horror');
INSERT INTO the_unnamable_encounters VALUES ('In a dusty and decaying roll-top desk, you find a mysterious manuscript. If you read it, make a Lore (-1) check. If you pass, draw 1 Spell. If you fail, the manuscript is nothing but the insane babbling of a previous renter. Stay here next turn reading it, but gain 2 Clue tokens.','Lore -1',NULL);
INSERT INTO the_unnamable_encounters VALUES ('Looking through the drawers in one of the rooms, you come across a stunningly beautiful crystal. As you pick it up, it shimmers for a moment, then sinks into your hand. You convulse for a moment as new knowledge rushes through your mind, but no harm seems to have been done. Draw 1 Skill.',NULL,'Dunwich Horror');
INSERT INTO the_unnamable_encounters VALUES ('Luck finds those who need it. If you Luck is 1 or lower, you find a luck penny between the floorboards. You may search the Skill deck and take the Luck card.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO the_unnamable_encounters VALUES ('Pass a Luck (-1) check to find a hidden cache concealed in the wall of an upstairs bedroom. Draw 1 Unique Item.','Luck -1',NULL);
INSERT INTO the_unnamable_encounters VALUES ('Pausing to wipe your brow, you make your way to the bathroom. Happily, the water still works, so you wash your face. However, after a moment, the cool water turns hot and sticky. Opening your eyes, you find that you are washing your face in blood pouring from the faucet and let out a shriek of terror. Pass a Will (-2) check or draw 1 Madness.','Will -2','Dunwich Horror');
INSERT INTO the_unnamable_encounters VALUES ('The ceiling beam suddenly buckles. Make a Speed (-1) check. If you pass, move to the street. If you fail, lose 2 Stamina.','Speed -1',NULL);
INSERT INTO the_unnamable_encounters VALUES ('The door slams shut behind you! Spend a turn delayed as you search for another way out.',NULL,'The Black Goat of the Woods');
INSERT INTO the_unnamable_encounters VALUES ('The house calls to you. If you follow its voice, it tells you which floorboards to pry up. You may draw 1 Unique item or Exhibit Item, but must also take the Tainted card.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO the_unnamable_encounters VALUES ('The house suddenly fills with terrible wails and screams. Lose 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO the_unnamable_encounters VALUES ('The roof caves in, but instead of a ceiling above, a swirling pool of shadow hurtles down towards you. Make a Speed (-1) check or become lost in time and space.','Speed -1','Kingsport Horror');
INSERT INTO the_unnamable_encounters VALUES ('Things seem to just disappear here. Choose 1 Common Item and discard it. If you do not have a Common Item, lose 1 Sanity.',NULL,'The Lurker at the Threshold');
INSERT INTO the_unnamable_encounters VALUES ('Walking down into the basement, you are startled when the light turns itself off just as you start to place your foot on the next step. Pass a Speed (-2) check or you fall down the stairs, badly injuring yourself. Draw 1 Injury.','Speed -2','Dunwich Horror');
INSERT INTO the_unnamable_encounters VALUES ('You are attacked by some unseen force. Lose 2 Stamina.',NULL,'The Black Goat of the Woods');
INSERT INTO the_unnamable_encounters VALUES ('You bump into Eric Colt. He tells you a horrible tale of the Mythos to test your nerve. If you listen, lose 2 Sanity. If this doesn''t drive you insane, take his Ally card if it is available. If it is not available, you may pump him for information instead. Gain 3 Clue tokens.',NULL,NULL);
INSERT INTO the_unnamable_encounters VALUES ('You bump into Eric Colt. He tells you a horrible tale of the Mythos to test your nerve. If you listen, lose 2 Sanity. If this doesn''t drive you insane, take his Ally card if it is available. If it is not available, you may pump him for information instead. Gain 3 Clue tokens.',NULL,'Dunwich Horror');
INSERT INTO the_unnamable_encounters VALUES ('You bump into Eric Colt. He tells you a horrible tale of the Mythos to test your nerve. If you listen, lose 2 Sanity. If this doesn''t drive you insane, take his Ally card if it is available. If it is not available, you may pump him for information instead. Gain 3 Clue tokens.',NULL,'Innsmouth Horror');
INSERT INTO the_unnamable_encounters VALUES ('You hear scurrying and squeaking of a horde of rats from inside the walls. Abruptly, you realize that they are moving to surround you. Pass a Speed (-1) check to make it to the front door first. If you fail, you are lost in time and space.','Speed -1',NULL);
INSERT INTO the_unnamable_encounters VALUES ('You hear the voice of Eric Colt from the next room. Drawing nearer, you see his back to you, as he listens to a haunting tune from a radio whose cord has been cut. If you wish to rescue him from the music''s grasp, lose 2 Sanity. If this does not drive you insane, take Eric Colt''s Ally card or, if it''s not available, take 3 Clue tokens.',NULL,'Kingsport Horror');
INSERT INTO the_unnamable_encounters VALUES ('You notice a glint of light in a crevice. If you reach in, make a Luck (-1) check. If you pass, draw 1 Unique Item. If you fail, you feel a sharp pain as teeth clamp down on your hand. You manage to pull free, but you lose 2 Stamina and 1 Sanity.','Luck -1',NULL);
INSERT INTO the_unnamable_encounters VALUES ('You pass the strange house and find yourself face to face with a foreign man with a penetrating gaze. If you have any Exhibit Items or your Will is 2 or lower, he seems to approve of your simpering manner, and he introduces himself as Dr. Ali Kafour. Take his Ally card or, if it is not available, listen to him expound upon the ancient Egyptian pantheon as it compares to that of Native American myths: Gain 2 Clue tokens.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO the_unnamable_encounters VALUES ('You see a warped mirror. If you look into it, you see yourself in another time and place, holding an ankh in one hand and a sacrificial blade in the other. Your number of Clue tokens doubles, but if you gain more than 3 Clue tokens in this manner, you are Cursed.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO the_unnamable_encounters VALUES ('You turn to flee from the monster, but as it pursues you  the crumbling house gives way beneath it! Pass a Luck (-2) check to either gain 2 Clue tokens or claim 1 monster trophy at random from the cup, ignoring the Endless ability. If you fail, move to the street.','Luck -2','Innsmouth Horror');
