CREATE TABLE the_witch_house_encounters (
    `list_encounter` VARCHAR(468) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(9) CHARACTER SET utf8,
    `list_expansion` VARCHAR(27) CHARACTER SET utf8
);
INSERT INTO the_witch_house_encounters VALUES ('"Excuse me, stranger, but have you ever seen this symbol before?" A man standing near the house holds up an occult symbol. Make a Lore (-1) check. If you pass, the man introduces himself as Thomas F. Malone, a police detective visiting Arkham on a case. He''s impressed with you and offers to join you. Take his Ally card. If it''s not available, he tells you some valuable information instead. Gain 2 Clue tokens. If you fail, nothing happens.','Lore -1',NULL);
INSERT INTO the_witch_house_encounters VALUES ('"Excuse me, stranger, but have you ever seen this symbol before?" A man standing near the house holds up an occult symbol. Make a Lore (-1) check. If you pass, the man introduces himself as Thomas F. Malone, a police detective visiting Arkham on a case. He''s impressed with you and offers to join you. Take his Ally card. If it''s not available, he tells you some valuable information instead. Gain 2 Clue tokens. If you fail, nothing happens.','Lore -1','Dunwich Horror');
INSERT INTO the_witch_house_encounters VALUES ('"Excuse me, stranger, but have you ever seen this symbol before?" A man standing near the house holds up an occult symbol. Make a Lore (-1) check. If you pass, the man introduces himself as Thomas F. Malone, a police detective visiting Arkham on a case. He''s impressed with you and offers to join you. Take his Ally card. If it''s not available, he tells you some valuable information instead. Gain 2 Clue tokens. If you fail, nothing happens.','Lore -1','The Black Goat of the Woods');
INSERT INTO the_witch_house_encounters VALUES ('"What a shame," a voice whispers, "such unused potential." Search the Unique Item deck and take the first Tome you find. If it requires a skill check to read, then you may immediately make a check to read it, without spending any movement points to do so.',NULL,'The King in Yellow');
INSERT INTO the_witch_house_encounters VALUES ('"You will be rewarded according to what you have learned," whispers the voice of a long-dead warlock. Lose 1 Stamina but take a Clue token for each Spell you possess.',NULL,'Kingsport Horror');
INSERT INTO the_witch_house_encounters VALUES ('A force from within the house threatens to take over your mind. Pass a Will (-1) check to avoid moving to the nearest monster''s location and the encountering it. If there are no monsters in any street area or location, a monster appears!','Will -1','Kingsport Horror');
INSERT INTO the_witch_house_encounters VALUES ('A gate and a monster appear!',NULL,NULL);
INSERT INTO the_witch_house_encounters VALUES ('A gate and a monster appear!',NULL,'Dunwich Horror');
INSERT INTO the_witch_house_encounters VALUES ('A gate and a monster appear!',NULL,'Kingsport Horror');
INSERT INTO the_witch_house_encounters VALUES ('A gate and a monster appear!',NULL,'Innsmouth Horror');
INSERT INTO the_witch_house_encounters VALUES ('A man motions you over and points to a chalk outline in the atrium of the old house. He directs your attention to a trail of what seems to be green blood. Pass a Lore (-1) check to offer useful assistance; if you do, take Thomas F. Malone''s Ally card, or, if it is not available, take 2 Clue tokens.','Lore -1','Kingsport Horror');
INSERT INTO the_witch_house_encounters VALUES ('A muffled cry and some thumping comes from a nearby closet. Pass a Fight (-2) check to open it and rescue whoever is inside, drawing a random Ally. If you fail, whatever trapped him attacks you too: A monster appears.','Fight -2','The King in Yellow');
INSERT INTO the_witch_house_encounters VALUES ('A woman poses by a window; the dim light revealing the outline of her beautiful figure, but hiding her face. "Will you paint me?" she asks. Make a Luck (-2) check. If you pass, you find a painting of the woman where she was standing. It has a Spell scribed on the back. Draw one Spell. If you fail, a monster appears!','Luck -2','The King in Yellow');
INSERT INTO the_witch_house_encounters VALUES ('An artist''s address book lies on a table with a list of names: Lizzie Burke, Pinkie McCormick, Tessie. You feel like you know them all, or knew them, and feel a stab of sadness. Gain 1 Clue token, but pass a Will (+0) check or lose 1 Sanity.','Will +0','The King in Yellow');
INSERT INTO the_witch_house_encounters VALUES ('Ever since you visited the witch house, you keep seeing a strange, rat-like creature out of the corner of you eye...and sometimes it looks like its face is almost human! Gain 1 Clue token, but take the Harried card.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO the_witch_house_encounters VALUES ('In an old journal you learn some horrible eldritch secrets. Roll a die. Lose that much Sanity and gain that many Clue tokens.',NULL,NULL);
INSERT INTO the_witch_house_encounters VALUES ('In the attic, you feel a force in your mind, trying to replace your thoughts with those of another. Make a Speed (-1) check to escape. If you pass, move to the streets. If you fail, lose 1 Spell, or if you have no Spells, lose 2 Sanity.','Speed -1','The Lurker at the Threshold');
INSERT INTO the_witch_house_encounters VALUES ('In the middle of the night, something in the dark is clutching at your chest! Make a Fight (+0) check and lose 2 Stamina if you fail.','Fight +0','The Lurker at the Threshold');
INSERT INTO the_witch_house_encounters VALUES ('Make a Luck (-1) check. If you pass, you find a dusty chest in an old closet. Draw 1 Common Item. If you fail, scratchy voices from the past claw at your mind. Lose 1 Sanity.','Luck -1','Dunwich Horror');
INSERT INTO the_witch_house_encounters VALUES ('On the front lawn a group of children hold hands and circle around a dead bird, chanting words you don''t recognize. Make a Lore (-2) check. If you pass draw 1 Spell.','Lore -2','The Black Goat of the Woods');
INSERT INTO the_witch_house_encounters VALUES ('One of the steps leading upstairs has rotted through. Pass a Speed (-1) check or lose 1 Stamina.','Speed -1','Innsmouth Horror');
INSERT INTO the_witch_house_encounters VALUES ('Pass a Luck (-1) check to find an odd-looking item in an old dusty display case. Draw 1 Unique Item.','Luck -1',NULL);
INSERT INTO the_witch_house_encounters VALUES ('Someone has left their mathematics homework lying on the dining room table. Pass a Lore (-1) check to see the deeper meanings. Gain 1 Clue token for each success.','Lore -1','The Black Goat of the Woods');
INSERT INTO the_witch_house_encounters VALUES ('Something about the angles in the attic room opens your mind to the myriad possibilities of other, nearly identical universes. Search the Spell deck for a Spell you already have, and take another copy of it. Then, as you continue to stare into the impossible angle, a Hound of Tindalos appears!',NULL,'Curse of the Dark Pharaoh');
INSERT INTO the_witch_house_encounters VALUES ('Stepping into one of the disused upstairs rooms, you suddenly find yourself elsewhere. Enter Another Time and have an encounter there, then immediately return here.',NULL,'Dunwich Horror');
INSERT INTO the_witch_house_encounters VALUES ('The ancient witch Keziah Mason appears before you. Make a Will (-2) check. If you pass, she teaches you something of value. Draw 1 Spell. If you fail, she casts a terrible spell upon you: You are Cursed.','Will -2','Dunwich Horror');
INSERT INTO the_witch_house_encounters VALUES ('The graffiti on the walls is actually Egyptian hieroglyphics. Make a Lore (+0) check. You may draw cards from the Spell deck equal to the number of successes, and keep one of them.','Lore +0','Curse of the Dark Pharaoh');
INSERT INTO the_witch_house_encounters VALUES ('The room is filled with glowing bubbles! You are having a hard time gaining your bearings and finding the door. Lose 1 Sanity and you are delayed, but then gain 3 Clue tokens.',NULL,'The Lurker at the Threshold');
INSERT INTO the_witch_house_encounters VALUES ('The strange, rat-like creature known as Brown Jenkin leaps out of the darkness at you! Search the monster cup for a Rat-thing. If you find one, battle it with a -1 penalty to your Combat checks. If you don''t, Brown Jenkin grabs one of your items and runs. Lose 1 Item of your choice.','Combat -1','Dunwich Horror');
INSERT INTO the_witch_house_encounters VALUES ('You are overcome by the echoing chants of the long-gone witches who have lived and died here - you pass out. Make a Will (-2) check. If you pass, you learn an ancient spell in your dreams. Draw 1 Spell. If you fail, you are missing half your items when you wake up. Discard half of your items (your choice, round down).','Will -2',NULL);
INSERT INTO the_witch_house_encounters VALUES ('You discover an incredibly vital piece of information in one of the dusty old books in the library. Gain 1 Clue token for every open gate on the board.',NULL,'Dunwich Horror');
INSERT INTO the_witch_house_encounters VALUES ('You feel the house actually breathe and speak your name. Lose 1 Sanity.',NULL,NULL);
INSERT INTO the_witch_house_encounters VALUES ('You find a banquet laid out in the dining room and feel compelled to sit down and eat. Make a Luck (+0) check and consult the following chart:Successes:0) You suddenly realize what you''ve been eating. Lose 3 Sanity.1) You gorge yourself, unable to stop eating. Stay here next turn.2) The food makes you feel sick. Lose 1 Stamina.3+) The meal refreshes you. Gain 3 Stamina.','Luck +0',NULL);
INSERT INTO the_witch_house_encounters VALUES ('You find a terrible collection of human remains with the walls. Pass a Will (-1) check or lose 2 Sanity.','Will -1','The Black Goat of the Woods');
INSERT INTO the_witch_house_encounters VALUES ('You find an old journal, largely devoured by vermin. Make a Luck (-3) check to see if certain vital pages remain intact. If you pass, draw 2 Spells and keep 1.','Luck -3','The Lurker at the Threshold');
INSERT INTO the_witch_house_encounters VALUES ('You see a prim and proper girl in puritanical attire, but there is something hungry in her eyes. "Would you like to see?" she asks, demurely. If you agree, she reaches forward to touch you. You feel a terrible cold, then the burning heat of the pyre! You realize  that she is the ghost of Keziah Mason, who was burned at the stake for witchcraft over a century ago! Make a Will (-1) check. You may gain 1 Clue token for each success or 1 Spell for every two successes.','Will -1','Curse of the Dark Pharaoh');
INSERT INTO the_witch_house_encounters VALUES ('You take a renowned visiting escape artist on a tour of the witch house. If you give him 2 of your Spells (discarding them), he introduces himself as Erich Weiss; take his Ally card if it''s available. If it''s not available, he shows you a trick instead, and you gain 2 Clue tokens.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO the_witch_house_encounters VALUES ('You turn to see a small furry form dart quickly out of the room, making off with one of your possessions. Discard 1 item of your choice. If you have no items, then nothing happens.',NULL,'Innsmouth Horror');
INSERT INTO the_witch_house_encounters VALUES ('You wake up suddenly after terrible dreams, unsure of how long you have been here. Lose 1 Sanity, and you are delayed.',NULL,'Innsmouth Horror');
