CREATE TABLE unvisited_isle_encounters (
    `list_encounter` VARCHAR(401) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO unvisited_isle_encounters VALUES ('A group of hooded cultists are having a meeting among the standing stones on the island. Pass a Sneak (-1) check to overhear some of what they have to say. Gain 2 Clue tokens.','Sneak -1',NULL);
INSERT INTO unvisited_isle_encounters VALUES ('A man wearing exotic robes and a strange hat sits in a shaded clearing, seemingly in a trance. As you approach, he says, "Come sit with me," without looking at you. If you are Cursed or have any Mask items, he tells you that he is called The Messenger and is meant to aid you. Take his Ally card or, if it is not available, gain 2 Clue Tokens.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO unvisited_isle_encounters VALUES ('A monster appears! If you do not defeat it you are Cursed.',NULL,'Innsmouth Horror');
INSERT INTO unvisited_isle_encounters VALUES ('A monster appears! If you pass a Combat check against it, you find its skin is covered with the scrawl of archaic runes, and may draw 1 Spell.',NULL,'The King in Yellow');
INSERT INTO unvisited_isle_encounters VALUES ('A monster is attacking a huddled figure in the shadows. If you pass the first Combat check you make against the monster, you may draw a random Ally or Spell.',NULL,'The King in Yellow');
INSERT INTO unvisited_isle_encounters VALUES ('A piece of driftwood conceals a book washed onto the beach by the tide. Oddly enough, the book does not seem to be wet. As you flip through the pages, the words burn themselves into your mind. Draw a Spell and immediately lose Sanity equal to its Sanity cost. If you are not drive insane, keep the Spell.',NULL,'Kingsport Horror');
INSERT INTO unvisited_isle_encounters VALUES ('A silent man brushes past you on the trail. Your arm goes numb with cold from the brief contact, and you whirl around to look at him, but he has disappeared. Lose 1 Stamina and pass a Will (-1) check or lose 1 Sanity as well.','Will -1',NULL);
INSERT INTO unvisited_isle_encounters VALUES ('As you row along the island''s shore, a tree branch cracks and falls toward you. Make a Speed (+0) check. If you fail, you are knocked out and wake up far downstream; move to the Graveyard and you turn ends.','Speed +0','Curse of the Dark Pharaoh');
INSERT INTO unvisited_isle_encounters VALUES ('As you start to climb back into your canoe and row to shore, you see a huge, shadowy shape disturb the water near the island. Waves of intense dread grip you, and you must pass a Will (-1) check or be Cursed.','Will -1',NULL);
INSERT INTO unvisited_isle_encounters VALUES ('Falling asleep beneath one of the ancient willows on the island, you dream of another life, one in which you called down strange entities and sacrificed in their name. When you awaken, you have retained some of the memories from that other life. Gain 1 Clue Token and 1 Spell.',NULL,'Dunwich Horror');
INSERT INTO unvisited_isle_encounters VALUES ('In the center of the island, you come across an ancient stone well with bones littering the ground around it. Staring into its black depths, a feeling of such dread overwhelms you that you immediately flee the area. Lose 1 Sanity and move to the street.',NULL,'Dunwich Horror');
INSERT INTO unvisited_isle_encounters VALUES ('Looking across the clearing, you spy another shadowy figure watching the same malefactors you have your eye on. Although your surveillance proves fruitless, you later meet your counterpart on the beach. Pass a Sneak (-1) check to take John Legrasse''s Ally card, or, if it''s not available, to increase your Sanity and Stamina to their maximum values.','Sneak -1','Kingsport Horror');
INSERT INTO unvisited_isle_encounters VALUES ('Looking up at the night sky from the island, you see constellations that you''ve never seen before. The entire sky is different here! Lose 1 Sanity and gain 1 Clue token.',NULL,NULL);
INSERT INTO unvisited_isle_encounters VALUES ('Pass a Luck (-1) check to notice an unusual shape in the reeds. Gain 1 Common Item.','Luck -1','The Black Goat of the Woods');
INSERT INTO unvisited_isle_encounters VALUES ('Something calls to you from the island''s heart... if only you could find it! Make a Luck (-2) check or exhaust the Find Gate spell, Dynamite item, or Gate Box item to automatically pass. If you pass, you manage to create a tunnel down into the earth. Gain 1d6 Clue tokens. If you exhausted an item or spell to pass the check and gained more that 3 Clue tokens, you must discard the item or spell used.','Luck -2','Curse of the Dark Pharaoh');
INSERT INTO unvisited_isle_encounters VALUES ('The clouds overhead begin to spiral. Pass a Lore (-1) check to make out the symbol of the Yellow Sign and gain 1 Clue token.','Lore -1','The King in Yellow');
INSERT INTO unvisited_isle_encounters VALUES ('The fog fills your lungs, trying to change you. Pass a Will (-1) check to resist or gain one Corruption card.','Will -1','The Black Goat of the Woods');
INSERT INTO unvisited_isle_encounters VALUES ('The ground is covered with a strange luminescent substance. Make a Lore (+0) check to keep yourself safe from its damaging effects. If you fail, you are Cursed.','Lore +0','The Lurker at the Threshold');
INSERT INTO unvisited_isle_encounters VALUES ('The seclusion on the island is making you more withdrawn and paranoid. Make a Will (+0) check to keep your wits. If you fail, lose 2 Sanity.','Will +0','The Lurker at the Threshold');
INSERT INTO unvisited_isle_encounters VALUES ('The willows seem to grow closer and more malevolent the longer you linger. Make a Speed (-1) check to make it back to your boat in time. If you  fail, you trip over a protruding root and are tangled in grasping boughs. You are delayed.','Speed -1','Innsmouth Horror');
INSERT INTO unvisited_isle_encounters VALUES ('The willows sway in a wind that you cannot hear or feel, and for a moment, the hatred of these ancient trees for the invader who has come to their island drives you to your knees. Pass a Will (-2) check or lose 3 Sanity.','Will -2',NULL);
INSERT INTO unvisited_isle_encounters VALUES ('Time and space distort around you. A gate and a monster appear!',NULL,'Dunwich Horror');
INSERT INTO unvisited_isle_encounters VALUES ('Time and space distort around you. A gate and a monster appear!',NULL,'Dunwich Horror');
INSERT INTO unvisited_isle_encounters VALUES ('Two monsters surface from the island''s dark waters. If you kill both them, you are Blessed.',NULL,'Kingsport Horror');
INSERT INTO unvisited_isle_encounters VALUES ('Walking along the beach, you spy a hermit crab with a strange design on its shell. Looking more closely, you realize that the weird mottling spells out secrets. Make a Will (-1) check and take 1 Clue token per success.','Will -1','Kingsport Horror');
INSERT INTO unvisited_isle_encounters VALUES ('Walking into a clearing, you feel that you are at the center of a web of enormous magical energy. You may return one gate token in play to the bottom of the gate token pile, replacing it with a new gate token from the top of the pile. Monsters are returned to the cup as though you had closed the gate you returned to the pile.',NULL,'Innsmouth Horror');
INSERT INTO unvisited_isle_encounters VALUES ('Walking into a clearing, you feel that you are at the center of a web of enormous magical energy. You may return one gate token in play to the gate token pile, replacing it with a new gate token from the top of the pile. Monsters are returned to the cup as though you had closed the gate.',NULL,'Dunwich Horror');
INSERT INTO unvisited_isle_encounters VALUES ('Walking into a clearing, you feel that you are at the center of a web of enormous magical energy. You may return one gate token in play to the gate token pile, replacing it with a new gate token from the top of the pile. Monsters are returned to the cup as though you had closed the gate.',NULL,'Dunwich Horror');
INSERT INTO unvisited_isle_encounters VALUES ('You come across a large pile of human bones under the boughs of one of the willows on the isle. Lose 1 Sanity, but find a scroll among the bones. Draw 1 Spell.',NULL,NULL);
INSERT INTO unvisited_isle_encounters VALUES ('You come across a man examining some old bones. Pass a Sneak (-1) check to get close enough to see what he''s doing. He finally notices you and is impressed with your skills, introducing himself as John Legrasse. Take his Ally card if it''s available, otherwise he shares a meal with you. Restore your Sanity and Stamina to their maximum value.','Sneak -1',NULL);
INSERT INTO unvisited_isle_encounters VALUES ('You come across a man examining some old bones. Pass a Sneak (-1) check to get close enough to see what he''s doing. He finally notices you and is impressed with your skills, introducing himself as John Legrasse. Take his Ally card if it''s available, otherwise he shares a meal with you. Restore your Sanity and Stamina to their maximum value.','Sneak -1','Dunwich Horror');
INSERT INTO unvisited_isle_encounters VALUES ('You come across a man examining some old bones. Pass a Sneak (-1) check to get close enough to see what he''s doing. He finally notices you and is impressed with your skills, introducing himself as John Legrasse. Take his Ally card if it''s available, otherwise he shares a meal with you. Restore your Sanity and Stamina to their maximum value.','Sneak -1','The Black Goat of the Woods');
INSERT INTO unvisited_isle_encounters VALUES ('You come upon a tree that has grown, cancer-like, around an ancient prayer plaque. Make a Fight (-2) check or exhaust the Wither spell, Shrivelling spell, or the Axe item to automatically pass. If you pass, draw Spells equal to your focus.','Fight -2','Curse of the Dark Pharaoh');
INSERT INTO unvisited_isle_encounters VALUES ('You find carvings on a standing stone etched in an ancient tongue but by a modern hand. Make a Lore (-1) check and gain 1 Clue token per success.','Lore -1','Innsmouth Horror');
INSERT INTO unvisited_isle_encounters VALUES ('You must have fallen into the water. A passerby managed to pull you out and resusitate you. He claims you were dead for a brief time. Perhaps you did go to the other side and returned with new knowledge. Make a Will (-2) check to recollect your experience. If you pass, gain 2 Spells. If you fail, lose 2 Sanity.','Will -2','The Lurker at the Threshold');
INSERT INTO unvisited_isle_encounters VALUES ('You see a group of masked Egyptian cultists performing a hideous ritual in a clearing. If you wish to get closer and listen, make a Sneak (+0) check. If you pass, draw 1 Spell. If you fail, the look up as one and point at you, and you know that you are marked. Place a Patrol marker on the street area of the Merchant District, as an aura of unnaturalness surrounds you.','Sneak +0','Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO unvisited_isle_encounters VALUES ('You see a group of masked Egyptian cultists performing a hideous ritual in a clearing. If you wish to get closer and listen, make a Sneak (+0) check. If you pass, draw 1 Spell. If you fail, the look up as one and point at you, and you know that you are marked. You are Barred from the Merchant District.','Sneak +0','Curse of the Dark Pharaoh');
INSERT INTO unvisited_isle_encounters VALUES ('You see Carl Sanford covertly trying to find a place on the island to recite a ritual. Make a Sneak (-2) check. If you pass, you get close enough to hear what he is saying and gain 3 Clue tokens.','Sneak -2','The Lurker at the Threshold');
INSERT INTO unvisited_isle_encounters VALUES ('You watch two women walk the island while they speak of the Hyades, Hali, and Lost Carcosa. Gain 1 Clue token, then make a Sneak (-2) check. If you pass, you hear further details, gaining 1 more Clue token. If you fail, they see you and call upon protection. A monster appears!','Sneak -2','The King in Yellow');
INSERT INTO unvisited_isle_encounters VALUES ('You''ve stumbled upon the Cult of the Black Goat! You may join them if you wish. To do so, you must discard at least 2 toughness worth of monster trophies, lose 3 Stamina, or an Ally. Take a "One of the Thousand" Cult Membership card. If you cannot or choose not to join, you must pass a Speed (-2) check or lose 2 Stamina.','Speed -2','The Black Goat of the Woods');
