CREATE TABLE ye_olde_magick_shoppe_encounters (
    `list_encounter` VARCHAR(377) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(18) CHARACTER SET utf8,
    `list_expansion` VARCHAR(43) CHARACTER SET utf8
);
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('"Ah, there you are. That item you ordered has come in." Oddly enough, you ordered no such item. If you wish, you may make a Will (-2) check to impersonate the rightful owner. If you pass, you may draw 1 Unique Item. If you fail, you are arrested.','Will -2','The King in Yellow');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('A famous occultist is in town giving a lecture. As part of his demonstration he offers to place you in a trance. If you agree, make a Will (-2) check. Gain 1 Clue token for each success. if you fail the check, lose 1 Sanity as you are assailed by traumatic visions from your subconscious.','Will -2','The Black Goat of the Woods');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('A group of concerned citizens have come to harangue the proprietor and customers of the Magic Shoppe. You can calm them down with a Will (-2) check. If you succeed, empty the Outskirts returning all monsters in it to the cup. If you fail, the terror level is increased by 1.','Will -2','Innsmouth Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('A smiling man greets you warmly. "It''s nice to see you again!" You believe he has you mistaken for someone else, but he responds, "Nonsense! I''ve been meaning to return this to you." He hands you a package and leaves. Gain 1 Common Item.',NULL,'The Black Goat of the Woods');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('A strange man roams the aisles looking desperately for something, muttering to himself. Make a Speed (-1) check, or he catches you watching him and attacks! Pass a Fight (+0) check to fend him off, or lose 1 Stamina.','Speed -1
Fight +0
','Curse of the Dark Pharaoh');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('As you begin to delve into the rare manuscripts, the proprietor of the shop coughs loudly and holds out his hand. You may pay $5 to search the Spell deck for a Spell.',NULL,'Kingsport Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('As you enter the Magick Shoppe, Miriam Beecher doesn''t even look up. "Sorry, we''re closed right now. I''m performing a cleansing of the store. You''ll have to leave." Move to the street.',NULL,'Dunwich Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('As you wait in line to buy something, a swindler with scars on his face and a strange accent gives you a wink, then steps in front of you and begins to distract the shopkeeper. If you leave without paying, draw 1 Exhibit Item or Unique Item, but you are Cursed.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Behind a bookshelf, you hear a woman whisper, "I have killed him I loved; the world''s athirst, now let it drink." When you look down that aisle, there''s no one there, but there is an item resting on the floor. Draw 1 Unique Item. You may purchase it for half list price (round up).',NULL,'The King in Yellow');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Customers in the store are gossiping about a recent strange occurrence, and who or what may have caused it. Turn the top card of a location of your choice faceup. The next investigator to have an encounter at that location draws that card.',NULL,'Kingsport Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Looking closely at a mummified head in the shop, you are horrified to find it looking back at you! Lose 1 Sanity.',NULL,NULL);
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Looking into a glass ball, you receive a vision of things to come. Turn the top card of one location deck of your choice face up. The next investigator to have an encounter at that location draws that encounter card.',NULL,NULL);
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher claims to have a healing salve in stock and offers to sell you some. You may spend $3 to recover up to 2 Stamina.',NULL,'The Black Goat of the Woods');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher eyes you carefully. "Hmm, if we''re going to survive, I''d better teach you this." Draw 2 Spells, keeping 1 and discarding the other.',NULL,'The King in Yellow');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher looks deep into your heart. "Prove to me your courage and I''ll do what I can to aid you." For every monster trophy you have, gain 1 Stamina or 1 Sanity.',NULL,'Dunwich Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher looks up as you enter the shop. "It''s about time you arrived. I have a job for you to do." Take the first Mission from the Unique Item deck.',NULL,'Dunwich Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher offers to cast a particularly potent and dangerous spell for you...for a price. If you are willing, spend $5 then draw a monster at random from the monster cup. If it has a moon dimensional symbol, discard it and draw again. Otherwise, return that monster and all monsters that share its dimensional symbol to the cup.',NULL,'Innsmouth Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher offers to cleanse your aura and restore your mental well-being, for a price. If you discard 1 Unique Item and pay $3, you are Blessed.',NULL,'The Lurker at the Threshold');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher offers to teach you the spell you need. You may pay $5 to search the Spell deck and take any one card you want. If you turn down her offer, nothing happens.',NULL,'Dunwich Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher offers to teach you the spell you need. You may pay $5 to search the Spell deck and take any one card you want. If you turn down her offer, nothing happens.',NULL,'Dunwich Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher offers to teach you the spell you need. You may pay $5 to search the Spell deck and take any one Spell you want. If you turn down her offer, nothing happens.',NULL,'The Black Goat of the Woods');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher offers to trade spells with you. You may discard 1 Spell to draw a new one from the Spell deck.',NULL,'Dunwich Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher talks to you for awhile, explaining some very interesting theories she has concerning the Mythos. Gain 1 Clue token.',NULL,NULL);
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher, the shopkeeper, peers closely at your face, then screams, "They''ve marked you! Get out! Get out!" and throws you out. Move to the street and lose 1 Sanity from this unsettling incident.',NULL,NULL);
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam Beecher thrusts a book into your hands. Taking a cursory glance through it, you notice that several pages are blank. She explains that a dark presence is erasing the knowledge it contains. Take a number of Clue tokens equal to six minus the number of elder sign tokens on the board.',NULL,'Kingsport Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Miriam looks into your face, and you feel as though you''re being judged. "I see. Your heart is in the right place. Tell me of your travels, and perhaps I can help you in return." Gain 1 Clue token for every gate trophy you have.',NULL,'Dunwich Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('No one is manning the shop, but an intriguing item is sitting on the counter. Draw 1 Unique Item. You may either discard it, keep it and pay its list price, or keep it without paying for it and be Cursed.',NULL,'The King in Yellow');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Pass a Lore (-1) check to recognize an item that Miriam Beecher has underpriced. If you do so, draw 1 Unique Item. You may purchase it for half its list price (rounded up).','Lore -1',NULL);
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Speaking with Miriam Beecher, she tells you she would be willing to trade for items, if you have anything of interest. Look at the top card of the Unique Item deck. If you want to keep it, discard one of your Unique Items or Spells.',NULL,'The Lurker at the Threshold');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('The item you have been hoping to purchase has already been sold. Make a Sneak (-1) check to sneak a peek at the ledger to see who purchased it. If you pass, gain 2 Clue tokens.','Sneak -1','The Lurker at the Threshold');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('There is an old, locked trunk for sale for $5. If you buy it, make a Luck (+0) check and consult the chart below:Successes:0) Empty!1) Gold coins! Roll 2 dice, add them together, and gain that much money.2+) Jackpot! Draw 2 Unique Items!','Luck +0',NULL);
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Upon discovering a severed - but twitching - hand, you find yourself trapped in an interminable time loop. You are delayed.',NULL,'Innsmouth Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('Water damage! In order to unload damaged books, the shop is holding a sale. For every $1 you pay, you may draw 1 Unique Item. You may keep any Tomes that you draw, and must discard the rest. You must pay the total up front, before you draw.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('With the "Legacy of the Pharaohs" exhibit in town, folks are crazy for faux-Egyptian trinkets. Pay $3 if you''d like to buy one, then make a Luck (-1) check. If you pass, it''s actually a real item! Draw 1 Exhibit Item or Unique Item.','Luck -1','Curse of the Dark Pharaoh');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('While discussing magic with Miriam Beecher, you mention a spell she doesn''t know and is eager to learn! You may discard 1 spell to draw 2 unique items. Choose 1 to keep, discarding the other.',NULL,'Innsmouth Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('You accidentally bump into a glass bottle filled with a strange grey powder. Make a Speed (-2) check to catch it before it breaks. If you fail, lose 1 Stamina as you break out into a fit of unexplained sneezing and itching.','Speed -2','The Lurker at the Threshold');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('You know what you are looking for, but the trick will be finding it. Pass a Luck (-2) check to search the Unique Item deck for the Livre d''Ivon card.','Luck -2','Kingsport Horror');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('You peek into the back room and see Miriam Beecher, the shopkeeper, unwrapping a mummy stolen from the visiting museum exhibit! If you turn her in, the Sheriff rewards you with a license to investigate as you see fit; take the Private Investigator card. However, Miriam''s neighbors think you betrayed her, and you are Barred from Uptown.',NULL,'Curse of the Dark Pharaoh');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('You peek into the back room and see Miriam Beecher, the shopkeeper, unwrapping a mummy stolen from the visiting museum exhibit! If you turn her in, the Sheriff rewards you with a license to investigate as you see fit; take the Private Investigator card, if it is available. However, Miriam''s neighbors think you betrayed her. Place a Patrol marker in the street area of Uptown.',NULL,'Curse of the Dark Pharaoh (Revised Edition)');
INSERT INTO ye_olde_magick_shoppe_encounters VALUES ('You see an interesting book sitting open on Miriam Beecher''s desk. Pass a Lore (-1) check or you peer closely at its pages only to realize too late that the book is Cursed... and now, so are you.','Lore -1',NULL);
