CREATE TABLE visions_of_hypnos (
    `list_name` VARCHAR(69) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8,
    `list_image` VARCHAR(54) CHARACTER SET utf8,
    `list_flavor` VARCHAR(189) CHARACTER SET utf8,
    `list_clue` VARCHAR(50) CHARACTER SET utf8,
    `list_encounter` VARCHAR(143) CHARACTER SET utf8
);
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Administration)','Kingsport Horror','/File%3AVisionOfHypnos3.png','"I was back in school, taking an exam, when suddenly I couldn''t breathe. I raised my hand to gain the proctor''s attention, but was ignored until I passed out, at which time I awoke."','Administration Building','Any investigator who has an encounter at Administration Building draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Arkham Asylum)','Kingsport Horror','/File%3AVisionOfHypnos13.png','"Last night''s vision was terrible. I was in the asylum, and I could only babble nonsense when I tried to speak. The doctors just shook their heads sadly and shut me away for good."','Arkham Asylum','Any investigator who has an encounter at Arkham Asylum draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Bank of Arkham)','Kingsport Horror','/File%3AVisionOfHypnos20.png','"In the dream, I gave an hourglass to the bank teller for a handful of coins. Only as I was leaving did I realize that the hourglass was my life."','Bank of Arkham','Any investigator who has an encounter at Bank of Arkham draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Bishop''s Brook Bridge and 607 Water St.)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"There was a river in my dream, and a small bridge. Crossing the bridge, I saw the water in the river turn red."','Bishop''s Brook Bridge and 607 Water St.','Any investigator who has an encounter at Bishop''s Brook Bridge draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Black Cave)','Kingsport Horror','/File%3AVisionOfHypnos6.png','"There in the darkness, after my lantern had faded, the nightmare things of my mind fell upon me, scratching, kicking, and biting."','Black Cave','Any investigator who has an encounter at Black Cave draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Cold Spring Glen and 7th House on the Left)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"I had a nightmare in which policemen stod in an overgrown ravine. These men were dead, and their faces were horrible to see."','Cold Spring Glen and 7th House on the Left','Any investigator who has an encounter at Cold Spring Glen draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Curiositie Shoppe)','Kingsport Horror','/File%3AVisionOfHypnos15.png','"Inside that old shop in my dreams, I found a book, both fascinating and blasphemous. However, before I could read the critical passage from it, I awoke, in a sweat."','Curiositie Shoppe','Any investigator who has an encounter at Curiositie Shoppe draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Darke''s Carnival and Artists'' Colony)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"In the dream, I saw a train racing by carrying brightly-colored tents, freaks, and wonders. I couldn''t stop myself. I jumped on the train."','Darke''s Carnival and Artists'' Colony','Any investigator who has an encounter at Darke''s Carnival draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Devil Reef and 607 Water St.)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"I dreamt of a rowboat. The man rowing was taking us to a small black island, where things that crawled out of the sea waited for us."','Devil Reef and 607 Water St.','Any investigator who has an encounter at Devil Reef draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Devil''s Hopyard and Congregational Hospital)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"It was an odd dream. As I walked up the hill, the grass and trees grew thinner. Soon, no life could be seen, as if I had climbed into space."','Devil''s Hopyard and Congregational Hospital','Any investigator who has an encounter at Devil''s Hopyard draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Dunwich Village and Hall School)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"In the dream, I saw farms, weathered and grey. Someone had been hung from a tree branch and the entire great oak was on fire."','Dunwich Village and Hall School','Any investigator who has an encounter at Dunwich Village draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Esoteric Order of Dagon and 7th House on the Left)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"I had a dream about a church, but it felt wrong, threatening. The priest looked pale and clammy, with large and watery eyes."','Esoteric Order of Dagon and 7th House on the Left','Any investigator who has an encounter at Esoteric Order of Dagon draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Falcon Point and Artists'' Colony)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"I was plagued by nightmares. A man in a boat took me out to sea and then demanded money. When I didn''t pay, he threw me overboard."','Falcon Point and Artists'' Colony','Any investigator who has an encounter at Falcon Point draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (First National Grocery and Congregational Hospital)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"There was a person in my dream; I think he wanted to give me a gift, but I didn''t know what to ask him for. He was trying so hard to help."','First National Grocery and Congregational Hospital','Any investigator who has an encounter at First National Grocery draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Gardners'' Place and Neil''s Curiosity Shop)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"In the dream, I saw an enormous shooting star burn across the sky. At my feet, the grass withered, died, and faded away."','Gardners'' Place and Neil''s Curiosity Shop','Any investigator who has an encounter at Gardners'' Place draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (General Store)','Kingsport Horror','/File%3AVisionOfHypnos5.png','"It was when I picked up the doll that I knew I was dreaming, for it moaned, and blood trickled from its glass eyes and tiny porcelain mouth."','General Store','Any investigator who has an encounter at General Store draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Gilman House Hotel and Hall School)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"I awoke in a dark, unfamiliar room. Someone outside was trying to break down the door. I awoke a second time, my heart racing."','Gilman House Hotel and Hall School','Any investigator who has an encounter at Gilman House Hotel draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Graveyard)','Kingsport Horror','/File%3AVisionOfHypnos10.png','"While I slept, I dreamt that I met my dead grandfather at the graveyard. He was eaten through with worms, but discoursed kindly with me, enquiring as to my life since his passing."','Graveyard','Any investigator who has an encounter at Graveyard draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Hibb''s Roadhouse)','Kingsport Horror','/File%3AVisionOfHypnos18.png','"Last night, a vision of an ancient wild debauch came upon me. Hoary Pan danced there with his pipes and moon-touched wine, and my spirit lay small and frightened inside me."','Hibb''s Roadhouse','Any investigator who has an encounter at Hibb''s Roadhouse draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Historical Society)','Kingsport Horror','/File%3AVisionOfHypnos23.png','"In the dream, I became convinced that anyone who read the secrets in the journal I bore would try to kill me. The more I hid it, however, the more others wanted to see."','Historical Society','Any investigator who has an encounter at Historical Society draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Independence Square)','Kingsport Horror','/File%3AVisionOfHypnos24.png','"I could only remember bits and pieces of the dream. There was a bloody stone and I was chained to it. I was dying, but people kept walking past without noticing me ..."','Independence Square','Any investigator who has an encounter at Independence Square draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Innsmouth Jail and Neil''s Curiosity Shop)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"I remember only pieces of the dream. I was locked in a small room. People outside were laughing at my panic."','Innsmouth Jail and Neil''s Curiosity Shop','Any investigator who has an encounter at Innsmouth Jail draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Library)','Kingsport Horror','/File%3AVisionOfHypnos2.png','"It was then that I saw that the book I was reading was bound in human flesh, and it was still dripping warm blood upon the ground. With a start at the sight, I instantly awoke."','Library','Any investigator who has an encounter at Library draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Ma''s Boarding House)','Kingsport Horror','/File%3AVisionOfHypnos25.png','"I dreamt that someone stood over me as I slept, muttering strange words and making arcane gestures."','Ma''s Boarding House','Any investigator who has an encounter at Ma''s Boarding House draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Marsh Refinery and St. Erasmus'' Home)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"I woke up with a fever. I''d had a nightmare of burning, the victim of some ancient trial by fire."','Marsh Refinery and St. Erasmus''s Home','Any investigator who has an encounter at Marsh Refinery draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Newspaper)','Kingsport Horror','/File%3AVisionOfHypnos17.png','"I dreamt that I was trying to read the newspaper. I knew, somehow, that it contained vital information, but it was all gibberish to me. It was as if I suddenly forgot how to read English."','Newspaper','Any investigator who has an encounter at Newspaper draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Police Station)','Kingsport Horror','/File%3AVisionOfHypnos16.png','"In the nightmare, I was locked in a cage and isolated from my fellow man. Strange things would come to gawk at me occasionally, but I was only a novelty to them."','Police Station','Any investigator who has an encounter at Police Station draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (River Docks)','Kingsport Horror','/File%3AVisionOfHypnos11.png','"I knew I should have avoided peering into the muck-topped water, but as I did so, I found myself submerged, pounding at the water''s surface, which was hard as granite."','River Docks','Any investigator who has an encounter at River Docks draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Science Building)','Kingsport Horror','/File%3AVisionOfHypnos7.png','"In that terrible nightmare, I was strapped down to a table while a faceless scientist cut slivers of my flesh to see what would happen."','Science Building','Any investigator who has an encounter at Science Building draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Silver Twilight Lodge)','Kingsport Horror','/File%3AVisionofHypnos4.png','"I dreamt that no one would look at or speak to me. After a moment, I realized it was because of the leprosy that pockmarked my skin."','Silver Twilight Lodge','Any investigator who has an encounter at Silver Twilight Lodge draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (South Church)','Kingsport Horror','/File%3AVisionOfHypnos8.png','"I dreamt I stood in church, singing in the choir. Then, a shriek of terror rang out, and all eyes turned to me. Maggots were pouring out from my robes."','South Church','Any investigator who has an encounter at South Church draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (St. Mary''s Hospital)','Kingsport Horror','/File%3AVisionOfHypnos26.png','"In the dream, I was paralyzed, but they mistook me for dead. They placed me in a morgue locker and notified the crematory."','St. Mary''s Hospital','Any investigator who has an encounter at St. Mary''s Hospital draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (The Unnamable)','Kingsport Horror','/File%3AVisionOfHypnos12.png','"And in that dream, I wandered through a house, while something wet and horrible snuffled along behind me. But I knew if I fled or looked back, it would be on me in an instant."','The Unnamable','Any investigator who has an encounter at The Unnamable draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (The Witch House)','Kingsport Horror','/File%3AVisionOfHypnos1.png','"With that strange certainty dreamers sometimes have, I knew that the woman was a witch, and had no business being alive this century."','The Witch House','Any investigator who has an encounter at The Witch House draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Train Station)','Kingsport Horror','/File%3AVisionOfHypnos19.png','"That night I dreamt of a pale, lonely little girl, waiting at the train station for a family that would never come."','Train Station','Any investigator who has an encounter at Train Station draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Unvisited Isle)','Kingsport Horror','/File%3AVisionOfHypnos9.png','"The weather suddenly turned ugly, as it is wont to do in dreams. The waters all around were whipped into a fury, and the willows groaned in pain."','Unvisited Isle','Any investigator who has an encounter at Unvisited Isle draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Velma''s Diner)','Kingsport Horror','/File%3AVisionOfHypnos14.png','"There was a great feast in the dream, but I soon came to find that I couldn''t stop eating, no matter how much it began to hurt ..."','Velma''s Diner','Any investigator who has an encounter at Velma''s Diner draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Whately Farm and St. Erasmus'' Home)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"The dream was so vivid. I was outside a boarded-up farmhouse surrounded by the dead livestock, perhaps torn apart by a bear."','Whateley Farm and St. Erasmus''s Home','Any investigator who has an encounter at Whateley Farm draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Wizard''s Hill and The Rope and Anchor)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"The dream was unnerving. Atop a lonely hill, voices whispered, but the words were overpowered by the thunderous flapping of wings."','Wizard''s Hill and The Rope and Anchor','Any investigator who has an encounter at Wizard''s Hill draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Woods)','Kingsport Horror','/File%3AVisionOfHypnos22.png','"Things lurked in the woods in that nightmare, writhing and clutching at my sleeves from just beyond my line of sight."','Woods','Any investigator who has an encounter at Woods draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Y''ha-nthlei and The Rope and Anchor)','Miskatonic Horror','/wiki/index.php?title=Special%3AUpload&wpDestFile=.png','"I felt their cold hands gripping my legs, dragging me beneath the water''s surface to the murky depths below. I awoke gasping for air."','Y''ha-nthlei and The Rope and Anchor','Any investigator who has an encounter at Y''ha-nthlei draws two cards, encountering one card of his choice and discarding the other.');
INSERT INTO visions_of_hypnos VALUES ('Vision of Hypnos (Ye Olde Magick Shoppe)','Kingsport Horror','/File%3AVisionOfHypnos21.png','"That''s when the dream turned ugly, as the spell tried to forced its way out from between my lips."','Ye Olde Magick Shoppe','Any investigator who has an encounter at Ye Olde Magick Shoppe draws two cards, encountering one card of his choice and discarding the other.');
