CREATE TABLE anothertime (
    `list_expansion` VARCHAR(54) CHARACTER SET utf8,
    `list_encounter` VARCHAR(700) CHARACTER SET utf8,
    `list_check` VARCHAR(18) CHARACTER SET utf8
);
INSERT INTO anothertime VALUES ('Dunwich Horror','Although the future is a frightening and confusing place, you come across a small statue of yourself, proving that, if nothing else, you made a difference to someone. You may discard 1 Madness card.',NULL);
INSERT INTO anothertime VALUES ('Miskatonic Horror: Lurker at the Threshold component','As you try to get your bearings you bump into a gentleman dressed as a musketeer who begins to angrily berate you in French. You get the impression he''s challenging you to a duel.If you accept the challenge, make a Fight (-1) check. If you pass, you take the man''s weapon as a trophy. Search the Unique Item deck and take the first Weapon you find. If you fail, gain an Injury card.If you decline the challenge, you are hunted through the streets of Paris. Make a Sneak (-1) check. If you pass, you manage to find a safe place to rest and recuperate, restoring your Stamina to full. If you fail, you are discovered and stripped of your belongings. Choose 2 of your items to keep and discard the rest.','Fight -1ORSneak -1');
INSERT INTO anothertime VALUES ('Dunwich Horror','Awakening, you find yourself in a Victorian masked ball. The night passes in a blur. Stay here next turn.',NULL);
INSERT INTO anothertime VALUES ('Dunwich Horror','Finding yourself in a primordial jungle, you are attacked by savage hominids directed by a hovering brain covered in black tentacles. Either pass a Speed (-1) [2] check or discard a Dynamite card to escape from them, gaining 2 Clue tokens in the process. If you do not escape, lose 2 Stamina and stay here next turn.','Speed -1 [2]');
INSERT INTO anothertime VALUES ('Dunwich Horror','Hurtled forward in time, you witness mankind''s final moments. Pass a Will (-2) check or draw a Madness card.','Will -2');
INSERT INTO anothertime VALUES ('Dunwich Horror','If Shub-Niggurath is the Ancient One, then you are thrown back through the ages to a time when primordial ooze is the only life. Pass a Fight (+0) [3] check to escape powerful grasping tentacles or you are devoured. If Shub-Niggurath is not the Ancient One, nothing happens.','Fight +0 [3]');
INSERT INTO anothertime VALUES ('Dunwich Horror','In the far-flung future, you are witness to an Earth that lies in ruin, populated only by hideous beetles. You return wiser, but your mind is unhinged by the experience. Gain 3 Clue tokens, but lose 3 Sanity.',NULL);
INSERT INTO anothertime VALUES ('Dunwich Horror','Pass a Luck (-2) check to escape back to the present with a precious object. Draw 1 Unique Item. If you fail, you are stranded in the medieval village. Stay here next turn.','Luck -2');
INSERT INTO anothertime VALUES ('Dunwich Horror','Pass a Luck (-2) check to wake up in an unfamiliar place. You find that you have become another person in a distant time. Years pass as you are married, raise a family, grow old, and finally die. However, it seems that you no sooner close your eyes for the final time than you open them again right back where you started, but with the memories of an extra lifetime. Draw 2 Skills, discarding 1 of them.','Luck -2');
INSERT INTO anothertime VALUES ('Dunwich Horror','Strolling down a quiet street, you are startled to see your mother, dead these many years. She laughs and flirts with a young man you recognize as your father. Smiling, you watch them talk awhile before going on your way. Restore your Sanity to its maximum value.',NULL);
INSERT INTO anothertime VALUES ('Dunwich Horror','Thrown back millions of years, you find that you have swapped bodies with an alien being. Make a Luck (-2) check to try and find a way to switch back. If you pass, return to Arkham. If you fail, you are devoured.','Luck -2');
INSERT INTO anothertime VALUES ('Dunwich Horror','Walking down a shaded lane, you are astonished to see an item that you lost years ago. Draw 1 Common Item.',NULL);
INSERT INTO anothertime VALUES ('Dunwich Horror','You are able to rescue a beautiful piece of art from the distant past. Gain $5.',NULL);
INSERT INTO anothertime VALUES ('Miskatonic Horror: Curse of the Dark Pharaoh component','You are in ancient Egypt among the Dark Pharaoh''s treasures! They are well-guarded, but you think you could steal one artifact.If you attempt to steal an item, make a Sneak (-2) check. If you pass, you may search the Exhibit Item deck and take one card of your choosing. If you fail, lose 1 Stamina as the guards remove you forcibly.If you do not attempt to steal anything, you notice the walls are adorned with paintings depicting the future. Make a Lore (-1) check and gain a Clue token for each success.','Sneak -2ORLore -1');
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You are in the Congregational Church during December of 1722. An angry mob has gathered outside while those within are racing to hide a strange collection of artifacts. Make a Sneak (-1) check. If you pass, gain 1 Unique Item. If you fail, the people inside the church turn on you. Lose 2 Stamina.','Sneak -1');
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You encounter people you know and places you are familiar with, but no one recognizes you. It is as if you''d never been born. Seeing how unhappy everyone here is, you realize what a positive impact you''ve made on those around you. Gain 1 Sanity.',NULL);
INSERT INTO anothertime VALUES ('Dunwich Horror','You find yourself in a beautiful garden. Wandering through its lovely paths, you realize that this is the lost Hanging Garden of Babylon. Gain 2 Sanity for witnessing one of the lost wonders of the world.',NULL);
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You find yourself in a small New England colonial town. On the door of one of the buildings is a symbol you recognize from the Silver Twilight Lodge. As you examine it, you overhear voices inside. Make a Sneak (-1) check. If you pass, you learn the secrets of their initiation. Take a Silver Twilight Lodge Membership. If you fail, the people inside discover you. Lose 1 Stamina as they drag you away.','Sneak -1');
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You find yourself in a small New England colony that suspects that you practice witchcraft. Make a Sneak (+1) check to avoid capture. If you fail, draw an Injury card as you endure their rigorous questioning.','Sneak +1');
INSERT INTO anothertime VALUES ('Miskatonic Horror: King in Yellow component','You find yourself in the recent past, just before a terrible hardeship is about to befall one of the investigators. Will you attempts to interfere?If you choose to interfere, make a Speed (-1) check to act in time. If you pass, you may choose any investigator and restore either his Sanity or his Stamina to full. If you fail, you are Cursed for trying to interfere in the natural order of things.If you choose not to interfere, make a Lore (-1) check and gain 1 Clue token for each success as you are able to analyze events as they unfold.','Speed -1ORLore -1');
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You find yourself in the trenches of the Great War. Make a Fight (+0) check to keep yourself from harm. If you fail, draw an Injury card.','Fight +0');
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You find yourself in Victorian England, but a man tells you he has a machine that can return you to your own time. Make a Luck (-1) check to see if the machine works. If you pass, return to Arkham. If you fail, you are delayed as the machine sends you to the wrong time.',NULL);
INSERT INTO anothertime VALUES ('Dunwich Horror','You find yourself surrounded by clay tablets and scrolls. Search the Unique Item deck and take a Tome of you choice, then regain 1 Sanity as you realize that you''ve seen the Great Library of Alexandria.',NULL);
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You have the opportunity to consult the Oracle at Delphi in Ancient Greece. If you wish, make a Lore (-1) check to interpret their message. Gain 1 Clue token for each success. If you fail the check, you are Cursed.','Lore -1');
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You quickly determine that you are in Kingsport in 1685. To your amazement, you are greeted by a man you know to still be alive in 1926, William Bain. If you pass a Will -2 check or discard an Ancient Tome, he offers you his help. Take his Ally card. If it isn''t available, you are Blessed.','Will -2');
INSERT INTO anothertime VALUES ('Dunwich Horror','You realize that the Hound has seen you as you gazed at it across the ages. If there is a Hound of Tindalos in the monster cup, it appears.',NULL);
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You recognize an old, dilapidated building as your home. On a hunch, you search the house to see if you''ve written a letter to yourself, knowing that you would be here at some point in the future. Make a Luck (-1) check. If you pass, you find a very informative letter from your future self. Gain 3 Clue tokens. If you fail, lose 1 Sanity as there is no sign that you ever returned to this place.','Luck -1');
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You recognize the building you are in as a library, but it is necessary to operate strange machines to find the books you seek. Make a Lore (-2) check. If you pass, gain 2 Clue tokens and then search the Common Item deck and take the first Tome you find.','Lore -2');
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You recognize the landscape as being Dunwich, but you see no recognizable buildings. A group of Vikings stand near a large stone covered in glyphs and are speaking a language you don''t understand. When the discussion is over, they begin to bury the stone. Make a Will (-1) check to memorize the location. If you pass, gain 2 Clue tokens.','Will -1');
INSERT INTO anothertime VALUES ('Dunwich Horror','You recognize this place from your childhood. You used to play here all the time. Gain 1 Sanity.',NULL);
INSERT INTO anothertime VALUES ('Miskatonic Horror: Dunwich Horror component','You see a flier looking for investors in a new plan to establish a railroad across the country. Pay $3 if you want to invest. If you do, gain a Retainer card and a Rail Pass.',NULL);
INSERT INTO anothertime VALUES ('Miskatonic Horror: Black Goat of the Woods component','You see primitive, hunched figures burning meat upon an altar. They chant in a language you do not recognize but the repetition begins to insinuate the words into your memory. Would you like to memorize the chant?If you do, make a Will (-1) check. If you pass, gain a "One of the Thousand" Membership card. If you fail, lose 2 Sanity.If you choose not to, the words affect your subconscious, shaping your dreams against your will. Lose 1 Sanity and gain 1 Clue token.','Will -1');
