CREATE TABLE other (
    `list_expansion` VARCHAR(54) CHARACTER SET utf8,
    `list_encounter` VARCHAR(451) CHARACTER SET utf8,
    `list_check` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO other VALUES ('The King in Yellow','"I am demoiselle Jeanne d''Ys," she says, her beautiful eyes and charming accent piercing your heart. If you stay with her, gain 1 Stamina and 1 Sanity, but you are delayed. If you leave her, pass a Luck (-1) check or lose 1 Stamina and 1 Sanity.','Luck -1');
INSERT INTO other VALUES ('The King in Yellow','"Is that you, Camilla?" a voice calls to you in the darkness. If you flee, lose 1 Stamina. If you answer, pass a Will (-2) check or lose 2 Sanity.','Will -2');
INSERT INTO other VALUES ('Kingsport Horror','"It is not too late," whispers the voice in the darkness. If the terror level is less than 6, draw a Spell.',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','"Mr. Skin''s the name, investigatin''s my game," he says, with a friendly smile. But there''s something about him that makes you feel like a helpless child before a ravenous beast. If you agree to let him come along, his form and face seem to shift... you may take any Ally of your choice, but you lose 2 Stamina and 2 Sanity.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','A crazed, half-dead explorer attacks you. Pass a Fight (+2) check to overcome him. If you succeed, take 1 Common Item and lose 1 Sanity as you contemplate this poor soul''s fate. If you fail, lose 1 Stamina.','Fight +2');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','A dark ocean laps at your feet, and you see gables of old-fashioned buildings across the water. Could this be Innsmouth? Your Luck slider is reset to the lowest possible number, but you gain 1 Clue token.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','A distant drumming can be heard. Strangely, it gives you a sense of security and protection, as if it were warding away some evil. Gain 1 Sanity.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','A foul-smelling ichor covers the ground. Pass a Will (-1) check or lose 1 Stamina as the odor overwhelms you.','Will -1');
INSERT INTO other VALUES ('The Black Goat of the Woods','A ghastly monster appears!',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','A ghostly ship captain offers you passage home, for a price. Return to Arkham, but you are Cursed.',NULL);
INSERT INTO other VALUES (NULL,'A glimmer of gold catches your eye. Gain $2.',NULL);
INSERT INTO other VALUES (NULL,'A glimpse of home gives you hope. Gain 1 Sanity.',NULL);
INSERT INTO other VALUES (NULL,'A hideous monster appears!',NULL);
INSERT INTO other VALUES ('Dunwich Horror','A hideous monster appears!',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','A hideous monster appears!',NULL);
INSERT INTO other VALUES ('Kingsport Horror','A horrendous monster appears!',NULL);
INSERT INTO other VALUES ('The King in Yellow','A horrible shadow falls across you. Roll a die. On a 1, either lose 5 Clue tokens or you are devoured.',NULL);
INSERT INTO other VALUES ('The King in Yellow','A large dog lopes alongside you for a time, warding you from harm. No encounter.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','A large mirror stands before you. Your reflection bears an unfamiliar mark upon its forehead. Make a Will (+0) check. If you pass, the mark fades from the reflection. If you fail, it remains and you are Cursed.','Will +0');
INSERT INTO other VALUES (NULL,'A lurking monster appears!',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','A man in a coat and hat takes your arm, and you find yourself leading the shadowy presence forward. All the reward you seem to need is his reassurance... perhaps you are being mystically controlled, but it''s hard to care. Gain 1 Sanity, but take the Local Guide card.',NULL);
INSERT INTO other VALUES (NULL,'A monster appears!',NULL);
INSERT INTO other VALUES (NULL,'A monster appears!',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','A monster appears!',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','A monster appears!',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','A monster appears!',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','A monster appears!',NULL);
INSERT INTO other VALUES ('Dunwich Horror','A monster appears!',NULL);
INSERT INTO other VALUES ('Dunwich Horror','A monster appears!',NULL);
INSERT INTO other VALUES ('Dunwich Horror','A monster appears!',NULL);
INSERT INTO other VALUES ('The King in Yellow','A monster appears!',NULL);
INSERT INTO other VALUES ('The King in Yellow','A monster appears!',NULL);
INSERT INTO other VALUES (NULL,'A monster appears from the shadows!',NULL);
INSERT INTO other VALUES ('Kingsport Horror','A monster appears, taking shape from the angle''s curve!',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','A mysterious woman warns you that you would be able to see all that you need to know if your mind were not clouded by the unnatural. Discard 2 Spells to gain 5 Clue tokens. If you can''t or choose not to, gain 1 Sanity.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','A nightmarish monster appears!',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','A powerful force is attempting to tear its way through the realities! Make a Lore (+0) [2] check to slow it down. If you pass, remove 1 Dunwich Horror token from the board.','Lore +0 [2]');
INSERT INTO other VALUES ('The Black Goat of the Woods','A revolting monster appears!',NULL);
INSERT INTO other VALUES (NULL,'A ripple in the air passes over you. Pass a Lore (-1) check or lose 1 Spell of your choice as it is burned from your mind.','Lore -1');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','A row of vaguely humanoid sculptures lines your path. As you walk past them, you cannot help but think that some malevolent force is watching you through their stone eyes. Lose 1 Sanity.',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','A scrap of paper flutters into your hands, with the words, "this world was inhabited at one time by another race who, in practicing black magic, lost their foothold and were expelled from the allegorical garden..." Lose up to 2 Clue tokens due to this misleading information, if able.',NULL);
INSERT INTO other VALUES ('The King in Yellow','A strange being pays you a visit, and test you. Make a Will (-2) check. If you fail, you lose 1 Sanity and 1 Stamina. If you pass, you gain 3 Clue tokens.','Will -2');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','A strange euphoria begins to overtake you. You are irrationally certain things will be okay. Gain 1 Sanity. Then make a Luck (-1) check. If you fail, overconfidence leads you astray and you are delayed.','Luck -1');
INSERT INTO other VALUES ('The Black Goat of the Woods','A strange rash has appeared on your skin, and you''ve developed a harsh, rattling cough. Lose 1 Stamina.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','A strange serpent-face person in a hooded robe speaks at you in an ancient tongue. Make a Lore (-2) check to decipher his words and gain 1 Clue token. If you fail, he bites you, disgusted, and leaves. Lose 1 Stamina.','Lore -2');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','A strange song conjures up images of a life you could have lived. Gain Clue tokens equal to your focus.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','A strangely-dressed man claiming to be a doctor offers to trade valuable information for an item he purports to need. You may discard any item that is not a Weapon and then gain 3 Clue tokens.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','A terrible monster appears!',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','A terrible monster appears!',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','A terrible monster appears!',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','A terrifying monster appears!',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','A thick pollen is infecting the air. You need to keep moving or you''re going to pass out from breathing it in. Pass a Speed (-1) check or you are delayed here.','Speed -1');
INSERT INTO other VALUES ('The King in Yellow','A tree, covered in blood and waving in the wind, stands before you. If you pass a Luck (-1) check, it is just a tree. If you fail, it attacks you! Lose 1 Sanity and 2 Stamina.','Luck -1');
INSERT INTO other VALUES ('The King in Yellow','A vortex sweeps you off your feet and into oblivion. Pass a Fight (+0) check or you are lost in space and time.','Fight +0');
INSERT INTO other VALUES ('Kingsport Horror','A web of light surrounds the object on the pedestal. You may draw a Unique Item, but if you do, every other investigator loses 1 Sanity and 1 Stamina.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','A window floats by, looking out on.. can it be Home? Pass a Luck (-1) check to return to Arkham.','Luck -1');
INSERT INTO other VALUES ('The Black Goat of the Woods','A wounded beast snarls at you, but it can''t move. You don''t think it''s going to live much longer. If you want to wait around, you are delayed, but you may draw a monster from the cup and take it as a monster trophy, even if it has the Endless ability.',NULL);
INSERT INTO other VALUES ('The King in Yellow','Along the shore, the cloud waves break. Pass a Fight (+1) check to gain 1 Stamina.','Fight +1');
INSERT INTO other VALUES ('Dunwich Horror','Although you believe that you''ve found a way home, the path looks perilous. You may roll 3 dice, losing 1 Stamina for each failure you roll. If you are not reduced to 0 Stamina, you may return to Arkham.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','Although you try your best, you are unable to hang on any longer. If you are in the second area of this Other World, move to its first area. If you are in its first area, you are lost in time and space.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','Although your journey has been perilous, you''ve found a possible way to get home. Pass a Luck (-1) check to return to Arkham.','Luck -1');
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','An enigmatic traveler sympathizes with your cause and offers some good advice. Gain 1 Clue token. Then make a Luck (-2) check. If you pass, you are Blessed.','Luck -2');
INSERT INTO other VALUES ('The Black Goat of the Woods','An enormous stone marker covered with arcane markings stands before you. Its true purpose is unclear, but you think you may be able to translate a small portion. Pass a Lore (-1) check to gain 1 Spell.','Lore -1');
INSERT INTO other VALUES ('Kingsport Horror','An unspeakable monster appears!',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','At some point in your other-worldly travels, you began suffering from a fever. Lose 1 Stamina. Then make a Will (-1) check to glean useful insights from your delirious dreams. If you pass, gain 1 Clue token.','Will -1');
INSERT INTO other VALUES ('The Black Goat of the Woods','At the top of the hill is an old stone well. You may toss $1 inside and pass a Luck (-2) check to be Blessed. If you fail, nothing happens.','Luck -2');
INSERT INTO other VALUES ('The King in Yellow','Black stars shine upon you, and reality is reversed. If you were Cursed, you are now Blessed. If you were Blessed, you are now Cursed.',NULL);
INSERT INTO other VALUES (NULL,'Carefully, you avoid the gaze of a gigantic eye watching an alter. You may try to pass a Sneak (-1) check to steal a scroll from the dais. Draw 1 Spell. If you fail, you are racked by pain and lose 3 Sanity.','Sneak -1');
INSERT INTO other VALUES ('Kingsport Horror','Certainly frail mortal creatures like you were not meant to see and hear such things. Lose 1 Sanity.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','Crushing tentacles pursue you! Pass a Speed (-1) check or you are reduced to 1 Stamina.','Speed -1');
INSERT INTO other VALUES ('Kingsport Horror','Dark tendrils grasp you! Pass a Luck (-1) check or be delayed.','Luck -1');
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Innsmouth Horror','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Curse of the Dark Pharaoh component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Curse of the Dark Pharaoh component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Curse of the Dark Pharaoh component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Curse of the Dark Pharaoh component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: King in Yellow component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: King in Yellow component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: King in Yellow component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: King in Yellow component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Black Goat of the Woods component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Black Goat of the Woods component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Black Goat of the Woods component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Black Goat of the Woods component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Lurker at the Threshold component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Lurker at the Threshold component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Lurker at the Threshold component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Lurker at the Threshold component','Discard this card and draw again.',NULL);
INSERT INTO other VALUES ('The King in Yellow','Eerie purple lights begin wending their way towards you. Pass a Will (+0) check or you are drawn to them and delayed.','Will +0');
INSERT INTO other VALUES ('Dunwich Horror','Excellent! There seems to be a narrow passage leading back. Return to Arkham.',NULL);
INSERT INTO other VALUES ('The King in Yellow','Exhausted, you lay down and sleep for a while. You are delayed.',NULL);
INSERT INTO other VALUES ('The King in Yellow','For once, fortune is with you. No encounter.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','Fortune favors everyone, each according to his station. If you are Cursed, discard all of your items. If you are Blessed, draw a Unique Item.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','From living blackness, a monster appears!',NULL);
INSERT INTO other VALUES ('The King in Yellow','Have you seen the Yellow Sign? Pass a Speed (+0) check to avert your eyes. If you fail, you are reduced to 1 Sanity.','Speed +0');
INSERT INTO other VALUES ('Kingsport Horror','Ho there, what''s this? Pass a Luck (-1) check to gain a Common Item.','Luck -1');
INSERT INTO other VALUES ('Dunwich Horror','Hurry! You must choose the correct crystal soon, or the gate will open and release a terrible creature. Pass a Luck (-2) check or a monster appears!','Luck -2');
INSERT INTO other VALUES ('Kingsport Horror','If violence is all it understands, then violence it shall have! Pass a Fight (-1) check to take a Clue token','Fight -1');
INSERT INTO other VALUES ('The King in Yellow','If you have a Unique Item, nothing happens this turn. If you do not have one, the winds seem to taunt you, mocking your helplessness. Lose 2 Sanity.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','In a quiet corner removed from every place and no place at once, you snatch a moment of respite, and have no encounter.',NULL);
INSERT INTO other VALUES ('The King in Yellow','In each facet of the gem is a monstrosity waiting to be born. Make a Luck (+0) check. If you fail, a monster appears!','Luck +0');
INSERT INTO other VALUES ('The King in Yellow','In some alternate history, you see a United States plunged into dictatorship. Suicide chambers are erected in city parks. This could be the shape of things to come. Gain 2 Clue tokens and lose 1 Sanity.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','In the dark, you stumble into a deep hole. Looking up, you see a gravestone bearing your name. Pass a Speed (-2) check to scramble out or lose 2 Sanity and be delayed.','Speed -2');
INSERT INTO other VALUES ('Dunwich Horror','In this place, it''s a stroke of good fortune when nothing terrible happens to you. No encounter.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','In this place, where all minds converge, you may trade Clue tokens with other investigators until the end of this phase.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','It seems as though you''ve run out of options for now, so you must bide your time. Stay here next turn.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','It seems that no matter where you go, there are always thieves waiting to prey upon the unwary. Lose $2.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','It seems that you are not the first to have come here. Gain 1 Clue token and $2.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','It takes you a moment to realize that the horrible screeching noise consists of English words spoken by something monstrous! Lose 1 Sanity, but gain 1 Clue token.',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','It was a diabolical trap, you suddenly realize... now that you''re inside it! Make a Lore (-1) check or you are delayed.','Lore -1');
INSERT INTO other VALUES ('The Black Goat of the Woods','It''s a dead end. You are delayed as you must retrace your path and try something different.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','It''s a door! You must have walked by the other side of that door a hundred times back home. Gain 1 Sanity. Then make a Fight (-2) check to break the lock. If you pass, return to Arkham.','Fight -2');
INSERT INTO other VALUES ('Kingsport Horror','Knowledge is power, but more importantly, it is hope and endurance in this prison where you find yourself. Lose 3 Stamina and 3 Sanity, but you reduce this loss by 1 Stamina and 1 Sanity for each Clue token you discard (to a maximuum of three).',NULL);
INSERT INTO other VALUES ('Dunwich Horror','Looking at the vast distances you still have to cross, you feel as though all is lost. Lose 1 Sanity.',NULL);
INSERT INTO other VALUES (NULL,'Luck is with you. You stumble on a cache of supplies. Draw 1 Common Item.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','Magic seems to inherently manipulate your environment in unpredictable ways. If you have 3 or more Spells, this world rejects you completely and you are lost in time and space.',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','Make a Fight (+0) or Will (+0) check. If you pass, you push through the walls of fatigue and confusion and realize what must be done. You may seal the gate through which you entered, but only by sacrificing yourself. If you choose to seal the gate, you are devoured.','Fight +0OrWill +0');
INSERT INTO other VALUES ('The Lurker at the Threshold','Make a Fight (-2) check to scale that sheer cliff. If you succeed, the view from the top grants you 1 Clue token. If you fail, lose 1 Stamina.','Fight -2');
INSERT INTO other VALUES ('The Lurker at the Threshold','Make a Luck (+0) check and consult the chart below.Successes:0-1) Thousands of minute creatures! Lose 1 Stamina2) You find $2 worth of gold ingots3+) Anywhere is better than here. Return to Arkham','Luck +0');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','Make a Luck (-1) check. If you fail, a monster appears! If you pass, you may draw 2 monsters from the cup and choose which one appears.','Luck -1');
INSERT INTO other VALUES ('The Lurker at the Threshold','Make a Luck (-2) check to come across a Unique Item!','Luck -2');
INSERT INTO other VALUES ('The Lurker at the Threshold','Make a Luck (-2) check to make it through the twisted forest. If you pass, you find $3 worth of precious baubles! If you fail, you are delayed.','Luck -2');
INSERT INTO other VALUES ('The Lurker at the Threshold','Make a Speed (-1) check to run for safety and return to Arkham. If you fail, you are caught and are delayed.','Speed -1');
INSERT INTO other VALUES (NULL,'Monsters lurk everywhere. Pass a Sneak (-2) check or stay here next turn.','Sneak -2');
INSERT INTO other VALUES ('Dunwich Horror','Muttering a quick prayer, you hope that the grate is weak enough to remove, since it''s the only way forward that you''ve found so far. Pass a Luck (-1) check or stay here next turn.','Luck -1');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','Nephren-Ka places your soul upon the Balance of Thoth, and finds you lacking. First discard Stamina or Sanity, whichever is higher, until your Stamina and Sanity are equal. Then you are surprised by a monster. If you defeat it, you may draw 1 Exhibit Item.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','Nothing but emptiness. No encounter.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','On the horizon, you see the hazy silhouette of the Ancient One. Pass a Will (-2) check or lose all your Sanity.','Will -2');
INSERT INTO other VALUES ('The Lurker at the Threshold','One glimpse at the sky and things fall into place for you. Gain 1 Clue token.',NULL);
INSERT INTO other VALUES (NULL,'Pass a Fight (-1) check to hang on to your prize despite the wind. Draw 1 Spell.','Fight -1');
INSERT INTO other VALUES (NULL,'Pass a Fight (-2) check to lever back the lid of the stone chest. Inside, you find $8. If you fail, lose 1 Stamina.','Fight -2');
INSERT INTO other VALUES (NULL,'Pass a Fight (-2) check to pry open a grate you find built into the wall. Inside, you find something fascinating. Draw 1 Unique Item.','Fight -2');
INSERT INTO other VALUES (NULL,'Pass a Luck (-1) check to discover a cache of ancient papers containing valuable information about the Mythos. Gain 1 Clue token for every success you rolled on your Luck check.','Luck -1');
INSERT INTO other VALUES (NULL,'Pass a Luck (-1) check to discover a useful object in your wanderings. Draw 1 Unique Item.','Luck -1');
INSERT INTO other VALUES (NULL,'Pass a Luck (-1) check to discover a vital document. Gain 2 Clue tokens.','Luck -1');
INSERT INTO other VALUES (NULL,'Pass a Luck (-1) check to find a quiet spot to rest. Gain 2 Stamina and 2 Sanity.','Luck -1');
INSERT INTO other VALUES ('Dunwich Horror','Pass a Luck (-1) check to find something of use among the devastation. Draw 1 Common Item.','Luck -1');
INSERT INTO other VALUES (NULL,'Pass a Luck (-1) check to find something to defend yourself with. Take the first Weapon from the Common Item deck.','Luck -1');
INSERT INTO other VALUES (NULL,'Pass a Luck (-1) check to find the gate back. If so, immediately return to Arkham.','Luck -1');
INSERT INTO other VALUES ('Dunwich Horror','Pass a Luck (-2) check to stumble across a valuable item. Take the first Unique Item with a list price of at least $4 from the Unique Item deck.','Luck -2');
INSERT INTO other VALUES (NULL,'Pass a Speed (-1) check to grab the carving before it falls. Draw 1 Spell.','Speed -1');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','Pass a Speed (-2) check to jump the fissure. If you fail, lose 1 Stamina and you are delayed.','Speed -2');
INSERT INTO other VALUES ('Dunwich Horror','Perhaps there''s something of use here? Pass a Luck (-1) check to either draw 1 Unique Item or draw 1 Common Item and gain $2. If you fail the check, nothing happens.','Luck -1');
INSERT INTO other VALUES ('Dunwich Horror','Placing your hand on the ancient cave painting, you have a vision. Gain 1 Clue token.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','Riding a spear of light, you flash through a thousand times and places. Pass a Luck (-1) [2] check to return to Arkham. Any monsters in the location you return to are automatically defeated and collected as trophies.','Luck -1 [2]');
INSERT INTO other VALUES ('The Lurker at the Threshold','Silence and warmth, for a change. Gain 1 Sanity.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','Small, but precious stones are embedded into the wall. Gain $3.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','Someone has drawn a crude map of the terrain ahead of you. Make a Lore (-1) check to interpret it. If you pass, return to Arkham. If you fail, you are lost in time and space.','Lore -1');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','Something followed you here... if there are any monsters in the same location as the gate you entered, they appear. If they are not defeated, they remain in their original location.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','Something small scurries away from you, carrying 1 of your Common Items with it.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','Stairs wind upward, yet descend downward- ascend, or fall? Pass a Luck (-1) check or you are lost in time and space.','Luck -1');
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','Stinging insects swarm about you! Make a Speed (-1) check to find shelter. If you fail, lose 1 Stamina.','Speed -1');
INSERT INTO other VALUES ('Kingsport Horror','Strength- and knowledge?- in numbers. Take a Clue token for every investigator, including you, currently in an Other World.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','Struggling to hold your breath, you cannot seem to find the surface of the mysterious sea. Lose 1 Sanity and 1 Stamina.',NULL);
INSERT INTO other VALUES (NULL,'Suddenly, the things you''ve seen make sense! Gain 1 Clue token.',NULL);
INSERT INTO other VALUES (NULL,'Suddenly you notice something that you had previously missed. Gain 1 Clue token.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','Ten thousand worlds lie arrayed before you; you are delayed.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','The air here is too noxious. You don''t think you can make it. Pass a Speed (-1) check or lose 1 Stamina.','Speed -1');
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','The air here tastes sour and burns your lungs. Pass a Fight (-1) check or lose 1 Stamina.','Fight -1');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','The Black Man lays his book before you. If you wish to open the book, pass a Luck (-2) check to gain 5 Clue tokens. if you fail, you are devoured.','Luck -2');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','The Bloated Woman makes you an offer. Lose 1 Sanity, then you may discard any amount of money, all at once, then draw a number of cards from the Unique Item deck equal to the total amount of money discarded. You may take one card from among those drawn with a value equal to or less than the amount of money discarded, then discard the rest.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','The bruising winds make movement difficult. Lose 1 Stamina.',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','The chess game with the strange serpent seems to go on for days. Pass a Lore (+2) check to gain $1 for each success you roll. If you fail, you are delayed.','Lore +2');
INSERT INTO other VALUES (NULL,'The colors are blinding. Pass a Lore (-1) check or stay here next turn.','Lore -1');
INSERT INTO other VALUES ('The King in Yellow','The creature demands a toll. Discard a Tome or lose all of your Clue tokens and you are delayed.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','The creature waves its hand at you. "Blessings upon you." If you have a Curse card, you may discard it.',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','The cultists thrust you forward, and the God of the Bloody Tongue surprises you! You gain a +1 to all skill checks against this monster for each Unique Item or Exhibit Item you have.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','The door slams shut behind you. You are in total blackness. Pass a Luck (-2) check, otherwise you are delayed.','Luck -2');
INSERT INTO other VALUES ('Dunwich Horror','The endless forest refuses to give up its mysteries. No encounter.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','The environment here adamently refuses to conform to logic or reason. For each Clue token you have, roll a die. If the result is a "1", discard that Clue token.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','The floor is crumbling beneath you! Make a Speed (-1) check or be lost in time and space.','Speed -1');
INSERT INTO other VALUES ('Dunwich Horror','The fumes overcome you at last, causing you to sink into a dreamless sleep. Stay here next turn.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','The ground is giving way! Pass a Speed (-1) check to escape; otherwise you are delayed.','Speed -1');
INSERT INTO other VALUES ('Dunwich Horror','The ground shifts under you feet, sending you tumbling head over heels. Lose 1 Stamina.',NULL);
INSERT INTO other VALUES (NULL,'The humidity and heat is exhausting. Lose 1 Stamina.',NULL);
INSERT INTO other VALUES (NULL,'The insanity of this place finally hits you. Lose 1 Sanity.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','The journey proves fruitful. Draw 1 Spell.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','The landscape around you begins to shift and reshape itself. Make a Lore (-2) check. If you pass, you recognize this place and may move to the first area of any Other World and gain 1 Clue token.','Lore -2');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','The mad scientist cackles as he pulls down on the lever of his machine. Pass a Speed (+1) check to reach the giant gem that powers it in time and gain $4. If you fail, you are thrown through a portal. Draw a Gate card, move to the Other World listed first, and have another encounter there.','Speed +1');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','The monster''s corpse lies before you, and to your horror, you find your mouth watering. If you consum it, make a Fight (-2) check. If you fail, lose Stamina equal to the number of dice rolled. If you pass, gain Stamina equal to the number of dice rolled.','Fight -2');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','The mystic energies of this place seem to have the power to rejuvenate you. You may discard 1 Spell or 1 Unique Item to restore your Stamina to full',NULL);
INSERT INTO other VALUES (NULL,'The obsidian door refuses to open. Pass a Fight (-1) check or stay here next turn, struggling with it.','Fight -1');
INSERT INTO other VALUES ('Dunwich Horror','The only way forward now is a terrifying leap off a cliff. Pass a Will (-2) check or stay here next turn.','Will -2');
INSERT INTO other VALUES (NULL,'The pinkish rays nearly get you. Pass a Sneak (+0) check or lose 2 Stamina.','Sneak +0');
INSERT INTO other VALUES (NULL,'The rope seems to extend upwards forever, but it''s the only way out of the crevasse you find yourself in. Pass a Fight (-1) check to climb it and return to Arkham. If you fail, you fall, losing 2 Stamina and staying here next turn.','Fight -1');
INSERT INTO other VALUES ('The King in Yellow','The shadows of men''s thoughts lengthen in the afternoon. Pass a Lore (-2) check to gain Clue tokens equal to the number of successes you roll.','Lore -2');
INSERT INTO other VALUES (NULL,'The shadowy entity gives up the chase. Lose 1 Stamina from exhaustion.',NULL);
INSERT INTO other VALUES (NULL,'The sky is spinning. Pass a Will (-2) check or pass out and stay here next turn.','Will -2');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','The stench of fecundity and blood surrounds you. A monster appears! If you do not evade it or defeat it on the first round of combat, it replicates, and you must evade or defeat a second one!',NULL);
INSERT INTO other VALUES (NULL,'The strain is too much for your mind. Lose 1 Sanity.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','The sucking mouths drain enough of your blood to leave you dizzy. Lose 1 Stamina.',NULL);
INSERT INTO other VALUES ('The King in Yellow','The tides of time and space collide. You meet your future self, and learn what is in store. Gain 1 Clue token, the pass a Will (+0) check or lose 1 Sanity.','Will +0');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','The time you have spent in this alien landscape is altering your perceptions. New, strange knowledge is burning itself into your mind. Lose 1 Sanity. Then, if you are still sane, gain 1 Spell.',NULL);
INSERT INTO other VALUES (NULL,'The unending blackness terrifies you. Pass a Will (-1) check or lose 1 Sanity and 1 Stamina from fear and exhaustion.','Will -1');
INSERT INTO other VALUES ('Kingsport Horror','The way is shut, and more doors close with each passing eon. If there are four or more elder sign tokens in play, take this card. While you have it, during Upkeep, you must discard a Clue token or 1 Item, if you have either. (errata: the following was not printed in the English version, but was in the French and German versions) Put a Clue on that card for each Item or Clue you discarded. Put that card back in the box when there are 3 Clues on it.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','The weight of eons bears down with a literal force. Pass a Luck (-1) check or discard all of your Clue tokens and become lost in time and space.','Luck -1');
INSERT INTO other VALUES ('Kingsport Horror','The weight of the world presses down on you. Lose 1 Stamina.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','There are two flasks here. You may drink one to gain 1 Sanity and lose 1 Stamina or drink the other to gain 1 Stamina and lose 1 Sanity.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','There are two paths for you to choose between. One of them leads home, while the other could lead anywhere. Pass a Luck (-1) check to return to Arkham.','Luck -1');
INSERT INTO other VALUES ('The Lurker at the Threshold','These loathsome beings are certainly not friendly. Make a Sneak (-1) check to avoid them and gain 1 Clue token. If you fail, lose 1 Sanity and 1 Stamina as you flee!','Sneak -1');
INSERT INTO other VALUES (NULL,'There is nothing here but barren wastes. No encounter.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','This area is filled with discarded antiques from Earth. Most of it is junk, but some of it might be worth something. Gain $3.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','Those lands outside the time and space known to men strip king and peasant equally. Discard all of your items, except those for which you either discard a Clue token or pay $3.',NULL);
INSERT INTO other VALUES (NULL,'Time and space bend around you. Make a Luck (-1) check. If you pass, return to Arkham. If you fail, stay here next turn.','Luck -1');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','To pass the time you have been having a conversation with yourself out loud. You are alarmed when you respond to you own questions in a language you have never heard before. Make a Lore (-1) check to interpet what you just said. If you pass, gain 1 Spell. If you fail, lose 1 Sanity.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','Try as you might, you are too tired to go on. Stay here next turn.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','Water begins to flood your immediate environment! Make a Fight (-1) check to prevent yourself from being swept away by the waves. If you fail, choose any aquatic location, move there, and do not take an explored marker.','Fight -1');
INSERT INTO other VALUES (NULL,'Wedged beneath a fallen stone is a scroll. Draw 1 Spell.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','What luck! There''s a way home here that you almost overlooked. Return to Arkham.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','What was that? Lose 1 Sanity.',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','What was that!? Make a Sneak (+3) check or you will find out as you are devoured by it.','Sneak +3');
INSERT INTO other VALUES ('The Lurker at the Threshold','What''s that? Another Gate? Hurry! Make a Speed (-1) check. If you fail, you are lost in time and space. If you pass with 1 success, nothing happens. If you pass with 2 or more successes, return to Arkham.','Speed -1');
INSERT INTO other VALUES ('The Lurker at the Threshold','What''s that behind you!? A monster appears.',NULL);
INSERT INTO other VALUES ('Dunwich Horror','Yes! You think you have a use for this item. Draw 1 Common Item.',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','You approach a tunnel only to feel a terrible tromping shake the ground from below... and then an unearthly screech rends the sky. Make a Sneak (-1) check. If you pass, 1 monster appears! If you fail, 2 monsters appear!','Sneak -1');
INSERT INTO other VALUES (NULL,'You are beginning to understand the strange creatures here. Gain 1 Clue token.',NULL);
INSERT INTO other VALUES (NULL,'You are lost in a labyrinth of high walls. Pass a Lore (-1) check or stay here next turn.','Lore -1');
INSERT INTO other VALUES (NULL,'You are not safe here. A monster appears!',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','You are not safe here. A monster appears!',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You are suddenly plagued by a vision of yourself inside a cell at the asylum hallucinating a journey to another world. Make a Luck (+1) check. If you fail, move immediately to Arkham Asylum and draw a Madness card.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','You are unsure if you are back in Arkham or not. Make a Will (-2) check. If you succeed, return to Arkham. If not, lose 2 Sanity as the landscape twists and warps in a nightmarish way.','Will -2');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You can barely see anything in the dim lighting, but you can hear something large and threatening nearby. Make a Sneak (+0) check. If you fail, the creature pounces. Draw an Injury card.','Sneak +0');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','You can hear it breathing... make a Will (-1) check. If you fail, you scream in terror, giving yourself away. Lose 1 Sanity and 2 Stamina.','Will -1');
INSERT INTO other VALUES (NULL,'You come across a slaughtered creature. Pass a Luck (-1) check to claim a monster trophy from the cup (even if it is Endless) and gain 2 Clue tokens.','Luck -1');
INSERT INTO other VALUES (NULL,'You come across a sleeping horror with a tentacle draped across a small gold idol. Silence is of the essence as you attempt to gently ease the idol out from under the creature''s pseudopod. Make a Sneak (-1) check. If you pass, gain $3. If you fail, lose 2 Stamina.','Sneak -1');
INSERT INTO other VALUES ('Kingsport Horror','You come upon a cavern filled with human brains. If you were to eat them, maybe you could also consume the knowledge they contain! Make a Lore (-1) check. If you pass, you may lose Sanity to take Clue tokens, at a rate of 2 Sanity each.','Lore -1');
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','You discover a complex series of glass tubing, flasks, and beakers. You may choose to sample one of the chemicals flwoing through this array. If you do, make a Luck (-2) check. If you pass, the concoction strangely changes you. Gain 1 Skill. If you fail, lose 1 Stamina.','Luck -2');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You discover a dimensional rift, bleeding macabre energies into your home world. Choose 1 open rift. You must then either discard 3 Clue tokens and close the rift or move to the rift''s current location, without gaining an "explored" marker. If no rifts are open, return to Arkham.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You discover you are able to hear the thoughts of an individual in Arkham. Roll a die and consult the following table:1) These are not the thoughts of a human being. Lose 1 Sanity.2-3) The thoughts are preoccupied with trivial matters. No effect.4-5) You discover something vital! Gain 1 Clue token.6) These are thoughts of a powerful wizard. Gain 1 Spell.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','You encounter a stranger who looks like a much older version of yourself. You are told, "Press on, you will succeed." Gain 2 Sanity.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','You feel a powerful pulse of malevolent intelligence. It wants to tell you secrets. For each point of Sanity you sacrifice, you may gain 1 Clue token.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','You feel an outside intelligence trying to take over your body, replacing your identity with its own. You fight it off with great difficulty. Make a Will (-2) check. If you pass, you gain a specialized knowledge from that intelligence. Draw 1 Skill. If you fail, you lose part of yourself in the struggle. Discard all of your Clue tokens.','Will -2');
INSERT INTO other VALUES ('The Lurker at the Threshold','You find a $5 bill on the ground here, with no possible explanation for its presence. Gain $5.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','You find a fresh water source that replenishes you. Gain 1 Stamina.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You find a number of old barrels, lost from some bygone century. Make a Luck (-1) check. If you pass, you discover something worthwhile. Gain a Common Item. If you fail, the barrels'' rotten contents nauseate you. Lose 1 Stamina.','Luck -1');
INSERT INTO other VALUES (NULL,'You find a quiet spot to rest and recuperate. Gain 1 Stamina.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','You find a scattered pile of familiar objects, each one something you have lost at some point in your life. Some of them may prove usefull now. Make a Luck (-1) check. If you pass, you may look at the bottom of the Common Item deck and then draw 1 Common Item from either the top or the bottom of the deck.','Luck -1');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You find a sheltered area, a veritable oasis in this strange place. You may take the opportunity to rest. If you do, you are delayed and gain 1 Sanity and 1 Stamina.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','You find a small gem that you plan on selling when you get the chance. Gain $3.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','You find a tiny corner of placidity, and remain there for a moment. Gain 1 Stamina and 1 Sanity.',NULL);
INSERT INTO other VALUES (NULL,'You find some valuable items that you can sell back in Arkham. Gain $3.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You find something that looks to be valuable, broken into many small pieces. If you wish, draw a Unique Item and stay here next turn as you reassemble it.',NULL);
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','You find the body of a long-dead explorer. Make a Luck (-2) check. For each success, you may draw and keep one card from the Common Item deck.','Luck -2');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You find this place is corrosive to your belongings. Metal rusts, wood rots, and cloth grows thin. For each Common Item you have, roll a die. If the result is a 1, discard the item.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','You grasp at the thing, but sense that even if you are unable to hold it, the reaching itself will teach you. Make a Luck (-2) check. If you pass, draw a Unique Item. If you fail, take a Clue token.','Luck -2');
INSERT INTO other VALUES ('The King in Yellow','You hear the call of a hunting creature in the sky above. Pass a Sneak (-2) check or you become its prey and lose 1 Stamina.','Sneak -2');
INSERT INTO other VALUES ('Curse of the Dark Pharaoh','You inadvertently summon the Haunter of the Dark to carry you through the void. You must lose Sanity equal to your current Stamina, or Stamina equal to your current Sanity, but gain 2 Clue tokens for each monster in the Sky.',NULL);
INSERT INTO other VALUES ('The Lurker at the Threshold','You pass the night in animated conversation with an old man sucking on a clay pipe. When you awaken, the man is gone without a trace, but you do gain 1 Clue token from his wisdom.',NULL);
INSERT INTO other VALUES ('The King in Yellow','You pick up a chestnut, and it begins to writhe in your hands. Pass a Speed (-1) check to fling it away. If you fail, the grub inside bursts forth, grows to impossible size, and attacks you. A monster appears!','Speed -1');
INSERT INTO other VALUES ('Kingsport Horror','You pick up a shock-white feather from the cracked ground, sensing something strange about it. Keep this card. You may discard it to prevent any investigator from losing up to 3 Sanity or Stamina.',NULL);
INSERT INTO other VALUES (NULL,'You push yourself to the limit. Roll one die for each point of Stamina you have. Lose 1 Stamina for each die that does not roll a success. If you do not fall unconscious, gain 1 Clue token for each die that rolled a success.',NULL);
INSERT INTO other VALUES ('Kingsport Horror','You reach out and touch a great pillar of darkness, anchoring your lost allies. If there are any investigators lost in time and space, you return to Arkham and they are moved to the street location nearest you.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','You recognize an odd object tucked inside a bird''s nest. Make a Sneak (-2) check to remove the object without attracting the attention of any of the large birds nearby. If you pass, gain 1 Common Item.','Sneak -2');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You recognize this landscape from a painting you saw recently. Mkae a Lore (-2) check to remember the details of the artwork. If you pass you recall a strange object depicted and can find that location. Gain 1 Unique Item.','Lore -2');
INSERT INTO other VALUES ('Miskatonic Horror: Dunwich Horror component','You see a reflection of yourself and realize how much your experiences have changed you. You believe the knowledge you''ve gained is worth the sacrifices you''ve made. If your Sanity is at full, you may discard 3 Clue tokens  to be Blessed. Otherwise, if you are not at full Sanity, for each Clue token you discard, gain 1 Sanity',NULL);
INSERT INTO other VALUES (NULL,'You sleep, fitfully, and awaken to the sound of your own voice, chanting something. Make a Lore (-2) check. If you pass, you are able to retain what you are saying. Draw 1 Spell and gain 2 Clue tokens. If you fail, the chant attracts something unsavory. A monster appears!','Lore -2');
INSERT INTO other VALUES (NULL,'You stare into the face of madness. Roll 1 die for each point of Sanity you have. Lose 1 Sanity for each die that does not roll a success. If you do not go insane, gain 1 Clue token for each die that rolled a success.',NULL);
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','You suspect you would travel more quickly if you weren''t carrying so many things. Discard 1 item or you are delayed.',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','You take careful notes of all of your experiences. You are certain they will come in handy later. Gain 1 Clue token.',NULL);
INSERT INTO other VALUES ('The King in Yellow','You wrestle shadows for what seems like days, only to emerge into a plain of blinding light. Lose either 1 Stamina or 1 Sanity.',NULL);
INSERT INTO other VALUES (NULL,'You''ve completed your task, but now you must escape before the portal closes! Pass a Speed (-2) check to return to Arkham. If you fail, you are lost in time and space. In either event, you automatically close the gate you entered through.','Speed -2');
INSERT INTO other VALUES ('The Lurker at the Threshold','You''ve never seen nor experienced anything so awful. Roll four dice. For each die that is not a success, lose 1 Sanity or 1 Stamina (your choice).',NULL);
INSERT INTO other VALUES ('The Black Goat of the Woods','Your feet begin to sink into a repulsive goo. Pass a Fight (-2) check to pull yourself out. If you fail, you are sucked into the unknown and are lost in time and space.','Fight -2');
INSERT INTO other VALUES ('Kingsport Horror','Your focus alone will see you through times of confusion. Pass a Will (-2) check or you are delayed.','Will -2');
INSERT INTO other VALUES (NULL,'Your mind is flooded with knowledge. Make a Lore (-2) check. If you pass it, draw 1 Spell, but lose 1 Sanity.','Lore -2');
INSERT INTO other VALUES ('The Black Goat of the Woods','Your path ends at two identical doors. Make a Luck (+0) check. If you succeed, return to Arkham. If not, you are lost in time and space.','Luck +0');
INSERT INTO other VALUES ('Miskatonic Horror: Kingsport Horror component','Your terrible thirst has finally convinced you to try drinking some of the water here. Make a Luck (-1) check and consult the following chart:Successes:0) Lose 1 Stamina.1) No effect.2) Gain 1 Stamina.3+) Gain 1 Stamina and draw 1 Spell.','Luck -1');
INSERT INTO other VALUES ('Kingsport Horror','Your travels are endless, packed tight into the space of but a moment. Lose 1 Stamina.',NULL);
