CREATE TABLE yuggoth (
    `list_expansion` VARCHAR(45) CHARACTER SET utf8,
    `list_encounter` VARCHAR(773) CHARACTER SET utf8,
    `list_check` VARCHAR(16) CHARACTER SET utf8
);
INSERT INTO yuggoth VALUES ('Curse of the Dark Pharaoh','"Help me!" The voice comes from a cylinder containing a human brain! You may search the Skill deck for the Lore card. If you take it, you lose 2 Sanity.',NULL);
INSERT INTO yuggoth VALUES ('The King in Yellow','A dark creeping fungus flows randomly across the ground. Pass a Luck (-2) check or lose 2 Stamina and set your Speed slider to its lowest possible value.','Luck -2');
INSERT INTO yuggoth VALUES ('Dunwich Horror','A horrid monster appears!',NULL);
INSERT INTO yuggoth VALUES ('The Black Goat of the Woods','A horrid monster appears!',NULL);
INSERT INTO yuggoth VALUES ('Miskatonic Horror: Dunwich Horror component','A horrid monster appears!',NULL);
INSERT INTO yuggoth VALUES (NULL,'A monster appears from the darkness!',NULL);
INSERT INTO yuggoth VALUES (NULL,'A strange creature stares at you with burning eyes. It is as if its gaze were stealing your soul. Pass a Luck (-1) check or roll a die and subtract 2 from it (minimum 0), then lose that much Stamina and Sanity.','Luck -1');
INSERT INTO yuggoth VALUES ('Curse of the Dark Pharaoh','Abundance to the Black Goat of the Woods
You must immediately fight Shub-Niggurath! Since there is only one player in this combat, you need one success to remove a doom token. If you are out of monster trophies, you are devoured. If you defeat Shub-Niggurath, she retreats into the void and you may escape to Arkham immediately. The gate to Yuggoth is sealed behind you, and you may take it as a trophy.
If Shub-Niggurath is the Ancient One in play, do not fill up her doom track before this combat; also, successes allow you to temporarily flip over the doom tokens to their elder sign sides instead of removing them. Once the battle is over, regardless of the outcome, flip all of the tokens on Shub-Niggurath''s doom track back to their doom token side and continue play.',NULL);
INSERT INTO yuggoth VALUES (NULL,'An alien mind forces its way into your body. Pass a Luck (-2) check to guess a way to drive it out, gaining 2 Clue tokens in the process, or else stay here next turn, serving as its host body.','Luck -2');
INSERT INTO yuggoth VALUES ('Kingsport Horror','An offering to the green pyramid, their buzzing voices command, lest you be lost for all time. You may discard a Unique Item to return to Arkham. Otherwise, you must discard a Common Item, or else become lost in time and space.',NULL);
INSERT INTO yuggoth VALUES ('The King in Yellow','As you stare up at the unfamiliar sky, you hum a song that your mother used to sing to you, and it helps to hold the madness at bay. No encounter.',NULL);
INSERT INTO yuggoth VALUES (NULL,'Breathing hard, you stay huddled against the rock until the sounds of pursuit fade into the distance. No encounter.',NULL);
INSERT INTO yuggoth VALUES (NULL,'Exposure and fear weaken your mind. Pass a Will (-2) check or you must lose either 2 Spells of your choice or lose 2 Sanity.','Will -2');
INSERT INTO yuggoth VALUES (NULL,'Fear grabs you as the buzzing entities approach. Pass a Will (-1) check or lose 2 Sanity.','Will -1');
INSERT INTO yuggoth VALUES ('Curse of the Dark Pharaoh','Make a Lore (-1) check to realize that you have come upon the "shining trapezohedron," and utter the proper protective spell. If you fail, lose 1 Sanity and set your Will slider to the lowest possible number.','Lore -1');
INSERT INTO yuggoth VALUES ('Dunwich Horror','Pass a Luck (-2) check to avoid becoming lost in the icy, dark valleys that predominate here. If you fail, stay here next turn.','Luck -2');
INSERT INTO yuggoth VALUES (NULL,'Pass a Sneak (-1) check or the creatures capture and experiment on you. Lose half of your items, then immediately return to Arkham with no memory of the experiments.','Sneak -1');
INSERT INTO yuggoth VALUES ('Curse of the Dark Pharaoh','Scuttling surrounds you in the dark as the creatures attack. Lose 1 Stamina. Alternatively, you may light a torch to drive them back and lose no Stamina, but upon seeing them, your mind recoils, and you lose 2 Sanity.',NULL);
INSERT INTO yuggoth VALUES ('Innsmouth Horror','Several Mi-Go up ahead are working on a strange device. They are blocking your path, so you must either pretend to be a human slave or take the long way around.If you pretend to be a slave, make a Will (-2) check. If you pass, they are fooled by your act and you slip past, quietly pocketing an odd device as you do so. Draw 1 Unique Item and return to Arkham. If you fail, one of them shoots you with a strange ray-gun. You are lost in time and space.If you go around, pass a Luck (-1) check or a monster appears! Either way, you are delayed.','Will -2ORLuck -1');
INSERT INTO yuggoth VALUES ('The Black Goat of the Woods','Stumbling around in the dark, you tumble down a sheer cliff. Pass a Speed (-1) check to avoid losing 1 Common  or Unique Item of your choosing.','Speed -1');
INSERT INTO yuggoth VALUES ('Kingsport Horror','Such travel ''cross the stars, these strange fungi declare, is a service for which they would have good and valuable recompense. Discard a Unique Item worth $5 or more, or else you are lost in time and space.',NULL);
INSERT INTO yuggoth VALUES ('The Lurker at the Threshold','The buzzing speech of the natives echoes from nearby. Make a Sneak (-2) check to remain hidden. If you fail, the creatures find you. You wake up in St. Mary''s Hospital with no memory of your trip to Yuggoth; discard 2 Clue tokens.','Sneak -2');
INSERT INTO yuggoth VALUES (NULL,'The creature''s grip is like steel! Pass a Fight (-2) check to break free and escape. If you fail, the creature''s grip tightens with a sickening pop. You are lost in time and space.','Fight -2');
INSERT INTO yuggoth VALUES ('The Lurker at the Threshold','The creatures have terrible ray guns! Make a Speed (-1) [2] check to sprint for cover. If you fail, you are lost in time and space.','Speed -1 [2]');
INSERT INTO yuggoth VALUES ('Miskatonic Horror: Dunwich Horror component','The creatures indulge in experimental surgery to find out how adaptable the human mind is. Lose 2 Sanity. Then, if you''re still sane, draw 2 Spells. Choose one to keep and discard the other.',NULL);
INSERT INTO yuggoth VALUES (NULL,'The cylindered head mocks your hopes. "You''ll never return home!" it cackles. Pass a Will (-2) check or lose 2 Sanity.','Will -2');
INSERT INTO yuggoth VALUES ('Dunwich Horror','The heavy, fetid musk of the fungus drives you down towards unconsciousness. You must pass a Will (-2) check or you are lost in time and space.','Will -2');
INSERT INTO yuggoth VALUES ('Dunwich Horror','The light of the stars is gathered here, on this distant planet. Curious, you bathe yourself in it and find yourself healed and transfigured. Either restore your Stamina to its maximum value or discard one of your Injury cards.',NULL);
INSERT INTO yuggoth VALUES ('The Black Goat of the Woods','The Mi-Go abruptly abandon their pursuit of you. Something had scared them off. You don''t plan on waiting around to find out what it is. Pass a Speed (+1) check or be devoured.','Speed +1');
INSERT INTO yuggoth VALUES ('The King in Yellow','The mi-go have transported you to Yuggoth! Pass a Lore (+0) check to gain 1 Clue token but lose 1 Sanity. If you fail, nothing happens.','Lore +0');
INSERT INTO yuggoth VALUES ('Curse of the Dark Pharaoh','The Mi-Go offer immortality... of a sort. If you accept, you are devoured, except that you keep all of your Spells, Skills, and Clue tokens, to be used with your next investigator. Then close and seal a gate to Yuggoth, if one is open.',NULL);
INSERT INTO yuggoth VALUES ('The King in Yellow','The mi-go offer to take your brain on a journey to the far reaches of space... but your body will have to stay here. If you accept, gain 3 Clue tokens but you are delayed.',NULL);
INSERT INTO yuggoth VALUES ('The King in Yellow','The mi-go question you about the Dynasty of America, ruled by "Emperor Castaigne." You must lose 2 Sanity or be delayed.',NULL);
INSERT INTO yuggoth VALUES ('Miskatonic Horror: Kingsport Horror component','The mi-go swarm up out of a hole in the black ground. It seems to be a mine of some kind, as they are carrying large bins of metallic ore. One of them has discovered something strange buried in the ground. You may make a Sneak (-2) check to steal it. If you pass, gain a Unique Item, but if you fail, lose 1 Stamina and you are delayed.','Sneak -2');
INSERT INTO yuggoth VALUES ('The Lurker at the Threshold','The natives capture you for medical experiments! Make a ''Luck (-3) check to escape. If you fail, exchange your current Stamina and Sanity totals (any Stamina or Sanity in excess of your maximums are lost).','Luck -3');
INSERT INTO yuggoth VALUES ('Kingsport Horror','The puzzle-shape consumes you. Make a Lore (-1) check. If you succeed, draw a Unique Item. If you fail, you must discard a Spell, a Common Item, a Unique Item, and 2 Clue tokens, or else you are devoured.','Lore -1');
INSERT INTO yuggoth VALUES ('Innsmouth Horror','The spores that the alien creatures implanted beneath your skin are changing you...Return to Arkham, but keep this card. Each time a new gate opens, draw 1 Spell and place a Clue token on this card.If there are 1-3 Clues on this card, you gain a +1 bonus to all Fight and Lore checks.If there are 4 Clues, treat all Sanity costs for spells as 0.If there are 5 Clues on this card, you are devoured.',NULL);
INSERT INTO yuggoth VALUES (NULL,'The stone creature pursues you. Pass a Speed (-1) check to escape with the statue, gaining $5 and 2 Clue tokens. If you fail, the creature smashes you off the cliff. You are lost in time and space.','Speed -1');
INSERT INTO yuggoth VALUES ('Kingsport Horror','The strange fungi pour their knowledge into the brain-case where your mind is imprisoned. Take 2 Clue tokens but you are reduced to 1 Sanity.',NULL);
INSERT INTO yuggoth VALUES ('The Black Goat of the Woods','The sun is so far away. Everything seems hopeless. Lose 1 Sanity.',NULL);
INSERT INTO yuggoth VALUES ('The Lurker at the Threshold','The three moons confound you. Make a Will (-2) check or lose 2 Sanity.','Will -2');
INSERT INTO yuggoth VALUES ('The Lurker at the Threshold','This alien city seems recently abandoned. Make a Luck (-1) [2] check to find a Unique Item the former inhabitants left behind. If you fail, you discover why they abandoned the city, instead. Lose 2 Sanity.','Luck -1 [2]');
INSERT INTO yuggoth VALUES ('The Lurker at the Threshold','What are these strange disks? If you pass a Luck (-1) check, they are tok''l coins worth $3! If you fail, they are hazardous Mi-Go artifacts; lose 1 Stamina.','Luck -1');
INSERT INTO yuggoth VALUES ('Curse of the Dark Pharaoh','You are swept away by a river of some dark substance. Make a Fight (-1) check or you are lost in time and space.','Fight -1');
INSERT INTO yuggoth VALUES ('The Black Goat of the Woods','You might be smarter than the Mi-Go realize. They''ve left you alone with some alien documents. Pass a Lore (-2) check to gain a Spell.','Lore -2');
INSERT INTO yuggoth VALUES ('The King in Yellow','You open a door, and quickly discover that the atmosphere outside cannot sustain human life! Pass a Speed (+0) check to seal the door again or lose 3 Stamina.','Speed +0');
INSERT INTO yuggoth VALUES ('Curse of the Dark Pharaoh','You peer through a strange machine of glass and stone, its lenses pointed towrds the dark, sunless sky. There, impossibly far away, you behold the Earth. Gain 2 Clue tokens, but make a Will (-3) check or lose 1 Sanity.','Will -3');
INSERT INTO yuggoth VALUES ('The Black Goat of the Woods','You see the faint glimmer of an object poised on a precipice. Pass a Fight (-2) check to climb your way out to it safely. If you succeed, draw 1 Unique Item. If you fail, the precipice crumbles and you are lost in time and space.','Fight -2');
INSERT INTO yuggoth VALUES ('Miskatonic Horror: Kingsport Horror component','You watch the creatures operate a device which seems to transport things to and from Earth. Make a Lore (-2) check to learn how to operate it. If you pass, return to Arkham.','Lore -2');
INSERT INTO yuggoth VALUES (NULL,'You''re dizzy from the strange ray. Pass a Will (-2) check or lose 1 item of your choice.','Will -2');
INSERT INTO yuggoth VALUES (NULL,'Your only hope is to steal a byakhee and some space mead! Pass a Sneak (-2) check to escape. Return to Arkham and gain 2 Clue tokens. If you fail, you are lost in time and space.','Sneak -2');
