CREATE TABLE relationships (
    `list_name` VARCHAR(29) CHARACTER SET utf8,
    `list_expansion` VARCHAR(27) CHARACTER SET utf8,
    `list_image` VARCHAR(89) CHARACTER SET utf8,
    `list_description` VARCHAR(338) CHARACTER SET utf8
);
INSERT INTO relationships VALUES ('The Best of Friends','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=TheBestOfFriendsRelationship.png','If you or your partner are in the same neighborhood, either of you may exhaust this card before making a check to gain +1 on that check. If the Ancient One has awakened, this card may not be used.');
INSERT INTO relationships VALUES ('Business Associates','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=BusinessAssociatesRelationship.png','After the initial setup, any time either you or your partner gains $1 or more (from any game effect other than this card), the other gains $1.');
INSERT INTO relationships VALUES ('Collectors','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=CollectorsRelationship.png','After the initial setup, any time either you or your partner gains 1 or more Common Items or Unique Items (from any game effect other than this card), the other may draw a random card of the same type and purchase it for the list price.');
INSERT INTO relationships VALUES ('Courageous Inspirations','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=CourageousInspirationsRelationship.png','Either you or your partner may exhaust this card before making a Horror check to gain a +1 to the check.');
INSERT INTO relationships VALUES ('Fellow Travelers','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=FellowTravelersRelationship.png','Either you or your partner may exhaust this card to gain 1 extra movement point.');
INSERT INTO relationships VALUES ('Friendly Rivals','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=FriendlyRivalsRelationship.png','Between you and your partner, the investigator with fewer monster trophies gains a +1 on Combat checks, and the investigator with fewer Gate trophies gains a +1 on Fight or Lore checks to close Gates. There is no effect in the case of ties.');
INSERT INTO relationships VALUES ('Hunters','Miskatonic Horror',NULL,'When you or your partner are in the same neighborhood, either of you may exhaust this card before making a Combat check against a monster to reduce its toughness by 1 (to a minimum of 1) during this Combat check.');
INSERT INTO relationships VALUES ('I''ll Vouch for My Friend','Miskatonic Horror',NULL,'After the initial setup, each time you or your partner gains a Bank Loan, Retainer, Silver Twilight Lodge Membership, Sheldon Gang Membership, Rail Pass, or "One of the Thousand" Cult Membership, the other may choose to take a card of the same type if he does not already have one.');
INSERT INTO relationships VALUES ('Keen Analysts','Miskatonic Horror',NULL,'If you or your partner are in the same location or street area and you both have at least 2 Clue tokens, either of you may exhaust this card to gain 1 Clue token.');
INSERT INTO relationships VALUES ('Members of the Book Club','Miskatonic Horror',NULL,'Anytime either you or your partner attempts to use a Tome (other than as a result of this card), the other may immediately attempt to use the same Tome, even if it has been exhausted or discarded.');
INSERT INTO relationships VALUES ('Mystic Knights','Miskatonic Horror',NULL,'Any time either you or your partner passes a Spell check with 2 or more successes, the casting investigator may exhaust this card. If he does so, you and your partner each gain 1 Sanity.');
INSERT INTO relationships VALUES ('Practitioners of the Art','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=PracticionersOfTheArtRelationship.png','Whenever you or your partner casts a Spell, either or both of you may contribute toward paying the Sanity cost.
Either you or your partner may exhaust this card before making a Spell check to gain a +1 to the check.');
INSERT INTO relationships VALUES ('Skullcrackers','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=SkullcrackersRelationship.png','Either you or your partner may exhaust this card before making a Combat check to gain a +1 to the check.');
INSERT INTO relationships VALUES ('Socially Connected','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=SociallyConnectedRelationship.png','After the initial setup, any time either you or your partner gains an Ally (from any game effect other than this card), the other draws an Ally at random from the Ally deck. If he currently has no Allies, he keeps it. If he does have one or more Allies, he keeps it and then chooses one of his Allies to reshuffle back into the Ally deck.');
INSERT INTO relationships VALUES ('Students of the Arcane','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=StudentsOfTheArcaneRelationship.png','After the initial setup, any time either you or your partner gains a Spell (from any game effect other than this card),  the other draws a random Spell from the Spell deck.');
INSERT INTO relationships VALUES ('Survivors','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=SurvivorsRelationship.png','Either you or your partner may exhaust this card before making an Evade check to gain a +1 to the check.');
INSERT INTO relationships VALUES ('Take Me Instead','Miskatonic Horror',NULL,'While you and your partner are in the same location or street area, anytime either of you loses Sanity, loses Stamina, or is arrested, Cursed, or delayed, the other may choose to suffer the effects instead. If the Ancient One has been awakened, this card may not be used.');
INSERT INTO relationships VALUES ('World Ain''t Big Enough for Us','The Lurker at the Threshold','/wiki/index.php?title=Special%3AUpload&wpDestFile=WorldAintBigEnoughForUsRelationship.png','If you or your partner is in an Other World location, either of you may exhaust this card before making a check to gain +1 on that check. If the Ancient One has awakened, this card may not be used.');
