CREATE TABLE devil_reef_encounters (
    `list_encounter` VARCHAR(352) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(13) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO devil_reef_encounters VALUES ('"You look a mite lost!" A fisherman has found you. If you are willing to spend $3 or discard an item in exchange, he''s willing to offer passage off this rock. If you accept the offer, move to any aquatic location aand have an encounter there.',NULL,'Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('A boat approaches, but the sailors don''t want to risk being smashed onto the reef by the waves. They shout at you to swim to them. If you do, make a Fight (-2) check. If you pass, move to Falcon Point and have an encounter there. If you fail, lose 1 Stamina swimming back to the reef.','Fight -2','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('A boat approaches... but who''s on it? Make a Luck (-2) check. If you pass, friendly fishermen offer you a lift to Falcon Point. If you accept, move there and immediately have an encounter. If you fail, the robed figures beat you and rob you. Lose 1 Stamina, 1 Sanity, and 1 item of your choice.','Luck -2','Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('A fashionably dressed woman tells you that the boat she hired has left her here, but it''s worth it for the adventure. She introduces herself as Erica Carlyle and seems intrigued by your tales of mystery. If you have $3 or less, she agrees to join you and help pay your way. Take her Ally card or, if it is not available, gain a Retainer card.',NULL,'Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('A glimpse of something shining in the sun catches your eye. A golden brooch has been left behind here. Gain $3.',NULL,'Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('A well-dressed man is standing on the reef gazing out at the sea. He tells you that he''s heard there''s something miraculous under the surface. If you give him 2 of your Spells (discarding them), he introduces himself as Erich Weiss; take his Ally card if it''s available. If it''s not available, he shows you a trick instead and you gain 2 Clue tokens',NULL,'Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('A young man from Falcon Point has been snooping out here, but now finds himself struggling to stay afloat just off the reef. Make a  Fight (+0) check to pull him out of the water. If successful, gain 1 Sanity as you drag him to safety. If not, lose 2 Sanity as the man disappears beneath the waves.','Fight +0','Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('After a long and terrifying night, the sunrise is a welcome sight. Gain 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('An empty rowboat drifts past. Wondering at its missing occupants, you decide that you have to act now. You may move to Falcon Point and immediately have an encounter there.',NULL,'Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('An engraved golden disk is wedged among the black rocks. Make a Lore (-1) check to recognize the runes carved into it. If you pass, you leave it alone and don''t touch it. If you fail, the moment your hand touches it, a jolt of energy parlyses you and you fall into the water. Lose 1 Sanity, move to Y''ha-nthlei, and immediately have an encounter there.','Lore -1','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('As far as the eye can see in any direction, the water is churning with large, fish-like creatures. Make a Will (+0) [2] check to resist a state of pure panic. If you fail, lose 2 Sanity. If you pass, gain 2 Clue tokens as you watch them head out to see.','Will (+0) [2]','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('High winds and higher waves buffet you as you struggle to cling to the reef. You are delayed.',NULL,'Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('Horrible man-shaped forms in the water are making a trade with the dark figures standing on the reef. You may attempt a Fight (-1) check to drive them off. If you pass, gain 1 Unique Item. If you fail, lose 1 Stamina.','Fight -1','Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('Seeing a wooden box drift by, you seize your chance and cling to it. Only halfway to shore do you realize that the box is a coffin. Move to Falcon Point. Once ashore, you may look inside. If you do, lose 2 Sanity and draw 1 Unique item.',NULL,'Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('Several shuffling figures crawl out of the water near you. Make a Sneak (-1) check  to avoid their notice. If you fail, they spot you and drag you beneath the waves. Lose 1 Stamina, move to Y''ha-nthlei, and have an encounter there.','Sneak -1','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('Sharp claws dig into your skin and pull you down into the water. Make a Fight (+1) [2] check to free yourself. If you pass, you make it back to the reef safe and sound. If you fail, you suffered grievious harm in the process. Draw an Injury card.','Fight +1 [2]','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('Strange symbols are carved into the black surface of the reef. Pass a Lore (-2) check to gain a Spell as you examine them.','Lore -2','Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('The stars above the water appear larger than you''ve ever seen them before. The skyscape seems strangely alien and threatening. Lose 1 Sanity.',NULL,'Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('The waves crashing against the reef are enormous. Make a Fight (-1) check to keep from being crushed by them. If you fail, lose 1 Stamina and choose 1 item to discard.','Fight -1','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('The wind here is strong enough to pick you up and throw you out to sea. Make a Fight (-1) check to keep youself on the ground. If you fail, lose 1 Stamina, move to Y''ha-nthlei, and have an encounter there.','Fight -1','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('These rocks are slick with slime and seawater. Make a Speed (-1) check to keep your balance. If you fail, lose 1 Stamina, move to Y''ha-nthlei, and have an encounter there.','Speed -1','Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('You are convinced you can see glints of gold beneath the water''s surface. You feel compelled to dive in after it. Make a Will (-1) check to recognize this as a hallucination. If you fail, lose 1 Sanity, move to Y''ha-nthlei, and have an encounter there.','Will -1','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('You can hear the engine of a boat passing. You shout to attract their attention.Make a Luck (-2) check. If you pass, you are rescued by federal agents. You may spend 1 Clue token to place it on any space on the Feds Raid Innsmouth track. Then move to Falcon Point and immediately have an encounter there. If you fail, lose 1 Sanity.','Luck -2','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('You come across a deserted boat. Make a Luck (+0) check. If you succeed, you may travel to any aquatic location and have an encounter there. If you fail, the boat was abandoned for a reason. You sink beneath the waves to Y''ha-nthlei. Move there and immediately have an encounter.','Luck +0','Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('You come across a strange monolith, and a vast shape disturbs the water nearby. If Father Dagon or Mother Hydra are Heralds this game, you must pass a Luck (-1) check or be devoured. In any event, if you survive, gain 2 Clue tokens.','Luck -1','Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('You fear you won''t survive the night if you can''t start a fire, but you''ll need to burn something. If you discard an item, gain 1 Sanity from the warmth. If you don''t, lose 1 Stamina from the cold.',NULL,'Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('You find an old bit of rope leading from the reef to somewhere under the water. Pulling it, you can tell something heavy is on the other side. Make a Luck (-2) check. If you pass, you eventually pull up an object wrapped up in oiled canvas. Gain a Unique Item. If you fail, the rope breaks and whatever it was attached to sinks.','Luck -2','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('You find the body of someone who was left handcuffed on the reef. Make a Will (-2) check. If you pass, you discover the man was still clutching something in his hands. Gain 1 Unique Item. If you fail, lose 1 Sanity.','Will -2','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('You find the wrecked remains of a small rowboat. You can see wide claw marks and large fish scales throughout the debris. Gain 1 Clue token and lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('You find yourself compelled to leap into the water. Draw one Innsmouth Look card.',NULL,'Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('You hear a distant chanting being carried on the wind. The words are strange and the voices are inhuman. Make a Lore (-2) check. If you pass, you are able to find a menaing in the words. Gain 1 Spell. If you fail, the sound chills you to your bones. Lose 1 Sanity.','Lore -2','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('You hide in a hollow of the rock to eavesdrop on the horrible croaking conversation of the Innsmouth folk and their strange allies. Pass a Sneak (-2) check to gain 2 Clue tokens.','Sneak -2','Innsmouth Horror');
INSERT INTO devil_reef_encounters VALUES ('You see a small boat carrying a few fishermen approaching the reef. In the water, you see dark silhouettes swimming quickly toward the boat. Make a Speed (-2) check to warn the men in time. If you pass, they manage to escape back toward Innsmouth. Gain 1 Sanity. If you fail, lose 1 Sanity as you see the men pulled into the sea.','Speed -2','Miskatonic Horror');
INSERT INTO devil_reef_encounters VALUES ('You spend the entire night out on the reef shivering but unharmed. Nothing happens.',NULL,'Miskatonic Horror');
