CREATE TABLE esoteric_order_of_dagon_encounters (
    `list_encounter` VARCHAR(397) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(11) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('"Do you seek the blessing of Dagon?" If you do, draw two Innsmouth Look cards and become Blessed.',NULL,'Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('"Do you seek the blessing of Dagon?" If you do, draw two Innsmouth Look cards and become Blessed.',NULL,'Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('"Do you seek the blessing of Dagon?" If you do, draw 2 Innsmouth Look cards and become Blessed.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('"Do you seek the blessing of Dagon?" If you do, draw 2 Innsmouth Look cards and become Blessed.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('"Do you seek the blessing of Dagon?" If you do, draw 2 Innsmouth Look cards and become Blessed.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('"Do you seek the blessing of Dagon?" If you do, draw 2 Innsmouth Look cards and become Blessed.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('A gate opens suddenly and pulls you into a strange landscape. Move immediately to Y''ha-nthlei and have an encounter there.',NULL,'Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('A locked cabinet seems to hold several antique, water-damaged texts. Make a Sneak (-2) check to pick the lock. If you pass, search the Unique Item deck and take the first Tome you find.','Sneak -2','Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('A series of primitive murals on the wall tell the story of an underwater city and the fish-like creatures that dwell there. The sight of them makes you very uneasy. Gain 2 Clue tokens and lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('Accidentally, you find yourself face to face with the altar of Dagon. You are Cursed.',NULL,'Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('Although you can''t tell from where, the Hall is filled with the sound of chanting. Lose 1 Sanity.',NULL,'Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('An odd, well-dressed man from overseas is examining the exterior of the Order. If you have any Exhibit Items or your Will is 2 or lower, he tells you it''s not safe here and introduces himself as Dr. Ali Kafour. Take his Ally card or, if it is not available, listen to him opine about similarities in the legends of island cultures and gain 2 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('At key points throughout this building are small plaques with strange symbols on them. If you have a "One of the Thousand" Cult Membership, gain 3 Clue tokens. If you do not have a "One of the Thusand" Cult Membership, make a Lore (-1) check. Gain 1 Clue token if you pass.','Lore -1','Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('Eavesdropping, you hear the priest speaking to his congregation. You are shocked when he mentions you by name and there is an angry, croaking cry from the others. Add 1 uprising token to the Deep Ones Rising track.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('From outside, you can hear the congregation engaged in a loud ritual honoring Dagon. As horrible as it is, the sound exhilarates you and feeds on your weaknesses. Gain 1 Stamina. Then, if you have an Injury or Madness card, add an uprising token to the Deep Ones Rising track and you are Blessed.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('Hissing and croaking, the barely-human congregation surrounds you. If you have an Elder Sign card, you may discard it to drive them back and seal this location. If not, you lose 1 Stamina and 1 Sanity and are moved to the street.',NULL,'Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('In the entryway are several photos of important figures in the history of the Order. You notice one with a strong familial resemblance to yourself. Draw 1 Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('Mingling with the congregation proves easier than you thought it would. Draw one Innsmouth Look card and make a Sneak (+0) check. If you pass, gain 2 Clue tokens.','Sneak +0','Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('Pass a Luck (-2) check to find a small amulet that seems out of place. If you take it, you are Blessed, but must move to the street and add one uprising token to the Deep Ones Rising track as one of the worshippers spots you and shouts an alarm. If you leave it, nothing happens.','Luck -2','Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('Passing by a mirror, you are startled to see yourself wearing a mask. You feel terrified to take the mask off. If you leave it on, lose 1 Sanity. If you take it off, draw 1 Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('The door to the basement seems unattended. You may attempt a Sneak (-2) check to try to investigate. If you pass, you find your way to the worship area and draw 1 Unique Item. If not, lose 1 Stamina and move to the street, as you are escorted outside by robed figures.','Sneak -2','Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('The Head of the Order, Robert Marsh, has caught you snooping around! Make a Will (-1) check. If you pass, you endure the encounter unharmed. If not, you are Cursed.','Will -1','Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('The members of the order have identified you as an outsider! Make a Speed (+0) check. If you pass, you move to the streets before you are caught. If you fail, lose 2 Stamina.','Speed +0','Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('The people in the building regard you strangely. If you are Blessed, they hiss and flee from you, leaving a Unique Item behind. If you are Cursed, they welcome you as one of their own. Draw one Innsmouth Look card.',NULL,'Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('The priest''s back is turned! Now''s your chance! Make a Speed (-1) check. If you pass, gain 2 Clue tokens. If you fail, you are moved to the street.','Speed -1','Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('You accidentally bump into a basin of water, dumping it all over yourself. You feel a strange acidic burn on your skin. Make a Fight (-1) check to resist the effects of this liquid. If you fail, draw a Corruption card.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('You are invited to take the first Oath of Dagon. If you refuse, lose 1 Stamina and move to the street. If you accept, lose 2 Sanity and make a Lore (-1) check, gaining a Clue token for each success.','Lore -1','Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('You believe you are alone in the building, but then you hear the sound of something large moving around. Make a Will (-2) check to avoid panicking. If you pass, gain 2 Clue tokens as you look around. If you fail, move to the streets.','Will -2','Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('You catch a glimpse of a tall, robed figure wearing an unearthly gold tiara. Something about the figure haunts you, but you try to block it from your mind... Pass a Will (+1) check or lose 1 Sanity and gain 1 Clue token.','Will +1','Innsmouth Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('You force yourself to approach the alter of Dagon, despite your misgivings. You see that someone had tried to carve a warding symbol into the stone but did not manage to finish. Make a Lore (-1) [2] check. If you pass, you know how to complete the symbol. Search the Unique Item deck and take an Elder Sign card if one is available. If it is not available or if you fail the check, you are Cursed.','Lore -1 [2]','Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('You can hear terrible sounds inside the Order, including many angry inhuman voices. Move to the streets and lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('You realize too late that you''ve walked into a trap. A horrifying monster appears!',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('You realize too late that you''ve walked into a trap. A horrifying monster appears!',NULL,'Miskatonic Horror');
INSERT INTO esoteric_order_of_dagon_encounters VALUES ('You see a priest glaring angrily at the Order''s building. If you are Cursed or either your Stamina or Sanity is 2 or lower, he introduces himself as Father Iwanicki, and says, "This place is abhorrent and you are righteous to stand against it." Take his Ally card or, if it is not available, you may search the Unique Item deck for the Holy Water card and take it.',NULL,'Miskatonic Horror');
