CREATE TABLE falcon_point_encounters (
    `list_encounter` VARCHAR(324) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(11) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO falcon_point_encounters VALUES ('"Fish teem in the waters past Devil Reef, but off Falcon Point? Barely any!" The old man spits. Pass a Will (-1) check to keep him talking and gain 1 Clue token.','Will -1','Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('"Weather''s changin''," say an old salt. Draw Mythos cards until you find an Environment (Weather) card. Place that card directly into play, ignoring the gate and monster movement information on that card. Discard the other Mythos cards you have drawn.',NULL,'Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('A boat is about to set out with a number of people trying to get out of Innsmouth. The sailors insist their passengers are carrying too much cargo. In a panic, the passengers try to sell it quickly for a discount. Draw 2 Common Item cards. You may purchase 1 for $1 less than its list price Discard any items not purchased.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('A bunch of fishermen risked a trip out to Devil Reef and have caught more fish than they would have imagined. If you wish to help them unload their catch from the boat, you are delayed. But as you help them, you find they''ve caught something more than fish. Gain 1 Unique Item.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('A federal agent is questioning people down by the shore. Frustrated, he tells you that he needs some solid proof before he can do anything. You may discard 5 [[toughness] worth of monster trophies or a gate trophy. If you do, gain 2 Clue tokens that you must spend to place on any 2 spaces of the Feds Raid Innsmouth track.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('A few shady figures are hanging out around Falcon Point at night. Pass a Fight (-1) check or lose all of your money. If you fail the check and have no money, choose 1 item to discard instead.','Fight -1','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('A group of fishermen are staring at the water looking worried. "Not safe to be on Falcon Point tonight." Move to the streets.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('A kindly fisherman offers you a ride to any aquatic location, where you have an encounter.',NULL,'Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('A local fisherman has left his boat just for a second. Pass a Sneak (-1) check to sneak aboard and pilot yourself to the aquatic location of your choice and have an encounter there.','Sneak -1','Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('A message in a bottle from someone trapped on Devil Reef washes up to shore. Gain 1 Clue token.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('A particularly old sailor takes great delight in teaching you old seafaring superstitions. Make a Luck (-2) check. If you pass, one of his tricks is much more effective than you would have imagined. Gain 1 Spell.','Luck -2','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('A pile of rocks seem too neatly stacked, as if done so by a human. Make a Fight (-2) check. If you pass you manage to unbury a hidden collection of strange golden jewels. Gain $3.','Fight -2','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('An old man is trying to sell trinkets that he''s found on the beach. Draw the top three cards from the Common Item deck. Each costs $2 more than its listed price. You may purchase as many of those three items as you wish and discard the rest.',NULL,'Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('Gazing at Devil Reef on the horizon, you are disturbed by the strange hopping of many silhouetted figures. Lose 1 Sanity.',NULL,'Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('One of the fishermen has had too much to drink and is muttering to himself about monsters in the water. If you spend the time to take care of him,  yo are delayed. If you do so, he tells you more and more of his experiences on the sea. Make a Lore (-1) check and gain 1 Clue token for each success.','Lore -1','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('One of the fishermen tells you it''s a dangerous business you''ve gotten mixed up in and he offers to sell you something to help. You may spend $3 to search the Common Item deck and take the first Weapon you find.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('People have been disappearing off the coast. If you have 3 or more Clue tokens, you''re fairly certain you can explain what''s going on, and the fishermen are willing to help however they can. You may move to any aquatic location. If you do, immediately have an encounter there.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('Sailors from all over the world are at Falcon Point tonight. The many different languages are difficult to interpret but the wide variety of stories provide much information. Make a Lore (-1) [2] check. If you pass, gain 4 Clue tokens.','Lore -1 [2]','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('Several strangely shaped footprints lead from the waterline into Innsmouth. Gain 1 Clue token.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('Something about the water here terrifies you in a completely irrational way. If you have a Madness card or if your Sanity is currently 2 or less, move to the streets.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('Talking with the locals, you hear the curious tale of Enoch Conger, a local man who once claimed to have caught a mermaid. If you pass a Will (-2) check or discard a Whiskey card, you hear the more disturbing version of the story, which ends with webbed footprints leading into the sea. Gain 3 Clue tokens and lose 1 Sanity.','Will -2','Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('The cold winds off the ocean are taking a toll on your health. Pass a Will (-1) check or lose 1 Stamina.','Will -1','Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('The fishermen at the tavern are happy to tell some tales, provided you''re picking up the tab. You may discard a Whiskey card or spend $5 to gain 2 Clue tokens.',NULL,'Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('The fishermen prove to be friendly and raucus. Gain 2 Sanity but lose 1 Stamina as they keep you awake all night with their songs and stories.',NULL,'Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('The sailors warned you not to ask too many question. Make a Will (+0) check and gain 1 Clue token for each success. If you gained 3 or more Clue tokens, add 1 Uprising token to the Deep Ones Rising track]].','Will +0','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('Wading out into the water, your feet feel something metallic beneath them. You discover a handful of gold coins! Gain $2. Then make a Luck (+0) check. If you fail, you are Cursed.','Luck +0','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('Walking along the beach, you find an old crate that has be washed ashore. If you decide to open it, make a Luck (-1) check. If you pass, gain 1 Common Item. If you fail, you are delayed, and the contents of the crate prove worthless.','Luck -1','Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('You don''t know where that boa is going, but you have an opportunity to jump aboard. Make a Sneak (+0) check. If you pass, move to the North Point Lighthouse and have an encounter there.','Sneak +0','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('You find a footlocker washed up on the shore. Make a Luck (-1) check as you open it and consult the chart below:Successes:0) The aquatic horror within is still alive! With a fishy stench and a revolting aspect, it oozes into the water and vanishes. Lose 1 Sanity.1-2) Gain a Common Item.3+) Gain $5.','Luck -1','Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('You negotiate with a salty old fisherman to get word to the outside. Spend $4 to gain a Clue token and place it on the space of your choice on the Feds Raid Innsmouth track.',NULL,'Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('You see the constables leading someone whose face is covered with a black bag down to the water. While they''re preparing their boat, you may make a Sneak (-1) check to release their prisoner. If you pass, gain 2 Sanity. If you fail, you are arrested and taken to the Innsmouth Jail.','Sneak -1','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('You see the debris of some wrecked boat floating in the water. Make a Luck (-2) check. If you pass, you spot something useful amid the splintered wood and torn canvas. Gain 1 Common Item.','Luck -2','Miskatonic Horror');
INSERT INTO falcon_point_encounters VALUES ('You''re conversing with some fishermen down by the water, your back to the waves, when their eyes go wide with fright and they begin to flee. Make a Speed (-1) check to follow them, else strong and rubbery arms grab you from behind and drag you out to Devil Reef. Move there and immediately have an encounter.','Speed -1','Innsmouth Horror');
INSERT INTO falcon_point_encounters VALUES ('You''ve accepted a fisherman''s offer of a boat ride, but in the middle of the trip, the craft suddenly capsizes! Pass a Fight (-2) check to swim safely to shore, or be delayed.','Fight -2','Innsmouth Horror');
