CREATE TABLE gilman_house_hotel_encounters (
    `list_encounter` VARCHAR(413) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO gilman_house_hotel_encounters VALUES ('"Oh dear," remarks the desk clerk, with a slight smile and a shake of her head. "Someone must have taken your bag by mistake. We''ll try to get that cleared up as soon as possible." Discard 1 Common or Unique Item of your choice.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('"Oh, no sir. The bus won''t be leaving today — mechanical difficulties. You''ll have to spend the night." Do they know that you know? A sleepless night robs you of 1 Sanity.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('A suitcase that doesn''t belong to you is underneath your bed. Make a Luck (-1) check. If you pass, gain 1 Unique Item. If you fail, the case is filled with old, blood-stained clothes. Lose 1 Sanity.','Luck -1','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Another traveller starts up a cheery conversation with you. Gain 1 Sanity.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('As you sleep, you dream of vast underwater spaces filled with strange, horrific creatures. Draw one Innsmouth Look card.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Before going to sleep, you decide to barricade the door with some of the room''s furniture, just to be safe. Pass a Fight (-1) check or lose 1 Stamina in the process.','FIght -1','Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Despite all the horrible stories you''ve heard, the desk clerk seems genuinely pleased to see you. "Welcome to Innsmouth," he says. "Welcome home." Draw two Innsmouth Look cards.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('During the night, you have a dream of the Dark Pharaoh in ancient Egypt. You learn much by observing him. Gain 1 Spell and then make a Will (+1) check. If you fail, reduce your maximum Sanity by 1.','Will +1','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('From your window, you spend the day watching the people of Innsmouth going about their business. Make a Lore (-1) check. If you pass, you quickly notice some odd behaviors. Gain 2 Clue tokens. If you fail, you are delayed as you spend all day watching, without noticing anything.','Lore -1','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Heavy footsteps come charging up the stairs towards your room during the night. Pass a Luck (-1) check to climb down the drainpipe on the outside of the building and move to the street. If you fail, you are arrested by Chief Constable Andrew Martin for unclear reasons and taken to Innsmouth Jail.','Luck -1','Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('If Velma''s Gratitude is facedown, you find Velma waiting for the bus back to Arkham. A couple big locals are looking at her threateningly and blocking her from getting out to the bus. If your current Fight is at least 4, you may draw 1 Injury to get them out of her way. If you do so, turn Velma''s Gratitude faceup. "I can''t thank you enough. You and your friends can eat at the diner for free whenever you like."',NULL,'Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('In the middle of the night, there''s too many heavy footsteps and scraping noises to sleep. Make a Will (-1) check to see if you can doze off. If you fail, you need to get some night air to relax. Move to the streets.','Will -1','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('In the middle of the night, you hear the sounds of violent fighting in the room next to yours. Make a Speed (-1) check. If you pass, you get next door in time to see a group of thugs surrounding a guest. They run away at the sight of you. If you fail, lose 1 Sanity when you find nothing but broken furniture.','Speed -1','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Joe Sargent is waiting here before returning to his bus. If you buy him a little lunch he''ll happily tell you what he knows about Innsmouth. you may spend $2 to gain 2 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Joe Sargent is willing to give you a ride to Arkham in his bus, provided you haven''t learned too much. If you have 3 or less Clue tokens, you may move to any location in Arkham and immediately have an encounter there.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Joe Sargent is wondering if you know anything about repairing bus engines. Make a Lore (-2) check. If you pass, you can tell the problem just by his description. Joe says he doesn''t really have any money to pay you, but offers one of his few possessions. Gain a Common Item card. If you fail, nothing happens.','Lore -2','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Joe Sargent tells you he''s running some errands and he''d be happy to pick something up for you if he can find it. Mkae a Luck (-1) check. Draw a number of Common Items equal to the number of successes rolled. You may choose 1 to purchase. Discard any items that are not purchased.','Luck -1','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Joe Sargent''s bus is waiting. You may spend $1 to hitch a ride to any Arkham location and have an encounter there.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Looking into a mirror, you can see that being in Innsmouth is changing you. You may gain up to 2 Corruption Cards. Then draw 2 Innsmouth Look cards. reduce the number of Innsmouth Look cards you draw by 1 for each Corruption card you have (to a minimum of 0).',NULL,'Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Looking out the window, the water looks beautiful and luminous, while the land looks gray and drab. Draw 1 Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Not only have you not been provided with a key to your door, but the deadbolt has been removed. Pass a Sneak (-1) check to find somewhere else to sleep and move to the street. If you fail, you are delayed and lose 1 Stamina and 2 Sanity when they come for you...','Sneak -1','Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('One of the other guests tells you about the shocking news from Dunwich. Roll 1 die for each Dunwich Horror token on the board. For each die that results in a failure, lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Something about the smell of this hotel is both distasteful and yet, somehow, familiar. Draw 1 Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('The desk clerk stops you as you go by. "This just came in for you." He hands you a telegram that reads "GET OUT OF INNSMOUTH STOP YOU KNOW TOO MUCH STOP." If you heed the telegram, move immediately to the Train Station. If you ignore it, further investigation yields 1 Clue token.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Walking down the hall to your room, you hear a banging from the other side of a door that is bolted shut. Opening the door, you discover a terrified man who can''t stop trembling. Make a Will (-2) check to calm him down. If you pass, gain 1 Sanity as you assure him that he''s safe now.','Will -2','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('When you open the wardrobe in your room, you discover a message written on the inside of the door. It warns of threats against your life and tells you how to avoid them. Take the Stealth card from the Skill deck if it is available. If not, gain a Clue token.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('You discover Joe Sargent wiping blood off of his hands. He tells you he hit something on the way here that got stuck on the front of the bus. Make a Luck (-2) check. If you pass, you may choose 1 monster token in the Outskirts to return to the monster cup.','Luck -2','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('You must have been sleepwalking! Move to Falcon Point and have an encounter there.',NULL,'Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('You see Joe Sargent facing the shoreline, muttering something to himself. Make a Sneak (-2) check to listen to the strange language he''s speaking and gain 1 Clue token for each success.','Sneak -2','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('You slept more soundly than you anticipated and wake up suddenly as you are being lifted out of your bed. Make a Fight (+0) check to wrestle free from your captors. If you fail, immediately move to Devil Reef and have an encounter.','Fight +0','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('You wake in the night hearing inhuman sounds getting closer. Make a Luck (-1) check. If you pass, the sounds grow more distant and nothing happens. If you fail, you escape out the window. Move to the streets and take the Harried card if it is available.','Luck -1','Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('You''ve never had such vivid dreams in your life! Move to the Dreamlands have an encounter there, and then return here immediately.',NULL,'Miskatonic Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Your door is locked from the outside! You are delayed.',NULL,'Innsmouth Horror');
INSERT INTO gilman_house_hotel_encounters VALUES ('Your inquiries have attracted the attention of some locals. Pass a Will (-2) check to calm them down, or add an uprising token to the Deep Ones Rising track.','Will -2','Innsmouth Horror');
