CREATE TABLE innsmouth_jail_encounters (
    `list_encounter` VARCHAR(464) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO innsmouth_jail_encounters VALUES ('A prisoner thinks he can get free if he gets enough money to bribe one of the constables. He offers to sell you the last of his belongings. Draw 1 Common Item. You may purchase it for the list price. If you do not have enough money but have at least $1, you may purchase it by discarding all of your money. If you have no money or choose not to purchase the item, it is discarded and nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('A pungent odor is emanating from the filthy jail cells. Pass a Will (-1) check or lose 1 Stamina.','Will -1','Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('An agent from the government is asking questions. The constables are trying to get him to go away. Make a Sneak (-2) check. For each success, you may spend 1 Clue token to place it on any space on the Feds Raid Innsmouth track. If you do not roll any successes, you are arrested and put in the Innsmouth Jail.','Sneak -2','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('As Chief Constable Martin asks you "just a few routine questions," you become unnerved by his hoarse voice and unblinking gaze. Pass a Will (-2) check or lose 1 Sanity.','Will -2','Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Chief Constable Martin has been cut pretty badly by a suspect and Constable Ropes is at a loss for treating the wound. Make a Lore (-2) check. If you pass, you manage to successfully administer some first aid and the Chief Constable produces a small gold coin from his desk and tosses it at you. Gain $3.','Lore -2','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Chief Constable Martin tells you that you''ll fit in just fine around here and offers you a job. Take a Retainer card and then draw 2 Innsmouth Look cards.',NULL,'Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Chief Constable Martin wants to question you and his integgogation methods are blood-chilling. Make a Will (-1) check to talk your way out of the situation without angering him. If you fail, lose 1 Stamina. Regardless of whether you pass or fail, you are delayed.','Will -1','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes "doesn''t like the look of ya." Pass a Fight (+1) check or lose 1 Stamina as he throws you out of the building. Regardess of the result, move to the street.','Fight +1','Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes has turned his back while the weapons locker is unlocked. If you wish to try covertly arming yourself, make a Sneak (-2) check. If you pass, search the Common Item deck and take the first Weapon you find. If you fail, you are arrested as you try to explain.','Sneak -2','Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes has turned his back while the weapons locker is unlocked. If you wish to try covertly arming yourself, make a Sneak (-2) check. If you pass, search the Common Item deck and take the first Weapon you find. If you fail, you are arrested as you try to explain.','Sneak -2','Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes has turned his back while the weapons locker is unlocked. If you wish to try covertly arming yourself, make a Sneak (-2) check. If you pass, search the Common Item deck and take the first Weapon you find. If you fail, you are arrested as you try to explain.','Sneak -2','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes has turned his back while the weapons locker is unlocked. If you wish to try covertly arming yourself, make a Sneak (-2) check. If you pass, search the Common Item deck and take the first Weapon you find. If you fail, you are arrested as you try to explain.','Sneak -2','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes has turned his back while the weapons locker is unlocked. If you wish to try covertly arming yourself, make a Sneak (-2) check. If you pass, search the Common Item deck and take the first Weapon you find. If you fail, you are arrested as you try to explain.','Sneak -2','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes has turned his back while the weapons locker is unlocked. If you wish to try covertly arming yourself, make a Sneak (-2) check. If you pass, search the Common Item deck and take the first Weapon you find. If you fail, you are arrested as you try to explain.','Sneak -2','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes is implying that if you don''t offer up a bribe, he''s going to make trouble for you. Discard $5 or a Unique Item. If you cannot or will not discard either, you are arrested.',NULL,'Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes is trying to read some old book he took from a suspect, but seems to be struggling with the material. He asks if it makes any sense to you. Make a Lore (-2) check. If you pass, gain 1 Spell.','Lore -2','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Constable Ropes wants to play some cards to pass the time. Make a Luck (-1) check. If you pass, gain $2 and 1 Common Item. If you fail, discard all of your money and 1 Common Item. If you have both no money and no Common Items to discard, you are arrested.','Luck -1','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('In a dark, disused corner of the jail, you find something that might come in handy. Draw 1 Common Item.',NULL,'Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Inside one of the cells, an emaciated old man calls out to you. "I know I won''t survive another night. But you might still escape! Take this and leave Innsmouth forever. He reaches into his shoe and pulls out some money. Gain $5.',NULL,'Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Near the cells, you find a small medical kit. It appears as if it''s never been opened. Gain 1 Stamina.',NULL,'Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('One of the prisoners claims to be a reporter trying to tell the truth about Innsmouth. He says he won''t get free but the important thing is that his notes make it to the newspaper. Make a Sneak (-1) check to get you hands on them. If you pass, gain 2 Clue tokens.','Sneak -1','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('Some prisoner from decades gone by has scrawled something on the wall. Make a Lore (-2) check to decipher it. If you succeed, gain a Spell.','Lore -2','Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('The constables are questioning a member of the Sheldon Gang. You think you could provide enough evidence to secure his release. If you spend at least 5 toughness worth of monster trophies or 1 gate trophy, the constables begrudgingly let him go. Impressed, the gang member tries to recruit you. Take a Sheldon Gang Membership card. If you do not spend the trophies, the constables arrest him and throw you out the front door. Move to the street and lose 1 Stamina.',NULL,'Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('The constables arrive in the morning to find the bars of the cell bent and all their prisoners missing. A few bloodied strips of the prisoners'' clothing is all that remains. The constables do not seem notably bothered. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('The constables take a keen interest in one of your more unusual possessions and are willing to trade information for it. If you discard one Unique Item of your choice, you may gain 3 Clue tokens.',NULL,'Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('The constables take a keen interest in one of your more unusual possessions and are willing to trade information for it. If you discard one Unique Item of your choice, you may gain 3 Clue tokens.',NULL,'Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('The constables take a keen interest in one of your more unusual possessions and are willing to trade information for it. If you discard 1 Unique Item of your choice, you may gain 3 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('The constables take a keen interest in one of your more unusual possessions and are willing to trade information for it. If you discard 1 Unique Item of your choice, you may gain 3 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('The constables take a keen interest in one of your more unusual possessions and are willing to trade information for it. If you discard 1 Unique Item of your choice, you may gain 3 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('The constables take a keen interest in one of your more unusual possessions and are willing to trade information for it. If you discard 1 Unique Item of your choice, you may gain 3 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('You discover a yellowing edition of the Innsmouth Courier from 1846. It is quite fragile and requires delicate handling to read. If you do so, you are delayed, but you gain 2 Clue tokens for your effort.',NULL,'Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('You overhear Constable Ropes speaking to someone on the phone. Although you only get one half of the conversation, you think you can fill in the details. Gain 1 Clue token.',NULL,'Innsmouth Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('You see a poster on the wall with your picture on it. There is a reward offered for your capture. Make a Sneak (+0) check to make yourself scarce. If you pass, take the Wanted card if it is available. If you fail, lose 1 Stamina and you are arrested.','Sneak +0','Miskatonic Horror');
INSERT INTO innsmouth_jail_encounters VALUES ('You walk in on a grisly sight. The constables are dragging a brutally beaten figure out of a cell. "A tragic suicide," they explain. Lose 1 Sanity.',NULL,'Innsmouth Horror');
