CREATE TABLE jail_cell_encounters (
    `list_encounter` VARCHAR(370) CHARACTER SET utf8,
    `list_skill_check` INT,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO jail_cell_encounters VALUES ('A black hood is thrown over your head, and you are taken to the docks, where you are placed on a small rowboat. After some time, your bonds are removed, and you are pushed roughly out of the boat and onto the ground. "Have fun!" the guards say, laughing. Pulling off your hood, you find yourself far out to sea on top of a reef. Move to Devil Reef and have an encounter.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('A black hood is thrown over your head, and you are taken to the docks, where you are placed on a small rowboat. After some time, your bonds are removed, and you are pushed roughly out of the boat and onto the ground. "Have fun!" the guards say, laughing. Pulling off your hood, you find yourself far out to sea on top of a reef. Move to Devil Reef and have an encounter.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('A black hood is thrown over your head and you are taken to the docks, where you are placed on a small rowboat. After some time, your bonds are removed and you are pushed roughly out of the boat and onto the ground. "Have fun!" the guards say, laughing. Pulling off your hood, you find yourself far out to sea on top of a reef. Move to Devil Reef and have an encounter.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('A black hood is thrown over your head and you are taken to the docks, where you are placed on a small rowboat. After some time, your bonds are removed and you are pushed roughly out of the boat and onto the ground. "Have fun!" the guards say, laughing. Pulling off your hood, you find yourself far out to sea on top of a reef. Move to Devil Reef and have an encounter.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('A black hood is thrown over your head and you are taken to the docks, where you are placed on a small rowboat. After some time, your bonds are removed and you are pushed roughly out of the boat and onto the ground. "Have fun!" the guards say, laughing. Pulling off your hood, you find yourself far out to sea on top of a reef. Move to Devil Reef and have an encounter.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('Constable Ropes enters your cell with a wooden baton. Some time later, he wearies of his sport and leaves you laying on the floor. Lose 1 Sanity and 1 Stamina. You are delayed, even if you are normally immune to being delayed.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('Constable Ropes enters your cell with a wooden baton. Some time later, he wearies of his sport and leaves you laying on the floor. Lose 1 Sanity and 1 Stamina. You are delayed, even if you are normally immune to being delayed.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('Constable Ropes enters your cell with a wooden baton. Some time later, he wearies of his sport and leaves you laying on the floor. Lose 1 Sanity and 1 Stamina. You are delayed, even if you are normally immune to being delayed.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('Constable Ropes enters your cell with a wooden baton. Some time later, he wearies of his sport and leaves you laying on the floor. Lose 1 Sanity and 1 Stamina. You are delayed, even if you are normally immune to being delayed.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('Constable Ropes enters your cell with a wooden baton. Some time later, he wearies of his sport and leaves you laying on the floor. Lose 1 Sanity and 1 Stamina. You are delayed, even if you are normally immune to being delayed.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('During the night, a harsh voice says, "Bring the prisoner." You are dragged from your cell to a disused house near the docks with a hole in the floor. Looking into it, you see a horrible shapeless mass that murmurs, "Tekeli-li! Tekeli-li!" Gasping, you barely have time to scream as the guard pushes you down into the hole. You are devoured.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('During the night, a harsh voice says, "Bring the prisoner." You are dragged from your cell to a disused house near the docks with a hole in the floor. Looking into it, you see a horrible shapeless mass that murmurs, "Tekeli-li! Tekeli-li!" Gasping, you barely have time to scream as the guard pushes you down into the hole. You are devoured.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('During the night, a harsh voice says, "Bring the prisoner." You are dragged from your cell to a disused house near the docks with a hole in the floor. Looking into it, you see a horrible shapeless mass that murmurs, "Tekeli-li! Tekeli-li!" Gasping, you barely have time to scream as the guard pushes you down into the hole. You are devoured.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('During the night, a harsh voice says, "Bring the prisoner." You are dragged from your cell to a disused house near the docks with a hole in the floor. Looking into it, you see a horrible shapeless mass that murmurs, ""Tekeli-li! Tekeli-li!" Gasping, you barely have time to scream as the guard pushes you down the hole. You are devoured.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('During the night, a harsh voice says, "Bring the prisoner." You are dragged from your cell to a disused house near the docks with a hole in the floor. Looking into it, you see a horrible shapeless mass that murmurs, ""Tekeli-li! Tekeli-li!" Gasping, you barely have time to scream as the guard pushes you down the hole. You are devoured.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('During the night, a harsh voice says, "Bring the prisoner." You are dragged from your cell to a disused house near the docks with a hole in the floor. Looking into it, you see a horrible shapeless mass that murmurs, ""Tekeli-li! Tekeli-li!" Gasping, you barely have time to scream as the guard pushes you down the hole. You are devoured.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('In the middle of the night, a voice says, "Hold the prisoner still." You struggle in the darkness, but a pungent liquid is forced down your throat, making your head swim. "That should do it," you hear, just before passing out. The next morning, you awaken in Sawbone Alley with a strange headache. Move to Sawbone Alley and draw three Innsmouth Look cards.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('Pretending to be asleep, you listen to Constable Ropes and the other guards talk. Gain 2 Clue tokens, and you are delayed, even if you are normally immune to being delayed.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('Pretending to be asleep, you listen to Constable Ropes and the other guards talk. Gain 2 Clue tokens, and you are delayed, even if you are normally immune to being delayed.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('Pretending to be asleep, you listen to Constable Ropes and the other guards talk. Gain 2 Clue tokens and you are delayed, even if you''re normally immune to being delayed.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('Pretending to be asleep, you listen to Constable Ropes and the other guards talk. Gain 2 Clue tokens and you are delayed, even if you''re normally immune to being delayed.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('Pretending to be asleep, you listen to Constable Ropes and the other guards talk. Gain 2 Clue tokens and you are delayed, even if you''re normally immune to being delayed.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave  you alone for awhile, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave  you alone for awhile, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave  you alone for awhile, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave  you alone for awhile, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Innsmouth Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave you alone for a while, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave you alone for a while, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave you alone for a while, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave you alone for a while, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave you alone for a while, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave you alone for a while, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave you alone for a while, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Miskatonic Horror');
INSERT INTO jail_cell_encounters VALUES ('The guards leave you alone for a while, so you examine your cell wall. Pushing aside some loose stones, you crawl out the tight opening to freedom and then replace the stones. Move to Sawbone Alley.',NULL,'Miskatonic Horror');
