CREATE TABLE marsh_refinery_encounters (
    `list_encounter` VARCHAR(442) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO marsh_refinery_encounters VALUES ('A couple of workers are walking with a half-hopping gait to the back of the building. One of them stumbles and drops a large canvas bag, spilling several strange objects on the ground. He tries to gather them back up quickly, but may have missed something. Make a Luck (-2) check. For each success, you may draw 1 Unique Item. Choose 1 to keep and discard the rest.','Luck -2','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('A monster appears!',NULL,'Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('A monster appears!',NULL,'Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('A monster appears!',NULL,'Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('A monster appears!',NULL,'Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('A polished mirror of some submarine material leans against the wall here. You gaze into it and make a Luck (-1) check. If you pass, the distorted world you see within grants you 1 Clue token. If you fail, draw one Innsmouth Look card as an awful truth becomes evident.','Luck -1','Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('A priest from the Esoteric Order of Dagon is here, blessing the equipment and the workers. He doesn''t realize you''re in the room as well. You are Blessed but gain 1 Corruption card.',NULL,'Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('A priest from the Esoteric Order of Dagon is here, picking through a collection of strange foreign jewelry. The conspiracy begins to take shape in your mind... Gain 1 Clue token, and then pass a Sneak (-2) check to move to the street.','Sneak -2','Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('An important piece of machinery has broken down and the workers are rushing to get it fixed. In the ensuing confusion, you''re able to examine the refinery''s ledgers. Make a Lore (-1) check. If you pass, gain 1 Clue token.','Lore -1','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('From the catwalk above, you have a clear view of the assembly line and the shambling, monstrous workers. Make a Lore (-1) check to realize what they really are. If you pass, gain 1 Clue token and lose 1 Sanity.','Lore -1','Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('Furtively, you pocket some processed gold. Make a Sneak (-2) check and gain $1 per success. If you get no successes, you are discovered and tossed out into the street.','Sneak -2','Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('If someone knew what he was doing, this would be the perfect opportunity for a robbery. If you have a Sheldon Gang Membership, gain $5. If you do not have a Sheldon Gang Membership, make a Sneak (-1) check instead. If you pass, gain $1.','Sneak -1','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('In the small office''s library, you discover the Sumatra Queen''s log. Reading it, you learn about Captain Obed Marsh''s travels to the South Pacific and his contact with the strange creatures that live beneath the waves. Make a Lore (-2) check and gain a Clue token for each success.','Lore -2','Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('Jacob Marsh greets you warmly. "Of course I know you! My aunt is your grandmother!" Draw two Innsmouth Look cards.',NULL,'Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('One of the night watchmen takes you by surprise! Make a Fight (+1) check. If you pass, you leave bruised and humbled. If you fail, lose 2 Stamina.','Fight +1','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('One of the workers catches sight of you. He looks concerned for a moment, but then just waves at you. Draw 1 Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('One of the workers falls backwards into the molten metal. His screams and the foul burning smell are horrifying. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('One of the workers sneaks over to you and offers you gold in exchange for an item of yours. You may discard 1 Unique Item to gain $4.',NULL,'Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('Part of your clothing has gotten wrapped up in one of the gears of the foundry. Make a Fight (+0) check to free yourself. If you fail, lose 1 Stamina as the gears bite into you.','Fight +0','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('Rotting floorboards give way beneath you. Make a Speed (-2) check or lose 1 Stamina.','Speed -2','Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('Some Innsmouth locals have cornered a man. If you decide to defend him, lose 3 Stamina. Even if you are knocked unconscious, the man, David Packard, is impressed by your brave act and offers you his help. Take his Ally card or, if it is not available, he gives you something "for protection." You may search the Common Item deck for Dynamite and take it.',NULL,'Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('The gold bars are still searing hot, but no one is around. You may lose up to 3 Stamina. Gain $2 for every 1 Stamina you lose.',NULL,'Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('Thick-looking men catch you where you don''t belong. The work you over and toss you into the street. Lose 1 Stamina.',NULL,'Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('While the workers are in the factory, you''re able to look through their lockers. Make a Sneak (-2) check and gain 1 Clue token for each success.','Sneak -2','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('Workers load some of the gold bars into a closet and then lock them inside. Once the coast is clear, you may make a Fight (-1) check to break the lock. If you pass, gain $2. If you fail, you must quickly escape out to the streets.','Fight -1','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('You find a curious collection of loathsome and alien jewelry. Could this be what the refined gold is derived from? If you choose to investigate more closely, make a Lore (-2) check. If you pass, draw 1 Unique Item. If you fail, you are Cursed.','Lore -2','Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('You find one of the older Innsmouth residents huddled in a corner. The thing is barely still human and quickly sufficating as its fish-like features no longer allow it to breathe air. Make a Will (-2) check and gain 1 Clue token for each success. If there were no successes rolled, lose 2 Sanity as you gaze into its bulbous eyes.','Will -2','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('You find your way into the office of Jacob Marsh and begin examining his accounts. Pass a Lore (-2) check to gain 2 Clue tokens.','Lore -2','Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('You hide yourself in a storage shed. Among the shelves are all kinds of strange items. Make a Luck (-1) check. If you pass, you find something useful. Gain 1 Common Item. If you fail, you knock one of the shelves over, making a terrible din. You are escorted to the streets.','Luck -1','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('You see a young woman sneak out of a window. Make a Speed (-1) check. If you fail, she''s disappeared into the night. If you pass, you catch up to Sarah Danforth, an archaeology student from Miskatonic. She tells you that important archaeological finds are being melted down for gold inside that refinery. Take her Ally card. If it is not available, gain 1 Clue token instead as she tells you everything she discovered in the refinery''s files.','Speed -1','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('You see flashlights in the darkness. The constables are here looking for you! Make a Speed (-1) check to elude them. If you fail, you are arrested and taken to the Innsmouth Jail.','Speed -1','Miskatonic Horror');
INSERT INTO marsh_refinery_encounters VALUES ('Your studies of the Innsmouth threat so far enable you to quickly pick the most relevant item from the crowd of artifacts and jewelry awaiting processing. You may spend 3 Clue tokens to draw 2 Unique Items, keeping one of your choice and discarding the other.',NULL,'Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('You''re not alone in here. Pass a Sneak (-2) check or a monster appears! If you defeat the monster, gain $5 as you discover a cache of gold.','Sneak -2','Innsmouth Horror');
INSERT INTO marsh_refinery_encounters VALUES ('You''ve snuck into the refinery, but now there are workers everywhere. Make a Will (-1) check to remain calm and stay where you are. If you fail, you are arrested when you try to leave and taken to Innsmouth Jail.','Will -1','Miskatonic Horror');
