CREATE TABLE yha_nthlei_encounters (
    `list_encounter` VARCHAR(410) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(23) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO yha_nthlei_encounters VALUES ('A pool in one of the rooms reveals many figures swimming beneath the floor you are standing on. You then see the shadow of something very large swim past. Make a Will (-1) check. If you fail, lose 2 Sanity.','Will -1','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('A strange series of glyphs lines the walls. If you try to interpret them, make a Lore (-1) check and gain a Clue token for each success. If you don''t roll any successes, you are Cursed.','Lore -1','Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('A tall tower seems to stretch up forever. A cool breeze from above makes you think it might lead back to the surface, but the stairs up are coated in slime. Make a Will (-2) check to carefully make the long climb. If you pass, there''s a boat not far from where you reach the surface. Move to any aquatic location and have an encounter there. If you fail, you slip and lose 2 Stamina as you fall down the steps.','Will -2','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('Amid skeletons and tattered clothing, you find the logs of several ships from over the last 200 years. If you wish to consult them you are delayed, but if you do, gain 3 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('Deep ones! If you hide from them, make a Sneak (-2) check. If you fight, make a Fight (-2) check. If you fail whichever check you attempt, lose 2 Stamina and 2 Sanity. If you pass, draw 1 Unique Item as you escape in the midst of all the chaos.','Sneak -2
-OR-
Fight -2
','Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('In a large round room with a glass ceiling, you are startled to discover an elderly man wearing exotic robes. He tells you that the gods have decreed that he should meet you in this strange place. If you are Cursed or have any Mask items, he tells you that he is called The Messenger and is meant to aid you. Take his Ally card or, if it is not available, gain 2 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('It''s easy to get separated in the winding tunnels. Return one Ally of your choice to the box. If do not have any Allies, nothing happens.',NULL,'Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('Move quickly, or you''ll be surrounded before you can escape with your prize! Pass a Speed (-1) check to draw a Unique Item. If you fail, you are devoured.','Speed -1','Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('On the far side of this cavern is a glittering idol that you''re certain is important, if only you can reach it. Make a Sneak (-2) check. If you pass, you may take your choice of 1 Unique Item or 3 Clue tokens. If you fail, you lose 1 Sanity and 1 Stamina, move to the first area of R''lyeh and are delayed.',NULL,'Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('Representatives from the Cult of the Black Goat are here to learn more of the Deep Ones! You may join the cult if you wish. To do so, you must discard at least 2 toughness worth of monster trophies, lose 3 Stamina, or discard an ally. Take a "One of the Thousand" Cult Membership Card. If you cannot or choose not to join, pass a Speed (-2) check or lose 2 Stamina.','Speed -2','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('Several of the fish creatures are trying to chase you toward a pool of strange dark water. Make a Speed (-1) check to prevent yourself from being forced into the pool. If you fail, move to the first area of R''lyeh and you are delayed.','Speed -1','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('Strangely, you feel you know exactly how to navigate the twisting caverns to find the object you are sinking. Gain 1 Unique Item and draw 1 Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('The air-filled cavern you''re in begins to fill with water as the tide shifts. You lose 1 Stamina and are delayed as you wait it out.',NULL,'Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('The creatures are engaged in some sort of ritual! You are immediately sucked through the open gate with the most difficult modifier (your choice if there are two equally difficult gates). If there are no open gates, nothing happens.',NULL,'Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('The deep ones are everywhere! Make a Fight (-1) check to barricade the hallway. If you fail, lose 2 Stamina struggling to escape the creatures.','Fight -1','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('The walls are covered with strange luminescent moss and lichens. You feel prolonged exposure to them is having a bad effect on you. Lose 1 Stamina.',NULL,'Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('The writing etched into the wall is looking more and more familiar. Gain 1 Spell and draw 1 Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('Two of the creatures walk past you carrying a large chest. Make a Sneak (-2) check. If you pass, you follow them and discover where they leave it. Gain 1 Unique Item from inside the chest once the creatures leave. If you fail, lose 1 Stamina as they roughly toss you aside.','Sneak -2','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You are overcome with a sense of fate, knowing that it was your destiny to be in this strange place. Make a Will (-1) check. If you pass, you realize that you will play a special role in saving the world. You may take the Anointed card if it is available. If you fail, you fear that you are doomed to die here. Lose 1 Sanity.','Will -1','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You desperately flee from pursuing deep ones and, with no other choice, leap into a dark, unexplored cavern. Make a Luck (-1) check. If you pass, move to Devil Reef. If you fail, you are lost in time and space.','Luck -1','Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You discover a chamber filled with scrolls, ancient tomes, and engraved stonework. Make a Luck (-2) check. If you pass, you stumble upon useful ancient knowledge. You may draw 2 Spells, choose 1 to keep and discard the other. If you fail, you stumble upon a terrible ancient evil. You are Cursed.','Luck -2','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You feel as though being in these underground caves is reinvigorating you. Gain 1 Stamina and draw one Innsmouth Look card.',NULL,'Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You find a curious doorway. If you pass through it, move to the Esoteric Order of Dagon and have an encounter there.',NULL,'Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You find a statue of Dagon, as large as a house, covered in strange writing. You fear that just being in its presence is dangerous. Make a Lore (-2) check as you look at the writing. Gain 1 Clue token for each success. If you gained 3 or more Clue tokens, you are Cursed.','Lore -2','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You find an abandoned temple. At the front, resting on an altar is a copy of the Ponape Scripture. Pass a Lore (-2) check to gain some useful insight from the book. If you succeed, you may close one gate to R''lyeh anywhere on the board. Keep the gate trophy and remove monsters with the matching dimensional symbol as normal.','Lore -2','Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You find precious golden jewelry, far more than you can carry. You may stop to collect some. If you do, make a Fight (+1) check and gain $1 for each success. You are delayed as you gather up all the loot.','Fight +1','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You inadvertently fall into one of the pools of water. Make a Speed (-1) check to get out before you are swarmed by Deep Ones. If you fail, lose 2 Stamina before you pull yourself back into the air.','Speed -1','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You see a large painting that you recognize as a map of the ocean floor. You can identify the city of Y''ha-nthlei on the map and see several other similar cities represented as well. Make a Lore (-2) check and gain 1 Clue token for each success. If you get no successes, lose 2 Sanity.','Lore -2','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You sense powerful, ancient voice attempt flood your mind with terrible thoughts. Pass a Will (-2) check or lose 2 Sanity.','Will -2','Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You step out onto a balcony overlooking thousands of these fish creatures, all chanting and bowing before an image of Dagon. Make a Will (-2) check. If you fail, lose 2 Sanity.','Will -2','Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You try to recall every scrap of information you learned about this place to prevent these creatures from running rampant. If you have 2 or fewer Clue tokens, add 1 Uprising token to the Deep Ones Rising track.',NULL,'Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You''ve been down here so long you fear you''re losing your sense of reality and your sense of self. You must either lose 2 Sanity or draw 1 Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO yha_nthlei_encounters VALUES ('You''ve got the proof you need, now all you have to do is escape this terrible place! Pass a Luck (-1) [2] check to move to Falcon Point, then remove all tokens from both the Feds Raid Innsmouth and the Deep Ones Rising tracks. In addition, remove 1 doom token from the doom track. If you fail, you are devoured.','Luck -1 [2]','Innsmouth Horror');
INSERT INTO yha_nthlei_encounters VALUES ('Your foot slips on one of the damp ledges and you go tumbling down a steep incline. Make a Luck (-1) check. If you pass, you end up landing right next to a rare and powerful artifact. Search the Unique Item deck and take the first Weapon you find. If you fail, you land on a bunch of rocks. Lose 2 Stamina.','Luck -1','Miskatonic Horror');
