CREATE TABLE artists_colony_encounters (
    `list_encounter` VARCHAR(612) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(20) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO artists_colony_encounters VALUES ('"Come on, love. Let''s go back to my place and I''ll paint your portrait for you." A tall, dark-haired lothario presses his affections upon a reluctant young lady nearby while holding onto her arm. If you wish, you may interfere. If so, pass a Fight (-1) check or a Will (-2) check to drive him off and gain 1 Sanity. If you fail, lose 1 Stamina as he backhands you cruelly before storming off.','Fight -1
OR
Will -2
','Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('"Hi there. I haven''t seen you around here before, have I? Why not join me for lunch? I''m Elizabeth Brundage." She turns out to be a motherly figure, keeping tabs on the artists in Kingsport. "Terrible what happened to poor Charles Baxter, really. He was such a promising poet, and to take his own life like that." She sighs, and you continue drawing the local gossip out of her. Gain 1 Clue token and 1 Sanity from the pleasant company.',NULL,'Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('"What do you think of my work?" An artist shows a series of sketches of creatures too horrific to even consider. Lose 1 Sanity. Then, if you are still sane, make a Will (+0) check. If you fail, you attack the man and are arrested for being a menace.','Will +0','Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('A desperate looking young man approaches you asking for financial help. He assures you he is a hard worker with a good future and that he will pay you back with interest. You may pay $3 to take a Retainer card.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('A friendly looking man catches sight of you and asks if you''re doing okay. He recommends borrowing his sketchbook and drawing what''s bothering you. If your current Sanity is 2 or less, gain 2 Sanity. The man seems quite alarmed at the things you draw.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('A local artist has just been commissioned to create work for a gallery in Boston. Overjoyed, he is spending money on anything he can find. You may choose 1 Common Item or Unique Item to discard in exchange for $2 greater than its list price.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('A painter who specializes in calm landscapes has his works for sale on the sidewalk. You suddenly see someone stealing one of his paintings. Make a Speed (-2) check to catch the thief. If you pass, the artist offers you a small painting as gratitude. Althought not valuable, you treasure the painting for its purity and simplicity. You are Blessed.','Speed -2','Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('A silver-tongued young painter tries to sell you one of his paintings. Pass a Will (-1) check or lose $3, if able. If you fail the check and have less than $3, he sells you the painting for whatever you have. Lose all your money.','Will -1','Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('A store is selling a painting that depicts you in the way you are currently dressed, but in a completely different time period. Move to the first area of Another Time, have an encounter there and return here immediately.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('A young painter, who clearly has some talent, is trying to sell his works but looks dejected. When a passerby shows a little interest, you decide to help him make the sale. Make a Lore (-2) check to point out the strengths of the work. If you pass, the painter splits the money from the sale with you. Gain $2.','Lore -2','Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('An art shop is selling an old engraving that depicts figures engaged in some arcane rite. You recognize it illustrates the use of magic in detail. You may purchase it for $3. If you do, gain 1 Spell.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('An artist is sketching a woman sitting across from him. You can tell, just by looking as his rendering of her, the two are very much in love. Gain 1 Sanity from this heartwarming scene.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('An unshaven, down-on-his-luck painter sits on the street corner, selling some of his possessions to make ends meet. Draw 1 Common Item. You may buy it for $2, regardless of its list price. If you don''t buy the item, discard it.',NULL,'Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('As you stroll past a pale, dark haired woman, she mumbles to herself, "Charles, I''m sorry. It was all my fault." Concerned, you take a second look at her and see a young woman consumed with guilt and grief. If you talk to her, make a Will (-2) check. If you pass, you find out that her name is Corla Fistienne and her ex-boyfriend recently committed suicide. You leave feeling that you''ve helped alleviate her guilt and prevented her from doing anything stupid. Gain 2 Sanity. If you fail or do not try to talk to her, the terror level increases by 1 when news of her suicide reaches the newspapers the next day.','Will -2','Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('As you walk down the street, a tomcat rubs himself across your legs. "Hello there, puss. Where did you come from?" If you pass a Luck (-1) check, you name the cat Foolishness. Take his Ally card, or if it''s not available, remove 2 rift tokens from the Kingsport board.','Luck -1','Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('As you walk down the street, a tomcat rubs himself across your legs. "Hello there, puss. Where did you come from?" If you pass a Luck (-1) check, you name the cat Foolishness. Take his Ally card, or if it''s not available, remove 2 rift tokens from the Kingsport board.','Luck -1','Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('As you walk down the street, a tomcat rubs himself across your legs. "Hello there, puss. Where did you come from?" If you pass a Luck (-1) check, you name the cat Foolishness. Take his Ally card or, if it''s not available, remove 2 rift tokens from the Kingsport board.','Luck -1','Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('As you walk down the street, a tomcat rubs himself across your legs. "Hello there, puss. Where did you come from?" If you pass a Luck (-1) check, you name the cat Foolishness. Take his Ally card or, if it''s not available, remove 2 rift tokens from the Kingsport board.','Luck -1','Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('At a small corner bar, you run into Derek Minot, who is busily getting drunk. Seeing a sympathetic ear, he tells you the tragic tale of his roommate, who recently killed himself. The tale is unpleasant and peculiar, making you suspect unnatural influences at work. Pass a Will (-2) check or lose 1 Sanity and 1 Stamina. In any event, gain 1 Clue token.','Will -2','Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('Erica Carlyle is browsing the art for sale and gets caught up in your stories of the unexplained. If you have $3 or less, she agrees to join you and help pay your way. Take her Ally card or, if it is not available, gain a Retainer card.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('If you have a Tome, a gaunt man with a maniacal gleam in his eyes comes up to you in the street. Introducing himself as Jim Redmond, he offers to buy any one of your Tomes for $5. If you sell it to him, return it to the box, gain $5, and lose 1 Sanity as you worry what he''s going to do with it. If you do not sell a Tome to Jim, or do not have one, nothing happens.',NULL,'Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('Passing a thin, pale artist who has a nasty twitch, you glance at one of his paintings and your horrified gaze is immediately captured. Pass a Will (-1) check or lose 1 Sanity and become delayed as you faint upon seeing the nightmarish creature he has depicted.','Will -1','Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('Sipping coffee at a small cafe, you suddenly grasp your throat. You''ve been poisoned! Make a Fight (-1) check to stave off its effects. If you fail, lose 2 Stamina.','Fight -1','Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('Sitting comfortably at an outdoor table in front of a picturesque cafe, you doze off. Have one encounter in the Dreamlands, then return here.',NULL,'Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('Somehow, as you race through this area, every piece of art you see has a yellow sign somewhere on it. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('Suddenly, an artist''s face lights up as he sees you. "Perfect! You''re just what I need for my next painting! Please, sit for me, won''t you? I can''t pay much, but I''ll make it worth your while." If you agree, you are delayed and gain $2.',NULL,'Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('You are surprised to bump into acquaitances who have decided to vacation here in Kingsport. They believe you have knowledge of the best places to visit and are keen to tag along. Make a Will (-1) check to politely discourage them. If you fail, take the Local Guide card.','Will -1','Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('You come across an odd book of poetry entitled Dreams and Fancies. If you read it, make a Luck (+0) check and consult the following chart:Successes:0) You are reduced to 0 Sanity.1) Gain two Clue tokens and lose 2 Sanity.2+) Gain 3 clues and lose 1 Sanity.','Luck +0','Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('You find a jeweler who crafts talismans, who asks you if you know anything about real magic. He''s willing to pay for a lesson. If you currently have a Spell, gain $2. If you do not currently have a Spell, nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('You find yourself drawn inexplicably to paintings of the sea. Draw 1 Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('You pause to watch a large bearded man sculpt in his front yard. His name is Ted Covey, and he proves to be loud, boisterous, and a good joke teller. You talk with him a while longer, then move on with a smile on your face. Gain 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO artists_colony_encounters VALUES ('You see a half-crumpled sketch lying next to a bench. It strikes you as interesting because it is clearly your face that was being sketched. When you unfold the paper, you are horrified to see it is a depiction of you being murdered horribly. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('You see a painting of a rural landscape with dark clouds on the horizon. You can see the faint image of monstrous appendages hidden among the clouds. Make a Will (-1) check. If you fail, lose 1 Sanity. If you had a Madness card before you failed the check, add 1 Dunwich Horror token to the board.','Will -1','Miskatonic Horror');
INSERT INTO artists_colony_encounters VALUES ('You stand on a street corner listening to a talented violinist play beautifully. Gain 1 Sanity. Then, if you pay $1, gain 1 additional Sanity.',NULL,'Miskatonic Horror');
