CREATE TABLE congregational_hospital_encounters (
    `list_encounter` VARCHAR(405) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO congregational_hospital_encounters VALUES ('"This was pulled out of the water yesterday. You might want to see it." The doctors show you the body of a deep one. The sight and odor are incredibly repugnant. Lose 1 Stamina. Then, if you are still conscious, make a Lore (-1) check and gain 1 Clue token for each success.','Lore -1','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('"You seem like you''ve got a level head. Care to help me with an experiment?" If you pass a Lore (-2) check or discard Research Materials, Dr. Herbert West offers to join you in thanks for your assistance. Take his Ally card, or if it''s not available, gain 3 monster trophies from the monster cup at random, ignoring Endless.','Lore -2','Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('"You seem like you''ve got a level head. Care to help me with an experiment?" If you pass a Lore (-2) check or discard Research Materials, Dr. Herbert West offers to join you in thanks for your assistance. Take his Ally card, or if it''s not available, gain 3 monster trophies from the monster cup at random, ignoring Endless.','Lore -2','Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('"You seem like you''ve got a level head. Care to help me with an experiment?" If you pass a Lore (-2) check or discard Research Materials, Dr. Herbert West offers to join you in thanks for your assistance. Take his Ally card or, if it''s not available, gain 3 monster trophies from the monster cup at random, ignoring Endless.','Lore -2','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('A panicked man with sores all over him bumps into you as he rushes in the door. Make a Speed (-1) check to quickly wash your hands and face before you become infected. If you fail, lose 1 Stamina.','Speed -1','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('A priest has been called in to counsel a particularly hopeless case. If you are Cursed or either your Stamina or Sanity is 2 or lower, he introduces himself as Father Iwanicki, and says, "I would like to offer my help, to make sure that no more suffer the same fate as this poor soul." Take his Ally card or, if it is not available, you may search the Unique Item deck for the Holy Water card and take it.',NULL,'Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('A strange sound echoes through the halls. It may be praying or chanting. No one else seems to hear it. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('An elderly patient asks you to sit and chat with her for a while. If you stay and listen to her, you are delayed as she talks nostalgically about her childhood and her family. You are then Blessed.',NULL,'Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Catching him in a rare moment of calm, you take some time to talk to Dr. Harris. Gain 2 Clue tokens.',NULL,'Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Despite your protests, the doctors are certain that you should not be allowed to leave the hospital. You are delayed, but may then gain 2 Stamina, 2 Sanity, or 1 of each.',NULL,'Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('During the night, a number of the graves in the cemetary were disturbed. You notice an object was unearthed as a result. make a Luck (-2) check. If you pass, gain a Unique Item. If you fail, gain a Common Item.','Luck -2','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Examining the graves, you are startled to see so many list the same date as the day of death. Lose 1 Sanity and then, if you are still sane, gain 1 Clue token.',NULL,'Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Exploring downstairs, you come across the door to the boiler room. Pass a Luck (-1) check to slip in and gain 1 Common Item.','Luck -1','Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('If you are hurt, one of the orderlies bandages up some of your wounds for you. Gain 1 Stamina.',NULL,'Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('In the hall, you can hear patients reciting lines from "the King in Yellow" back and forth to each other, seemingly unaware that they''re saying anything at all. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('In the middle of the night, you hear a strange noise coming from the graveyard. You''ve stumbled upon the Cult of the Black Goat! You may join them if you wish. To do so, you must discard at least 2 toughness worth of monster trophies, lose 3 Stamina, or an Ally. Take a "One of the Thousand" Cult Membership card. If you cannot or choose not to join, pass a Speed (-2) check or lose 2 Stamina.','Speed -2','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Making your way through the private wards, you come across a poor old soul who has recently passed away, but has not yet been noticed by the orderlies. Sitting on the table near him is a gold watch. You may gain $4, but if so, you must pass a Luck (-1) check or be Cursed.','Luck -1','Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('One of the doctors is struggling to wrestle an object from the grip of an unmoving man on a gurney. "I''m sorry. We''re a little short on staff right now. Could you help me?" If you help, make a Fight (-2) check to pry the item free. If you pass, gain 1 Unique Item. If you fail, gain 1 Common Item and lose 1 Sanity as the man''s hand comes loose from his arm.','Fight -2','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('one of the staff doctors was fired for very erratic research methods, and Dr. Matthew Harris would like your help in reviewing the records of his work. Make a Lore (-2) check to make sense of it. If you pass, draw 2 Spells, choose 1 to keep and discard the other.','Lore -2','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Peering around the corner into a back alley, you watch in horror as a mass of white worms crawls out of a gnarled old man''s body. They envelope a hobo tied up nearby, disappearing into the man''s flesh and eating him alive. Pass a Will (-1) check or roll a die and lose that much Sanity. Even if you pass, lose 1 Sanity unless you are immune to Nightmarish.','Will -1','Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Taking a shortcut through the cemetary, you are horrified when something grabs your foot. Lose 1 Sanity before you realize that you''ve snagged yourself on a root.',NULL,'Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Taking a wrong turn, you wind up in a supply closet and the door locks behind you. You are delayed while you wait for someone to let you out.',NULL,'Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('The staff asks you to take a box of unclaimed lost-and-found items to the new church for the benefit of the poor. As a reward, you''re encouraged to claim something from the box for yourself. Draw 3 Common Items, choose 1 to keep, and discard the others.',NULL,'Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Walking through the graveyard near the hospital, you overhear two gravediggers gossiping about some strange things that happened nearby recently.Gain 1 Clue token.',NULL,'Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Walking through the graveyard, you are frightened by a strange green fire that seems to flicker off in the distance between the graves. Move to the street.',NULL,'Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('You become very suspicious when you see a masked figure passing through the halls. Following him, you end up somewhere very strange. Move to the first area of Lost Carcosa, have an encounter there, and then return here immediately.',NULL,'Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('You explore an ancient crypt in the cemetary and come across a giant mass of white grave worms. Lose 2 Sanity. In addition, any Crawling Ones in Arkham (including the Sky and the Outskirts) move here and encounter you.',NULL,'Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('You have a horrifying vision of yourself on an operating table, horribly wounded. Make a Will (+1) check to convince yourself it''s only an illusion. If you pass, lose 1 Sanity. If you fail, the pain feels very real to you. Lose 1 Sanity and 2 Stamina.','Will +1','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('You hear a scream from the other side of the reception area. Right before your eyes, a perfectly healthy orderly begins to age and shrivel, ultimately turning to sand and being swept out of the room by a gust of wind. Make a Will (+0) check. If you fail, lose 2 Sanity.','Will +0','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('You notice a creepy old man dragging a sack near the graveyard. If you want to investigate his suspicious activity, pass a Sneak (-2) check to gain 1 Unique Item and 1 Spell. If you fail, roll  2 dice and add them together. You lose that many total points of Sanity and/or Stamina, split up however you like.','Sneak -2','Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('You overhear a doctor confessing that he has no idea what''s causing the strange symptoms his patient is suffering. Make a Lore (-2) check to recognize the problem. If you pass, the doctor asks permission to call on you for future help. Take a Retainer card.','Lore -2','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('You see a door marked "Private" leading down to a small storage room. You may make a Sneak (-1) check to go through undetected. If you pass, you discover a number of historical documents and photos concerning the old church that used to be here. Gain 1 Clue token. If you fail, you are escorted out. Move to the streets.','Sneak -1','Miskatonic Horror');
INSERT INTO congregational_hospital_encounters VALUES ('You stumble across a wormhole-riddled corpse lying beneath a gravestone. Lose 1 Sanity. Mustering your courage, you turn it over to see who it was. If you pass a Luck (-2) check, you don''t recognize the man, but he was clutching an odd item. Gain 1 Unique Item. If you fail, you don''t recognize the man, but he has nothing of value.','Luck -2','Kingsport Horror');
INSERT INTO congregational_hospital_encounters VALUES ('Your doctors give you a pill to help you relax. Move to the first are of the Dreamlands, have an encounter there, and then immediately return.',NULL,'Miskatonic Horror');
