CREATE TABLE hall_school_encounters (
    `list_encounter` VARCHAR(398) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(16) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO hall_school_encounters VALUES ('A couple of students have snuck outside, behind the school. Make a Sneak (-2) check to overhear what they say to each other when they think no one else is listening. If you pass, gain 2 Clue tokens.','Sneak -2','Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('A glass display case holds various trophies and certificates earned by students over the years. You notice one of the certificates is covered in text written in an ancient language. Make a Lore (-2) check to translate. If you pass, gain 1 Spell.','Lore -2','Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('A student presents a detailed report on the history of the Dark Pharaoh. Make a Will (-2) check. If you pass, you learn a great deal questioning her. Gain 2 Clue tokens. If you fail, lose 1 Sanity as she describes what it was like to live under the Pharaoh''s reign.','Will -2','Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('After looking in the school records, you begin to feel a malevolent force has begun to follow you. Make a Will (-1) check to shake the feeling. If you fail, take the Harried card if it is available.','Will -1','Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Among the papers in the archive, you discover some signed by Asenath Waite. Pass a Lore (-1) check to gain 1 Spell. Whether you pass or not, you must then pass a Will (-1) check or lose 2 Sanity.','Lore -1
Will -1
','Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('Elections are underway for class president and the competition has grown mean-spirited. You see a fight break out right in front of you. Make a Fight (-1) check to break it up. If you fail, lose 1 Sanity as you can''t stop the students viciously attacking one another.','Fight -1','Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Having gotten permission to look through the archive in the basement, you come across a parchment signed by Eben Hall. Pass a Lore (-1) check to gain 1 Spell.','Lore -1','Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('If the Rare Book Collection card is facedown and you have the Necronomicon, John Miles tells you that the Miskatonic Library  has been looking for another copy. You may return the Necronomicon to the box to turn the Rare Book Collection card faceup. If the Rare Book Collection card is faceup, if you do not have the Necronomicon, or if you do not want to discard the Necronomicon, nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Looking through the school''s archive, you find papers detailing the 1722 raid on the Congregational Church. Fascinated, you read it carefully. Gain 3 Clue tokens.',NULL,'Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('One of the classrooms is closed today and students are not allowed to go in. Inside you find animal blood was painted on the walls as part of some horrific rite. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('One of the students has received a letter from her home in Dunwich. She''s very concerned about the events that are being described. Gain 1 Clue token for each Dunwich Horror token on the board. Then lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Principal Miles invites you to have lunch in the cafeteria. Gain 1 Stamina.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Principal Miles is hesitant to allow you in the students'' lockers. Make a Will (-2) check to convince him. If you pass, you discover one student''s notes on a foray into the arcane arts. Gain 1 Spell.','Will -2','Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Principal Miles is looking for guest lecturers. If your Lore is currently 4 or higher, gain a Retainer card.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Principal Miles is suspicious of your presence at his school. Pass a Will (-2) check or be arrested and go to the Police Station.','Will -2','Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('Principal Miles is very interested in acquiring more books for the library. You may discard 1 Tome in exchange for $2 more than its list price.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Principal Miles shows you the work that the students have been creating in their art class. You can see one student has talent well beyond her years and a strange insight into creatures from beyond. Make a Lore (-2) check and gain 1 Clue token for each success as you examine her work.','Lore -2','Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Searching the school''s archives, you read about the history of Kingsport. Gain 1 Clue token.',NULL,'Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('Someone sneaks a book in with your other belongings. Make a Luck (-1) check. If you pass, gain 1 Spell. If you fail, it is a text that describes the agonizing horrors befalling humanity. Lose 1 Sanity.','Luck -1','Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('The further back you look, the more the school''s records are incomplete and disorganized, but you find some remarkable things among the paperwork. Draw 2 Spells, choose 1 to keep and discard the other. But the long search results in you being delayed.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('The halls are too crowded with students to proceed. Move to the street.',NULL,'Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('The school is selling some of its old texts. You may spend $2 to search the Common Item deck and take the first Tome you find.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('The students seem all too eager to tell you rumors and ghost stories. Make a Lore (-1) check to discern the useful from the hyperbole. If you pass, gain 1 Clue token. If you fail, you are delayed by the excess of dubious information.','Lore -1','Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('The teachers claim you are disrupting class and insist that you leave. Move to the streets.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('Underneath some papers in the archive, you see a glint of light. Pass a Luck (-2) check to gain 1 Unique Item.','Luck -2','Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('You encounter a lovely young lady visiting her old school. She smiles at you, and something intangible passes between the two of you. If you add 2 Rift progress tokens to any spaces on the Rift track, she introduces herself as Asenath Waite. Take her Ally card, or if it''s not available, gain 1 Retainer and 1 Spell.',NULL,'Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('You encounter a lovely young lady visiting her old school. She smiles at you, and something intangible passes between the two of you. If you add 2 Rift progress tokens to any spaces on the Rift track, she introduces herself as Asenath Waite. Take her Ally card, or if it''s not available, gain 1 Retainer and 1 Spell.',NULL,'Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('You encounter a lovely young lady visiting her old school. She smiles at you, and something intangible passes between the two of you. If you add 2 Rift progress tokens to any spaces on the rift track, she introduces herself as Asenath Waite. Take her Ally card or, if it''s not available, gain 1 Retainer and 1 Spell.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('You encounter a lovely young lady visiting her old school. She smiles at you, and something intangible passes between the two of you. If you add 2 Rift progress tokens to any spaces on the rift track, she introduces herself as Asenath Waite. Take her Ally card or, if it''s not available, gain 1 Retainer and 1 Spell.',NULL,'Miskatonic Horror');
INSERT INTO hall_school_encounters VALUES ('You have a long talk with Principal Miles. Pass a Will (-1) check to gain 1 Clue token, otherwise move to the street.','Will -1','Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('You have a pleasant little chat with some of the students. Gain 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('You read a book in the library about some horrible Polynesian rituals. Lose 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('You spend some time reading Eben Hall''s original papers. You are delayed. Pass a Lore (-1) check to gain 1 Spell and 1 Clue token. If you fail, lose 1 Sanity.','Lore -1','Kingsport Horror');
INSERT INTO hall_school_encounters VALUES ('You stumble across an excerpt from the Necronomicon in the archives. Pass a Lore (-1) [2] check to search the Spell deck and take a spell of your choice.','Lore -1 [2]','Kingsport Horror');
