CREATE TABLE north_point_lighthouse_encounters (
    `list_encounter` VARCHAR(397) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO north_point_lighthouse_encounters VALUES ('"Wait here, I think I''ve got an old heirloom that may help you." Basil Elton goes into the lighthouse to look. If you pass a Luck (-1) check, gain 1 Unique Item. If you fail the check, he can''t find it.','Luck -1','Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('A few fishermen have stopped by to chat with Basil Elton. They''re willing to give you a ride on their boat if you''d like. You may move to any aquatic location and have an encounter there.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('A few fishermen stop by and offer to sell some of their catch. If you''re willing to buy any, Basil Elton is willing to cook it. You may spend $1 to gain 1 Stamina.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('A few of the fishermen have come by to warn Basil Elton that there''s something dangerous in the waters near Innsmouth. Gain 1 Clue token as they describe the creatures seen near Devil Reef.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('A haunting, beautiful melody draws you to the misty sea cliffs. It seems to be coming from out to sea, and it pulls at you with unrelenting pressure. Pass a Will (-1) check or roll a die and lose that much Stamina as you leap from the cliff before you come to your senses.','Will -1','Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('A terrifying storm rolls in just as you reach the lighthouse. Basil Elton, the lighthouse keeper, asks for your help keeping the beacon lit. If you accept, make a Will (-2) check. If you pass, the light stays lit throughout the storm, and you are Blessed. If you fail or refuse to help, the light goes out and there is a terrible shipwreck. Many lives are lost and the terror level increases by 1.','Will -2','Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('A well-dressed Egyptian man is visiting Basil Elton. If you have any Exhibit Items or your Will is 2 or lower, he takes an interest in your story as well. He introduces himself as Dr. Ali Kafour. Take his Ally card or, if it is not available, listen to him discuss journeys into the underworld as described in assorted cultures. Gain 2 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Ambling up the trail to the lighthouse, you knock on the door, but no one answers. Apparently you''re not the only one out enjoying this brisk, clear day. Nothing happens.',NULL,'Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Basil Elton calls you to the top of the lighthouse, quickly pointing to the water. Make a Luck (-1) check. If you pass, you see the strange ship he''s pointing to. You may take the Visions card if it is available.','Luck -1','Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Basil Elton invites you to tell him your story. If you wish to do so, you are delayed, but Basil offers a great deal of insight. Gain 1 Sanity and 1 Clue token.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Basil Elton is able to explain much about the creatures you have encountered. Gain 2 Clue tokens for each monster trophy you have. If you have no monster trophies, gain 1 Clue token.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Basil Elton is chatting with several old fishermen. Listening to their friendly conversation, you gain 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Basil Elton tells you some tales of his adventures, offering you some advice on how to interact with the denizens of other worlds. You may immediately pay only 1 gate trophy or 5 toughness worth of monster trophies to gain the Captain of the White Ship card. If you cannot or will not pay, you lose the opportunity and will have to pay the normal cost if you later change your mind.',NULL,'Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Basil Elton, the lighthouse keeper, politely invites you in for dinner. Gain 1 Sanity and 1 Stamina.',NULL,'Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Basil Elton, the lighthouse keeper, talks with you about strange ships he''s seen moored just off the island-- ships that no one else claims to have seen. Gain 2 Clue tokens.',NULL,'Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Basil keeps a trunk of odd items that have washed up on the shore over the years. Make a Lore (-2) check. If you pass, you recognize something. Gain 1 Unique Item.','Lore -2','Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Basil points out a location where, as stories tell, a ship carrying gold sank. Make a Luck (-2) check. If you pass, you find the legendary wreck! Gain $3.','Luck -2','Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('For a moment, the lighthouse illuminates some horrible creature in the water. When the light rotates around again, the thing is gone. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('In despair, someone has thrown himself into the water. Make a Fight (-1) check. If you pass, you manage to pull him out of the water without harm to yourself. If you fail, lose 1 Stamina wrestling the man back to shore.','Fight -1','Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Noticing an older gentleman slip on the trail up ahead, you move to catch him. If you pass a Speed (-1) check, he introduces himself as Basil Elton, and-- seeing something in your eyes-- offers his services. If his Ally card is available, take it, then close the North Point Lighthouse for the rest of the game, and move to the street.','Speed -1','Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Noticing an older gentleman slip on the trail up ahead, you move to catch him. If you pass a Speed (-1) check, he introduces himself as Basil Elton, and-- seeing something in your eyes-- offers his services. If his Ally card is available, take it, then close the North Point Lighthouse for the rest of the game, and move to the street.','Speed -1','Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Noticing an older gentleman slip on the trail up ahead, you move to catch him. If you pass a Speed (-1) check, he introduces himself as Basil Elton, and-- seeing something in your eyes-- offers his services. If his Ally card is available, take it, then close the North Point Lighthouse for the rest of the game and move to the street.','Speed -1','Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Sitting next to Basil Elton on the edge of a sea cliff, he tells you stories about his adventures in the Dreamlands on a White Ship, and his fateful search for fabled Cathuria-- a search that left him unable to dream ever again. Gain 1 Clue token.',NULL,'Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Sitting on the edge of a sheer sea cliff, Basil Elton clutches a mostly empty whiskey bottle and sings melancholy songs. Worried, you stay to make sure nothing happens to him. You are delayed.',NULL,'Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Standing outside at the top of the lighthouse, the railing suddenly breaks. Make a Speed (+0) check to catch yourself. If you fail, lose 2 Stamina from the fall.','Speed +0','Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Staring out across the sea, you see a dark ship that gleams like obsidian pass between two islands, driven by oars. After rubbing your eyes, the ship is gone. Lose 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Talking to Basil Elton about his past, he tries to teach you certain powerful rituals he witnessed during his travels. Make a Lore (-2) check. For each success, draw 1 Spell. Choose 1 of the Spells to keep and discard the rest.','Lore -2','Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('The light illuminates strange shapes in the sky! Lose 1 Sanity for each monster in the Sky. Then, if you have not gone insane, choose 1 monster token in the Sky to return to the monster cup.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('The lighthouse is in need of fixing before the sun sets. Make a Speed (-1) check to help Basil Elton get it working again in time. If you pass, you feel happy to have helped. Gain 1 Sanity. If you fail, you are delayed while you continue working into the night to get the light repaired. Then, whether you passed or not, Basil gratefully pays you $1 for your efforts.','Speed -1','Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('The more you can tell Basil Elton about the plot of "The King in Yellow," the more he can explain what''s actually happening. If the Act I card is currently in play, gain 2 Clue tokens. If the Act II card is currently in play, gain 3 Clue tokens instead.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('The view from the top of the lighthouse is breathtaking. You find it truly inspiring. Gain 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('There are mysterious forces watching over the keeper of this lighthouse. Make a Luck (-2) check. If you pass, these forces are pleased with the kindness you have shown him and you are Blessed.','Luck -2','Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('Watching the waves wash in and out, you drift off to sleep. Move to the first area of the Dreamlands, have an encounter there, and then return here immediately.',NULL,'Miskatonic Horror');
INSERT INTO north_point_lighthouse_encounters VALUES ('You notice an odd ship docked by the shore, but no one else seems to pay it any mind. If you decide to swim out to the ship, roll a die to see how you are received. On a success, move to the second area of any Other World of your choice, even if there isn''t currently an open gate leading there. On a failure, you are lost in time and space.',NULL,'Kingsport Horror');
