CREATE TABLE st_erasmuss_home_encounters (
    `list_encounter` VARCHAR(438) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO st_erasmuss_home_encounters VALUES ('"Sorry folks, it''s time for lights out! You can come back tomorrow, but for now you''ll all have to leave!" Move to the street',NULL,'Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('"What is this? You reckon it''s valuable?" One of the mariners received a package from a shipmate who still travels to exotic locations. Make a Lore (+1) check to identify the object. If you pass, draw 1 Unique Item. You may purchase this item for $1 less than the list price (to a minimum of $1). If you do not purchase the item, it is discarded.','Lore +1','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('A mysterious stranger visits one of the tenants in the middle of the night. In the morning, he finds he can no longer speak. You can see the fear in his eyes as he draws you a map of the places he''s been. Make a Lore (-1) check. If you pass, gain 2 Clue tokens. If you fail, you don''t understand, but the man''s panic causes you to lose 1 Sanity.','Lore -1','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('A wealth of experience can be gained by talking with these old-timers. You may stay here next turn to make a Lore (-2) check. If you pass, gain 1 Skill.','Lore -2','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('An attendant sees you admiring the sailing memorabilia. He tells you there''s a lot more in crates stored downstairs. Make a Luck (-2 check. If you pass, draw 3 Common Items, choose 1 to keep, and then discard the others. If you fail, you are delayed while you search fruitlessly.','Luck -2','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('An old woman leans up against the fence, gasping for air. "Don''t mind me, young''un. These lungs are just old and worn out." Still, something deep inside tells you that you can help her out, if you''re willing to make a sacrifice. If you discard 1 Skill, she smiles and says, "I don''t know what you did, but I''m in your debt." Granny Orne joins you. Take her Ally card, or if it''s not avaiable, draw the top five Unique Items and keep one.',NULL,'Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('An old woman leans up against the fence, gasping for air. "Don''t mind me, young''un. These lungs are just old and worn out." Still, something deep inside tells you that you can help her out, if you''re willing to make a sacrifice. If you discard 1 Skill, she smiles and says, "I don''t know what you did, but I''m in your debt." Granny Orne joins you. Take her Ally card, or if it''s not avaiable, draw the top five Unique Items and keep one.',NULL,'Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('An old woman leans up against the fence, gasping for air. "Don''t mind me, young''un. These lungs are just old and worn out." Still, something deep inside tells you that you can help her out, if you''re willing to make a sacrifice. If you discard 1 Skill, she smiles and says, "I don''t know what you did, but I''m in your debt." Granny Orne joins you. Take her Ally card or, if it''s not available, draw the top five Unique Items and keep one.',NULL,'Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('An old woman leans up against the fence, gasping for air. "Don''t mind me, young''un. These lungs are just old and worn out." Still, something deep inside tells you that you can help her out, if you''re willing to make a sacrifice. If you discard 1 Skill, she smiles and says, "I don''t know what you did, but I''m in your debt." Granny Orne joins you. Take her Ally card or, if it''s not available, draw the top five Unique Items and keep one.',NULL,'Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('Basil Elton, the old lighthouse keeper, is visiting friends here and invites you out to see the lighthouse. You may move to the North Point Lighthouse and draw 2 cards, encountering one card of your choice and discarding the other.',NULL,'Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('Danny Houghton, half dozing in his chair, begins to talk, muttering about the horrible creatures he''s seen during his time at sea. Lose 1 Sanity and gain 1 Clue token.',NULL,'Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('Danny Houghton is eager to hear your story and believes your strange tales. It''s good to talk to someone. Gain 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('Danny Houghton, one of the ancient mariners here, grabs your arm firmly and urgently whispers a tale of his youth in your ear. You hear how the Kingsport fishing fleettrespassed into Innsmouth waters and were attacked, finny hands pulling under the boats and their crews. Lose 1 Sanity and gain 1 Clue token.',NULL,'Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('Danny Houghton pulls you aside and tells you to never put to sea without knowing a little something worth knowing. He teaches you a complex riddle that, at first, makes no sense. Make a Lore (-1) check to figure it out. If you pass, gain 1 Spell.','Lore -1','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('Doc Warren comes around to check up on the old timers here, and offers to take a look at you too. If you accept, pass a Luck (-1) check to gain 1 Stamina. If you fail, he makes a mistake due to his encroaching senility and you lose 1 Stamina.','Luck -1','Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('George Cotton, the local stonecutter, stops in to say hello to some of the old salts. Afterwards, he talks about the strange goings-on at the nearby cemetary. Gain 1 Clue token.',NULL,'Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('Hanging out with the old salts who live here for awhile, you play a few hands of bridge. Gain 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('In the attic is a large chest that no one can recall where it came from. There''s no key, but you try to break it open. Make a Fight (-2) check. If you pass, gain 1 Unique Item.','Fight -2','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('In the middle of the night, one of the retired sailors gets up and begins walking toward the water. Make a Fight (+0) check to stop him and get him back to bed. If you fail, lose 1 Sanity as the man disappears beneath the waves.','Fight +0','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('Nets Foster tries to sell you one of his wooden carvings. They''re worthless, but he''s a convincing salesman. Pass a Will (-2) check or lose $2.','Will -2','Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('Old Ben James is visiting St. Eramus''s Home for Retired Mariners to spin an entertaining yarn for the old sea dogs. Pass a Lore (-1) check to recognize a helpful fact buried in the story and gain 1 Clue token.','Lore -1','Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('One of the kind old men who live here offers you a strange carving. Pass a Lore (-1) check to gain 1 Spell.','Lore -1','Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('One of the old salts says he can predict a change in the weather because his knee hurts. Make a Luck (-2) check. If you pass, you may discard the Environment Mythos Card currently in play.','Luck -2','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('One of the sailors looks at you curiously. "You got family in Innsmouth?" Draw an Innsmouth Look card.',NULL,'Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('One of the sailors speaks to you as if you were a shipmate from years ago. He mentions strange sea creatures. Gain 1 Clue token.',NULL,'Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('The home was formerly a mansion in the early days of Kingsport. One of the caretakers points out graffiti scratched into the basement''s stonework from the 18th century. Make a Lore (-1) check. If you pass, the city''s history becomes cleare to you. Gain 1 Clue token.','Lore -1','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('The mariners are comparing coins from different countries. You recognize the runes carved on one of the coins as being from a very early culture. Gain 1 Clue token.',NULL,'Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('The old boys have lured you into a game of high-stakes cards. Make a Luck (-1) check. If you pass, you not only keep your money, you gain 1 Unique Item in the process. If you fail, discard all of your money to a maximum of $5.','Luck -1','Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('The staff asks you to consider making a donation to the retirement home. If you spend $2, their gratitude warms your heart and you gain 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('They may be retired, but these old sailors are happy to make a little money from the occasional return to the water. You may pay $2 to move to any aquatic location.',NULL,'Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('You are startled to notice a primitive idol of the god Dagon on the mantle. Pass a Lore (-2) check to decipher the writing on it. If so, gain 2 Clue tokens and lose 1 Sanity.','Lore -2','Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('You hear one of the sailors talking to a caretaker about having seen "The King in Yellow" in its original French. He explains how some of the passages were altered in translation. Gain 1 Clue token.',NULL,'Miskatonic Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('You notice a rare and ancient artifact sitting atop a sea chest. Pass a Will (-2) check to convince the old salt who owns it to give it to you. Gain 1 Unique Item.','Will -2','Kingsport Horror');
INSERT INTO st_erasmuss_home_encounters VALUES ('You''re promised the tale of a lifetime, but it turns out to be a long story about nothing. You are delayed.',NULL,'Miskatonic Horror');
