CREATE TABLE strange_high_house_encounters (
    `list_encounter` VARCHAR(384) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO strange_high_house_encounters VALUES ('A window opens, and a strange, gentle man dressed in archaic clothes smiles at you. If you pass a Will (-2) check or discard Ancient Tome, he introduces himself as William Bain and offers you his help. Take his Ally card. if it isn''t available, you are Blessed.','Will -2','Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('A window opens, and a strange, gentle man dressed in archaic clothes smiles at you. If you pass a Will (-2) check or discard Ancient Tome, he introduces himself as William Bain and offers you his help. Take his Ally card. if it isn''t available, you are Blessed.','Will -2','Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('A window opens, and a strange, gentle man dressed in archaic clothes smiles at you. If you pass a Will (-2) check or discard an Ancient Tome, he introduces himself as William Bain and offers you his help. Take his Ally card. If it isn''t available, you are Blessed.','Will -2','Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('A window opens, and a strange, gentle man dressed in archaic clothes smiles at you. If you pass a Will (-2) check or discard an Ancient Tome, he introduces himself as William Bain and offers you his help. Take his Ally card. If it isn''t available, you are Blessed.','Will -2','Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('After a visit with William Bain, he performs a ritual prayer. Shortly thereafter, there is a knock at the door and he opens it to reveal grey, hoary Nodens. You explain recent events to him, and he frowns, fearsomely. Remove 2 doom tokens from the Ancient One''s doom track, but lose 3 Sanity.',NULL,'Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('After seeing some of the objects you have brought with you, [[William Bain is interested in perhaps trading with you. You may either discard 1 Common Item to gain 1 Unique Item or discard 1 Unique Item to gain 1 Common Item.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('An open window seems particularly inviting. If you climb inside, you discover several sea chests. Pass a Luck (-1) check to find something useful in them and gain 1 Common Item.','Luck -1','Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('As you approach the house, you see an object falling down the side of the hill. make a Speed (-1) check to catch it before it disappears down the slope. If you pass, gain 1 Unique Item. If you fail, lose 1 Stamina scrambling across the rocks.','Speed -1','Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('Hearing the stories of what''s going on in Dunwich, William Bain seems unconcerned and tells you that it''s not as bad as you make it sound. You may discard 2 Clue tokens to remove 1 Dunwich Horror token from the board.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('If you have 3 or more Clue tokens, you know that William Bain was once a member of a powerful cult. He tells you that it was a long time ago and it is all behind him, but offers to teach you what he remembers from those days. Gain 1 Spell. If you have 2 or fewer Clue tokens, nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('Inexplicably, William Bain walks in through a door that leads to a shear drop-off. Once inside he begins pulling items out of his large coat pockets. Most of it seems like random junk. Make a Luck (+0) check. If you pass, he hands you something useful. Gain 1 Common Item.','Luck +0','Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('Something about your presence is disturbing William Bain and he may ask you to leave, one way or another. If you have 1 or more Corruption Cards, you are lost in time and space. If you do not have any Corruption Cards, but you currently have 3 or less Sanity, move to the Wireless Station and have an encounter there. Otherwise, nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('The peculiar William Bain regretfully tells you there is little he can offer you. Make a Will (-1) check. If you pass, you notice the small stack of gold coins next to his books. While William is not certain what help those will be, he happily gives them to you. Gain $5. If you fail, nothing happens.','Will -1','Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('The thick mist has covered the top of the hill. You can''t seem to find the house. You are delayed while you search.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('There are no doors leading into the strange old house built on the peak here, but you find an old book leaning against one of the walls, as though someone left it for you. If you pass a Luck (-1) check, it is a particularly rare book. Take the first Tome from the Unique Item deck. If you fail, it''s still a useful book, but not as rare. Take the first Tome from the Common Item deck.',NULL,'Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('When you finally reach the house, William Bain is inside making a thick stew and happily invites to join him for a meal. Make a Luck (-2) check. If you fail, the stew is merely invigorating. Gain 1 Stamina. If you pass, its unique ingredients have a strange effect on you. Gain 1 Stamina and you may take the Psychic card if it is available.','Luck -2','Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain is here, and he takes you to visit the Dreamlands. Move to the Dreamlands and draw 2 cards, encountering one and discarding the other, then return.',NULL,'Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain is here, and he takes you to visit the Dreamlands. Move to the Dreamlands and draw 2 cards, encountering one and discarding the other, then return.',NULL,'Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain is here, and he takes you to visit the Dreamlands. Move to the Dreamlands and draw 2 cards, encountering one and discarding the other, then return.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain is here, and he takes you to visit the Dreamlands. Move to the Dreamlands and draw 2 cards, encountering one and discarding the other, then return.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain is here, and he takes you to visit the Dreamlands. Move to the Dreamlands and draw 2 cards, encountering one and discarding the other, then return.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain is here, and he takes you to visit the Dreamlands. Move to the Dreamlands and draw 2 cards, encountering one and discarding the other, then return.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain is here, dressed in his curiously outdated clothing, and he teaches you a spell. Gain 1 Spell.',NULL,'Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain isn''t here right now but a Nightgaunt is! You must immediately move to the open gate of your choice and enter it.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain offers to lend you a hand. You may immediately move to the open gate of your choice and enter it.',NULL,'Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('William Bain tells you that Nodens has sent one of his Nightgaunts to help you, but the journey will be dangerous. If you wish to accept the help, make a Will (-2) check. If you pass, move to the second area of any Other World you choose. If you fail, the Nightgaunt has left you lost in time and space.','Will -2','Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('You are stunned to discover a mysterious man in exotic looking robes. He claims to have been waiting for you. If you are Cursed or have any Mask items, he tells you that he is called The Messenger and is meant to aid you. Take his Ally card or, if it is not available, gain 2 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('You can''t begin to fathom how old William Bain really is. He tells you the history of Kingsport as if he had witnessed the whole thing firsthand. Gain 2 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('You find William Bain''s company helps to calm your thoughts and heal your mind. You may either discard 1 Madness card if you have one or restore your Sanity to its maximum.',NULL,'Miskatonic Horror');
INSERT INTO strange_high_house_encounters VALUES ('You just have one last chasm to cross, but it looks rather dangerous. Pass a Fight (-1) check or move to the Wireless Station.','Fight -1','Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('You plead with William Bain for assistance. If you pass a Will (-1) check, he agrees and works a powerful spell. Remove all rift progress tokens from 1 rift, closing it immediately. If you fail, he refuses explaining that he cannot interfere with the world of man without endangering himself.','Will -1','Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('You sit and chat with the pleasant, if old-fashioned, William Bain. He seems to be very poorly informed of the outside world, but extremely knowledgable of more exotic subjects. Nothing happens.',NULL,'Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('You talk with William Bain for a time, and he grows increasingly nervous. If you are Cursed, you find yourself suddenly overwhelmed with terror and hurl yourself out the only door to the small house. As the door opens directly over the cliff, you fall to the sea below and are devoured. If you are not Cursed, you control yourself, and nothing happens.',NULL,'Kingsport Horror');
INSERT INTO strange_high_house_encounters VALUES ('You visit with the strange, otherworldly William Bain for awhile, when suddenly he hushes you, frantically locks the door and all the windows, and then douses the light. The two of you crouch in silence as a chilling shadow makes its way around the house, trying every door and window before leaving. You are delayed and lose 1 Sanity.',NULL,'Kingsport Horror');
