CREATE TABLE the_rope_and_anchor_encounters (
    `list_encounter` VARCHAR(365) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO the_rope_and_anchor_encounters VALUES ('"Sorry folks, it''s midnight. Time to close up." Move to the street.',NULL,'Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('A brawl breaks out between a couple of the regulars, and Jonas Rigg has to fire his .45 in the air to break it up. Pass a Will (-1) check or move to the street with most of the startled crowd.','Will -1','Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('A few members of the Sheldon Gang are gathered in the corner. One of them notices you watching and confronts you. If you spend at least 5 toughness worth of monster trophies or 1 Gate trophy, they accept you into the gang. Take a Sheldon Gang Membership card. If you do not spend the trophies, they throw you out. Move to the street and lose 1 Stamina.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('A pale, ordinary man stares out the window at the peak of the Kingsport Head as if longing for something. Pass a Fight (-2) check or discard Lucky Cigarette Case to spark his interest in you and his surroundings. If so, he introduces himself as Thomas Olney. Take his Ally card, or if it''s not available, remove 1 doom token from the Ancient One''s doom track.','Fight -2','Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('A pale, ordinary man stares out the window at the peak of the Kingsport Head as if longing for something. Pass a Fight (-2) check or discard Lucky Cigarette Case to spark his interest in you and his surroundings. If so, he introduces himself as Thomas Olney. Take his Ally card, or if it''s not available, remove 1 doom token from the Ancient One''s doom track.','Fight -2','Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('A pale, ordinary man stares out the window at the peak of the Kingsport Head as if longing for something. Pass a Fight (-2) check or discard the Lucky Cigarette Case to spark his interest in you and his surroundings. If so, he introduces himself as Thomas Olney. Take his Ally card or, if that''s not available, remove 1 doom token from the Ancient One''s doom track.','Fight -2','Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('A pale, ordinary man stares out the window at the peak of the Kingsport Head as if longing for something. Pass a Fight (-2) check or discard the Lucky Cigarette Case to spark his interest in you and his surroundings. If so, he introduces himself as Thomas Olney. Take his Ally card or, if that''s not available, remove 1 doom token from the Ancient One''s doom track.','Fight -2','Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('An old man with a concertina sings an ancient ballad about creatures coming in the night. Listening carefully to its lyrics, the song''s story is both terrifying and revealing. Lose 1 Sanity and gain 1 Clue token.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('During the night, someone has broken all the windows and smashed all the furniture. Until repairs can be made, the tavern can''t accommodate any patrons. Move to the streets.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('In perfect unison, the loud and boisterous crowd suddenly falls silent, turns to you and all ask, "Have you seen the yellow sign?" Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('It''s a raid! Make a Speed (+0) check to get out before the police round you up. If you fail, you are arrested for being in an establishment selling liquor.','Speed +0','Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('It''s a slow night and the bartender, Jonas Rigg, strikes up a conversation with you. The stories he hears have been getting stranger and stranger lately. If the terror level is currently 4 or lower, gain 1 Clue token. If it is currently 5 or higher, gain 2 Clue tokens.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Jonas Rigg hands you a tavern puzzle and offers you a free drink if you can solve it. Make a Lore (-1) check to get the metal ring free from the rest of the iron sculpture. If you pass, gain 1 Sanity.','Lore -1','Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Jonas Rigg is curious about the exhibit of Egyptian antiquities. If you choose to tell him what you know, he picks up your tab at the end of the night. You are restored to your maximum Sanity, but are delayed.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Jonas Rigg suspects you may not be in your right mind. Roll a die for each point of Sanity you currently have. If you roll at least 1 success, the bartender apologizes and offers you some free soup. Gain 1 Stamina. If you don''t roll any successes, move to the streets and discard one Weapon if you are able.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Jonas Rigg, the bartender, looks you over as you enter the dim, smoky tavern. "I''m guessing you want to buy something besides drinks." You may buy up to 3 Clue tokens for $2 each.',NULL,'Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Jonas Rigg, the bartender, looks you over as you enter the dim, smoky tavern. "I''m guessing you want to buy something besides drinks." You may buy up to 3 Clue tokens for $2 each.',NULL,'Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Jonas Rigg, the bartender, looks you over as you enter the dim, smoky tavern. "I''m guessing you want to buy something besides drinks." You may buy up to 3 Clue tokens for $2 each.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Jonas Rigg, the bartender, looks you over as you enter the dim, smoky tavern. "I''m guessing you want to buy something besides drinks." You may buy up to 3 Clue tokens for $2 each.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Jonas Rigg, the bartender, looks you over as you enter the dim, smoky tavern. "I''m guessing you want to buy something besides drinks." You may buy up to 3 Clue tokens for $2 each.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Jonas Rigg, the bartender, looks you over as you enter the dim, smoky tavern. "I''m guessing you want to buy something besides drinks." You may buy up to 3 Clue tokens for $2 each.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('One of the sailors tells you a horrible story about large fish creatures pulling men under the water. If there are 3 or less uprising tokens on the Deep Ones Rising track, gain 1 Clue token. If there are 4 or more uprising tokens on the Deep Ones Rising track, gain 2 Clue tokens and lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Sliding into a booth, you sit on something. Picking it up, you realize that someone left an item behind. If you pass a Luck (-1) check, it may prove useful to you. Gain 1 Common Item.','Luck -1','Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Some of the locals are cooking up some fish stew in the fireplace. After a wary glance, you are invited to join them. Restore your Stamina to its maximum.',NULL,'Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Someone bumps into you at the crowded bar. Pass a Luck (-1) check or lose $3, if able. If you don''t have any money or you fail the check, nothing happens.','Luck -1','Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('The mood in the tavern is jovial tonight, and you join in singing a chorus of rousing songs. Restore your Sanity to its maximum.',NULL,'Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Tonight, the old Yankee fishermen who frequent the tavern are trading long, rambling tales of the sea. You listen for awhile, but although the tales are entertaining, they are uninformative. Nothing happens.',NULL,'Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Tonight, the old Yankee fishermen who frequent the tavern are trading long, rambling tales of the sea. You listen for awhile, but although the tales are entertaining, they are uninformative. Nothing happens.',NULL,'Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Tonight, the old Yankee fishermen who frequent the tavern are trading long, rambling tales of the sea. You listen for awhile, but although the tales are entertaining, they are uninformative. Nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Tonight, the old Yankee fishermen who frequent the tavern are trading long, rambling tales of the sea. You listen for awhile, but although the tales are entertaining, they are uninformative. Nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Tonight, the old Yankee fishermen who frequent the tavern are trading long, rambling tales of the sea. You listen for awhile, but although the tales are entertaining, they are uninformative. Nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Tonight, the old Yankee fishermen who frequent the tavern are trading long, rambling tales of the sea. You listen for awhile, but although the tales are entertaining, they are uninformative. Nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Troubles weighing heavily upon your worried brow, you drink rather more than you intended. If your current Stamina is 3 or less, you are delayed and lose 1 item of your choice.',NULL,'Kingsport Horror');
INSERT INTO the_rope_and_anchor_encounters VALUES ('Unfortunately, due to Prohibition, the quality of liquor isn''t what it used to be. You get a bad batch and wind up vomiting in the alley. Lose 1 Stamina.',NULL,'Kingsport Horror');
