CREATE TABLE the_causeway_encounters (
    `list_encounter` VARCHAR(416) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO the_causeway_encounters VALUES ('A couple of Kingsport children got stuck on a rock outcropping while looking for a rumored treasure. Make a Luck (-2) check. If you pass, the rumors are true. Gain a Unique Item. Regardless of whether you pass or not, you are delayed rescuing the children.','Luck -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('A group of chanting voices echoes across the hillside. Make a Lore (-1) check to discern what they''re saying. If you pass, gain 1 Spell',NULL,'Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('A man is running up the hill, trying to escape vicious creatures that are attacking him. You may attempt to defend him if you wish. If you do, lose 3 Stamina. Even if you are knocked unconscious, the man, David Packard, owes you his life and intends to pay his debt. Take his Ally card or, if it is not available, he gives you something "for protection." You may search the Common Item deck for Dynamite and take it.',NULL,'Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('A rock slide has made this route unusable. Another path up the hill will have to be found. You are delayed while you find the new path.',NULL,'Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('A small collection of symbols was carved into the rock some untold number of years ago. Make a Lore (-2) check to interpret them. If you pass, you understand their occult significance and gain 2 Clue tokens.','Lore -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('A woman is up on the hill with binoculars bird watching. She claims there''s been some strange bird behaviors lately. Make a Lore (+0) check to understand what she''s explaining. If you pass, gain 1 Clue token.','Lore +0','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('As you are climbing, a rock falls towards you. Pass a Speed (-2) check or lose 2 Stamina and move to the Harborside streets.','Sneak -2','Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('As you are climbing, a rock falls towards you. Pass a Speed (-2) check or lose 2 Stamina and move to the Harborside streets.','Speed -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('In a lonely spot on the cliffside, you are suddenly gripped by a strange, terrifying vertigo. Pass a Luck (-2) check or lose 2 Sanity and move to Harborside streets.','Luck -2','Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('In a lonely spot on the cliffside, you are suddenly gripped by a strange, terrifying vertigo. Pass a Luck (-2) check or lose 2 Sanity and move to the Harborside streets.','Luck -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('One of the Wireless Station workers is driving up in a truck. If you wish, you may make a Speed (-1) check to grab the back. If you pass, move to the Wireless Station and immediately have an encounter there. If you fail, lose 1 Stamina.','Speed -1','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('Pausing, you stop to admire the clear blue sky. Nothing happens.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('Pulling yourself up the cliff, you come face to face with a snake. Pass a Will (-2) check or lose 2 Sanity, 1 Stamina, and move to the Harborside streets.','Will -2','Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('Pulling yourself up the cliff, you come face to face with a snake. Pass a Will (-2) check or lose 2 Sanity, 1 Stamina, and move to the Harborside streets.','Will -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('The causeway ends here at a precipice that overlooks the sea, and for one mad instant, you long to hurl yourself from the cliff. Lose 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('The path winds back and forth, providing a very pleasant afternoon''s walk. Nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('The rock crumbles beneath you, and you slip and fall. Move to the Harborside streets.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('The sun is rapidly setting and the terrain is too dangerous to try to climb in the dark. Pass a Speed (-2) check or lose 1 Sanity and 1 Stamina and move to the Harborside streets.','Speed -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('The sun is rapidly setting and the terrain is too dangerous to try to climb in the dark. Pass a Speed (-2) check or lose 1 Sanity and 1 Stamina and move to the Harborside streets.','Speed -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('Wiping the sweat from your brow, you stop to rest on a rock for awhile. You are delayed.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('You are winded from the hard climb and stop to rest. You are delayed.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('You come across some strange, rubbery bones, and a featureless skull. Lose 1 Sanity, then gain 1 Unique Item, as you find something the creature was carrying when it died.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('You discover a secret trail. Move to the Wireless Station and immediately have an encounter there.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('You feel a sudden sharp pain in your ankle and see that you''ve been bitten by a snake! Make a Lore (-2) check to treat the wound. If you fail, lose 2 Stamina and move to the Harborside streets to get help.','Lore -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('You feel a sudden sharp pain in your ankle and see that you''ve been bitten by a snake! Make a Lore (-2) check to treat the wound. If you fail, lose 2 Stamina and move to the Harborside streets to get help.','Lore -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('You find a decaying scroll, weighted down with a rock. Gain 1 Spell.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('You find yourself nearly fainting in exhaustion during the hard climb. Lose 1 Stamina.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('You lean against a wooden railing that protects visitors from falling off the cliffside accidentally and just gaze out to sea for awhile. Nothing happens.',NULL,'Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('You see a sudden green flash of light somewhere ahead of you on the path. Racing to get there, you find a smoldering, scorched book. If you wish, you may try to gain what knowledge you can from it before it is reduced to ashes. If you do, lose 1 Stamina as it burns your hands and then, if you are still conscious, gain 1 Spell.',NULL,'Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('You see a trunk on a rock below that has apparently fallen and split open. If you wish you may try to climb down and retrieve it. Make a Fight (-1) check to reach it safely. If you fail, lose 2 Stamina. Then, whether you passed or not, if you are still conscious, gain 1 Unique Item.','Fight -1','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('You slowly clamber up the stone formation known as the Face of Neptune. Pass a Fight (-2) check or lose 2 Stamina and move to Harborside streets.','Fight -2','Kingsport Horror');
INSERT INTO the_causeway_encounters VALUES ('You slowly clamber up the stone formation known as the Face of Neptune. Pass a Fight (-2) check or lose 2 Stamina and move to the Harborside streets.','Fight -2','Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('You suspect you may be carrying too many things to make this climb! If you have 4 or more items you must either discard 1 or lose 1 Stamina.',NULL,'Miskatonic Horror');
INSERT INTO the_causeway_encounters VALUES ('You think you could reach the Wireless Station by scrambling up a steep incline. If you wish to give it a try, make a Fight (-1) check. If you pass, move to the Wireless Station. If you fail, lose 1 Stamina and move to the Harborside streets.','Fight -1','Miskatonic Horror');
