CREATE TABLE wireless_station_encounters (
    `list_encounter` VARCHAR(397) CHARACTER SET utf8,
    `list_skill_check` VARCHAR(8) CHARACTER SET utf8,
    `list_expansion` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO wireless_station_encounters VALUES ('"Hey! Get out of here!" Hiram Grumbacher, the construction foreman, angrily runs you off the construction site. Move to the Causeway.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('"Hey there! What are you doing here?" Will Critchett, a muscular, unpleasant worker demands that you explain your presence on the construction site. Pass a Will (-2) check or move to the Causeway.','Will -2','Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('"You all right?" One of the workers is concerned that you may have serious injuries. If you currently have 3 Stamina or less, he administers some first aid. Gain 1 Stamina. Otherwise, nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('A couple of friendly workers share their lunch with you. Gain 2 Stamina.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('A few engineers are testing some of the radio equipment intended for use here. They''re having some difficulty making it work. Make a Lore (-2) check to recognize the problem. If you pass, they want to put you on the payroll as a consultant. Take a Retainer card.','Lore -2','Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('A thick mist comes rolling down the hill and envelops the entire construction site. Make a Luck (+0) check. If you fail, you take a spill down the hillside. Lose 1 [[Stamina and move to the Causeway.','Luck +0','Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('A truck has stalled, blocking the narrow path leading away from the construction site. You are delayed while it gets moved.',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('A truck is rolling down the hill out of control! Make a Speed (+0) check to avoid being hit. If you fail, lose 2 Stamina.','Speed +0','Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('A workman''s wife is expecting a baby! Cigars are being passed around to celebrate and, without even knowing who you are, you are welcomed into the festivities. Gain 1 Sanity and 1 Stamina.',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('Equipment and materials have been stolen from the site, and the workers are constantly watching for strangers. Make a Sneak (-1) check. If you fail, you''re spotted and suspected of being a thief. Take the Wanted card if it is available.','Sneak -1','Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('Harsh, buffeting winds force you to cling to the cliffside in terror. You are delayed.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('If Coded Messages is facedown, you may pay the radio operators who are working on the site to help you out. You may spend $5 to relay information for you. If you do, turn Coded Messsages faceup. If you do not spend the money, nothing happens.',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('Inching your way across a narrow ledge, you make the mistake of looking down at the dizzying fall below you. Lose 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('It''s a tough climb and you need a rest. You are delayed but gain 1 Stamina.',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('Looking up into the night sky, you are horrified to see large, black things circling overhead. Lose 1 Sanity.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('Mixed in with the other trash from the site, you spot an oddly-shaped object wrapped in canvas. Make a Sneak (-2) check to retrieve it without drawing attention to yourself. If you pass, search the Common Item deck and take the first Weapon you find. Clearly someone was trying to hide the evidence of a criminal activity. If you fail, you decide not to risk being caught and leave it alone.','Sneak -2','Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('One of the foremen asks if you''re one of the engineers. Make a Lore (-2) check to pass yourself off as a technical specialist. If you fail, move to the Causeway and have an Encounter there.','Lore -2','Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('One of the speakers that is not currently attached to any radio equipment begins broadcasting a voice that speaks directly to you. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('Rain makes the trail slippery and treacherous. Pass a Luck (-2) check or lose 2 Stamina and over to the Causeway.','Luck -2','Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('Spotting a glint of metal on the ground, you pick it up and dust it off, only to reveal a gold coin! Gain $2.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('Suddenly, the ground collapses underneath you! Pass a Fight (-2) check or lose 2 Stamina and move to the Causeway.','Fight -2','Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('The majority of the workers didn''t show up today. The ones who did are wandering around in a daze. Take 1 Common Item, as no one is watching the equipment, but lose 1 Sanity from the strange behavior of the people.',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('The path up to the Wireless Station is being carefully watched. You are politely but unambiguously told to stay away. Move to the Causeway.',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('The workers are all elsewhere having lunch. You spot something in the back of one of the trcuks that looks useful. You may make a Sneak (-1) check to steal the item is you wish. If you pass, draw 2 Common Items, choose 1 to keep and discard the other. If you fail, you are caught and arrested.','Sneak -1','Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('The workers yell as they lose control of a heavy metal pole they were lifting into place. It falls towards you! Pass a Speed (-2) check or you are reduced to 0 Stamina.','Speed -2','Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('Tucked in a crevice, you find 1 Common Item.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('When the workers showed up this morning, the beams were bent and twisted completely out of shape. You can''t imagine what it was that was strong enough to do such a thing. Lose 1 Sanity.',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('Without warning, lightning begins to strike the beams of the station. Make a Luck (+1) check. If you fail, you are touching one of the beams at the wrong moment. Take an Injury card as the lightning courses through you.','Luck +1','Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('You come across a pleasant, white-haired young man. He introduces himself as Dr. Hamlin Hayes and tells you about the Wireless Station they''re building here. "When it''s completed, we''ll be able to send and receive wireless messages all the way to Antartica!" Gain 1 Sanity and 1 Stamina from the rest and pleasant conversation.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('You encounter a bespectacled young man named Donald Stoll and make the mistake of asking him about the Wireless Station. He subjects you to a long-winded, technical explanation. You are delayed.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('You get a chance to try out some of the radio equipment. You hear a strange mechanical voice reciting numbers. Make a Lore (-2) check to decode any kind of meaning from what you hear. Gain 1 Clue token for each success.','Lore -2','Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('You pause to look over the construction site, marveling at man''s ability to encroach even here, in this isolated, haunting place. Nothing happens.',NULL,'Kingsport Horror');
INSERT INTO wireless_station_encounters VALUES ('You see an older man gazing out at the city of Kingsport, reminiscing about the changes the town has seen. If you currently have 3 or more Clue tokens, much of what he says makes terrible sense and gives you insight into the inner workings of the town. you may choose any rift progress marker to either discard (if its associated rift is closed) or turn face down (if its associated rift is open).',NULL,'Miskatonic Horror');
INSERT INTO wireless_station_encounters VALUES ('You see the corner of some worn antique trunk poking up out of the ground where the workmen have been digging. Make a Sneak (-2) check to dig it up and reveal the contents. If you pass, gain 1 Common Item. If you fail, move to the Causeway','Sneak -2','Miskatonic Horror');
